#!/bin/sh

DAEMON=wsd_simple_server
ONVIF_CONFIG=/etc/onvif.json
MOTORS_CONFIG=/etc/motors.json
MOTORS_BIN="/bin/motors"
RAPTOR_CONFIG=/etc/raptor.conf

. /usr/share/common

iface="$(iface_default)"

CAMERA=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $OS_RELEASE_FILE)

raptor_conf_get() {
	section="$1"
	key="$2"

	sed -n "/^\[$section\]/,/^\[/{ /^$key[[:space:]]*=/{s/^[^=]*=[[:space:]]*//;s/[[:space:]]*#.*$//;s/^[[:space:]]*//;s/[[:space:]]*$//;p;q}}" "$RAPTOR_CONFIG"
}

raptor_bool_default() {
	section="$1"
	key="$2"
	default="$3"

	val=$(raptor_conf_get "$section" "$key" | tr 'A-Z' 'a-z')
	[ -n "$val" ] || val="$default"

	case "$val" in
		true|yes|1|on) echo "true" ;;
		false|no|0|off) echo "false" ;;
		*) echo "$default" ;;
	esac
}

raptor_rtsp_scheme() {
	if [ "$(raptor_bool_default rtsp tls true)" = "true" ]; then
		echo "rtsps"
	else
		echo "rtsp"
	fi
}

raptor_rtsp_port() {
	port=$(raptor_conf_get rtsp port)
	if [ -n "$port" ]; then
		echo "$port"
	elif [ "$(raptor_rtsp_scheme)" = "rtsps" ]; then
		echo "322"
	else
		echo "554"
	fi
}

raptor_rtsp_endpoint() {
	case "$1" in
		0)
			key="endpoint_main"
			def="ch0"
			;;
		1)
			key="endpoint_sub"
			def="ch1"
			;;
		*)
			echo ""
			return
			;;
	esac

	ep=$(raptor_conf_get rtsp "$key")
	[ -n "$ep" ] || ep="$def"
	echo "${ep#/}"
}

raptor_webrtc_enabled() {
	raptor_bool_default webrtc enabled true
}

raptor_webrtc_scheme() {
	if [ "$(raptor_bool_default webrtc https true)" = "true" ]; then
		echo "https"
	else
		echo "http"
	fi
}

raptor_webrtc_port() {
	port=$(raptor_conf_get webrtc http_port)
	[ -n "$port" ] || port="8554"
	echo "$port"
}

configure_raptor_onvif_profiles() {
	rtsp_scheme=$(raptor_rtsp_scheme)
	rtsp_port=$(raptor_rtsp_port)
	endpoint_main=$(raptor_rtsp_endpoint 0)
	endpoint_sub=$(raptor_rtsp_endpoint 1)

	jct "$tmpfile" set profiles.stream0.url "${rtsp_scheme}://%s:${rtsp_port}/${endpoint_main}"
	jct "$tmpfile" set profiles.stream1.url "${rtsp_scheme}://%s:${rtsp_port}/${endpoint_sub}"
	jct "$tmpfile" set audio.backchannel.uri "${rtsp_scheme}://%s:${rtsp_port}/${endpoint_main}"

	if [ "$(raptor_webrtc_enabled)" = "true" ]; then
		webrtc_scheme=$(raptor_webrtc_scheme)
		webrtc_port=$(raptor_webrtc_port)
		stream0_width=$(jct "$tmpfile" get profiles.stream0.width 2>/dev/null | tr -d '\n')
		stream0_height=$(jct "$tmpfile" get profiles.stream0.height 2>/dev/null | tr -d '\n')

		jct "$tmpfile" set profiles.webrtc.name "WebRTC"
		[ -n "$stream0_width" ] && jct "$tmpfile" set profiles.webrtc.width "$stream0_width"
		[ -n "$stream0_height" ] && jct "$tmpfile" set profiles.webrtc.height "$stream0_height"
		jct "$tmpfile" set profiles.webrtc.type "H264"
		jct "$tmpfile" set profiles.webrtc.url "${webrtc_scheme}://%s:${webrtc_port}/webrtc.html"
	fi
}

start() {
	echo_title "Starting ONVIF discovery"

	if ! is_gateway_reachable; then
		echo_error "Disabled"
		exit 1
	fi

	# Start one instance per active non-loopback interface
	for active_iface in $(ip -4 -o addr show | awk '$2 != "lo" {print $2}' | sort -u); do
		PIDFILE="/run/${DAEMON_SHORT}_${active_iface}.pid"
		DAEMON_ARGS="-i $active_iface -x http://%s/onvif/device_service -m $CAMERA -n thingino -p $PIDFILE"
		start_daemon
	done

	tmpfile="$(mktemp -u).json"
	echo '{}' > $tmpfile
	jct $tmpfile set camera.manufacturer "Thingino"
	jct $tmpfile set camera.model "$CAMERA"
	jct $tmpfile set camera.hardware_id "ingenic_$SOC_MODEL"
	jct $tmpfile set camera.serial_num "$(fw_printenv -n ethaddr | sed 's/://g' | tr -d "\n")"
	jct $tmpfile set camera.firmware_ver "$(awk -F'[=,"]' '/^BUILD_ID/{print $3 $4}' /etc/os-release | tr -d "\n")"
	jct $tmpfile set server.ifs $iface
	configure_raptor_onvif_profiles
	jct $tmpfile set server.username "$(raptor_conf_get rtsp username | tr -d '\n')"
	jct $tmpfile set server.password "$(raptor_conf_get rtsp password | tr -d '\n')"

	# conditional PTZ config
	if [ -f "$MOTORS_BIN" ]; then
		steps_pan=$(jct $MOTORS_CONFIG get motors.steps_pan | tr -d "\n")
		steps_tilt=$(jct $MOTORS_CONFIG get motors.steps_tilt | tr -d "\n")

		jct $tmpfile set ptz.enable 1
		jct $tmpfile set ptz.max_step_x "$steps_pan"
		jct $tmpfile set ptz.max_step_y "$steps_tilt"
	else
		jct $tmpfile set ptz.enable 0
	fi
	jct $ONVIF_CONFIG import $tmpfile
	rm -f $tmpfile
}

stop() {
	echo_title "Stopping ONVIF discovery"

	for pidfile in /run/${DAEMON_SHORT}_*.pid; do
		[ -f "$pidfile" ] || continue
		PIDFILE="$pidfile"
		stop_daemon
	done
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
