THINGINO_JCT_SITE_METHOD = git
THINGINO_JCT_SITE = https://github.com/themactep/jct
THINGINO_JCT_SITE_BRANCH = master
THINGINO_JCT_VERSION = 9a6ebadf5ad1eebcea8279e164fc1a0aef69092e

THINGINO_JCT_LICENSE = MIT
THINGINO_JCT_LICENSE_FILES = LICENSE

define THINGINO_JCT_BUILD_CMDS
	$(MAKE) CROSS_COMPILE=$(TARGET_CROSS) LDFLAGS="$(TARGET_LDFLAGS)" -C $(@D)
endef

define THINGINO_JCT_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/jct \
		$(TARGET_DIR)/usr/bin/jct
endef

$(eval $(generic-package))
