#!/bin/env sh
# Sends data to MQTT server
# https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
# https://mosquitto.org/documentation/

. /usr/share/prudynt-helpers
. /usr/share/send2common

domain="mqtt"
config_file="/etc/send2.json"

message_looks_like_json() {
	# Treat payload as JSON when it is wrapped in braces or brackets
	local trimmed
	trimmed=$(printf '%s' "$1" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
	case "$trimmed" in
		\{*\}|\[*\])
			return 0
			;;
		*)
			return 1
			;;
	esac
}

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      MQTT server FQDN or IP address
	-p port      MQTT port
	-u username  MQTT username
	-P password  MQTT password
	-t topic     Topic
	-m message   Message body
	-v           Verbose output
	-S           Send photo
	-V           Send video
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	client_id=$(get_value client_id)
	host=$(get_value host)
	message=$(get_value message)
	password=$(get_value password)
	port=$(get_value port)
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
	tls_skip_verify=$(get_value tls_skip_verify)
	topic=$(get_value topic)
	topic_photo=$(get_value topic_photo)
	topic_video=$(get_value topic_video)
	use_ssl=$(get_value use_ssl)
	username=$(get_value username)
}

read_config

while getopts h:m:p:t:u:vP:SV flag; do
	case "$flag" in
		h) host=$OPTARG ;;
		m) message=$OPTARG ;;
		p) port=$OPTARG ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		P) password=$OPTARG ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) file=$OPTARG; send_photo="false"; send_video="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

# use config settings only if not set from command line
if [ -z "$send_photo$send_video" ]; then
        send_photo=$(get_value send_photo)
        send_video=$(get_value send_video)
fi

if [ -z "$host" ]; then
	echo_error "MQTT broker host is not set"
	exit 1
fi

if [ -z "$topic" ]; then
	echo_error "MQTT topic is not set"
	exit 1
fi

if [ -z "$message" ]; then
	echo_error "MQTT message template is not set"
	exit 1
fi

if [ "true" = "$send_photo" ] && [ -z "$topic_photo" ]; then
	echo_error "MQTT topic for sending snapshot is not set"
	exit 1
fi

[ -z "$client_id" ] && client_id=$(hostname)
[ -z "$port" ] && port=1883

message=$(date +"$message")

# mosquitto_pub with the broker settings passed as arguments. Building a
# shell string and running it through sh -c let a password or message with
# spaces, quotes or $(...) be re-parsed (and re-expanded) by the shell.
mqtt_pub() {
	set -- mosquitto_pub "$@" -h "$host" -p "$port" -i "$client_id"
	[ "true" = "$verbose" ] && set -- "$@" -d
	[ -n "$username" ] && set -- "$@" -u "$username"
	[ -n "$password" ] && set -- "$@" -P "$password"
	if [ "true" = "$use_ssl" ]; then
		set -- "$@" --capath /etc/ssl/certs
		[ "true" = "$tls_skip_verify" ] && set -- "$@" --insecure
	fi
	"$@"
}

failed=0

if message_looks_like_json "$message"; then
	tmpfile="$(mktemp -u).json"
	echo "$message" > $tmpfile
	garbage="$garbage $tmpfile"

	[ "true" = "$verbose" ] && echo_command "publish $tmpfile to $topic"
	if ! mqtt_pub -t "$topic" -f "$tmpfile"; then
		echo_error "Failed to send MQTT message"
		failed=1
	fi
else
	[ "true" = "$verbose" ] && echo_command "publish message to $topic"
	if ! mqtt_pub -t "$topic" -m "$message"; then
		echo_error "Failed to send MQTT message"
		failed=1
	fi
fi

if [ -n "$file" ] && [ -f "$file" ]; then
	[ "true" = "$verbose" ] && echo_command "publish $file to $topic"
	if ! mqtt_pub -t "$topic" -f "$file"; then
		echo_error "Failed to send file via MQTT"
		failed=1
	fi
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	if [ -z "$photo" ]; then
		echo_error "Failed to get photo"
		failed=1
	else
		[ "true" = "$verbose" ] && echo_command "publish $photo to $topic_photo"
		if ! mqtt_pub -t "$topic_photo" -f "$photo"; then
			echo_error "Failed to send photo via MQTT"
			failed=1
		fi
	fi
fi

if [ "true" = "$send_video" ]; then
	video=$(copy_video)
	if [ -z "$video" ]; then
		echo_error "Failed to get video"
		failed=1
	else
		[ "true" = "$verbose" ] && echo_command "publish $video to $topic_video"
		if ! mqtt_pub -t "$topic_video" -f "$video"; then
			echo_error "Failed to send video via MQTT"
			failed=1
		fi
	fi
fi

exit $failed
