#!/bin/env sh
# Sends data to ntfy.sh
# https://docs.ntfy.sh/publish/

. /usr/share/prudynt-helpers
. /usr/share/send2common

domain="ntfy"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      NTFY server FQDN or IP address
	-p port      NTFY server port
	-u username  NTFY username
	-P password  NTFY password
	-T token     NTFY token
	-t topic     Topic
	-n title     Message title
	-m message   Message body
	-a URL       Attachment URL
	-c URL       Click URL
	-f file      Attach file
	-i URL       Icon URL
	-z N         Priority: 1-lowest, 5-highest
	-d N         Delay
	-S           Send photo
	-V           Send video
	-v           Verbose output
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	actions=$(get_value actions)
	attach=$(get_value attach)
	call=$(get_value call)
	click=$(get_value click)
	delay=$(get_value delay)
	email=$(get_value email)
	filename=$(get_value filename)
	host=$(get_value host)
	icon=$(get_value icon)
	message=$(get_value message)
	password=$(get_value password)
	port=$(get_value port)
	priority=$(get_value priority)
	tags=$(get_value tags)
	title=$(get_value title)
	token=$(get_value token)
	topic=$(get_value topic)
	twilio_token=$(get_value twilio_token)
	use_ssl=$(get_value use_ssl)
	username=$(get_value username)
}

read_config

while getopts a:c:d:h:i:m:n:t:p:u:vz:P:T:f:SV flag; do
	case "$flag" in
		a) attach=$OPTARG ;;
		c) click=$OPTARG ;;
		d) delay=$OPTARG ;;
		h) host=$OPTARG ;;
		i) icon=$OPTARG ;;
		m) message=$OPTARG ;;
		n) title=$OPTARG ;;
		p) port=$OPTARG ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		z) priority=$OPTARG ;;
		P) password=$OPTARG ;;
		T) token=$OPTARG ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) filename=$OPTARG; send_photo="false"; send_video="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

# use config settings only if not set from command line
if [ -z "$filename" ] && [ "true" != "$send_photo" ] && [ "true" != "$send_video" ]; then
        send_photo=$(get_value send_photo)
        send_video=$(get_value send_video)
fi

if [ -z "$topic" ]; then
	echo_error "NTFY topic is not set"
	exit 1
fi

[ -z "$host" ] && host="ntfy.sh"
[ -z "$port" ] && port=80
[ "true" = "$use_ssl" ] && scheme="https" || scheme="http"

command="$CURL -X POST"

if [ -n "$priority" ]; then
	command="$command -H 'p: $priority'"
fi

if [ "true" = "$verbose" ]; then
	command="$command --verbose"
else
	command="$command --silent"
fi

if [ -n "$token" ]; then
	command="$command -H 'Authorization: Bearer $token'"
elif [ -n "$username" ] && [ -n "$password" ]; then
	command="$command -u $username:$password"
fi

if [ -n "$message" ]; then
	message="$(date +"$message")"
	command="$command -H 'Message: $message'"
fi

if [ -n "$title" ]; then
	title="$(date +"$title")"
	command="$command -H 'Title: $title'"
fi

# Seems only one attachment is allowed at a time
# so we prioritize file over snapshot over video.
if [ -n "$filename" ] && [ -f "$filename" ]; then
	command="$command -T $filename -H 'Filename: $(basename "$filename")'"
elif [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	[ -f "$photo" ] && command="$command -T $photo -H 'Filename: $(basename "$photo")'"
elif [ "true" = "$send_video" ]; then
	video=$(copy_video)
	[ -f "$video" ] && command="$command -T $video -H 'Filename: $(basename "$video")'"
fi

command="$command $scheme://$host:$port/$topic"

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send NTFY message"
	exit 1
fi

exit 0
