#!/bin/sh

chip=$(ipcinfo -c)
family=$(ipcinfo -f)

basic() {
	# set boot delay
	fw_setenv bootdelay 0
	# don't load f2fs module (disabled in kernel)
	sed -i "s!f2fs!#f2fs!g" /etc/modules
	# freely uart for telemetry
	sed -i "s!console::respawn:/sbin/getty -L console 0 vt100 # GENERIC_SERIAL!#console::respawn:/sbin/getty -L console 0 vt100 # GENERIC_SERIAL!g" /etc/inittab

	# tune socket buffer
	echo "net.core.rmem_default=512000" >> /etc/sysctl.conf
}

prefix=${family}

majestic_generic() {
	yaml-cli -s .isp.slowShutter disabled
	# enable digital image stabilization
	# yaml-cli -s .isp.dis true
	yaml-cli -s .image.contrast 50
	yaml-cli -s .image.luminance 50
	yaml-cli -s .video0.size 1920x1080
	yaml-cli -s .video0.fps 30
	yaml-cli -s .video0.bitrate 5120
	yaml-cli -s .video0.codec h264
	yaml-cli -s .video0.rcMode cbr
	yaml-cli -s .video0.gopSize 1.5
	# lowdelay support only imx307 sensor
	if [ ${sensor} = "imx307" ]; then
		yaml-cli -s .isp.lowDelay true
		# yaml-cli -s .video0.sliceUnits 4
	fi
	if [ ${sensor} = "imx335" ]; then
		yaml-cli -s .isp.drc 350
		yaml-cli -s .isp.sensorConfig /etc/sensors/imx335_i2c_4M.ini
	fi
	yaml-cli -s .hls.enabled false
	yaml-cli -s .netip.enabled false
	yaml-cli -s .jpeg.enabled false
}

streamer() {
	if [ -f /usr/bin/majestic ]; then
		majestic_generic
		# outgoing rtp stream to udp
		yaml-cli -s .outgoing.enabled true
		yaml-cli -s .outgoing.server udp://127.0.0.1:5600
	fi

	if [ -f /usr/bin/venc ]; then
		if [ ${sensor} = "imx335" ]; then
			sed -i "s!version=200_imx307B!version=300_imx335B!g" /etc/venc.conf
			sed -i "s!size=720p!size=1292x972!g" /etc/venc.conf
		fi
	fi
}

finish() {
	# complete tweaks and add marker
	touch /etc/system.ok
	echo "Preparing system done."
	reboot
}

case "$1" in
	t31l | t31n | t31x | t31zx)
		echo "Preparing system tweaks for ${chip}..."

		basic
		streamer
		finish
		;;
	*)
		echo "Usage: $0 {t31l|t31n|t31x|t31zx}"
		exit 1
esac
