#!/bin/sh

. /etc/init.d/rc.common

config="/etc/imp.conf"

check_imp() {
	local soc=$(soc -f)
	local isp_path
	if [ "$soc" = "t10" ] || [ "$soc" = "t20" ]; then
		isp_path="/proc/jz/isp/isp_info"
	else
		isp_path="/proc/jz/isp/isp-fs"
	fi

	echo -n "Connecting to libimp-control: "
	local i=10
	while [ "$i" -gt 0 ]; do
		if grep -Eq "running|Software" $isp_path; then
			run "imp-control getdeviceid > /dev/null"
			check_result
			return
		fi
		i=$((i-1))
		sleep 1
	done
	die "Timeout. Cannot connect to libimp-control."
}

restore_config() {
	echo -n "Restoring IMP Configuration: "
	[ -f "$config" ] || quit "Nothing to restore"

	while read -r line; do
		run "imp-control $line > /dev/null"
	done < $config
	check_result
}

start() {
	starting
	is_streamer_disabled && quit "Streamer disabled" || ok

	check_imp
	restore_config
}

case "$1" in
	start | restart | reload)
		start
		;;
	stop)
		:
		;;
	*)
		die "Usage: $0 {start|restart|reload}"
		;;
esac

exit 0
