#!/bin/sh

config="/etc/imp.conf"

check_imp() {
	echo -n "Connecting to libimp-control: "
	i=0
	platform=$(soc -f)
	if [ "$platform" = "t10" ] || [ "$platform" = "t20" ]; then
		isp_path="/proc/jz/isp/isp_info"
	else
		isp_path="/proc/jz/isp/isp-fs"
	fi

	while :; do
		grep -Eq "running|Software" $isp_path &&
			imp-control getdeviceid > /dev/null &&
			echo " OK" && return
		echo -n "."
		i=$((i + 1))
		sleep 1
		[ $i -gt 10 ] && echo " FAIL (timeout)" && exit 1
	done
}

start() {
	check_imp
	echo -n "Restoring IMP Configuration: "
	if [ -f "$config" ]; then
		echo
		while read -r line; do
			echo -e " * $line"
			imp-control $line > /dev/null
		done < $config
		echo "Done"
	else
		echo "Disabled"
		return
	fi
}

case "$1" in
	start | restart | reload)
		start
		;;
	stop)
		:
		;;
	*)
		echo "Usage: $0 {start|restart|reload}"
		exit 1
		;;
esac

exit 0
