#!/bin/sh

. /usr/share/common

config="/etc/imp.conf"

check_imp() {
	local isp_path

	case "$SOC_FAMILY" in
		t10 | t20)
			isp_path="/proc/jz/isp/isp_info" ;;
		*)
			isp_path="/proc/jz/isp/isp-fs" ;;
	esac

	echo "Connect to libimp-control"
	local i=10
	while [ "$i" -gt 0 ]; do
		if grep -Eq "running|Software" $isp_path; then
			imp-control getdeviceid > /dev/null
			echo -n " "
			return
		fi
		i=$((i-1))
		echo -n "."
		sleep 1
	done
	die " Timeout"
}

restore_config() {
	echo -n "Restore IMP Configuration: "
	if [ -f "$config" ]; then
		while read -r line; do
			imp-control $line > /dev/null
		done < $config
	else
		echo "Nothing to restore"
		exit 1
	if
}

start() {
	is_streamer_disabled && quit "Streamer disabled"
	check_imp
	restore_config
}

case "$1" in
	start)
		starting
		start
		;;
	stop)
		true
		;;
	reload | restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
