THINGINO_ADDONS_VERSION = 1.0
THINGINO_ADDONS_SITE_METHOD = local
THINGINO_ADDONS_SITE = $(THINGINO_ADDONS_PKGDIR)/files

define THINGINO_ADDONS_LINUX_CONFIG_FIXUPS_NETFILTER
	$(call KCONFIG_ENABLE_OPT,CONFIG_IP_ADVANCED_ROUTER)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_PRIVACY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_ROUTER_PREF)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_ROUTE_INFO)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_OPTIMISTIC_DAD)
	$(call KCONFIG_SET_OPT,CONFIG_IPV6_SIT,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_NDISC_NODETYPE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_MULTIPLE_TABLES)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_SUBTREES)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_MROUTE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NETFILTER)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_ADVANCED)
	$(call KCONFIG_SET_OPT,CONFIG_NF_CONNTRACK,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NF_CONNTRACK_PROCFS)
	$(call KCONFIG_SET_OPT,CONFIG_NETFILTER_XTABLES,m)
	$(call KCONFIG_SET_OPT,CONFIG_NETFILTER_XT_MARK,m)
	$(call KCONFIG_SET_OPT,CONFIG_NETFILTER_XT_TARGET_LOG,m)
	$(call KCONFIG_SET_OPT,CONFIG_NETFILTER_XT_TARGET_TCPMSS,m)
	$(call KCONFIG_SET_OPT,CONFIG_NETFILTER_XT_MATCH_STATE,m)
	$(call KCONFIG_SET_OPT,CONFIG_NF_DEFRAG_IPV4,m)
	$(call KCONFIG_SET_OPT,CONFIG_NF_CONNTRACK_IPV4,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NF_CONNTRACK_PROC_COMPAT)
	$(call KCONFIG_SET_OPT,CONFIG_IP_NF_IPTABLES,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP_NF_FILTER,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP_NF_TARGET_REJECT,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP_NF_MANGLE,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP6_NF_IPTABLES,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP6_NF_FILTER,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP6_NF_TARGET_REJECT,m)
	$(call KCONFIG_SET_OPT,CONFIG_IP6_NF_MANGLE,m)
	$(call KCONFIG_SET_OPT,CONFIG_DNS_RESOLVER,m)
endef

ifeq ($(BR2_PACKAGE_THINGINO_ADDONS_NETFILTER),y)
	THINGINO_ADDONS_LINUX_CONFIG_FIXUPS += $(THINGINO_ADDONS_LINUX_CONFIG_FIXUPS_NETFILTER)
endif

$(eval $(generic-package))
