osd0.0.font_size = 18
osd0.1.font_size = 18
osd0.2.font_size = 18
image.hflip = 0
image.vflip = 0
sensor.i2c_addr = 0x30
sensor.width = 1280
sensor.height = 720
sensor.fps = 25
video0.width = 1280
video0.height = 720
video1.width = 640
video1.height = 360
