#!/bin/sh

. /usr/share/common

[ -z "$1" ] && die "Usage: $0 <mmc port> [-r]"

endpoint=/sys/devices/platform/jzmmc_v1.2.$1/present
[ -f $endpoint ] || die "No endpoint $endpoint"

# Do REMOVE if -r supplied, otherwise INSERT
[ "$2" = "-r" ] && action=REMOVE || action=INSERT
echo $action > $endpoint

exit 0
