#!/bin/sh

# Configuration of the bridge should be done in /etc/network/interfaces.d/bridgeX
# Read more at https://wiki.debian.org/BridgeNetworkConnections

quit() { echo "$1"; exit 0; }

[ -x /sbin/brctl ] || \
	quit "No bridge ports control utility"

[ -z "$IF_BRIDGE_PORTS" ] && \
	quit "No bridge ports defined"

case "$IF_BRIDGE_PORTS" in
	none)
		INTERFACES=""
		;;

	all)
		INTERFACES=$(grep eth /proc/net/dev | sed 's/\(\ *\)\(eth[^:]*\)\(.*\)/\2/')
		;;

	*)
		INTERFACES="$IF_BRIDGE_PORTS"
		;;
esac

brctl delbr $IFACE

for i in $INTERFACES; do
	ip link set $i down
done
