#!/bin/sh

if [ ! -x /sbin/vconfig ]; then
	echo "No VLAN support"
	exit 0
fi

if [ -z "$IF_VLAN_RAW_DEVICE" ] && [ -z "$(echo $IFACE | grep '.\+\.[0-9]\+$')" ]; then
	echo "$IFACE: No VLAN"
	exit 0
fi

vconfig rem $IFACE
