################################################################################
#
# thingino-mosquitto-20x
#
################################################################################

THINGINO_MOSQUITTO_20X_VERSION = 2.0.22
THINGINO_MOSQUITTO_20X_SITE = https://sources.buildroot.net/mosquitto
THINGINO_MOSQUITTO_20X_SOURCE = mosquitto-$(THINGINO_MOSQUITTO_20X_VERSION).tar.gz
THINGINO_MOSQUITTO_20X_LICENSE = EPL-2.0 or EDLv1.0
THINGINO_MOSQUITTO_20X_LICENSE_FILES = LICENSE.txt epl-v20 edl-v10
THINGINO_MOSQUITTO_20X_INSTALL_STAGING = YES

THINGINO_MOSQUITTO_20X_MAKE_DIRS = lib client
THINGINO_MOSQUITTO_20X_MAKE_OPTS = prefix=/usr WITH_CJSON=no

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_USE_MBEDTLS),y)
THINGINO_MOSQUITTO_20X_DEPENDENCIES += mbedtls
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_TLS=yes TLS_IMPL=mbedtls WITH_TLS_PSK=no
else ifeq ($(BR2_PACKAGE_OPENSSL),y)
THINGINO_MOSQUITTO_20X_DEPENDENCIES += host-pkgconf openssl toolchain-external-custom
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_TLS=yes TLS_IMPL=openssl
else
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_TLS=no WITH_TLS_PSK=no
endif

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_LIBWEBSOCKETS),y)
THINGINO_MOSQUITTO_20X_DEPENDENCIES += libwebsockets
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_WEBSOCKETS=yes
endif

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_BROKER),y)
THINGINO_MOSQUITTO_20X_MAKE_DIRS += src
else
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_BROKER=no
endif

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_BROKER_DYNAMIC_SECURITY_PLUGIN),y)
THINGINO_MOSQUITTO_20X_DEPENDENCIES += cjson openssl
THINGINO_MOSQUITTO_20X_MAKE_DIRS += plugins
THINGINO_MOSQUITTO_20X_MAKE_OPTS := $(filter-out WITH_CJSON=no,$(THINGINO_MOSQUITTO_20X_MAKE_OPTS))
THINGINO_MOSQUITTO_20X_MAKE_OPTS += WITH_CJSON=yes
endif

define THINGINO_MOSQUITTO_20X_CONFIGURE_CMDS
	:
endef

define THINGINO_MOSQUITTO_20X_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(TARGET_CONFIGURE_OPTS) \
		DIRS="$(THINGINO_MOSQUITTO_20X_MAKE_DIRS)" \
		$(THINGINO_MOSQUITTO_20X_MAKE_OPTS)
endef

define THINGINO_MOSQUITTO_20X_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(TARGET_CONFIGURE_OPTS) \
		DIRS="$(THINGINO_MOSQUITTO_20X_MAKE_DIRS)" \
		$(THINGINO_MOSQUITTO_20X_MAKE_OPTS) \
		DESTDIR=$(STAGING_DIR) install
endef

define THINGINO_MOSQUITTO_20X_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(TARGET_CONFIGURE_OPTS) \
		DIRS="$(THINGINO_MOSQUITTO_20X_MAKE_DIRS)" \
		$(THINGINO_MOSQUITTO_20X_MAKE_OPTS) \
		DESTDIR=$(TARGET_DIR) install
	rm -f $(TARGET_DIR)/etc/mosquitto/*.example
	$(THINGINO_MOSQUITTO_20X_INSTALL_TARGET_CONF)
endef

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_BROKER),y)
define THINGINO_MOSQUITTO_20X_INSTALL_TARGET_CONF
	$(INSTALL) -D -m 0644 $(@D)/mosquitto.conf \
		$(TARGET_DIR)/etc/mosquitto/mosquitto.conf
endef
endif

ifeq ($(BR2_PACKAGE_THINGINO_MOSQUITTO_20X_BROKER),y)
define THINGINO_MOSQUITTO_20X_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(THINGINO_MOSQUITTO_20X_PKGDIR)/files/S50mosquitto \
		$(TARGET_DIR)/etc/init.d/S50mosquitto
endef

define THINGINO_MOSQUITTO_20X_USERS
	mosquitto -1 mosquitto -1 * - - - Mosquitto user
endef
endif

$(eval $(generic-package))
