#!/bin/sh

. /usr/share/common

start() {
	echo_title "U-Boot environment"
	# Dumps the U-Boot environment to a file automatically
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
