#!/bin/sh

. /usr/share/common

start() {
	echo "Creating U-Boot environment dump in $ENV_DUMP_FILE"
	refresh_env_dump
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
