#!/bin/sh

LINK_FILE="/var/run/boot"
DAEMON_ARGS="0.05 $LINK_FILE"

. /usr/share/common

start() {
	echo "Starting LED daemon..."

	start_daemon
	touch $LINK_FILE
}

stop() {
	echo "Stopping LED daemon..."

	rm -f $LINK_FILE
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
