#!/bin/sh

LINK_FILE="/var/run/boot"
DAEMON_ARGS="0.05 $LINK_FILE"

. /etc/init.d/rc.common


start() {
	starting
	start_daemon
	touch $LINK_FILE
}

stop() {
	stopping
	rm -f $LINK_FILE
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
