#!/bin/sh

. /usr/share/common

start() {
	echo "Setting initial system time"

	if [ ! -f "$FILE_OS_RELEASE" ]; then
		echo "- No release file found, not setting system clock"
		exit 1
	fi

	if date -u -s "@$(stat -c%X "$FILE_OS_RELEASE")" >/dev/null; then
		echo "- $(date) (fail-safe)"
	else
		echo "- Failed to set time"
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
