#!/bin/sh

. /etc/init.d/rc.common

usb_console_en && [ -f /etc/init.d/F02failsafe-usb ] && exit

echo_c 104 "\nPress the [f] key to enter failsafe mode\n"

stty -icanon min 0 time 20 -echo
key=$(dd bs=1 count=1 2>/dev/null)
stty sane

if [ "$key" = "f" ]; then
	echo_c 118 "Failsafe mode..."
	touch /tmp/.fs
	. /etc/profile
	exec setsid /sbin/getty -n -l /bin/sh -L console 0 vt100
fi

print_release

/etc/init.d/rcS

exit 0
