#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-T 60 /dev/watchdog"

start() {
	starting
	[ "true" = "$(get disable_watchdog)" ] && quit "Disabled"
	start_daemon
}

stop() {
	stopping
	stop_daemon
}

case "$1" in
	start | stop)
		$1
		;;

	restart | reload)
		stop
		sleep 1
		start
		;;

	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
