#!/bin/sh

. /etc/init.d/rc.common

# DAEMON_ARGS="-T 60 /dev/watchdog"
DAEMON_ARGS="/dev/watchdog"

start() {
	starting
	[ "true" = "$(envvar disable_watchdog)" ] && disabled
	start_daemon
}

stop() {
	stopping
	stop_daemon
	# start-stop-daemon -q -K -s KILL -n $DAEMON
}

case "$1" in
	start | stop)
		$1
		;;

	restart | reload)
		stop
		sleep 1
		start
		;;

	*)
		die 1 "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
