#!/bin/sh

. /etc/init.d/rc.common

for prefix in F; do
	for i in $(ls /etc/init.d/${prefix}??* 2> /dev/null); do
		# Ignore dangling symlinks (if any).
		[ -f "$i" ] || continue

		/bin/sh -c "$i" 2>&1
	done
done

exit 0
