#!/bin/sh

. /etc/init.d/rc.common

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.

for prefix in K S; do
	for i in $(ls -r /etc/init.d/${prefix}??* 2> /dev/null); do
		# Ignore dangling symlinks (if any).
		[ -f "$i" ] || continue

		/bin/sh -c "$i stop" 2>&1 | tee >(logger -p daemon.info -t $i)
	done
done

exit 0
