#!/bin/sh

. /etc/init.d/rc.common

echo_c 196 "\n\nGoing to reboot!\n"

# Run init scripts in reversed numerical order.
for i in $(find /etc/init.d/ -name "[KS]*" -executable | sort -nr); do
	/bin/sh -c "$i stop"
	# | log
done

exit 0
