#!/bin/sh

export SENSOR=$(cat /etc/sensor/model)
export SOC=$(/usr/sbin/soc -f)
export TZ=$(cat /etc/TZ)

# Seritificates for curl in non-interactive shell
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Set the firmware creation time as the base system time
/bin/date -s @$(stat -t /etc/os-release | cut -d" " -f12)

# Start all init scripts in /etc/init.d
# executing them in numerical order.
execute_and_log() {
	script="$1"
	mkfifo /tmp/initlogpipe

	while IFS= read -r line; do
		echo "$line" | logger -t "$script"
		echo "$line"
	done < /tmp/initlogpipe &

	logger_pid=$!

	if /bin/sh -c "$script start" > /tmp/initlogpipe 2>&1; then
		: # Success
	else
		: # Failure
	fi

	rm -f /tmp/initlogpipe
}

for i in /etc/init.d/S??*; do
	[ ! -f "$i" ] && continue
	execute_and_log "$i" &
	wait
done

exit 0
