#!/bin/sh

DAEMON_ARGS="-n -C64 -t -D $RSYSLOG_ADDRESS"

RSYSLOG_IP=$(fw_printenv -n rsyslog_ip)
RSYSLOG_PORT=$(fw_printenv -n rsyslog_port)
if [ -n "$RSYSLOG_IP" ]; then
	DAEMON_ARGS="$DAEMON_ARGS -R $RSYSLOG_IP"
	[ -n "$RSYSLOG_PORT" ] && DAEMON_ARGS="$DAEMON_ARGS:$RSYSLOG_PORT"
	[ "true" = "$(fw_printenv -n rsyslog_local)" ] && DAEMON_ARGS="$DAEMON_ARGS -L"
fi

. /etc/init.d/rc.common

start() {
	starting
	start_daemon
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
