#! /bin/sh

DAEMON_ARGS="-d /etc/seedrng"

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		start_daemon
		;;
	stop)
		stopping
		stop_daemon
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac
