#! /bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-d /etc/seedrng"

case "$1" in
        start | stop | restart | reload)
        	starting
                start_daemon_with_pid
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
