#! /bin/sh

DAEMON="seedrng"
DAEMON_ARGS="-d /etc/seedrng"
PIDFILE="/run/$DAEMON.pid"

. /usr/share/common

start() {
	echo "Starting seedrng..."

	start_daemon
}

stop() {
	echo "Stopping seedrng..."

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
