#!/bin/sh

start() {
	echo -n "Setting Timezone: "
	# Get the timezone from the u-boot environment variable
	timezone=$(fw_printenv -n timezone 2> /dev/null)
	if [ -z "$timezone" ]; then
		echo "Using system default"
		exit 1
	fi

	echo "$timezone"

	# Check if the values in /etc/timezone and /etc/TZ match the ones from fw_printenv
	current_timezone=$(cat /etc/timezone 2> /dev/null)
	current_tz_value=$(cat /etc/TZ 2> /dev/null)

	if [ "$timezone" = "$current_timezone" ] && [ "$timezone" = "$current_tz_value" ]; then
		echo "Timezone settings are up to date"
		exit 0
	fi

	# Search for the timezone in the file
	tzjs="/var/www/a/tz.js"
	matching_line=$(grep -i -F "$timezone" $tzjs)
	if [ -z "$matching_line" ]; then
		echo "Timezone not found in $tzjs"
		exit 1
	fi

	# Extract the value associated with the timezone
	value=$(echo "$matching_line" | sed "s/^.*v:'\([^']*\)'.*$/\1/")

	# Write the TZ file first
	echo $value > /etc/TZ

	# Then write the timezone file
	echo $timezone > /etc/timezone

	export TZ=$value

	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
