#!/bin/sh

. /etc/init.d/rc.common

set_timezone() {
	# Get the timezone from the u-boot environment variable
	timezone=$(get timezone 2> /dev/null)
	if [ -z "$timezone" ]; then
		warn "Timezone value not found in environment"
		return 1
	fi

	# Check if the values in /etc/ match those in environment
	current_timezone=$(cat /etc/timezone)
	current_tz_value=$(cat /etc/TZ)
	if [ "$timezone" = "$current_timezone" ] && [ "$timezone" = "$current_tz_value" ]; then
		info "Timezone is already set"
		return 0
	fi

	# Search for the timezone in the file
	tzjs="/var/www/a/tz.js"
	matching_line=$(grep -i -F "$timezone" $tzjs)
	if [ -z "$matching_line" ]; then
		warn "Timezone $timezone not found in $tzjs"
		return 1
	fi

	# set timezone in system environment
	tz=$(echo "$matching_line" | sed "s/^.*v:'\([^']*\)'.*$/\1/")
	export TZ=$tz
	info "Set TZ to $tz ($timezone)"

	# save timezone
	echo $tz > /etc/TZ
	echo $timezone > /etc/timezone
	info "Save timezone configuration"
}

set_time() {
	date=$(date -s @$(stat -c%X /etc/os-release))
	info "Set fail-safe system time to: $date"
}

case "$1" in
	start)
		starting
		set_timezone
		set_time
		;;
	stop)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
