#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		date=$(date -s @$(stat -c%X /etc/os-release))
		quit "Set time to $date (fail-safe)"
		;;
	stop)
		stopping
		ok
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
