#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting

		[ -x /sbin/dusk2dawn ] || die "dusk2dawn not found"

		if grep -q dusk2dawn $CRONTABS; then
			info "already in crontab"
		else
			printf "# run dusk2dawn nightly at 0:00\n0 0 * * * dusk2dawn\n" >> $CRONTABS
			info "dusk2dawn added to crontab"
		fi
		ok
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
