#!/bin/sh

ENV_TXT="/etc/uenv.txt"

start () {
	echo -n "U-Boot ENV: "

	boot_status=$(fw_printenv -n boot_complete)
	if [ -f "$ENV_TXT" ] && { [ "$boot_status" = "false" ] || [ -z "$boot_status" ]; }; then
			ENV_TMP=$(mktemp)
			sed 's/=/ /' $ENV_TXT >$ENV_TMP
			fw_setenv -s $ENV_TMP
			fw_setenv boot_complete true
			echo "U-Boot ENV updated. Rebooting now..."
			sync; sleep 2
			reboot -f
	else
			echo "OK"
	fi
}

case "$1" in
start)
	$1
	;;
stop|restart)
	true
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
