#!/bin/sh

case "$1" in
start)
	HOSTNAME=$(fw_printenv -n hostname 2>/dev/null)
	echo -n "Setting hostname: "
	if [ -n "$HOSTNAME" ]; then
			hostname "$HOSTNAME"
	fi
	echo "OK"
	;;
stop)
	true
	;;
*)
	echo "Usage: $0 {start}"
	exit 1
	;;
esac

exit 0
