#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
#		for file in $(find /etc/ -path '*/sysctl\.*' -name '*.conf'); do
#		sysctl -q -p $file
#		done
		sysctl -q -p || die "Failed to apply sysctl settings"
		check_result
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
