#!/bin/sh

start() {
	echo "Applying sysctl settings..."

	if sysctl -q -p; then
		echo "Sysctl settings applied"
	else
		echo "Failed to apply sysctl settings"
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
