#!/bin/sh

. /etc/init.d/rc.common

ENV_FILE="/etc/uenv.txt"

provision_environment() {
	[ -f "$ENV_FILE" ] || die "$ENV_FILE is missing"

	local tmpfile=$(mktemp)
	echo "boot_complete true" >> $tmpfile
	sed 's/=/ /' $ENV_FILE >> $tmpfile
	echo "sysupgrade_complete false" >> $tmpfile
	fw_setenv -s $tmpfile
	ok
	echo_c 220 "\nU-Boot environment updated. Rebooting in 30 seconds..."
	sync
	reboot -d 30 -f
#	echo wdt > /proc/jz/reset/reset
}

case "$1" in
	start)
		starting
		[ "true" = "$(get boot_complete)" ] || provision_environment
		ok
		;;
	stop)
		stopping
		ok
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
