#!/bin/sh

. /etc/init.d/rc.common

ENV_TXT="/etc/uenv.txt"

case "$1" in
	start)
		starting
		[ ! -f "$ENV_TXT" ] && ok && exit 0
		[ "true" = "$(envvar boot_complete)" ] && ok && exit 0

		ENV_TMP=$(mktemp)
		sed 's/=/ /' $ENV_TXT > $ENV_TMP
		echo "boot_complete true" >> $ENV_TMP
		fw_setenv -s $ENV_TMP

		info "U-Boot ENV updated. Rebooting now..."

		/etc/init.d/K99watchdog stop
		sync
		sleep 2
		reboot -f
		;;
	stop | restart)
		true
		;;
	*)
		die 1 "Usage: $0 {start}"
		;;
esac

exit 0
