#!/bin/sh

DAEMON="hostname"

. /etc/init.d/rc.common

update_hosts_file() {
	sed -i "/^127.0.1.1/s/\t.*$/\t$1/" /etc/hosts
}

start_hostname() {
	HOSTNAME=$(fw_printenv -n hostname 2>/dev/null)
	[ -z "$HOSTNAME" ] && {
		OS_NAME=$(sed -n 's/^HOSTNAME=//p' /etc/os-release)
		MAC_SUFFIX=$(fw_printenv -n wlanmac | sed 's/://g;s/.*\(....\)$/\1/')
		HOSTNAME="${OS_NAME}-${MAC_SUFFIX}"
	}
	starting
	hostname "$HOSTNAME"
	[ $? -eq 0 ] && { echo "OK"; update_hosts_file "$HOSTNAME"; } || echo "FAIL"
}

case "$1" in
	start) 
		start_hostname
		;;
	stop) 
		true
		;;
	*) 
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

exit 0
