#!/bin/sh

. /etc/init.d/rc.common

FILE_HOSTNAME=/etc/hostname
FILE_HOSTS=/etc/hosts
FILE_OS_RELEASE=/etc/os-release

set_hostname() {
	[ "$hostname" = "$(hostname)" ] || run "hostname $hostname"
	info "Hostname is $(hostname)"
}

update_hostname() {
	[ "$(cat $FILE_HOSTNAME)" = "$hostname" ] && return
	run "echo $hostname > $FILE_HOSTNAME"
}

update_hosts() {
	local ip="127.0.1.1"
	[ "$(sed -nE "s/^$ip\s+(.*)$/\1/p" $FILE_HOSTS)" = "$hostname" ] && return
	run "sed -i /^$ip/d $FILE_HOSTS"
	run "echo -e $ip\\\t$hostname >> $FILE_HOSTS"
}

update_os_release() {
	[ "$(sed -nE "s/^hostname=(.*)$/\1/p" $FILE_OS_RELEASE)" = "$hostname" ] && return
	run "sed -i \"/^hostname/s/=.*$/=$hostname/\" $FILE_OS_RELEASE"
}

generate() {
	os_hostname=$(sed -n 's/^HOSTNAME=//p' /etc/os-release)
	info "OS hostname: $os_hostname"

	mac_suffix=$(fw_printenv -n wlanmac | sed -E 's/://g;s/.*(.{4})$/\1/')
	info "MAC suffix: $mac_suffix"

	hostname="${os_hostname}-$mac_suffix"
	info "Generated hostname: $hostname"
}

case "$1" in
	start)
		starting
		hostname=$(hostname)
		[ -z "$hostname" ] && generate
		set_hostname
		update_hosts
		#update_os_release
		update_hostname
		run "export HOSTNAME=\"$hostname\""
		ok
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
