#!/bin/sh

. /usr/share/common

start() {
	echo "Configuring DNS..."

	if [ -f "$RESOLV_DEFAULT_FILE" ]; then
		cat "$RESOLV_DEFAULT_FILE" > "$RESOLV_WORKING_FILE"
		echo "- Using default DNS servers"
	else
		echo "- No static DNS servers found"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
