#!/bin/sh

. /etc/init.d/rc.common

set_pin() {
	if [ "$(gpio value $1)" -eq $2 ]; then
		info "Pin $1 is already set to $2"
	else
		info "Switch pin $1 to $2"
		run "gpio set $1 $2"
	fi
}

start() {
        starting
        DEFAULT_PINS=$(fw_printenv -n gpio_default)
        for pin_raw in $(fw_printenv | grep ^gpio_led_ | awk -F= '{print $2}'); do
        	[ "$pin_raw" = "${pin_raw//[^0-9]/}" ] && pin_raw="${pin_raw}O"
                pin="${pin_raw:0:-1}"
                suffix="${pin_raw:0-1}"
                case "$suffix" in
                        o) pin_on=0; pin_off=1 ;;
                        O) pin_on=1; pin_off=0 ;;
                        *) die "Unknown suffix!"
                esac

                if echo "$DEFAULT_PINS" | grep -E "\b$pin_raw\b" > /dev/null; then
                        set_pin $pin $pin_on
		else
                        set_pin $pin $pin_off
                fi
        done
        ok
}

case "$1" in
        start | restart | reload)
                start
                ;;
        stop)
                true
                ;;
        *)
                die "Usage: $0 {start|stop|restart|reload}"
                ;;
esac

exit 0
