#!/bin/sh

. /usr/share/common

start() {
	echo_title "Configuring USB"

	if [ -z "$gpio_usb_en" ]; then
		echo_warning "USB power GPIO is not set"
		exit 1
	fi

	if [ "$gpio_usb_en" = "${gpio_usb_en//[^0-9]/}" ]; then
		gpio_usb_en="${gpio_usb_en}O"
	fi

	pin="${gpio_usb_en:0:-1}"
	case "${gpio_usb_en#$pin}" in
		o)
			if ! gpio set $pin 0; then
				echo_error "Failed to set USB power GPIO $pin to $state"
				exit 1
			fi
			;;
		O)
			if ! gpio set $pin 1; then
				echo_error "Failed to set USB power GPIO $pin to $state"
				exit 1
			fi
			;;
		*)
			echo_error "Invalid state $state"
			exit 1
			;;
	esac

	echo_info "Set USB power GPIO $pin to $state"
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
