#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		{
			info "IRCUT filter engaged"
			ircut off > /dev/null 2>&1
			sleep 0.5
			info "IRCUT filter disengaged"
			ircut on > /dev/null 2>&1
		}
		ok
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
