#!/bin/sh

DAEMON="dusk2dawn"
CRONTABS="/etc/cron/crontabs/root"

start() {
	echo "Setting $DAEMON..."

	if [ ! -x /sbin/$DAEMON ]; then
		echo "- $DAEMON not found"
		exit 1
	fi

	if grep -q $DAEMON $CRONTABS; then
		echo "- $DAEMON already in crontab"
	else
		printf "# run $DAEMON nightly at 0:00\n0 0 * * * $DAEMON\n" >> $CRONTABS
		echo "- $DAEMON added to crontab"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
