#!/bin/sh

. /etc/init.d/rc.common

SOC_FAMILY=$(/usr/sbin/soc -f)
SOC_MODEL=$(/usr/sbin/soc -m)

MMC_MODULE="jzmmc_v12"

MMC_GPIO_CD=$(get gpio_mmc_cd)
MMC_GPIO_PWR=$(get gpio_mmc_power)

# Default CD-PIN for Ingenic PB27 (GPIO59)
[ -z "$MMC_GPIO_CD" ] && MMC_GPIO_CD="59"

set_gpio() {
	info "Set GPIO $1 to F$2 D$3"
	gpio-diag $1 func $2 drive $3
}

set_power() {
	# Set additional MMC GPIOs
	# This needs to run AFTER the driver has been loaded for the sd card to mount during boot
	for gpio in $MMC_GPIO_PWR; do
		if [ "${#gpio}" -eq 3 ] && [ "${gpio%[oO]}" != "$gpio" ]; then
			case "${gpio#??}" in
				"O")
					info "Set GPIO "${gpio%[oO]}" high"
					run "gpio set "${gpio%[oO]}" 1"
					;;
				"o")
					info "Set GPIO "${gpio%[oO]}" low"
					run "gpio set "${gpio%[oO]}" 0"
					;;
			esac
		fi
	done
}

load_module() {
	grep -q "$MMC_MODULE" /proc/modules && die "$MMC_MODULE is already loaded"
	info "Load $MMC_MODULE $MMC_PARAM"
	modprobe $MMC_MODULE $MMC_PARAM || die "Failed to load module!"
	set_power
}

start() {
	starting

	MMC_PARAM="cd_gpio_pin=$MMC_GPIO_CD"

	# Check if MDIO directory exists
	if [ -d /proc/jz/mdio ]; then
		echo -n "/proc/jz/mdio directory exists, MSC1 disabled... " | log
	else
		case "$SOC_FAMILY" in
			t10 | t20 | t21 | t30 | t40 | t41)
				info "Skip GPIO setup for $SOC_MODEL"
				;;
			t23 | t31)
				if [ "$SOC_MODEL" = "t31a" ]; then
					info "Skip GPIO setup for $SOC_MODEL"
					return 1
				else
					set_gpio pb08 1 2
					set_gpio pb09 1 1
					set_gpio pb10 1 1
					set_gpio pb11 1 1
					set_gpio pb13 1 1
					set_gpio pb14 1 1
				fi
				;;
			*)
				die "Unsupported SOC type: $SOC_FAMILY"
				;;
		esac
	fi
	load_module
}

case "$1" in
	start)
		$1
		;;
	stop)
		true
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
