#!/bin/sh

. /etc/init.d/rc.common

SOC_FAMILY=$(/usr/sbin/soc -f)
SOC_MODEL=$(/usr/sbin/soc -m)

MMC_MODULE="jzmmc_v12"

MMC_GPIO_CD=$(get gpio_mmc_cd)
MMC_GPIO_PWR=$(get gpio_mmc_power)

# Default CD-PIN for Ingenic PB27 (GPIO59)
[ -z "$MMC_GPIO_CD" ] && MMC_GPIO_CD="59"

set_gpios() {
	# Set additional MMC GPIOs
	# This needs to run AFTER the driver has been loaded for the sd card to mount during boot
	for gpio in $MMC_GPIO_PWR; do
		if [ "${#gpio}" -eq 3 ] && [ "${gpio%[oO]}" != "$gpio" ]; then
			case "${gpio#??}" in
				"O") gpio set "${gpio%[oO]}" 1 2>&1 | log ;;
				"o") gpio set "${gpio%[oO]}" 0 2>&1 | log ;;
			esac
		fi
	done
}

load_module() {
	grep -q "$MMC_MODULE" /proc/modules && die "$MMC_MODULE is already loaded"
	modprobe $MMC_MODULE $MMC_PARAM && ok || { fail && die; }
	set_gpios
}

start() {
	starting

	MMC_PARAM="cd_gpio_pin=$MMC_GPIO_CD"

	# Check if MDIO directory exists
	if [ -d /proc/jz/mdio ]; then
		echo -n "/proc/jz/mdio directory exists, MSC1 disabled... " | log
	else
		case "$SOC_FAMILY" in
			t10 | t20 | t21 | t30 | t40 | t41)
				# do nothing
				;;
			t23)
				die "Unsupported: T23"
				;;
			t31)
				if [ "$SOC_MODEL" = "t31a" ] || [ "$SOC_MODEL" = "t31al" ]; then
					echo "Skipping GPIO setup for $SOC_MODEL"
					return 1
				else
					gpio-diag pb08 func 1 drive 2
					gpio-diag pb09 func 1 drive 1
					gpio-diag pb10 func 1 drive 1
					gpio-diag pb11 func 1 drive 1
					gpio-diag pb13 func 1 drive 1
					gpio-diag pb14 func 1 drive 1
				fi
				;;
			*)
				die "Unsupported SOC type: $SOC_FAMILY"
				;;
		esac
	fi
	load_module
}

case "$1" in
	start)
		$1
		;;
	stop)
		true
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
