#!/bin/sh

. /etc/init.d/rc.common

MMC_MODULE="jzmmc_v12"
MMC_GPIO_CD=$(get gpio_mmc_cd)
MMC_GPIO_PWR=$(get gpio_mmc_power)

# Default CD-PIN for Ingenic PB27 (GPIO59)
[ -z "$MMC_GPIO_CD" ] && MMC_GPIO_CD="59"

set_gpio() {
	info "Set GPIO $1 to F$2 D$3"
	gpio-diag $1 func $2 drive $3
}

set_power() {
	# Set additional MMC GPIOs
	# This needs to run AFTER the driver has been loaded for the sd card to mount during boot
	for gpio in $MMC_GPIO_PWR; do
		[ "${#gpio}" -ne 3 ] && continue
		[ "${gpio%[oO]}" = "$gpio" ] && continue

		case "${gpio#??}" in
			"O")
				info "Set GPIO "${gpio%[oO]}" high"
				run "gpio set "${gpio%[oO]}" 1"
				;;
			"o")
				info "Set GPIO "${gpio%[oO]}" low"
				run "gpio set "${gpio%[oO]}" 0"
				;;
		esac
	done
}

load_module() {
	grep -q "$MMC_MODULE" /proc/modules && die "$MMC_MODULE is already loaded"
	info "Load $MMC_MODULE $MMC_PARAM"
	modprobe $MMC_MODULE $MMC_PARAM || die "Failed to load module!"
	set_power
}

start() {
	MMC_PARAM="cd_gpio_pin=$MMC_GPIO_CD"
	load_module
}

case "$1" in
	start)
		starting
		start
		check_result
		;;
	stop)
		stopping
		ok
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
