#!/bin/sh

load_modules() {
	local file="$1"
	[ -r "${file}" ] || return 0
	while read module args; do
		case "$module" in
			"" | "#"*)
				continue
				;;
		esac
		echo -n " ${module}... "
		modprobe ${module} ${args} && echo "OK" || echo "FAIL"
	done < "${file}"
}

case "$1" in
	start)
		echo "Loading modules: "

		load_modules "/etc/modules"

		if [ -d "/etc/modules.d" ]; then
			for conf in /etc/modules.d/*; do
				load_modules "${conf}"
			done
		fi
		;;
esac

exit 0
