#!/bin/sh

. /etc/init.d/rc.common

load_modules() {
	local file=$1
	[ -r "$file" ] || return 0

	while read -r module args; do
		case "$module" in
			"" | "#"*)
				continue
				;;
		esac
		run "modprobe $module $args"
	done < $file
}

case "$1" in
	start)
		starting
		load_modules /etc/modules
		[ -d /etc/modules.d ] || quit
		for conf in /etc/modules.d/*; do
			load_modules $conf
		done
		;;
esac

exit 0
