#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-r /dev/urandom"

start() {
	starting
	start_daemon_with_pid
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
