#!/bin/sh

NAME="rngd"
DAEMON="/sbin/${NAME}"
DAEMON_ARGS="-r /dev/urandom"
PIDFILE="/run/$NAME.pid"

start() {
	printf "Starting ${NAME}: "
	start-stop-daemon -q -S -x $DAEMON -- $DAEMON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping ${NAME}: "
	start-stop-daemon -K -q -x $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -f $PIDFILE
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
