#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-d /etc/seedrng"

start() {
	starting
	start_daemon_with_pid
}

stop() {
	stopping
	start_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
