#!/bin/sh

. /usr/share/common

MDEV="/sbin/mdev"

start() {
	echo_title "Configuring mdev"

	echo "$MDEV" > /proc/sys/kernel/hotplug
	$MDEV -s
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
