#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		echo /sbin/mdev > /proc/sys/kernel/hotplug
		/sbin/mdev -s && ok || fail
		;;
	stop | restart | reload)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit $?
