#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		pwbackup restore
		check_result
		;;
	stop | save)
		stopping
		pwbackup save
		check_result
		;;
	*)
		die "Usage: $0 {start|stop|save}"
		;;
esac

exit 0
