#!/bin/sh

. /etc/init.d/rc.common

DROPBEAR_KEY="/etc/dropbear/dropbear_ed25519_host_key"
SSHKEY_ENV=$(get sshkey_ed25519)

generate_keys() {
	info "Generate a key"
	run "dropbearkey -t ed25519 -f $DROPBEAR_KEY"
}

restore_keys() {
	info "Restore the key"
	# FIXME: run fails on pipes
	echo $SSHKEY_ENV | base64 -d | gzip -d > $DROPBEAR_KEY
}

save_keys() {
	info "Back up the key"
	SSHKEY_ENV=$(gzip -c $DROPBEAR_KEY | base64 | tr -d '\n')
	run "fw_setenv sshkey_ed25519 $SSHKEY_ENV"
}

case "$1" in
	start)
		starting
		if [ -s "$DROPBEAR_KEY" ]; then
			info "Key present on the filesystem"
			if [ -z "$SSHKEY_ENV" ]; then
				info "Key backup not found in the environment"
				save_keys
			fi
		else
			info "Key not found on the filesystem"
			if [ -z "$SSHKEY_ENV" ]; then
				info "Key backup not found in the environment"
				generate_keys
				save_keys
			else
				info "Key backup present in the environment"
				restore_keys
			fi
		fi
		ok
		;;
	reload | stop | restart)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
