#!/bin/sh

. /etc/init.d/rc.common

DROPBEAR_KEY="/etc/dropbear/dropbear_ed25519_host_key"
SSHKEY_ENV=$(get sshkey_ed25519)

generate_keys() {
	run "dropbearkey -t ed25519 -f $DROPBEAR_KEY"
	info "Generated dropbear host keys."
}

restore_keys() {
	run "echo \"$SSHKEY_ENV\" | base64 -d | gzip -d > $DROPBEAR_KEY"
	info "SSH Key restored."
}

save_keys() {
	SSHKEY_ENV=$(gzip -c $DROPBEAR_KEY | base64 | tr -d '\n')
	run "fw_setenv sshkey_ed25519 \"$SSHKEY_ENV\""
	info "SSH key backed up."
}

case "$1" in
	start)
		starting
		if [ -s "$DROPBEAR_KEY" ]; then
			if [ -z "$SSHKEY_ENV" ]; then
				save_keys
			fi
		else
			if [ -z "$SSHKEY_ENV" ]; then
				generate_keys
				save_keys
			else
				restore_keys
			fi
		fi
		ok
		;;
	reload | stop | restart)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
