#!/bin/sh

DROPBEAR_KEY_FILE="/etc/dropbear/dropbear_ed25519_host_key"

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		test -f $DROPBEAR_KEY_FILE || dropbearkey -t ed25519 -f $DROPBEAR_KEY_FILE
		ok
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
