#!/bin/sh

. /etc/init.d/rc.common

case "$1" in
	start)
		starting
		run "ifup -a"
		check_result
		;;

	stop)
		stopping
		run "ifdown -a"
		check_result
		;;

	restart | reload)
		stop
		sleep 1
		start
		;;

	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
