#!/bin/sh

. /etc/init.d/rc.common

start() {
	starting
	ifup -v -a || die "Failed to bring up network"
	check_result
}

stop() {
	stopping
	ifdown -v -a || die "Failed to bring down network"
	check_result
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
