#!/bin/sh

. /etc/init.d/rc.common

DEV="wg0"
IP="$(fw_printenv -n wg_address)"
RESOLV_CONF="/tmp/resolv.conf"
RESOLV_BAK="${RESOLV_CONF}.bak"

case "$1" in
	force | start)
		starting
		# "force" is for testing, to start wireguard on demand without having it enabled at boot
		[ "xtrue" = "x$(fw_printenv -n wg_enabled)" ] || quit "Disabled"
		[ "force" = "$1" ] || quit "Disabled"
		ip link show $DEV 2>&1 | grep -q 'UP' && die "WireGuard interface $DEV already running"

		rm -f /tmp/wgconf_*
		wgconf=$(mktemp /tmp/wgconf_XXXXXX)

		echo '[Interface]' >> $wgconf
		echo "PrivateKey=$(fw_printenv -n wg_privkey)" >> $wgconf

		v=$(fw_printenv -n wg_port)
		[ -n "$v" ] && echo "ListenPort=$v" >> $wgconf

		echo '[Peer]' >> $wgconf
		echo "Endpoint=$(fw_printenv -n wg_endpoint)" >> $wgconf
		echo "PublicKey=$(fw_printenv -n wg_peerpub)" >> $wgconf

		v=$(fw_printenv -n wg_peerpsk)
		[ -n "$v" ] && echo "PresharedKey=$v" >> $wgconf

		v=$(fw_printenv -n wg_allowed)
		[ -n "$v" ] && echo "AllowedIPs=$v" >> $wgconf

		v=$(fw_printenv -n wg_keepalive)
		[ -n "$v" ] && echo "PersistentKeepalive=$v" >> $wgconf

		mtu=$(fw_printenv -n wg_mtu)
		[ -n "$mtu" ] && link_mtu="mtu $mtu"

		run "ip link add dev $DEV type wireguard"
		run "wg setconf $DEV $wgconf"
		run "ip address add ${IP} dev $DEV"
		run "ip link set $link_mtu up dev $DEV"

		DNS=$(fw_printenv -n wg_dns)
		if [ -n "$DNS" ] ; then
			resolv_tmp=$(mktemp)
			grep -v nameserver $RESOLV_CONF >> $resolv_tmp
			for x in $(echo $DNS | tr "," " ") ; do
				echo "nameserver $x" >> $resolv_tmp
			done
			mv $RESOLV_CONF $RESOLV_BAK
			mv $resolv_tmp $RESOLV_CONF
		fi

		for r in $(fw_printenv -n wg_allowed | tr "," " ") ; do
			run "ip route add $r dev $DEV"
		done

		true
		check_result
		;;

	stop)
		stopping
		for r in $(ip route | awk '/dev wg/{print $1}') ; do
			run "route del $r dev $DEV"
		done
		run "ip link set down $DEV"
		[ -n "$IP" ] && run "ip address del $IP dev $DEV"
		[ -s $RESOLV_BAK ] && mv $RESOLV_BAK $RESOLV_CONF

		true
		check_result
		;;

	*)
		die "Usage: $0 {force|start|stop}"
		;;
esac

exit 0
