#!/bin/sh

DAEMON_ARGS="-n -S /etc/ntpd_callback"

DEF_CONF="/etc/default/ntp.conf"
TMP_CONF="/tmp/ntp.conf"

. /etc/init.d/rc.common

start() {
	starting
	if [ "true" = "$(get wlanap_enabled)" ]; then
		touch $TMP_CONF
		DAEMON_ARGS="-n -l"
	fi

	if [ -f $TMP_CONF ]; then
		info "work config found"
	else
		if [ -f $DEF_CONF ]; then
			info "default config found"
		else
			info "restore default config from ROM"
			run "cp /rom$DEF_CONF $DEF_CONF"
		fi
		info "make a work config from default config"
		run "cp $DEF_CONF $TMP_CONF"
	fi
	start_daemon_with_pid
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
