#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-n"

start() {
	starting
	[ ! -f /tmp/ntp.conf ] && cat /etc/default/ntp.conf > /tmp/ntp.conf
	start_daemon_with_pid
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
