#!/bin/sh

DAEMON_ARGS="-f -c /etc/cron/crontabs"

. /usr/share/common

start() {
	echo "Starting crond..."

	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon
}

stop() {
	echo "Stopping crond..."

	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
