#!/bin/sh

DAEMON_ARGS="-f -c /etc/cron/crontabs"

. /etc/init.d/rc.common

start() {
	starting
	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon_with_pid
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
