#!/bin/sh

DAEMON_ARGS="-k -K 300 -b /etc/issue.net -R"
# -k              Disable remote port forwarding
# -K <keepalive>  (0 is never, default 0, in seconds)
# -b bannerfile   Display the contents of bannerfile before user login
# -R              Create hostkeys as required

. /etc/init.d/rc.common

start() {
	umask 077
	starting
	start_daemon
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
