#!/bin/sh

DAEMON_ARGS="-k -K 300 -b /etc/issue.net -R"
# -k              Disable remote port forwarding
# -K <keepalive>  (0 is never, default 0, in seconds)
# -b bannerfile   Display the contents of bannerfile before user login
# -R              Create hostkeys as required

DROPBEAR_KEY_FILE="/etc/dropbear/dropbear_ed25519_host_key"

. /etc/init.d/rc.common

start() {
	echo "Starting dropbear sshd"

	if [ -L /etc/dropbear -a "$(readlink /etc/dropbear)" = "/var/run/dropbear" ]; then
		if rm -f /etc/dropbear >/dev/null 2>&1; then
			mkdir -p /etc/dropbear
		else
			echo "No persistent location to store SSH host keys. New keys will be"
			echo "generated at each boot. Are you sure this is what you want to do?"
			mkdir -p "$(readlink /etc/dropbear)"
		fi
	fi

	umask 077
	test -f $DROPBEAR_KEY_FILE || dropbearkey -t ed25519 -f $DROPBEAR_KEY_FILE

	start_daemon
}

stop() {
	echo "Stopping dropbear sshd..."

	stop_daemon_with_pid
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
