#!/bin/sh

DAEMON_ARGS="-k -K 300 -R"
# -k              Disable remote port forwarding
# -K <keepalive>  (0 is never, default 0, in seconds)
# -b bannerfile   Display the contents of bannerfile before user login
# -R              Create hostkeys as required

DROPBEAR_KEY_FILE="/etc/dropbear/dropbear_ed25519_host_key"

. /usr/share/common

start() {
	echo "Starting dropbear sshd..."

	umask 077

	if [ ! -f $DROPBEAR_KEY_FILE ]; then
		echo "- Generating ed25519 host key..."
		dropbearkey -t ed25519 -f $DROPBEAR_KEY_FILE
	fi

	start_daemon
}

stop() {
	echo "Stopping dropbear sshd..."

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
