#!/bin/sh

DAEMON_ARGS="-i $(ip addr show | awk '/inet.*brd/{print $NF}' | head -1) -s"

. /etc/init.d/rc.common

start() {
	starting
	start_daemon_with_pid
}

stop() {
	stopping
	stop_daemon_with_pid
}

case "$1" in
        start | stop)
        	$1
                ;;
 	reload | restart)
        	stop
        	sleep 1
	        start
 		;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
                ;;
esac

exit 0
