#!/bin/sh

DAEMON_ARGS="-i $(ip addr show | awk '/inet.*brd/{print $NF}' | head -1) -s"

. /etc/init.d/rc.common

start() {
	echo "Starting mdnsd..."

	start_daemon
}

stop() {
	echo "Stopping mdnsd..."

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
