#!/bin/sh

DAEMON_ARGS="-c /etc/mosquitto/mosquitto.conf"

. /etc/init.d/rc.common

start() {
	starting
	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
