#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-c /etc/mosquitto/mosquitto.conf"

start() {
	starting
	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon_with_pid
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
