#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-f -c /etc/crontabs"

start() {
	starting
	[ -f $DAEMON_FULL ] || disabled
	start_daemon_with_pid
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || disabled
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		sleep 1
		start
		;;
	*)
		die 1 "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
