#!/bin/sh

DAEMON="crond"
PIDFILE="/run/$DAEMON.pid"

CROND_ARGS="-f -c /etc/crontabs"

start() {
	printf 'Starting %s: ' $DAEMON
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -q -p $PIDFILE -S -b -m -x /sbin/$DAEMON -- $CROND_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf 'Stopping %s: ' $DAEMON
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -q -p $PIDFILE -K
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -f $PIDFILE
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
