#!/bin/sh

DAEMON_ARGS="-f -c /etc/crontabs"

. /etc/init.d/rc.common

start() {
	starting
	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon_with_pid
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
