#!/bin/sh

. /usr/share/common

start() {
	echo_title "Starting Telegram bot daemon"

	start_daemon
}

stop() {
	echo_title "Stopping Telegram bot daemon"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
