#!/bin/sh

. /etc/init.d/rc.common

start() {
	echo "Starting Telegram bot daemon..."

	start_daemon
}

stop() {
	echo "Stopping Telegram bot daemon..."

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
