#!/bin/sh

. /usr/share/common

start() {
	echo "Checking sysupgrade..."

	if [ "true" != "$sysupgrade_complete" ]; then
		echo "- Mark sysupgrade complete"
		fw_setenv sysupgrade_complete true
		# play_sound thingino.pcm
	fi
}

stop() {
	echo "Checking for upgrade..."

	if [ -f "/tmp/upgrade.me" ]; then
		echo "- Running sysupgrade..."
		sysupgrade -p
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
