#!/bin/sh

. /usr/share/common

start() {
	echo_title "Checking sysupgrade"

	if [ "true" != "$sysupgrade_complete" ]; then
		echo_info "Mark sysupgrade complete"
		fw_setenv sysupgrade_complete true

		if [ -f "$PORTAL_MODE_FLAG" ]; then
			echo_info "Portal mode is active"
		else
			fifo="/run/prudynt/audio_out"
			max=10; i=0
			while [ $i -lt $max ] && [ ! -p "$fifo" ]; do
				sleep 1
				i=$((i + 1))
			done
			if [ -p "$fifo" ]; then
				play /usr/share/sounds/thingino.opus
			else
				echo_warning "FIFO $fifo not found after ${max}s"
			fi
		fi
	fi
}

stop() {
	echo_title "Checking for upgrade"

	if [ -f "/tmp/upgrade.me" ]; then
		echo_warning "Running full upgrade"
		yes yes | sysupgrade -f
	elif [ -f "/tmp/update.me" ]; then
		echo_warning "Running partial upgrade"
		sysupgrade -p
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
