#!/bin/sh

. /etc/init.d/rc.common

start() {
	SYSUPGRADE_COMPLETE=$(fw_printenv -n sysupgrade_complete)

	if [ "$SYSUPGRADE_COMPLETE" = "false" ]; then
		starting
		ok
		#play_sound thingino.pcm
		fw_setenv sysupgrade_complete=true
		info_n "Update completed!"
	fi
}

case "$1" in
	start | restart)
			start
			;;
	stop | reload)
			;;
	*)
			echo "Usage: $0 {start|stop|restart|reload}"
			exit 1
			;;
esac

exit 0
