#!/bin/sh

. /etc/init.d/rc.common

ENV_FILE="/etc/uenv.txt"

cleanup() {
	run "rm $tmpfile"
}

backup_env() {
	local tmpfile=$(mktemp -u)
	fw_printenv > $tmpfile

	# Do not back up suspiciously small dump
	if [ $(stat -c%s $tmpfile) -le 512 ]; then
		cleanup
		die "Dump is too small!"
	fi

	if cmp -s $tmpfile $ENV_FILE; then
		cleanup
		quit "No changes"
	fi

	run "mv -f $tmpfile $ENV_FILE"
	check_result
}

case "$1" in
	start)
		starting
		backup_env
		;;
	stop)
		stopping
		backup_env
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
