WIFI_BCM43438_VERSION = $(LINUX_VERSION_PROBED)
WIFI_BCM43438_SITE_METHOD = local
WIFI_BCM43438_VERSION=1.0
WIFI_BCM43438_SITE = $(LINUX_DIR)/drivers/net/wireless/bcmdhd_1_141_66

define WIFI_BCM43438_LINUX_CONFIG_FIXUPS
		$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
		$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
		$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
		$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
		$(call KCONFIG_SET_OPT,CONFIG_BCMDHD_1_141_66=m)
		$(call KCONFIG_SET_OPT,CONFIG_BCMDHD_1_141_66_SDIO,y)
endef

define WIFI_BCM43438_INSTALL_TARGET_CMDS
        $(INSTALL) -m 755 -d $(TARGET_DIR)/usr/lib/firmware
        $(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_BCM43438_PKGDIR)/files/fw_bcm43438a1.bin
        $(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_BCM43438_PKGDIR)/files/nv_bcm43438a1.txt
endef

$(eval $(kernel-module))
$(eval $(generic-package))


