LIBSRT_VERSION = 1.5.4
LIBSRT_SOURCE = v$(LIBSRT_VERSION).tar.gz
LIBSRT_SITE = https://github.com/Haivision/srt/archive/refs/tags
LIBSRT_LICENSE = MPL-2.0
LIBSRT_LICENSE_FILES = LICENSE
LIBSRT_INSTALL_STAGING = YES

LIBSRT_DEPENDENCIES = mbedtls

LIBSRT_INSTALL_TARGET = NO

LIBSRT_CONF_OPTS = \
	-DENABLE_APPS=OFF \
	-DENABLE_TESTING=OFF \
	-DENABLE_SHARED=OFF \
	-DENABLE_STATIC=ON \
	-DENABLE_LOGGING=OFF \
	-DUSE_ENCLIB=mbedtls \
	-DCMAKE_C_FLAGS="$(TARGET_CFLAGS)" \
	-DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS)"

$(eval $(cmake-package))
