INGENIC_SYSTEM_LIBS_NEO_SITE_METHOD = git
INGENIC_SYSTEM_LIBS_NEO_SITE = https://github.com/gtxaspec/ingenic-system-libs-neo
INGENIC_SYSTEM_LIBS_NEO_SITE_BRANCH = main
INGENIC_SYSTEM_LIBS_NEO_VERSION = 3e1189021e4f273b701b5d8bb8a07b19699333d6
INGENIC_SYSTEM_LIBS_NEO_INSTALL_STAGING = YES

INGENIC_SYSTEM_LIBS_NEO_LICENSE = MIT
INGENIC_SYSTEM_LIBS_NEO_DEPENDENCIES = ingenic-lib

define INGENIC_SYSTEM_LIBS_NEO_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) CROSS_COMPILE=$(TARGET_CROSS)
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) strip CROSS_COMPILE=$(TARGET_CROSS)
endef

define INGENIC_SYSTEM_LIBS_NEO_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) install-staging \
		DESTDIR=$(STAGING_DIR) CROSS_COMPILE=$(TARGET_CROSS)
endef

define INGENIC_SYSTEM_LIBS_NEO_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/libalog.so $(TARGET_DIR)/usr/lib/libalog.so
	$(INSTALL) -D -m 0755 $(@D)/libsysutils.so $(TARGET_DIR)/usr/lib/libsysutils.so
endef

$(eval $(generic-package))
