INGENIC_SYSTEM_LIBS_NEO_SITE_METHOD = git
INGENIC_SYSTEM_LIBS_NEO_SITE = https://github.com/gtxaspec/ingenic-system-libs-neo
INGENIC_SYSTEM_LIBS_NEO_SITE_BRANCH = main
INGENIC_SYSTEM_LIBS_NEO_VERSION = 3e1189021e4f273b701b5d8bb8a07b19699333d6
INGENIC_SYSTEM_LIBS_NEO_INSTALL_STAGING = YES

INGENIC_SYSTEM_LIBS_NEO_LICENSE = MIT
INGENIC_SYSTEM_LIBS_NEO_DEPENDENCIES = ingenic-lib

define INGENIC_SYSTEM_LIBS_NEO_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) CROSS_COMPILE=$(TARGET_CROSS)
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) strip CROSS_COMPILE=$(TARGET_CROSS)
endef

define INGENIC_SYSTEM_LIBS_NEO_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) install-staging \
		DESTDIR=$(STAGING_DIR) CROSS_COMPILE=$(TARGET_CROSS)
endef

define INGENIC_SYSTEM_LIBS_NEO_INSTALL_TARGET_CMDS
	$(if $(BR2_PACKAGE_INGENIC_SYSTEM_LIBS_NEO_LIBALOG),
		$(INSTALL) -D -m 0755 $(@D)/libalog.so $(TARGET_DIR)/usr/lib/libalog.so
	)
	$(if $(BR2_PACKAGE_INGENIC_SYSTEM_LIBS_NEO_LIBSYSUTILS),
		$(INSTALL) -D -m 0755 $(@D)/libsysutils.so $(TARGET_DIR)/usr/lib/libsysutils.so
	)
endef

define INGENIC_SYSTEM_LIBS_NEO_FINALIZE_TARGET
	$(if $(BR2_PACKAGE_INGENIC_SYSTEM_LIBS_NEO_LIBALOG),
		$(INSTALL) -m 0755 $(BUILD_DIR)/ingenic-system-libs-neo-$(INGENIC_SYSTEM_LIBS_NEO_VERSION)/libalog.so \
			$(TARGET_DIR)/usr/lib/libalog.so
	)
	$(if $(BR2_PACKAGE_INGENIC_SYSTEM_LIBS_NEO_LIBSYSUTILS),
		$(INSTALL) -m 0755 $(BUILD_DIR)/ingenic-system-libs-neo-$(INGENIC_SYSTEM_LIBS_NEO_VERSION)/libsysutils.so \
			$(TARGET_DIR)/usr/lib/libsysutils.so
	)
endef
INGENIC_SYSTEM_LIBS_NEO_TARGET_FINALIZE_HOOKS += INGENIC_SYSTEM_LIBS_NEO_FINALIZE_TARGET

$(eval $(generic-package))
