#!/bin/sh
. /usr/share/thingino-agent-api-common
require_method_one_of GET PATCH
require_token_if_configured

path_info=${PATH_INFO:-}

case "${REQUEST_METHOD:-GET}" in
	GET)
		case "$path_info" in
			""|/)
				run_agentctl_json config
				;;
			/schema)
				run_agentctl_json schema
				;;
			*)
				json_error 404 "Not Found"
				;;
		esac
		;;
	PATCH)
		case "$path_info" in
			""|/) ;;
			*) json_error 404 "Not Found" ;;
		esac
		body_file=$(read_request_body_file)
		trap 'rm -f "$body_file"' EXIT INT TERM
		run_agentctl_json apply-config "$body_file"
		;;
esac