#!/bin/sh
. /usr/share/thingino-agent-api-common
require_method POST
require_token_if_configured

body_file=$(read_request_body_file)
trap 'rm -f "$body_file"' EXIT INT TERM

enabled=$(json_field "$body_file" enabled)
channel=$(json_field "$body_file" channel)
[ -n "$channel" ] || channel=all

case "$enabled" in
	true|1|on|yes) state=on ;;
	false|0|off|no) state=off ;;
	*) json_error 400 "privacy.enabled must be true or false" ;;
esac

run_agentctl_json privacy "$state" "$channel"