#!/bin/sh
. /usr/share/thingino-agent-api-common

resource=$(api_resource_path)

case "$resource" in
	capabilities/*)
		require_method GET
		require_token_if_configured
		run_agentctl_json capabilities "${resource#capabilities/}"
		;;
	runtime/*)
		require_method GET
		require_token_if_configured
		run_agentctl_json runtime "${resource#runtime/}"
		;;
	settings/*)
		require_method_one_of GET PATCH
		require_token_if_configured
		setting_path=${resource#settings/}
		case "${REQUEST_METHOD:-GET}" in
			GET)
				run_agentctl_json get-setting "$setting_path"
				;;
			PATCH)
				body_file=$(read_request_body_file)
				trap 'rm -f "$body_file"' EXIT INT TERM
				run_agentctl_json set-setting "$setting_path" "$body_file"
				;;
		esac
		;;
	*)
		json_error 404 "Not Found"
		;;
esac