#!/bin/sh

# only work on a WLAN interface
if [ "wlan0" != "$IFACE" ]; then
	exit 0
fi

wlan0_missing() {
	! test -f /etc/network/interfaces.d/wlan0
}

wlan0_disabled() {
	! grep -q '^auto wlan0' /etc/network/interfaces.d/wlan0 >/dev/null
}

wlan0_no_ssid() {
	! grep -q 'ssid=' /etc/wpa_supplicant.conf >/dev/null
}

wlan0_no_pass() {
	! grep -q 'psk=' /etc/wpa_supplicant.conf >/dev/null
}

# exit 1 to stop the interface from being brought up, and dhcp being attempted
if wlan0_missing; then
	echo "WLAN interface not configured" >&2
	exit 1
elif wlan0_disabled; then
	echo "WLAN manually disabled" >&2
	exit 1
elif wlan0_no_ssid; then
	echo "WLAN disabled, no SSID" >&2
	exit 1
elif wlan0_no_pass; then
	echo "WLAN disabled, no password" >&2
	exit 1
fi

exit 0
