attwifi.apple.com 172.16.0.1
captive.apple.com 172.16.0.1
clients.l.google.com 172.16.0.1
clients3.google.com 172.16.0.1
connectivitycheck.android.com 172.16.0.1
connectivitycheck.gstatic.com 172.16.0.1
connectivity-check.ubuntu.com 172.16.0.1
google.com 172.16.0.1
gstatic.com 172.16.0.1
play.googleapis.com 172.16.0.1
www.apple.com 172.16.0.1
www.gstatic.com 172.16.0.1
www.google.com 172.16.0.1
* 172.16.0.1
