H:/var/www-portal
I:index.html
A:*

# Android
P:/generate_204:http://172.16.0.1/x/portal.cgi
P:/generate204:http://172.16.0.1/x/portal.cgi
P:/gen_204:http://172.16.0.1/x/portal.cgi
P:/gen204:http://172.16.0.1/x/portal.cgi
P:/mobile/status.php:http://172.16.0.1/x/portal.cgi

# Apple
P:/hotspot-detect.html:http://172.16.0.1/x/portal.cgi
P:/hotspot.html:http://172.16.0.1/x/portal.cgi
P:/success.txt:http://172.16.0.1/x/portal.cgi
P:/library/test/success.html:http://172.16.0.1/x/portal.cgi

# Windows
P:/ncsi.txt:http://172.16.0.1/x/portal.cgi
P:/connecttest.txt:http://172.16.0.1/x/portal.cgi
P:/redirect:http://172.16.0.1/x/portal.cgi

# Alt
P:/kindle-wifi/wifiredirect.html:http://172.16.0.1/x/portal.cgi
P:/kindle-wifi/wifistub.html:http://172.16.0.1/x/portal.cgi
