#!/bin/sh

set_gpio() {
	echo "Set GPIO $1 to F$2 D$3"
	gpio-diag "$1" func "$2" drive "$3"
}

set_gpio pb08 1 2
set_gpio pb09 1 1
set_gpio pb10 1 1
set_gpio pb11 1 1
set_gpio pb13 1 1
set_gpio pb14 1 1
