#!/bin/sh

set_gpio() {
	echo "Set GPIO $1 to F$2 D$3"
	gpio-diag mode "$1" "func$2"
	gpio-diag drive "$1" "$3"
}

set_gpio pa08 3 2
set_gpio pa09 3 1
set_gpio pa10 3 1
set_gpio pa11 3 1
set_gpio pa16 3 1
set_gpio pa17 3 1
