#!/bin/sh

. /etc/init.d/rc.common

start() {
	starting
	modulename="$(fw_printenv -n wlandev)"
	moduleopts="$(fw_printenv -n wlandevopts)"
	gpionum="$(fw_printenv -n gpio_wlan)"
	mac_address=$(fw_printenv -n wlanmac)

	wlandev_check || die 1 "Disabled"

	if [ -n "$gpionum" ]; then
		num=${gpionum%[oO]}
		state=${gpionum#$num}

		case "$state" in
			O)
				gpio_cmd="high"
				;;
			o)
				gpio_cmd="low"
				;;
		esac

		echo -en "\n Set GPIO $num $gpio_cmd... "
		gpio $gpio_cmd $num 2>&1 | logger -p daemon.info -t $0 || die 1 "FAIL"

		echo "OK"
	fi

	#FIXME Assume that we are SDIO, and we need to insert
	echo -n " Send INSERT to MMC1 ... "
	if mmc 1 2>&1 | logger -p daemon.info -t $0; then
		echo "OK"
	else
		echo "FAIL"
	fi

	if ! lsmod | grep -q "$modulename"; then
		echo -n " Load module $modulename ... "
		if modprobe $modulename $moduleopts 2>&1 | logger -p daemon.info -t $0; then
			echo "OK"
		else
			echo "FAIL"
		fi
	fi

	sleep 1

	if [ -n "$mac_address" ]; then
		ip link set dev wlan0 address $mac_address 2>&1 | logger -p daemon.info -t $0
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		die 1 "Usage: $0 {start}"
		;;
esac

exit 0
