#!/bin/sh

. /etc/init.d/rc.common

start() {
	starting_batch

	wlandev="$(get wlandev)"
	if [ -z "$wlandev" ]; then
		warn "wlandev is empty"
		exit 1
	fi

	gpio_wlan="$(get gpio_wlan)"
	if [ -n "$gpio_wlan" ]; then
		num=${gpio_wlan%[oO]}
		state=${gpio_wlan#$num}

		case "$state" in
			O)
				gpio_cmd="high"
				;;
			o)
				gpio_cmd="low"
				;;
		esac

		info "Set GPIO $num $gpio_cmd"
		gpio $gpio_cmd $num 2>&1 | log
	fi

	#FIXME Assume that we are SDIO, and we need to insert
	info "Send INSERT to MMC1"
	mmc 1 2>&1 | log

	if ! grep -q "^$wlandev " /proc/modules; then
		wlandevopts="$(get wlandevopts)"
		info "Load module $wlandev with $wlandevopts"
		modprobe $wlandev $wlandevopts 2>&1 | log
	fi

	sleep 1

	wlanmac=$(get wlanmac)
	if [ -n "$wlanmac" ]; then
		info "Set MAC address $wlanmac"
		ip link set dev wlan0 address $wlanmac 2>&1 | log
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
