#!/bin/sh

. /usr/share/common

IFACE=wlan0
CONFIG="/etc/$DAEMON_SHORT.conf"
PIDFILE="/run/$DAEMON_SHORT.$IFACE.pid"
WLAN_INT_FILE="/etc/network/interfaces.d/wlan0"
DAEMON_ARGS="-i $IFACE -c $CONFIG -P $PIDFILE -B"

ssid_changed() {
	current_ssid=$(grep '^ssid=' $CONFIG | cut -d= -f2- | tr -d '"')
	[ "$wlan_ssid" != "$current_ssid" ]
}

start() {
	starting

	# convert plain-text password no matter what
	if [ -n "$wlan_pass" ] && [ ${#wlan_pass} -lt 64 ]; then
		tmpfile=$(mktemp)
		wpa_passphrase "$wlan_ssid" "$wlan_pass" > $tmpfile
		wlan_pass=$(grep '^\s*psk=' $tmpfile | cut -d= -f2 | tail -n 1)
		fw_setenv wlan_pass $wlan_pass
		rm -f $tmpfile
	fi

	iface_exists "wlan0" || quit "No wireless interface"

	[ -z "$wlan_pass" ] && quit "WiFi password missing"
	[ -z "${wlan_ssid}${wlan_bssid}" ] && quit "WiFi network missing"

	if grep -q "^#auto wlan0" $WLAN_INT_FILE; then
		quit "wlan0 manually disabled"
	fi

	if [ ! -f "$CONFIG" ] || ssid_changed; then
		wpa_passphrase "$wlan_ssid" "dummy_password" > $CONFIG
		sed -i "s/psk=.*$/psk=${wlan_pass}/" $CONFIG
		if [ -n "$wlan_bssid" ]; then
			sed -i "s/^\s*ssid=.*$/\tbssid=$wlan_bssid/" $CONFIG
		else
			sed -i '/}/i\\tscan_ssid=1' $CONFIG
		fi
	fi

	[ "true" = "$wlanap_enabled" ] && quit "WLAN AP enabled"

	start-stop-daemon -S -x $DAEMON_FULL -- $DAEMON_ARGS 2>&1 | log
}

stop() {
	stopping
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
