#!/bin/sh

DAEMON=wpa_supplicant
IFACE=wlan0
CONFIG="/etc/$DAEMON.conf"
PIDFILE="/run/$DAEMON.$IFACE.pid"

start() {
	printf 'Starting %s: ' "$DAEMON"
	ssid="$(fw_printenv -n wlanssid)"
	pass="$(fw_printenv -n wlanpass)"

	if [ -z "$ssid" ] || [ -z "$pass" ]; then
		echo "WiFi credentials missing"
		exit 0
	fi

	generate_wpa_supplicant_conf() {
		if [ ${#pass} -lt 64 ]; then
			wpa_passphrase "$ssid" "$pass" > $CONFIG
		else
			wpa_passphrase "$ssid" "dummy_password" > $CONFIG
			sed -i "s/psk=.*$/psk=$pass/" $CONFIG
		fi
		sed -i '/ssid/a \\tscan_ssid=1' $CONFIG

		if [ ${#pass} -lt 64 ]; then
			psk=$(grep '^\s*psk=' $CONFIG | cut -d= -f2 | tail -n 1)
			fw_setenv wlanpass "$psk"
		fi
	}

	if [ ! -f "$CONFIG" ] || [ ${#pass} -lt 64 ] || ssid_changed; then
		generate_wpa_supplicant_conf
	fi

	start-stop-daemon -S -x /sbin/$DAEMON -- -i $IFACE -c $CONFIG -P $PIDFILE -B 2>&1 | logger -t $0
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return $status
}

ssid_changed() {
	current_ssid=$(grep '^ssid=' $CONFIG | cut -d= -f2- | tr -d '"')
	[ "$ssid" != "$current_ssid" ]
}

stop() {
	printf 'Stopping %s: ' $DAEMON
	start-stop-daemon -K -q -p "$PIDFILE" -x /sbin/$DAEMON
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return $status
}

restart() {
	stop
	start
}

case "$1" in
	start | stop | restart)
		$1
		;;
	reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
