#!/bin/sh

. /etc/init.d/rc.common

wlandev=$(get wlandev)
[ -z "$wlandev" ] && die "wlandev is empty, exit."

show_help() {
	echo "Usage: $0 <command>
Where command:
  setup       Set up Wi-Fi credentials
  info        Display connection details
  temp        Display module temperature details
  rssi        Display signal details
"
}

rssi() {
	if ! ip link show wlan0 > /dev/null 2>&1; then
		echo "Error: wlan0 interface does not exist."
		exit 1
	fi

	case "$wlandev" in
		ssv*)
			echo "rf rssi" > /proc/ssv/phy0/ssv_cmd
			cat /proc/ssv/phy0/ssv_cmd | sed -n 's/.*ofdm RSSI \(-[0-9]*\).*/\1/p'
			;;
		atbm*)
			iwpriv wlan0 common get_rssi | sed -n 's/.*rssi=\(-[0-9]*\).*/\1/p'
			;;
		818*)
			iwconfig wlan0 | sed -n 's/.*Signal level=\([0-9]*\)\/100.*/-\1/p'
			;;
		bcm*|syn*)
			echo "Broadcom not supported yet."
			;;
		aic*)
			echo "AICSemi not supported yet."
			;;
		hi*)
			echo "HiSilicon not supported yet."
			;;
		*)
			echo "Unknown wireless device type."
			;;
	esac

}

show_info() {
	case "$wlandev" in
		atbm*) iwpriv wlan0 common get_ap_info ;;
		rtl*) iwconfig wlan0 ;;
		*) echo "Not supperted on $wlandev" ;;
	esac
}

setup() {
	echo_c 208 "Thingino Wi-Fi setup"
	echo "Wi-Fi driver: $(echo_c 10 $wlandev)"
	read -r -p "Enter Wi-Fi SSID: " ssid
	while :; do
		read -r -p "Enter Wi-Fi Password: " password
		[ ${#password} -ge 8 ] && [ ${#password} -le 64 ] && break
		echo_c 160 "Passwords is not between 8 and 64 characters. Please try again."
	done

	fw_setenv wlanssid "$ssid"
	fw_setenv wlanpass "$password"

	echo_c 40 "Wi-Fi settings updated. Please restart for changes to take effect.\n"
}

temp() {
	if ! ip link show wlan0 > /dev/null 2>&1; then
		echo "Error: wlan0 interface does not exist."
		exit 1
	fi

	case "$wlandev" in
		ssv*)
				echo "SSV not supported yet."
				;;
		atbm*)
				iwpriv wlan0 common get_tjroom | sed -n 's/.*stempC:\([0-9]*\).*/\1/p'
				;;
		818*)
				echo "Realtek not supported yet."
				;;
		bcm*|syn*)
				echo "Broadcom not supported yet."
				;;
		aic*)
				echo "AICSemi not supported yet."
				;;
		hi*)
				echo "HiSilicon not supported yet."
				;;
		*)
				echo "Unknown wireless device type."
				;;
	esac
}

case "$(basename $0)" in
	wlaninfo) exec wlan info ;;
	wlansetup) exec wlan setup ;;
	wlantemp) exec wlan temp ;;
	wlanrssi) exec wlan rssi ;;
esac

case "$1" in
	setup) setup ;;
	info) show_info ;;
	temp) temp ;;
	rssi) rssi ;;
	*) show_help ;;
esac

exit 0
