#!/bin/sh

PIDFILE="/var/run/odhcp6c_$IFACE.pid"
TIMEOUT=10

# run this script only for interfaces that have the dhcp-v6-enabled option set,
# or if IPv6 is globally enabled (not disabled)
[ "$(sysctl -n net.ipv6.conf.all.disable_ipv6)" -ne 0 ] || [ "$IF_DHCP_V6_ENABLED" != "true" ] && exit 0

do_start() {
	{ start-stop-daemon -m -S -p "$PIDFILE" -x /sbin/odhcp6c -- -t120 -S15 "$IFACE" 2>&1 & echo $! > /tmp/odhcp6c.pid; } | {
		PID=$(cat /tmp/odhcp6c.pid)
		( sleep 10 && echo "DHCPv6 timeout reached on $IFACE, exiting." && kill "$PID" && exit 1 ) & SLEEP_PID=$!
		while read -r line; do
			if echo "$line" | grep -q "Adding address"; then
				echo "DHCPv6 configured on $IFACE!"
				kill "$SLEEP_PID"; wait "$PID"; rm -f /tmp/odhcp6c.pid; exit 0
			fi
		done
		kill "$SLEEP_PID"; rm -f /tmp/odhcp6c.pid; exit 1
	}
}

do_stop() {
	if [ -f "$PIDFILE" ]; then
		kill "$(cat "$PIDFILE")"
		rm -f "$PIDFILE"
	fi
}

case "$MODE" in
	start)
		case "$PHASE" in
			post-up)
				echo "Starting odhcp6c for $IFACE"
				do_start
				;;
		esac
		;;

	stop)
		case "$PHASE" in
			pre-down)
				echo "Stopping odhcp6c for $IFACE"
				do_stop
				;;
		esac
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
