#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic
SENSOR_EXT_PARAM=""

echo 1 >/proc/sys/vm/overcommit_memory

check_return() {
	if [ $? -ne 0 ]; then
		echo err: $1
		echo exit
		exit
	fi
}

log() {
	logger -s -p daemon.info -t ingenic "$1"
}

case "$SENSOR" in
	jxf22)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	jxf23)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	jxh42)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2135)
		ISP_PARAM="isp_clk=100000000"
		SENSOR_PARAM=""
		;;
	sc2232)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2235)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	*)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
esac

echo --------------------
echo "ISP_PARAM: ${ISP_PARAM}"
echo "SENSOR: ${SENSOR}"
echo "SENSOR_PARAM: ${SENSOR_PARAM}"
echo --------------------

if ! grep -q "^tx_isp" /proc/modules; then
	modprobe tx-isp-${SOC} $ISP_PARAM
	check_return "modprobe isp drv"
fi

if ! grep -q "^${SENSOR}" /proc/modules; then
	modprobe sensor_${SENSOR}_${SOC} $SENSOR_PARAM $SENSOR_EXT_PARAM
	check_return "modprobe sensor drv"
fi

if ! grep -q "^audio" /proc/modules; then
	modprobe audio spk_gpio=-1
	check_return "modprobe audio"
fi
