#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# Generic MT7601U
if [ "$1" = "mt7601u-generic" ]; then
	modprobe mt7601u
	exit 0
fi

# Generic RTL8188EU
if [ "$1" = "rtl8188eu-generic" ]; then
	modprobe 8188eu
	exit 0
fi

# Generic RTL8188FU
if [ "$1" = "rtl8188fu-generic" ]; then
	modprobe 8188fu
	exit 0
fi

# Generic RTL8733BU
if [ "$1" = "rtl8733bu-generic" ]; then
	modprobe 8733bu
	exit 0
fi

# T10 NVT
if [ "$1" = "mt7601sta-t10-nvt" ]; then
	modprobe cfg80211
	modprobe mt7601sta
	exit 0
fi

# T21 BJS
if [ "$1" = "rtl8188fu-t21-bjs" ]; then
	set_gpio 50 0
	modprobe 8188fu
	exit 0
fi

# T21 Smartwares
if [ "$1" = "rtl8188fu-t21-smartwares" ]; then
	set_gpio 49 1
	modprobe 8188fu
	exit 0
fi

# T31 Aoni EP01J05
if [ "$1" = "rtl8188fu-t31-aoni-ep01j05" ]; then
	set_gpio 43 1
	modprobe 8188fu
	exit 0
fi

# T31 CamHi
if [ "$1" = "mt7601u-t31-camhi" ]; then
	set_gpio 61 0
	modprobe mac80211
	exit 0
fi

# T31 Camhipro
if [ "$1" = "rtl8733bu-t31-camhipro" ]; then
	set_gpio 61 0
	modprobe 8733bu
	exit 0
fi

exit 1
