GADGET_SERIAL_VERSION = 1.0
GADGET_SERIAL_SITE_METHOD = local
GADGET_SERIAL_SITE = $(GADGET_SERIAL_PKGDIR)

define GADGET_SERIAL_INSTALL_SCRIPTS
	$(INSTALL) -D -m 0755 $(GADGET_SERIAL_PKGDIR)/files/F02failsafe-usb \
		$(TARGET_DIR)/etc/init.d/F02failsafe-usb
endef

GADGET_SERIAL_POST_INSTALL_TARGET_HOOKS += GADGET_SERIAL_INSTALL_SCRIPTS

$(eval $(generic-package))
