WYZE_ACCESSORY_VERSION = 1.0
WYZE_ACCESSORY_SITE_METHOD = local
WYZE_ACCESSORY_SITE = $(WYZE_ACCESSORY_PKGDIR)/files

define WYZE_ACCESSORY_INSTALL_TARGET_CMDS_SPOTLIGHT
	$(INSTALL) -m 755 -D $(WYZE_ACCESSORY_PKGDIR)/files/spotlight_ctl $(TARGET_DIR)/usr/sbin/spotlight_ctl
	$(INSTALL) -m 755 -d $(TARGET_DIR)/etc/modules.d
	echo ch341 >> $(TARGET_DIR)/etc/modules.d/accessory
endef

define WYZE_ACCESSORY_INSTALL_TARGET_CMDS_CAR
	$(INSTALL) -m 0755 -D $(WYZE_ACCESSORY_PKGDIR)/files/car_control $(TARGET_DIR)/usr/sbin/car_control
	$(INSTALL) -m 0755 -d $(TARGET_DIR)/etc/modules.d
	echo cp210x >> $(TARGET_DIR)/etc/modules.d/accessory
endef

define WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS_SPOTLIGHT
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL_CH341,m)
endef

define WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS_CAR
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL_CP210X,m)
endef

ifeq ($(BR2_PACKAGE_WYZE_ACCESSORY_SPOTLIGHT),y)
	WYZE_ACCESSORY_INSTALL_TARGET_CMDS += $(WYZE_ACCESSORY_INSTALL_TARGET_CMDS_SPOTLIGHT)
	WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS += $(WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS_SPOTLIGHT)
endif

ifeq ($(BR2_PACKAGE_WYZE_ACCESSORY_CAR),y)
	WYZE_ACCESSORY_INSTALL_TARGET_CMDS += $(WYZE_ACCESSORY_INSTALL_TARGET_CMDS_CAR)
	WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS += $(WYZE_ACCESSORY_LINUX_CONFIG_FIXUPS_CAR)
endif

define WYZE_ACCESSORY_INSTALL_CMDS
    $(WYZE_ACCESSORY_INSTALL_TARGET_CMDS)
endef

$(eval $(generic-package))

define WYZE_ACCESSORY_INSTALL_TARGET_CMDS
    $(call WYZE_ACCESSORY_INSTALL_TARGET_CMDS_SPOTLIGHT)
    $(call WYZE_ACCESSORY_INSTALL_TARGET_CMDS_CAR)
endef
