#!/bin/sh
# Enable the DWC2 USB controller and its PHY in a 4.4 kernel device tree.
# BR2_PACKAGE_THINGINO_KOPT_DWC2 builds the driver, but most vendor trees
# (every T32 and T33 board, early T41) ship the otg and otg_phy nodes
# disabled, so a camera that needs USB, a USB WiFi one above all, got no bus.
#
# A tree built from the SoC .dtsi carries the nodes as the otg and otg_phy
# labels. A camera profile's own .dts is usually a decompiled dtb with no
# labels, so its nodes are reopened by their full path. A tree with more than
# one controller (A1) is left alone: which of them is wired is board-specific.
#
# Usage: inject-usb-dt.sh <linux-dir> <host|otg>
set -e

LINUX="$1"
MODE="$2"
DTSDIR="$LINUX/arch/mips/boot/dts/ingenic"
[ -f "$DTSDIR/Makefile" ] && [ -f "$LINUX/.config" ] || exit 0

# Print the fragment for tree $1; what it did goes to stderr.
fragment() {
	python3 - "$1" "$MODE" <<'PY'
import os, re, sys

dts, mode = sys.argv[1], sys.argv[2]


def load(path, seen):
    if path in seen or not os.path.isfile(path):
        return ""
    seen.add(path)
    s = open(path).read()
    for inc in re.findall(r'^\s*#include\s+"([^"]+)"', s, re.M):
        s += "\n" + load(os.path.join(os.path.dirname(path), inc), seen)
    return s


# Paths of the nodes defined in this file whose first compatible is compat.
# Nodes reopened through a &label are not paths and are skipped.
def paths(src, compat):
    found, stack = [], []
    for line in src.splitlines():
        line = line.split("//")[0]
        m = re.match(r"^\s*(?:[\w-]+\s*:\s*)?(/|&[\w-]+|[\w,.+-]+(?:@[\w,.+-]+)?)\s*\{", line)
        if m:
            stack.append(m.group(1))
        elif re.match(r'^\s*compatible\s*=\s*"%s"' % re.escape(compat), line) and stack:
            if stack[0] == "/" and not any(n.startswith("&") for n in stack):
                found.append(stack[1:])
        for _ in range(line.count("};")):
            if stack:
                stack.pop()
    return found


def override(path, body):
    out, ind = "/ {\n", "\t"
    for n in path:
        out += "%s%s {\n" % (ind, n)
        ind += "\t"
    out += "".join("%s%s\n" % (ind, b) for b in body)
    for _ in path:
        ind = ind[:-1]
        out += "%s};\n" % ind
    return out + "};\n"


src = open(dts).read()
tree = load(dts, set())
body = ('status = "okay";', 'dr_mode = "%s";' % mode)
otg, phy = paths(src, "ingenic,dwc2-hsotg"), paths(src, "ingenic,innophy")
name = os.path.basename(dts)

print("/* Generated by thingino-kopt for BR2_PACKAGE_THINGINO_KOPT_DWC2. */")
if len(otg) > 1 or len(phy) > 1:
    print("thingino-kopt: %s: %d USB controllers, left as is" % (name, len(otg)), file=sys.stderr)
elif otg and phy:
    print(override(otg[0], body) + override(phy[0], body), end="")
    print("thingino-kopt: %s: USB %s (by path)" % (name, mode), file=sys.stderr)
elif re.search(r"^\s*otg\s*:", tree, re.M) and re.search(r"^\s*otg_phy\s*:", tree, re.M):
    for label in ("otg", "otg_phy"):
        print("&%s {\n%s};" % (label, "".join("\t%s\n" % b for b in body)))
    print("thingino-kopt: %s: USB %s" % (name, mode), file=sys.stderr)
else:
    print("thingino-kopt: %s: no otg/otg_phy nodes, left as is" % name, file=sys.stderr)
PY
}

# The trees this kernel config builds, from the dtb-$(CONFIG_...) lines.
# shellcheck disable=SC2016
sed -n 's/^dtb-\$(\(CONFIG_[A-Z0-9_]*\))[[:space:]]*+=[[:space:]]*\([^[:space:]]*\)\.dtb.*/\1 \2/p' "$DTSDIR/Makefile" | while read -r opt name; do
	grep -q "^$opt=y" "$LINUX/.config" || continue
	dts="$DTSDIR/$name.dts"
	[ -f "$dts" ] || continue

	inc="$name-thingino-usb.dtsi"
	# Rewritten only on change, so an unchanged board does not rebuild the dtb.
	fragment "$dts" >"$DTSDIR/$inc.tmp"
	if cmp -s "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"; then
		rm -f "$DTSDIR/$inc.tmp"
	else
		mv "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"
	fi
	grep -q "#include \"$inc\"" "$dts" || printf '\n#include "%s"\n' "$inc" >>"$dts"
done
exit 0
