################ JZ_MAC #########################
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_JZ_MAC_V12),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_JZ_MAC_V12
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_V12)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_MODE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_RMII)
endef
endif

ifeq ($(BR2_PACKAGE_THINGINO_KOPT_JZ_MAC_V13),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_JZ_MAC_V13
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_V13)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_MODE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZ_MAC_RMII)
endef
endif

################ MMC #########################
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_BLOCK)
	$(call KCONFIG_SET_OPT,CONFIG_MMC_BLOCK_MINORS,8)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_BLOCK_BOUNCE)
	$(call KCONFIG_SET_OPT,CONFIG_JZMMC_V12,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_SDMA)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC0),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC0)
	$(call KCONFIG_SET_OPT,CONFIG_MMC0_MAX_FREQ,48000000)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC1),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1)
	$(call KCONFIG_SET_OPT,CONFIG_MMC0_MAX_FREQ,24000000)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC0_4BIT),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0_4BIT
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC0_PB_4BIT)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC0_8BIT),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0_8BIT
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC0_PB_8BIT)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC1_4BIT),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1_4BIT
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1_PB_4BIT)
endef
endif
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_MMC1_8BIT),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1_8BIT
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1_PB_8BIT)
endef
endif

################ DWC2 #########################
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_DWC2),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_DWC2
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_ARCH_HAS_OHCI=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_SUPPORT=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_COMMON=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_OTG=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_JZ_DWC2)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_DWC2_DUAL_ROLE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_DWC2_VERBOSE_VERBOSE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_GADGET)
	$(call KCONFIG_SET_OPT,CONFIG_USB_GADGET_VBUS_DRAW,2)
	$(call KCONFIG_SET_OPT,CONFIG_USB_GADGET_STORAGE_NUM_BUFFERS,2)
endef
endif

################ RTC #########################
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_RTC),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_RTC
# CONFIG_RTC_CLASS=y
# CONFIG_RTC_HCTOSYS=y
# CONFIG_RTC_SYSTOHC=y
# CONFIG_RTC_HCTOSYS_DEVICE="rtc0"
# # CONFIG_RTC_DEBUG is not set
# # RTC interfaces
# CONFIG_RTC_INTF_SYSFS=y
# CONFIG_RTC_INTF_PROC=y
# CONFIG_RTC_INTF_DEV=y
endef
endif

################ PWM #########################
ifeq ($(BR2_PACKAGE_THINGINO_KOPT_PWM),y)
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS_PWM
	$(call KCONFIG_ENABLE_OPT,CONFIG_MFD_CORE=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MFD_JZ_TCU=y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PWM=y)
endef
endif

####################################################

#This is required for BR to successfully concatenate the kernel options when used with modules
define THINGINO_KOPT_LINUX_CONFIG_FIXUPS
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_JZ_MAC_V12)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_JZ_MAC_V13)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0_4BIT)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC0_8BIT)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1_4BIT)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_MMC1_8BIT)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_DWC2)
	$(call THINGINO_KOPT_LINUX_CONFIG_FIXUPS_PWM)
endef

$(eval $(generic-package))
