#!/bin/sh

DAEMON_ARGS=""

. /usr/share/common

start() {
	echo_title "Starting Day/Night daemon"

	start_daemon
}

stop() {
	echo_title "Stopping Day/Night daemon"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart | reload)
		stop || true
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
