#!/bin/bash
# Read sensor type from the environment
SENSOR=$1
SOC=$2
#clocks should be completely independent of sensor parameteress
#		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
#		ISP_PARAM="isp_clk=125000000"
#		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
#		ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
#		AVPU_PARAM="clk_name=mpll avpu_clk=500000000"
#define isp_memopt 1 and 2

case "$SENSOR" in
    ar1337)
        SENSOR_PARAM=""
        ;;
    bf3a03)
        SENSOR_PARAM=""
        ;;
    c2399)
        SENSOR_PARAM=""
        ;;
    c23a98)
        SENSOR_PARAM=""SENSOR_MODEL

        ;;
    c3390)
        SENSOR_PARAM=""
        ;;
    c4390)
        SENSOR_PARAM=""
        ;;
    cv2001)
        SENSOR_PARAM=""
        ;;
    cv3001)
        SENSOR_PARAM=""
        ;;
    cv4001)
        SENSOR_PARAM=""
        ;;
    gc0328)
        SENSOR_PARAM=""
        ;;
    gc032a)
        SENSOR_PARAM=""
        ;;
    gc1034)
        SENSOR_PARAM=""
        ;;
    gc1054)
        SENSOR_PARAM=""
        ;;
    gc1084)
        SENSOR_PARAM=""
        ;;
    gc2023)
        SENSOR_PARAM=""
        ;;
    gc2033)
        SENSOR_PARAM=""
        ;;
    gc2053)
        SENSOR_PARAM="sensor_max_fps=30 data_interface=1"
        ;;
    gc2063)
        SENSOR_PARAM=""
        ;;
    gc2083)
        SENSOR_PARAM="shvflip=1"
        ;;
    gc2093)
        SENSOR_PARAM=""
        ;;
    gc3003)
        SENSOR_PARAM=""
        ;;
    gc3003a)
        SENSOR_PARAM=""
        ;;
    gc4023)
        SENSOR_PARAM=""
        ;;
    gc4653)
        SENSOR_PARAM=""
        ;;
    gc4c33)
        SENSOR_PARAM=""
        ;;
    gc5035)
        SENSOR_PARAM=""
        ;;
    gc5603)
        SENSOR_PARAM=""
        ;;
    imx298)
        SENSOR_PARAM=""
        ;;
    imx307)
        SENSOR_PARAM=""
        ;;
    imx327)
        SENSOR_PARAM=""
        ;;
    imx335)
        SENSOR_PARAM=""
        ;;
    jxf23)
        SENSOR_PARAM=""
        ;;
    jxf28p)
        SENSOR_PARAM=""
        ;;
    jxf32)
        SENSOR_PARAM=""
        ;;
    jxf35)
        SENSOR_PARAM=""
        ;;
    jxf352)
        SENSOR_PARAM=""
        ;;
    jxf355p)
        SENSOR_PARAM=""
        ;;
    jxf37)
        SENSOR_PARAM=""
        ;;
    jxf37p)
        SENSOR_PARAM=""
        ;;
    jxf38p)
        SENSOR_PARAM=""
        ;;
    jxf51)
        SENSOR_PARAM=""
        ;;
    jxf53)
        SENSOR_PARAM=""
        ;;
    jxh61p)
        SENSOR_PARAM=""
        ;;
    jxh62)
        SENSOR_PARAM=""
        ;;
    jxh63)
        SENSOR_PARAM=""
        ;;
    jxh66)
        SENSOR_PARAM=""
        ;;
    jxk03)
        SENSOR_PARAM=""
        ;;
    jxk04)
        SENSOR_PARAM=""
        ;;
    jxk05)
        SENSOR_PARAM=""
        ;;
    jxk06)
        SENSOR_PARAM=""
        ;;
    jxq03)
        SENSOR_PARAM=""
        ;;
    jxq03p)
        SENSOR_PARAM=""
        ;;
    mis2006)
        SENSOR_PARAM=""
        ;;
    mis2008)
        SENSOR_PARAM=""
        ;;
    mis4001)
        SENSOR_PARAM=""
        ;;
    mis5001)
        SENSOR_PARAM=""
        ;;
    os02d20)
        SENSOR_PARAM=""
        ;;
    os02g10)
        SENSOR_PARAM=""
        ;;
    os02k10)
        SENSOR_PARAM=""
        ;;
    os03b10)
        SENSOR_PARAM=""
        ;;
    os04b10)
        SENSOR_PARAM=""
        ;;
    os04c10)
        SENSOR_PARAM=""
        ;;
    os04l10)
        SENSOR_PARAM=""
        ;;
    os05a10)
        SENSOR_PARAM=""
        ;;
    os05a20)
        SENSOR_PARAM=""
        ;;
    ov2740)
        SENSOR_PARAM=""
        ;;
    ov2745)
        SENSOR_PARAM=""
        ;;
    ov5648)
        SENSOR_PARAM=""
        ;;
    ov5695)
        SENSOR_PARAM=""
        ;;
    ov8856)
        SENSOR_PARAM=""
        ;;
    ov9732)
        SENSOR_PARAM=""
        ;;
    ps5258)
        SENSOR_PARAM=""
        ;;
    ps5260)
        SENSOR_PARAM=""
        ;;
    ps5268)
        SENSOR_PARAM=""
        ;;
    ps5270)
        SENSOR_PARAM=""
        ;;
    ps5520)
        SENSOR_PARAM=""
        ;;
    sc1346)
        SENSOR_PARAM=""
        ;;
    sc200ai)
        SENSOR_PARAM=""
        ;;
    sc201cs)
        SENSOR_PARAM=""
        ;;
    sc202cs)
        SENSOR_PARAM=""
        ;;
    sc2210)
        SENSOR_PARAM=""
        ;;
    sc2232h)
        SENSOR_PARAM=""
        ;;
    sc2235)
        SENSOR_PARAM=""
        ;;
    sc2239)
        SENSOR_PARAM=""
        ;;
    sc2239p)
        SENSOR_PARAM=""
        ;;
    sc223a)
        SENSOR_PARAM=""
        ;;
    sc230ai)
        SENSOR_PARAM=""
        ;;
    sc2310)
        SENSOR_PARAM=""
        ;;
    sc2315e)
        SENSOR_PARAM=""
        ;;
    sc2332)
        SENSOR_PARAM=""
        ;;
    sc2335)
        SENSOR_PARAM=""
        ;;
    sc2336)
        SENSOR_PARAM=""
        ;;
    sc301IoT)
        SENSOR_PARAM=""
        ;;
    sc3235)
        SENSOR_PARAM=""
        ;;
    sc3335)
        SENSOR_PARAM=""
        ;;
    sc3336)
        SENSOR_PARAM=""
        ;;
    sc3338)
        SENSOR_PARAM=""
        ;;
    sc401ai)
        SENSOR_PARAM=""
        ;;
    sc4236)
        SENSOR_PARAM=""
        ;;
    sc4236h)
        SENSOR_PARAM=""
        ;;
    sc4238)
        SENSOR_PARAM=""
        ;;
    sc4335)
        SENSOR_PARAM=""
        ;;
    sc4336)
        SENSOR_PARAM=""
        ;;
    sc4336p)
        SENSOR_PARAM=""
        ;;
    sc450ai)
        SENSOR_PARAM=""
        ;;
    sc500ai)
        SENSOR_PARAM=""
        ;;
    sc5235)
        SENSOR_PARAM=""
        ;;
    sp1405)
        SENSOR_PARAM=""
        ;;
    tp2850)
        SENSOR_PARAM=""
        ;;
	*)
		echo "Unknown sensor"
		;;
esac

echo sensor_"$SENSOR"_"$SOC" $SENSOR_PARAM
