WIFI_HWSIM_LICENSE = GPL-2.0

HWSIM_MODULE_NAME = mac80211_hwsim
HWSIM_MODULE_OPTS =

define WIFI_HWSIM_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211_WEXT)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_CCM,m)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_CTR,m)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_GCM,m)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_SEQIV,m)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_HWSIM,m)
endef

$(eval $(generic-package))
