#!/bin/sh

. /etc/init.d/rc.common

if [ "$IFACE" = "wlan0" ]; then
	if [ -z "$(fw_printenv -n wlanssid)" ] || [ -z "$(fw_printenv -n wlanpass)" ]; then
		info "wlan0 disabled, no SSID/pass"
		exit 1
	elif [ "$(fw_printenv -n disable_wlan)" = "true" ]; then
		info "WLAN manually disabled."
		exit 1
	fi
fi
