#!/bin/sh

. /etc/init.d/rc.common

nfsip=$(sed -n '/^[^ ]*:.* \/ nfs.*[ ,]addr=\([0-9.]\+\).*/s//\1/p' /proc/mounts)

# Check if the interface is not a USB device, then set the MAC address, unless using nfsroot
if [ -n "$nfsip" ] && ip route get "$nfsip" | grep -q "dev $IFACE"; then
	info "Skipping MAC address setup for $IFACE, used for NFS from $nfsip"
elif [ "$IFACE" = "eth0" ] && ! readlink -f /sys/class/net/$IFACE/device | grep -q "usb"; then
	info "Setting eth0 MAC address from environment"
	MAC_ADDR=$(get ethaddr)
	[ -n "$MAC_ADDR" ] && /sbin/ip link set dev $IFACE address "$MAC_ADDR"
fi

exit 0
