#!/bin/sh

echo_c 208 \$-
if echo $- | grep -q i > /dev/null; then
	echo "Interactive"
else
	echo "Non-interactive"
fi


echo_c 208 tty
if tty > /dev/null; then
	echo "Interactive"
else
	echo "Non-interactive"
fi

exit 0
