#!/bin/sh

DAEMON="onvif_notify_server"
DAEMON_ARGS="-c /etc/onvif.json -p /run/$DAEMON.pid"
MOTION="/run/motion"

. /usr/share/common

start() {
	echo_title "Starting ONVIF Notify service"

	[ -d "$MOTION" ] || mkdir -p $MOTION

	start_daemon
}

stop() {
	echo_title "Stopping ONVIF Notify service"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
