THINGINO_USTREAM_SSL_VERSION = 99bd3d2b167ccdffb6de072d02c380cb37b23e33
THINGINO_USTREAM_SSL_SITE = https://git.openwrt.org/project/ustream-ssl.git
THINGINO_USTREAM_SSL_SITE_METHOD = git
THINGINO_USTREAM_SSL_LICENSE = ISC
THINGINO_USTREAM_SSL_LICENSE_FILES = ustream-ssl.h
THINGINO_USTREAM_SSL_INSTALL_STAGING = YES
THINGINO_USTREAM_SSL_DEPENDENCIES = libubox thingino-wolfssl
THINGINO_USTREAM_SSL_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release -DWOLFSSL=ON

$(eval $(cmake-package))
