THINGINO_USTREAM_SSL_VERSION = 5a81c108d20e24724ed847cc4be033f2a74e6635
THINGINO_USTREAM_SSL_SITE = https://git.openwrt.org/project/ustream-ssl.git
THINGINO_USTREAM_SSL_SITE_METHOD = git
THINGINO_USTREAM_SSL_LICENSE = ISC
THINGINO_USTREAM_SSL_LICENSE_FILES = ustream-ssl.h
THINGINO_USTREAM_SSL_INSTALL_STAGING = YES
THINGINO_USTREAM_SSL_DEPENDENCIES = libubox thingino-wolfssl
THINGINO_USTREAM_SSL_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release -DWOLFSSL=ON

$(eval $(cmake-package))
