#!/bin/sh

PORTAL_MODE_FLAG="/run/portal_mode"
SOC_FAMILY="$(soc -f)"

config="/etc/imp.conf"

is_streamer_disabled() {
	[ "true" = "$disable_streamer" ] || [ -f "$PORTAL_MODE_FLAG" ]
}

check_imp() {
	local isp_path

	case "$SOC_FAMILY" in
		t10 | t20)
			isp_path="/proc/jz/isp/isp_info"
			;;
		*)
			isp_path="/proc/jz/isp/isp-fs"
			;;
	esac

	echo "Connecting to libimp-control"
	local i=10
	while [ "$i" -gt 0 ]; do
		if grep -Eq "running|Software" $isp_path; then
			imp-control getdeviceid >/dev/null
			echo -n " "
			return
		fi
		i=$((i - 1))
		echo -n "."
		sleep 1
	done
	echo "Timeout" >&2
	exit 1
}

start() {
	echo -c 15 "IMP Configuration"

	if is_streamer_disabled; then
		echo "Streamer disabled" >&2
		exit 1
	fi

	check_imp

	if [ -f "$config" ]; then
		echo "Restore IMP Configuration"
		while read -r line; do
			imp-control $line >/dev/null
		done <$config
	else
		echo "Nothing to restore"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
