FAAC_SITE_METHOD = git
FAAC_SITE = https://github.com/knik0/faac
FAAC_SITE_BRANCH = master
FAAC_VERSION = 6d9b02edd268bd2f3377a388ed77dde4f34556c8

FAAC_LICENSE = MPEG-4-Reference-Code, LGPL-2.1+
FAAC_LICENSE_FILES = COPYING

FAAC_DEPENDENCIES = host-pkgconf

FAAC_INSTALL_STAGING = YES
FAAC_INSTALL_TARGET = YES

FAAC_CONF_ENV += CFLAGS="$(TARGET_CFLAGS) -ffast-math"

FAAC_CONF_OPTS = \
	-Dfloating-point=single \
	-Dmax-channels=2

ifneq ($(BR2_PACKAGE_FAAC_INSTALL_BIN),y)
define FAAC_REMOVE_TARGET_BINARY
	rm -f $(TARGET_DIR)/usr/bin/faac
endef
FAAC_POST_INSTALL_TARGET_HOOKS += FAAC_REMOVE_TARGET_BINARY

define FAAC_REMOVE_STAGING_BINARY
	rm -f $(STAGING_DIR)/usr/bin/faac
endef
FAAC_POST_INSTALL_STAGING_HOOKS += FAAC_REMOVE_STAGING_BINARY
endif

$(eval $(meson-package))
