FAAC_SITE_METHOD = git
FAAC_SITE = https://github.com/knik0/faac
FAAC_SITE_BRANCH = master
FAAC_VERSION = 64fc54142912088eecabaa159339768eca30f3d6

FAAC_LICENSE = MPEG-4-Reference-Code, LGPL-2.1+
FAAC_LICENSE_FILES = COPYING

FAAC_DEPENDENCIES = host-pkgconf

FAAC_INSTALL_STAGING = YES
FAAC_INSTALL_TARGET = YES

FAAC_CONF_OPTS = \
	$(if $(BR2_PACKAGE_FAAC_ENABLE_DRM),-Ddrm=true,-Ddrm=false) \
	-Dfloating-point=single

ifneq ($(BR2_PACKAGE_FAAC_INSTALL_BIN),y)
define FAAC_REMOVE_TARGET_BINARY
	rm -f $(TARGET_DIR)/usr/bin/faac
endef
FAAC_POST_INSTALL_TARGET_HOOKS += FAAC_REMOVE_TARGET_BINARY

define FAAC_REMOVE_STAGING_BINARY
	rm -f $(STAGING_DIR)/usr/bin/faac
endef
FAAC_POST_INSTALL_STAGING_HOOKS += FAAC_REMOVE_STAGING_BINARY
endif

$(eval $(meson-package))
