#!/bin/sh

. /etc/init.d/rc.common

usb_console=$(fw_printenv -n usb_console)

if [ "$usb_console" = "true" ]; then
	# Load g_serial module and set USB role
	modprobe g_serial iManufacturer="thingino" iProduct="USB Gadget Serial Console"
	usb-role -m device

	# Wait for failsafe prompt
	sleep 2

	# Display the failsafe message only on ttyGS0
	echo_c 208 "\nPress the [f] key to enter failsafe mode [USB gadget]\n" > /dev/ttyGS0

	# Set up the terminal settings for ttyGS0
	stty -icanon min 0 time 20 -echo < /dev/ttyGS0

	# Read the key input from ttyGS0
	key_gs0=$(dd bs=1 count=1 2> /dev/null < /dev/ttyGS0)

	# Restore terminal settings for ttyGS0
	stty sane < /dev/ttyGS0

	# Check for failsafe mode input from ttyGS0
	if [ "$key_gs0" = "f" ]; then
		echo_c 118 "Entering failsafe mode..." > /dev/ttyGS0
		while true; do setsid /sbin/getty -n -l /bin/sh ttyGS0 0 vt100; sleep 1; done &
	else
		/etc/init.d/rcS > /dev/ttyGS0 2>&1
		if [ "$(get debug)" = "1" ]; then cmd="-n -l /bin/sh"; else cmd="-L"; fi; while true; do setsid /sbin/getty $cmd ttyGS0 0 vt100; sleep 1; done &
	fi
fi
