#!/bin/sh

. /etc/init.d/rc.common

usb_console=$(fw_printenv -n usb_console)

if [ "$usb_console" = "true" ]; then
	modprobe g_serial
	usb-role -m device
	sleep 2

	echo_c 208 "\nPress the [f] key to enter failsafe mode\n" > /dev/ttyGS0

	stty -icanon min 0 time 20 -echo < /dev/ttyGS0

	key_gs0=$(dd bs=1 count=1 2> /dev/null < /dev/ttyGS0)

	stty sane < /dev/ttyGS0

	if [ "$key_gs0" = "f" ]; then
		echo_c 118 "Entering failsafe mode..." > /dev/ttyGS0
		/bin/sh < /dev/ttyGS0 > /dev/ttyGS0 2>&1
	else
		/etc/init.d/rcS > /dev/ttyGS0 2>&1
	/sbin/getty -L ttyGS0 115200 vt100
	fi
else
	echo_c 208 "\nPress the [f] key to enter failsafe mode\n"

	stty -icanon min 0 time 20 -echo

	key=$(dd bs=1 count=1 2> /dev/null)

	stty sane

	if [ "$key" = "f" ]; then
		echo_c 118 "Entering failsafe mode..."
		/bin/sh
	else
		/etc/init.d/rcS
	fi
fi

