#!/bin/sh

. /etc/init.d/rc.common

INITAB="/etc/inittab"

case "$1" in
	start)
		starting
		info "Load g_serial module"
		run "modprobe g_serial"

		info "Start serial gadget console"
		grep ttyGS0 $INITAB || echo "::respawn:/sbin/getty -L ttyGS0 115200 vt100" >> $INITAB
		kill -1 1
		;;
	stop)
		stopping
		info "Stopping gadget console"
		sed -i /ttyGS0/d $INITAB
		kill -1 1

		info "Unload g_serial module"
		run "rmmod -w g_serial"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
