#!/bin/sh

HOSTS=/tmp/dnsd.conf

cp /etc/dnsd-ap.conf ${HOSTS}
hostname=$(fw_printenv -n hostname)
grep $hostname ${HOSTS} > /dev/null || echo $(hostname).local $(hostname -i) >> ${HOSTS}

dumpleases -f /run/udhcpd_ap.leases -d | grep -v "^Mac Address" |
while read line; do
	ip=$(echo $line | cut -s -F 2)
	hostname=$(echo $line | cut -s -F 3)
	[ " " != "${line:34:1}" ] && echo $hostname.local $ip >> ${HOSTS}
done
