#!/bin/sh

. /etc/init.d/rc.common

CNET=100.64.1

# Define net_dev in the global scope
net_dev="wlan0"  # default device
if [ "$wlan_module" = "hi3881" ]; then
	net_dev="ap0"
	sed -i 's/wlan0/ap0/g' /etc/udhcpd-ap.conf
fi

start() {
	echo "Starting WLAN AP..."

	(iface_exists "eth0" || iface_exists "usb0") && quit "Wired interface found"
	iface_exists "$net_dev" || quit "Wireless port not found"
	# quit if credentials are set, AP conflicts with normal wifi operation

	[ "true" = "$wlanap_enabled" ] || quit "WLAN AP disabled"

	touch /var/run/udhcpd_ap.leases
	cp /etc/resolv-ap.conf /tmp/resolv.conf

	ip a add dev $net_dev ${CNET}.1/24
	ip link set $net_dev up
	ip route add ${CNET}.0/24 dev $net_dev > /dev/null 2>&1

	cp /etc/dnsd-ap.conf /tmp/dnsd.conf
	hostname=$(hostname)
	grep $hostname /tmp/dnsd.conf > /dev/null || echo $hostname.local ${CNET}.1 >> /tmp/dnsd.conf

	start-stop-daemon -S -x /sbin/udhcpd -- -S -I ${CNET}.1 /etc/udhcpd-ap.conf 2>&1
	start-stop-daemon -S -x /sbin/dnsd -- -i ${CNET}.1 -c /tmp/dnsd.conf -d

	mac_address=$(ip link show $net_dev | awk '/ether/ {print $2}')
	last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')

	if [ -n "$wlanap_ssid" ]; then
		sed -i '/ssid=/ s/ssid="[^"]*"/ssid="'"$wlanap_ssid"'"/' /etc/wpa-ap.conf
	else
		sed -i '/ssid=/ s/ssid="[^"]*"/ssid="THINGINO-'"$last_two"'"/' /etc/wpa-ap.conf
	fi

	[ ${#wlanap_pass} -lt 8 ] && wlanap_pass="thingino"

	[[ ${#wlanap_pass} -eq 64 && "$wlanap_pass" =~ ^[0-9a-fA-F]{64}$ ]] && quote='' || quote='"'
	sed -i '/psk=/ s/psk=["]*[^"]*["]*/psk='"$quote$wlanap_pass$quote"'/' /etc/wpa-ap.conf

	start-stop-daemon -S -x /sbin/wpa_supplicant -- -i $net_dev -B -c /etc/wpa-ap.conf 2>&1
}

stop() {
	echo "Stopping WLAN AP..."

	start-stop-daemon -K -q -x /sbin/udhcpd
	start-stop-daemon -K -q -x /sbin/dnsd
	start-stop-daemon -K -q -x /sbin/wpa_supplicant
	ip address delete dev $net_dev ${CNET}.1/24
	ip link set $net_dev down
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
