#!/bin/sh

# You don't usually need to touch this file at all, the full configuration
# of the bridge can be done in /etc/network/interfaces.
# Read more at https://wiki.debian.org/BridgeNetworkConnections

[ ! -x /usr/sbin/brctl ] && exit 0

case "$IF_BRIDGE_PORTS" in
  "")
    exit 0 ;;
  none)
    INTERFACES="" ;;
  all)
    INTERFACES=`grep eth /proc/net/dev|sed 's/\(\ *\)\(eth[^:]*\)\(.*\)/\2/'` ;;
  *)
    INTERFACES="$IF_BRIDGE_PORTS" ;;
esac

brctl addbr $IFACE &&

for i in $INTERFACES; do
  if [ -x /etc/network/if-pre-up.d/vlan ]; then
    env IFACE=$i /etc/network/if-pre-up.d/vlan
  fi
  brctl addif $IFACE $i && ip link set dev $i up
done

brctl stp $IFACE off
