################################################################################
#
# mt7601sta
#
################################################################################

MT7601STA_VERSION = $(LINUX_VERSION_PROBED)
MT7601STA_SITE_METHOD = local
MT7601STA_SITE = $(LINUX_DIR)/drivers/net/wireless/mt7601u
MT7601STA_MODULE_MAKE_OPTS = CONFIG_MT7601_STA=m
#        KVER=$(LINUX_VERSION_PROBED) \
#        KSRC=$(LINUX_DIR) \
#        USER_EXTRA_CFLAGS="-Wno-error"

define MT7601STA_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
endef

#	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_SUPPORT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_USB)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_NET)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211_DEFAULT_PS)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211_WEXT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_HAS_RC)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
#	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")

$(eval $(kernel-module))
$(eval $(generic-package))
