#!/bin/sh

RESOLV_DEFAULT_FILE="/etc/default/resolv.conf"
RESOLV_WORKING_FILE="/tmp/resolv.conf"

if [ ! -f /etc/network/interfaces.d/$IFACE ]; then
	echo -c 160 -e "No configuration file for $IFACE" >&2
	exit 0
fi

if grep -q static /etc/network/interfaces.d/$IFACE >/dev/null; then
	echo -c 160 -e "$IFACE uses dynamic IP address" >&2
	exit 0
fi

if [ ! -f "$RESOLV_DEFAULT_FILE" ]; then
	echo -c 160 -e "$IFACE does not use static DNS servers" >&2
	exit 0
fi

if [ ! -f "$RESOLV_WORKING_FILE" ]; then
	echo -c 240 -e "- Adding static DNS servers for $IFACE"
	cp "$RESOLV_DEFAULT_FILE" "$RESOLV_WORKING_FILE"
fi

grep -v '^#' /etc/default/resolv.conf | while read line; do
	if ! grep -q "^$line$" "$RESOLV_WORKING_FILE" >/dev/null; then
		echo -c 240 -e "- append $line"
		echo "$line" >>"$RESOLV_WORKING_FILE"
	fi
done

exit 0
