#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic
SOC=$(ipcinfo -f || fw_printenv -n soc)

echo 1 >/proc/sys/vm/overcommit_memory

check_return() {
	if [ $? -ne 0 ]; then
		echo err: $1
		echo exit
		exit
	fi
}

log() {
	logger -s -p daemon.info -t ingenic "$1"
}

if ! grep -q "^sinfo" /proc/modules; then
	modprobe sinfo
	check_return "modprobe sinfo"
fi

if fw_printenv -n sensor >/dev/null; then
	export SENSOR=$(fw_printenv -n sensor)
	log "Get data from environment and set SENSOR as ${SENSOR}"
else
	echo 1 >/proc/jz/sinfo/info
	check_return "start sinfo"
	SENSOR_INFO=$(cat /proc/jz/sinfo/info)
	check_return "get sensor type"
	SENSOR=${SENSOR_INFO#*:}
	if [ "sensor not found" = "$SENSOR" ]; then
		unset SENSOR
		fw_setenv sensor
	else
		log "Get data from sinfo and set SENSOR as ${SENSOR}"
		fw_setenv sensor $SENSOR && log "Write detected ${SENSOR} to U-Boot ENV"
	fi
fi

case "$SENSOR" in
	gc2053)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_max_fps=25 data_interface=1"
		;;
	jxf23| ov2735b | sc2232h | sc2335)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	jxf37)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	sc2232 | sc2300)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2332)
		ISP_PARAM=""
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	*)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
esac

echo --------------------
echo "ISP_PARAM: ${ISP_PARAM}"
echo "SENSOR: ${SENSOR}"
echo "SENSOR_PARAM: ${SENSOR_PARAM}"
echo --------------------

if ! grep -q "^tx_isp" /proc/modules; then
	modprobe tx-isp-${SOC} $ISP_PARAM
	check_return "modprobe isp drv"
fi

if ! grep -q "^${SENSOR}" /proc/modules; then
	modprobe sensor_${SENSOR}_${SOC} $SENSOR_PARAM
	check_return "modprobe sensor drv"
fi

if ! grep -q "^audio" /proc/modules; then
	modprobe audio spk_gpio=-1
	check_return "modprobe audio"
fi
