#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic

echo 1 >/proc/sys/vm/overcommit_memory

check_return() {
	if [ $? -ne 0 ]; then
		echo err: $1
		echo exit
		exit
	fi
}

log() {
	logger -s -p daemon.info -t ingenic "$1"
}

case "$SENSOR" in
	gc2053)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_max_fps=25 data_interface=1"
		;;
	jxf23| ov2735b | sc2232h | sc2335)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	jxf37)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	sc2232 | sc2300)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2332)
		ISP_PARAM=""
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	*)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
esac

echo --------------------
echo "ISP_PARAM: $ISP_PARAM"
echo "SENSOR: $SENSOR"
echo "SENSOR_PARAM: $SENSOR_PARAM"
echo --------------------

if ! grep -q "^tx_isp" /proc/modules; then
	modprobe tx-isp-${SOC} $ISP_PARAM
	check_return "modprobe tx-isp-${SOC}"
fi

if ! grep -q "^${SENSOR}" /proc/modules; then
	modprobe sensor_${SENSOR}_${SOC} $SENSOR_PARAM
	check_return "modprobe sensor_${SENSOR}_${SOC}"
fi

if ! grep -q "^audio" /proc/modules; then
	modprobe audio spk_gpio=-1
	check_return "modprobe audio"
fi
