THINGINO_WOLFSSL_VERSION = 5.7.4
THINGINO_WOLFSSL_SITE = $(call github,wolfSSL,wolfssl,v$(THINGINO_WOLFSSL_VERSION)-stable)
THINGINO_WOLFSSL_INSTALL_STAGING = YES

THINGINO_WOLFSSL_LICENSE = GPL-2.0+
THINGINO_WOLFSSL_LICENSE_FILES = COPYING LICENSING
THINGINO_WOLFSSL_CPE_ID_VENDOR = wolfssl
THINGINO_WOLFSSL_CONFIG_SCRIPTS = wolfssl-config
# From git
THINGINO_WOLFSSL_AUTORECONF = YES
THINGINO_WOLFSSL_DEPENDENCIES = host-pkgconf

THINGINO_WOLFSSL_CONF_OPTS = \
	--disable-examples \
	--disable-crypttests \
	--disable-option-checking

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-all
else
THINGINO_WOLFSSL_CONF_OPTS += --disable-all
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DISTRO),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-distro
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_EXPERIMENTAL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-experimental
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_THREADLOCAL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-threadlocal
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DEBUG_CODE_POINTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-debug-code-points
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DEBUG_TRACE_ERRCODES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-debug-trace-errcodes
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HARDEN_TLS),y)
THINGINO_WOLFSSL_CONF_OPTS += --string enable-harden-tls
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_32BIT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-32bit
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_16BIT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-16bit
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_64BIT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-64bit
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KDF),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kdf
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HMAC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hmac
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DO178),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-do178
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asm
else
THINGINO_WOLFSSL_CONF_OPTS += --disable-asm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FIPS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fips
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ENGINE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-engine
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_REPRODUCIBLE_BUILD),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-reproducible-build
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BENCHMARK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-benchmark
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LINUXKM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-linuxkm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LINUXKM_DEFAULTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-linuxkm-defaults
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LINUXKM_PIE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-linuxkm-pie
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LINUXKM_BENCHMARKS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-linuxkm-benchmarks
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SP_MATH_ALL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sp-math-all
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SP_MATH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sp-math
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SP_ASM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sp-asm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FASTMATH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fastmath
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FASTHUGEMATH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fasthugemath
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HEAPMATH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-heapmath
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-all
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALL_CRYPTO),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-all-crypto
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KYBER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kyber
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DILITHIUM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dilithium
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_XMSS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-xmss
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LMS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-lms
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SINGLETHREADED),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-singlethreaded
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RWLOCK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rwlock
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRYPTONLY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-cryptonly
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ech
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DTLS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dtls
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DTLS_MTU),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dtls-mtu
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KEYLOG_EXPORT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-keylog-export
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TLS13_DRAFT18),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tls13-draft18
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TLS13),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tls13
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_QUIC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-quic
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_POSTAUTH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-postauth
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HRRCOOKIE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hrrcookie
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RNG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rng
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SCTP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sctp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SRTP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-srtp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MCAST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-mcast
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BIND),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-bind
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LIBSSH2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-libssh2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENSSH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-openssh
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENVPN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-openvpn
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENRESTY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-openresty
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_NGINX),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-nginx
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CHRONY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-chrony
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENLDAP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-openldap
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LIGHTY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-lighty
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RSYSLOG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rsyslog
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HAPROXY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-haproxy
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WPAS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wpas
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WPAS_DPP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wpas-dpp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_NTP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ntp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FORTRESS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fortress
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LIBWEBSOCKETS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-libwebsockets
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_NET_SNMP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-net-snmp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KRB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-krb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FFMPEG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ffmpeg
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_IP_ALT_NAME),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ip-alt-name
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_QT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-qt
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BUMP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-bump
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SNIFFER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sniffer
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SIGNAL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-signal
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_STRONGSWAN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-strongswan
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HITCH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hitch
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MEMCACHED),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-memcached
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENSSLCOEXIST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-opensslcoexist
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SMIME),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-smime
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PSA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-psa
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PSA_LIB_STATIC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-psa-lib-static
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENSSLALL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-opensslall
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENSSLEXTRA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-opensslextra
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ERROR_QUEUE_PER_THREAD),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-error-queue-per-thread
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MAXSTRENGTH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-maxstrength
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HARDEN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-harden
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_IPV6),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ipv6
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LEANPSK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-leanpsk
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LEANTLS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-leantls
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LOWRESOURCE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-lowresource
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TITANCACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-titancache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HUGECACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hugecache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BIGCACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-bigcache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SMALLCACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-smallcache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SAVESESSION),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-savesession
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SAVECERT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-savecert
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WRITEDUP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-writedup
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ATOMICUSER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-atomicuser
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PKCALLBACKS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pkcallbacks
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESCBC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aescbc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESCBC_LENGTH_CHECKS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aescbc-length-checks
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESGCM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesgcm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESGCM_STREAM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesgcm-stream
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESCCM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesccm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESEAX),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aeseax
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESSIV),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aessiv
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESCTR),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesctr
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESOFB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesofb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESCFB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aescfb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AES_BITSLICED),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aes-bitsliced
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM4_ECB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm4-ecb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM4_CBC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm4-cbc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM4_CTR),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm4-ctr
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM4_GCM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm4-gcm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM4_CCM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm4-ccm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ARMASM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-armasm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RISCV_ASM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-riscv-asm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_XILINX),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-xilinx
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ARIA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aria
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CAAM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-caam
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESNI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesni
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_INTELASM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-intelasm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALIGNDATA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aligndata
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_INTELRAND),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-intelrand
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AMDRAND),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-amdrand
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AFALG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-afalg
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_HASH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-hash
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_HMAC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-hmac
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_AES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-aes
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_RSA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-rsa
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_DH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-dh
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI_ECC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi-ecc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KCAPI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-kcapi
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DEVCRYPTO),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-devcrypto
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CAMELLIA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-camellia
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MD2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-md2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_NULLCIPHER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-nullcipher
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RIPEMD),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ripemd
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BLAKE2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-blake2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BLAKE2S),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-blake2s
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHA224),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sha224
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHA3),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sha3
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHAKE128),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-shake128
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHAKE256),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-shake256
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHA512),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sha512
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHA384),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sha384
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM3),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm3
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SESSIONCERTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sessioncerts
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KEYGEN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-keygen
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CERTGEN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-certgen
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CERTREQ),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-certreq
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CERTEXT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-certext
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CERTGENCACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-certgencache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SEP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sep
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HKDF),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hkdf
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HPKE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hpke
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_X963KDF),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-x963kdf
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SRTP_KDF),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-srtp-kdf
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DSA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dsa
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECCSHAMIR),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-eccshamir
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ecc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SM2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sm2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECCCUSTCURVES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ecccustcurves
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_COMPKEY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-compkey
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BRAINPOOL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-brainpool
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CURVE25519),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-curve25519
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ED25519),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ed25519
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ED25519_STREAM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ed25519-stream
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CURVE448),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-curve448
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ED448),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ed448
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ED448_STREAM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ed448-stream
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FPECC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fpecc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECCENCRYPT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-eccencrypt
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ECCSI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-eccsi
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SAKKE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sakke
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PSK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-psk
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PSK_ONE_ID),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-psk-one-id
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ERRORSTRINGS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-errorstrings
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ERRORQUEUE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-errorqueue
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SSLV3),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sslv3
else
THINGINO_WOLFSSL_CONF_OPTS += --disable-sslv3
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TLSV10),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tlsv10
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OLDTLS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-oldtls
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TLSV12),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tlsv12
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_STACKSIZE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-stacksize
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MEMORY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-memory
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TRACKMEMORY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-trackmemory
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MEMORYLOG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-memorylog
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_STACKLOG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-stacklog
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WOLFSENTRY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wolfsentry
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_QT_TEST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-qt-test
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RSA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rsa
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OAEP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-oaep
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RSAPUB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rsapub
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RSAVFY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rsavfy
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RSAPSS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rsapss
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dh
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ANON),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-anon
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asn
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASN_PRINT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asn-print
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aes
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DTLS13),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dtls13
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DTLSCID),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dtlscid
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DTLS_FRAG_CH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dtls-frag-ch
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CODING),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-coding
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BASE64ENCODE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-base64encode
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_BASE16),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-base16
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MD4),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-md4
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DES3),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-des3
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DES3_TLS_SUITES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-des3-tls-suites
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ARC4),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-arc4
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MD5),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-md5
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SHA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sha
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SIPHASH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-siphash
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CMAC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-cmac
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESXTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesxts
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESXTS_STREAM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aesxts-stream
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_XTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-xts
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WEBSERVER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-webserver
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WEBCLIENT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-webclient
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RC2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rc2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CUDA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-cuda
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CERTSERVICE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-certservice
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PWDBASED),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pwdbased
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WOLFENTROPY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wolfentropy
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ENTROPY_MEMUSE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-entropy-memuse
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AESKEYWRAP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-aeskeywrap
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SELFTEST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-selftest
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_POLY1305),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-poly1305
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CHACHA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-chacha
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_XCHACHA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-xchacha
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HASHDRBG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hashdrbg
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FILESYSTEM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-filesystem
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_INLINE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-inline
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OCSP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ocsp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OCSPSTAPLING),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ocspstapling
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OCSPSTAPLING2),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ocspstapling2
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-crl
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRL_MONITOR),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-crl-monitor
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SNI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sni
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MAXFRAGMENT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-maxfragment
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALPN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-alpn
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TRUSTEDCA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-trustedca
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TRUNCATEDHMAC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-truncatedhmac
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RENEGOTIATION_INDICATION),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-renegotiation-indication
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SECURE_RENEGOTIATION),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-secure-renegotiation
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SECURE_RENEGOTIATION_INFO),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-secure-renegotiation-info
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FALLBACK_SCSV),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-fallback-scsv
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_KEYING_MATERIAL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-keying-material
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SUPPORTEDCURVES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-supportedcurves
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_FFDHE_ONLY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ffdhe-only
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SESSION_TICKET),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-session-ticket
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TICKET_NONCE_MALLOC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ticket-nonce-malloc
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_EXTENDED_MASTER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-extended-master
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TLSX),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tlsx
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_EARLYDATA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-earlydata
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PKCS7),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pkcs7
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WOLFSSH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wolfssh
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SSH),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-ssh
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WOLFTPM),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wolftpm
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_WOLFCLU),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-wolfclu
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SCEP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-scep
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SRP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-srp
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_INDEF),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-indef
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ALTCERTCHAINS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-altcertchains
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SMALLSTACKCACHE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-smallstackcache
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SMALLSTACK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-smallstack
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_VALGRIND),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-valgrind
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TESTCERT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-testcert
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_IOPOOL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-iopool
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_JNI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-jni
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASIO),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asio
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_APACHEHTTPD),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-apachehttpd
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ENC_THEN_MAC),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-enc-then-mac
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_STUNNEL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-stunnel
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CURL),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-curl
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_TCPDUMP),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-tcpdump
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SBLIM_SFCB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sblim-sfcb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LIBEST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-libest
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ENCKEYS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-enckeys
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PKCS12),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pkcs12
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SCRYPT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-scrypt
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_EXAMPLES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-examples
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRYPTTESTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-crypttests
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRYPTTESTS_LIBS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-crypttests-libs
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PKCS11),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pkcs11
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_PKCS8),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-pkcs8
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_STATICMEMORY),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-staticmemory
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MCAPI),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-mcapi
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CRYPTOCB),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-cryptocb
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASYNCCRYPT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asynccrypt
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASYNCCRYPT_SW),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asynccrypt-sw
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_ASYNCTHREADS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-asyncthreads
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_AUTOSAR),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-autosar
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SESSIONEXPORT),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sessionexport
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OLDNAMES),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-oldnames
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MEMTEST),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-memtest
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_HASHFLAGS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-hashflags
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DEFAULTDHPARAMS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-defaultdhparams
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_LINUXKM_LKCAPI_REGISTER),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-linuxkm-lkcapi-register
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_CONTEXT_EXTRA_USER_DATA),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-context-extra-user-data
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_IOTSAFE),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-iotsafe
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_IOTSAFE_HWRNG),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-iotsafe-hwrng
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_MAKECLEAN),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-makeclean
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_USERSETTINGS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-usersettings
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPTFLAGS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-optflags
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_SYS_CA_CERTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-sys-ca-certs
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_DUAL_ALG_CERTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-dual-alg-certs
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_RPK),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-rpk
endif

ifeq ($(BR2_PACKAGE_THINGINO_WOLFSSL_OPENSSL_COMPATIBLE_DEFAULTS),y)
THINGINO_WOLFSSL_CONF_OPTS += --disable-openssl-compatible-defaults
endif

# enable ARMv8 hardware acceleration
ifeq ($(BR2_aarch64),y)
THINGINO_WOLFSSL_CONF_OPTS += --enable-armasm
# the flag -mstrict-align is needed to prevent build errors caused by
# some inline assembly in parts of the AES structure using the "m"
# constraint
THINGINO_WOLFSSL_CONF_ENV += CPPFLAGS="$(TARGET_CPPFLAGS) -mstrict-align"
else
THINGINO_WOLFSSL_CONF_OPTS += --disable-armasm
endif

ifeq ($(BR2_ARM_INSTRUCTIONS_THUMB),y)
THINGINO_WOLFSSL_CONF_OPTS += --with-arm-target=thumb
endif

$(eval $(autotools-package))
