#!/bin/sh

. /etc/init.d/rc.common

DAEMON_ARGS="-d -c /etc/go2rtc.yaml"

start() {
	starting
	start_daemon
}

stop() {
	stopping
	stop_daemon
}

restart() {
	stop || true
	sleep 1
	reload
}

reload() {
	start
}

case "$1" in
	start | stop | restart | reload)
		$1
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
esac

exit 0
