WIFI_MT7601STA_VERSION = $(LINUX_VERSION_PROBED)
WIFI_MT7601STA_SITE_METHOD = local
WIFI_MT7601STA_SITE = $(LINUX_DIR)/drivers/net/wireless/mt7601u

WIFI_MT7601STA_MODULE_MAKE_OPTS = \
	KSRC=$(LINUX_DIR) \
	KVERSION=$(LINUX_VERSION_PROBED) \
	CONFIG_WLAN=y \
	CONFIG_WIRELESS=y \
	CONFIG_WIRELESS_EXT=y \
	CONFIG_WEXT_CORE=y \
	CONFIG_WEXT_PROC=y \
	CONFIG_WEXT_PRIV=y \
	CONFIG_CFG80211=y \
	CONFIG_MAC80211=y \
	CONFIG_MAC80211_RC_MINSTREL=y \
	CONFIG_MAC80211_RC_MINSTREL_HT=y \
	CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y \
	CONFIG_MAC80211_RC_DEFAULT="minstrel_ht" \
	CONFIG_MT7601_STA=m

#define WIFI_MT7601STA_LINUX_CONFIG_FIXUPS
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
#endef

#	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_SUPPORT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_USB)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_NET)
#	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211_DEFAULT_PS)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211_WEXT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_HAS_RC)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
#	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
#	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")

$(eval $(kernel-module))
$(eval $(generic-package))
