WIFI_B43_VERSION = $(LINUX_VERSION_PROBED)
WIFI_B43_SITE_METHOD = local
WIFI_B43_VERSION=1.0
WIFI_B43_SITE = $(LINUX_DIR)/drivers/net/wireless/b43

define WIFI_B43_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
	$(call KCONFIG_ENABLE_OPT,CONFIG_SSB_SDIOHOST_POSSIBLE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SSB_SDIOHOST)
	$(call KCONFIG_SET_OPT,CONFIG_B43=m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_B43_SSB)
	$(call KCONFIG_SET_OPT,CONFIG_B43_SDIO,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_B43_PIO)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SSB)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SSB_BLOCKIO)
endef

#WIFI_B43_MODULE_MAKE_OPTS = \
#	KSRC=$(LINUX_DIR) \
#	KVERSION=$(LINUX_VERSION_PROBED) \
#	CONFIG_WLAN=y \
#	CONFIG_WIRELESS=y \
#	CONFIG_WIRELESS_EXT=y \
#	CONFIG_WEXT_CORE=y \
#	CONFIG_WEXT_PROC=y \
#	CONFIG_WEXT_PRIV=y \
#        CONFIG_CRYPTO=y \
#	CONFIG_CFG80211=y \
#	CONFIG_MAC80211=y \
#	CONFIG_MAC80211_RC_MINSTREL=y \
#	CONFIG_MAC80211_RC_MINSTREL_HT=y \
#	CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y \
#	CONFIG_MAC80211_RC_DEFAULT="minstrel_ht" \
#	CONFIG_SSB_POSSIBLE=y \
#	CONFIG_MAC80211=y \
#	CONFIG_HAS_DMA=y \
#	CONFIG_SSB_SDIOHOST_POSSIBLE=y \
#	CONFIG_SSB_SDIOHOST=y \
#	CONFIG_B43=m \
#	CONFIG_B43_SDIO=y \
#	B43_SDIO=y

define WIFI_B43_INSTALL_TARGET_CMDS
	$(INSTALL) -m 755 -d $(TARGET_DIR)/usr/lib/firmware
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_B43_PKGDIR)/files/fw_bcm43436b0.bin
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_B43_PKGDIR)/files/fw_bcm43438a1.bin
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_B43_PKGDIR)/files/nv_bcm43436b0.txt
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_B43_PKGDIR)/files/nv_bcm43438a1.txt
endef

$(eval $(kernel-module))
$(eval $(generic-package))
