#!/bin/sh

DAEMON="/usr/sbin/prusa-connectd"
DAEMON_ARGS="daemon"
PIDFILE="/run/prusa-connectd.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo -c 15 "Starting Prusa Connect service"

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo -c 15 "Stopping Prusa Connect service"
	stop_daemon
}

status() {
	if pidof prusa-connectd >/dev/null; then
		echo "prusa-connectd is running"
		return 0
	fi
	echo "prusa-connectd is stopped"
	return 1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart | reload)
		stop || true
		sleep 1
		start
		;;
	status)
		status
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 1
		;;
esac

exit 0
