#!/bin/sh

DAEMON="majestic"
DAEMON_PATH="/usr/bin"
PIDFILE="/var/run/$DAEMON.pid"

DAEMON_ARGS="-s"

[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

load_majestic() {
	printf 'Starting %s: ' "$DAEMON"
	[ -f $DAEMON_PATH/$DAEMON ] || echo -en "DISABLED, "

	start-stop-daemon -b -m -S -p "$PIDFILE" -x sh -- -c "/lib/ld-musl-mipsel.so.1 --preload /usr/lib/libimp_control.so $DAEMON_PATH/$DAEMON $DAEMON_ARGS"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

start() {
	export SENSOR=$(fw_printenv -n sensor)
	load_majestic
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	[ -f $DAEMON_PATH/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop || true
	sleep 1
	reload
}

reload() {
	load_majestic
}

case "$1" in
	start | stop | restart | reload)
		"$1"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
