#!/bin/sh

RESOLV_WORKING_FILE="/tmp/resolv.conf"

case "$1" in
	bound | renew)
		echo "Use DHCP provided DNS servers"

		if [ -L $RESOLV_WORKING_FILE ]; then
			echo "Create linked $RESOLV_WORKING_FILE"
			[ -e $RESOLV_WORKING_FILE ] || touch $RESOLV_WORKING_FILE
		fi

		:> "$RESOLV_WORKING_FILE"

		if [ -n "$domain" ]; then
			echo "Populate $RESOLV_WORKING_FILE with domain $domain"
			echo "search $domain" >> "$RESOLV_WORKING_FILE"
		fi

		for i in $dns; do
			echo "Populate $RESOLV_WORKING_FILE with nameserver $i"
			echo "nameserver $i" >> "$RESOLV_WORKING_FILE"
		done
		;;
esac

exit 0
