#!/bin/sh
# shellcheck disable=SC2154

RESOLV_WORKING_FILE="/tmp/resolv.conf"

case "$1" in
	bound | renew)
		echo "Use DHCP provided DNS servers"

		if [ -L $RESOLV_WORKING_FILE ]; then
			echo "Create linked $RESOLV_WORKING_FILE"
			[ -e $RESOLV_WORKING_FILE ] || touch $RESOLV_WORKING_FILE
		fi

		(
			flock 9
			grep "# added by odhcp6c" "$RESOLV_WORKING_FILE" \
				>"$RESOLV_WORKING_FILE.new" 2>/dev/null
			grep -v "# added by odhcp6c\|# added by udhcpc" "$RESOLV_WORKING_FILE" \
				>"$RESOLV_WORKING_FILE.rest" 2>/dev/null

			if [ -n "$domain" ]; then
				echo "Populate $RESOLV_WORKING_FILE with domain $domain"
				echo "search $domain # added by udhcpc" >>"$RESOLV_WORKING_FILE.new"
			fi

			for i in $dns; do
				echo "Populate $RESOLV_WORKING_FILE with nameserver $i"
				echo "nameserver $i # added by udhcpc" >>"$RESOLV_WORKING_FILE.new"
			done

			cat "$RESOLV_WORKING_FILE.rest" >>"$RESOLV_WORKING_FILE.new"
			rm -f "$RESOLV_WORKING_FILE.rest"
			mv "$RESOLV_WORKING_FILE.new" "$RESOLV_WORKING_FILE"
			chmod 0644 "$RESOLV_WORKING_FILE"
		) 9>/tmp/resolv.conf.lock
		;;
esac

exit 0
