WIFI_ATBM6012BX_SITE_METHOD = git
WIFI_ATBM6012BX_SITE = https://github.com/gtxaspec/atbm-wifi
WIFI_ATBM6012BX_SITE_BRANCH = master
WIFI_ATBM6012BX_VERSION = 13953b6e9090e620640edf4c6ea8ffc2e46da6b4

WIFI_ATBM6012BX_LICENSE = GPL-2.0

ATBM6012BX_MODULE_NAME = atbm6012bx

WIFI_ATBM6012BX_MODULE_MAKE_OPTS = \
	KDIR=$(LINUX_DIR)

define WIFI_ATBM6012BX_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
	$(if $(BR2_PACKAGE_THINGINO_BLUETOOTH), \
	    $(call KCONFIG_SET_OPT,CONFIG_BT,y))
endef

LINUX_CONFIG_LOCALVERSION = $(shell awk -F "=" '/^CONFIG_LOCALVERSION=/ {print $$2}' $(BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE))

define WIFI_ATBM6012BX_COPY_CONFIG
	$(INSTALL) -D -m 0644 $(@D)/configs/atbm6012bx.config \
		$(@D)/.config
endef

define WIFI_ATBM6012BX_COPY_CONFIG_BLE
	echo "CONFIG_ATBM_BLE=y" >> $(@D)/.config
	echo "CONFIG_ATBM_BLE_WIFI_PLATFORM=y" >> $(@D)/.config
endef

define WIFI_ATBM6012BX_INSTALL_CONFIGS
	$(INSTALL) -m 0755 -d $(TARGET_DIR)/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)
	touch $(TARGET_DIR)/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)/modules.builtin.modinfo

	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/share/wifi
	$(INSTALL) -m 0644 -t $(TARGET_DIR)/usr/share/wifi \
		$(WIFI_ATBM_WIFI_PKGDIR)/files/*.txt
endef

define WIFI_ATBM6012BX_INSTALL_CONFIGS_WIFI
	$(INSTALL) -D -m 0644 $(@D)/firmware/firmware_lite_usb.bin \
		$(TARGET_DIR)/lib/firmware/$(call qstrip,$(ATBM6012BX_MODULE_NAME))_fw.bin
endef

define WIFI_ATBM6012BX_INSTALL_CONFIGS_BLE
	$(INSTALL) -D -m 0644 $(@D)/firmware/firmware_usb_wifi_bt_comb.bin \
		$(TARGET_DIR)/lib/firmware/$(call qstrip,$(ATBM6012BX_MODULE_NAME))_fw.bin
endef

WIFI_ATBM6012BX_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6012BX_INSTALL_CONFIGS

WIFI_ATBM6012BX_PRE_CONFIGURE_HOOKS += WIFI_ATBM6012BX_COPY_CONFIG

ifeq ($(BR2_PACKAGE_THINGINO_BLUETOOTH),y)
	WIFI_ATBM6012BX_MODULE_MAKE_OPTS += \
		EXTRA_CFLAGS="-DCONFIG_WIFI_BT_COMB -DCONFIG_ATBM_BLE_ADV_COEXIST"

	WIFI_ATBM6012BX_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6012BX_INSTALL_CONFIGS_BLE
	WIFI_ATBM6012BX_PRE_CONFIGURE_HOOKS += WIFI_ATBM6012BX_COPY_CONFIG_BLE
else
	WIFI_ATBM6012BX_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6012BX_INSTALL_CONFIGS_WIFI
endif

$(eval $(kernel-module))
$(eval $(generic-package))
