#!/bin/sh

start() {
	echo_title "Starting mosquitto"
	start-stop-daemon -S -q -m -b -p /var/run/mosquitto.pid \
		--exec /usr/sbin/mosquitto \
		-- -c /etc/mosquitto/mosquitto.conf
}

stop() {
	echo_title "Stopping mosquitto"
	start-stop-daemon -K -q -p /var/run/mosquitto.pid
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
