WIFI_RTL8188EU_VERSION = $(LINUX_VERSION_PROBED)
WIFI_RTL8188EU_SITE_METHOD = local
WIFI_RTL8188EU_SITE = $(LINUX_DIR)/drivers/net/wireless/rtl818x/rtl8188eu

RTL8188EU_MODULE_NAME = 8188eu
RTL8188EU_MODULE_OPTS =

WIFI_RTL8188EU_MODULE_MAKE_OPTS = \
	KSRC=$(LINUX_DIR) \
	KVERSION=$(LINUX_VERSION_PROBED) \
	CONFIG_WLAN=y \
	CONFIG_WIRELESS=y \
	CONFIG_WIRELESS_EXT=y \
	CONFIG_WEXT_CORE=y \
	CONFIG_WEXT_PROC=y \
	CONFIG_WEXT_PRIV=y \
	CONFIG_CRYPTO=y \
	CONFIG_CFG80211=y \
	CONFIG_MAC80211=y \
	CONFIG_MAC80211_RC_MINSTREL=y \
	CONFIG_MAC80211_RC_MINSTREL_HT=y \
	CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y \
	CONFIG_MAC80211_RC_DEFAULT="minstrel_ht" \
	CONFIG_RTL8188EU=m

# wpa_supplicant handles roaming; disable the driver's own L2 roaming
ifeq ($(BR2_PACKAGE_THINGINO_WPA_SUPPLICANT_ROAMING),y)
WIFI_RTL8188EU_MODULE_MAKE_OPTS += USER_EXTRA_CFLAGS=-DBR2_PACKAGE_THINGINO_WPA_SUPPLICANT_ROAMING
endif

$(eval $(kernel-module))
$(eval $(generic-package))
