WIFI_RTL8188EU_VERSION = $(LINUX_VERSION_PROBED)
WIFI_RTL8188EU_SITE_METHOD = local
WIFI_RTL8188EU_SITE = $(LINUX_DIR)/drivers/net/wireless/rtl818x/rtl8188eu

WIFI_RTL8188EU_MODULE_MAKE_OPTS = \
	KSRC=$(LINUX_DIR) \
	KVERSION=$(LINUX_VERSION_PROBED) \
	CONFIG_WLAN=y \
	CONFIG_WIRELESS=y \
	CONFIG_WIRELESS_EXT=y \
	CONFIG_WEXT_CORE=y \
	CONFIG_WEXT_PROC=y \
	CONFIG_WEXT_PRIV=y \
	CONFIG_CRYPTO=y \
	CONFIG_CFG80211=y \
	CONFIG_MAC80211=y \
	CONFIG_MAC80211_RC_MINSTREL=y \
	CONFIG_MAC80211_RC_MINSTREL_HT=y \
	CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y \
	CONFIG_MAC80211_RC_DEFAULT="minstrel_ht" \
	CONFIG_RTL8188EU=m

$(eval $(kernel-module))
$(eval $(generic-package))
