#!/usr/bin/env bash
# Render config/config.yml for one or more Thingino cameras and restart Frigate.
#
# Each camera gets both Thingino RTSP streams: ch1 (sub) for detect and ch0
# (main) for record, plus an ONVIF block so Frigate can drive PTZ presets and
# autotracking.
#
# Usage:
#   ./add-camera.sh [options] <camera-ip> [<camera-ip> ...]
#
# Examples:
#   ./add-camera.sh 192.168.88.31
#   ./add-camera.sh --name porch --detect-width 1280 --detect-height 720 192.168.88.31
#   ./add-camera.sh --autotracking --return-preset home 192.168.88.34
#   ./add-camera.sh 192.168.88.31 192.168.88.34
#
# Options:
#   --name NAME        Camera name (single IP only; default: cam-<ip>)
#   --rtsp-port PORT   RTSP port (default: 554)
#   --onvif-port PORT  ONVIF HTTP port (default: 80)
#   --detect-width N   Detect width (default: 640)
#   --detect-height N  Detect height (default: 360)
#   --detect-fps N     Detect fps (default: 5)
#   --autotracking     Enable ONVIF autotracking (default: disabled)
#   --return-preset P  Preset to return to after tracking (default: home)
#   --engine ENGINE    Container engine: podman or docker (default: autodetect)
#   --restart          Restart Frigate after writing the config (default)
#   --no-restart       Do not restart Frigate
#   -h, --help         Show this help
#
# Credentials are not written into the config: it references
# {FRIGATE_RTSP_USER} and {FRIGATE_RTSP_PASSWORD}, which come from .env.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"
CONFIG_FILE="$CONFIG_DIR/config.yml"

NAME=""
RTSP_PORT="554"
ONVIF_PORT="80"
DETECT_WIDTH="640"
DETECT_HEIGHT="360"
DETECT_FPS="5"
AUTOTRACKING="false"
RETURN_PRESET="home"
ENGINE=""
RESTART=1

usage() {
	sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
	case "$1" in
	--name) NAME="$2"; shift 2 ;;
	--rtsp-port) RTSP_PORT="$2"; shift 2 ;;
	--onvif-port) ONVIF_PORT="$2"; shift 2 ;;
	--detect-width) DETECT_WIDTH="$2"; shift 2 ;;
	--detect-height) DETECT_HEIGHT="$2"; shift 2 ;;
	--detect-fps) DETECT_FPS="$2"; shift 2 ;;
	--autotracking) AUTOTRACKING="true"; shift ;;
	--return-preset) RETURN_PRESET="$2"; shift 2 ;;
	--engine) ENGINE="$2"; shift 2 ;;
	--restart) RESTART=1; shift ;;
	--no-restart) RESTART=0; shift ;;
	-h | --help) usage; exit 0 ;;
	-*) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
	*) break ;;
	esac
done

[ $# -ge 1 ] || { usage >&2; exit 1; }
if [ -n "$NAME" ] && [ $# -gt 1 ]; then
	echo "ERROR: --name only applies to a single camera" >&2
	exit 1
fi

for arg in "$@"; do
	case "$arg" in
	*[!0-9.]* | .* | *.) echo "ERROR: not an IPv4 address: $arg" >&2; exit 1 ;;
	esac
done

camera_block() {
	local name="$1" ip="$2"

	cat <<EOF
  $name:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@$ip:$RTSP_PORT/ch1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@$ip:$RTSP_PORT/ch0
          roles:
            - record
    detect:
      width: $DETECT_WIDTH
      height: $DETECT_HEIGHT
      fps: $DETECT_FPS
    onvif:
      host: $ip
      port: $ONVIF_PORT
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
      autotracking:
        enabled: $AUTOTRACKING
        calibrate_on_startup: false
        zooming: disabled
        track:
          - person
        required_zones:
          - all
        return_preset: $RETURN_PRESET
        timeout: 10
    zones:
      all:
        friendly_name: All
        coordinates: 0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
EOF
}

mkdir -p "$CONFIG_DIR" "$SCRIPT_DIR/media"

{
	cat <<'EOF'
# Generated by add-camera.sh. Edits made here or in the Frigate UI are
# overwritten on the next run; change the script instead.
#
# Streams: ch1 (sub) is decoded for detect, ch0 (main) is recorded untouched.
# The ONVIF block lets Frigate list and call the camera's PTZ presets and,
# when enabled, autotrack objects.

version: 0.18-0

mqtt:
  enabled: false

detectors:
  cpu:
    type: cpu

record:
  enabled: true
  motion:
    days: 1
  alerts:
    retain:
      days: 1
      mode: motion
  detections:
    retain:
      days: 1
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 1

cameras:
EOF

	for ip in "$@"; do
		if [ -n "$NAME" ]; then
			camera_name="$NAME"
		else
			camera_name="cam-${ip//./-}"
		fi
		camera_block "$camera_name" "$ip"
		echo "  added $camera_name ($ip)" >&2
	done
} >"$CONFIG_FILE"

echo "Wrote $CONFIG_FILE"

if [ "$RESTART" -eq 0 ]; then
	exit 0
fi

if [ -z "$ENGINE" ]; then
	if command -v podman >/dev/null 2>&1; then
		ENGINE="podman"
	elif command -v docker >/dev/null 2>&1; then
		ENGINE="docker"
	else
		echo "No podman or docker found; start Frigate manually" >&2
		exit 0
	fi
fi

if "$ENGINE" ps --format '{{.Names}}' 2>/dev/null | grep -qx frigate; then
	echo "Restarting frigate with $ENGINE"
	"$ENGINE" restart frigate >/dev/null
else
	echo "frigate is not running; start it with 'podman compose up -d'"
fi
