WIFI_RTL8188FU_SITE_METHOD = git
WIFI_RTL8188FU_SITE = https://github.com/gtxaspec/rtl8188ftv-wifi
WIFI_RTL8188FU_SITE_BRANCH = master
WIFI_RTL8188FU_VERSION = 6e3c1c2d244f5056d2a7ade3dbcf9daa3876fc06
# $(shell git ls-remote $(WIFI_RTL8188FU_SITE) $(WIFI_RTL8188FU_SITE_BRANCH) | head -1 | cut -f1)

WIFI_RTL8188FU_LICENSE = GPL-2.0
WIFI_RTL8188FU_LICENSE_FILES = COPYING

WIFI_RTL8188FU_MODULE_MAKE_OPTS = \
	CONFIG_RTL8188FU=m

define WIFI_RTL8188FU_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

define WIFI_RTL8188FU_INSTALL_CONFIGS
	$(INSTALL) -m 755 -d $(TARGET_DIR)/lib/firmware
	$(INSTALL) -m 644 -t $(TARGET_DIR)/lib/firmware $(WIFI_RTL8188FU_PKGDIR)/files/PHY_REG_PG.txt
endef

WIFI_RTL8188FU_POST_INSTALL_TARGET_HOOKS += WIFI_RTL8188FU_INSTALL_CONFIGS

$(eval $(kernel-module))
$(eval $(generic-package))
