#!/bin/sh

STREAMER_APP="streamer"
DAEMON="/usr/sbin/record"
PIDFILE="/run/record.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON"
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo -c 15 "Starting Record service"

	if pidof -o $$ "$(basename "$DAEMON")" >/dev/null; then
		echo "$DAEMON is already running" >&2
		exit 1
	fi

	if ! pidof "$STREAMER_APP" >/dev/null 2>&1; then
		echo "Streamer is not running" >&2
		exit 1
	fi

	if [ "true" != "$record_enabled" ]; then
		echo "Recording disabled" >&2
		exit 1
	fi

	start_daemon
}

stop() {
	echo -c 15 "Stopping Recording service"

	stop_daemon

	find /tmp/ -name "record.*" -maxdepth 0 -delete
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;

	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0
