#!/bin/sh

on_exit() {
	mountpoint -q /proc && umount /proc
	exec /sbin/init $*
}

trap on_exit 0

mount -t proc proc /proc || exit
grep -q overlay /proc/filesystems || exit

if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
	if grep -q ubifs /proc/cmdline; then
		mount -t ubifs ubi0:rootfs_data /overlay
	else
		mtdblkdev=$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/')
		mtdchrdev=$(grep 'rootfs_data' /proc/mtd | cut -d: -f1)

		if [ "$(xxd -l 2 -p /dev/${mtdblkdev})" != "8519" ]; then
			echo "Invalid JFFS2 header, or /dev/${mtdblkdev} is not formatted as JFFS2."
			flash_eraseall -j /dev/${mtdchrdev}
			echo "Reformatting done. Attempting to remount..."
		fi

		if mount -t jffs2 /dev/${mtdblkdev} /overlay; then
			echo "JFFS2 filesystem mounted successfully."
		else
			echo "Failed to mount JFFS2, trying fallback to tmpfs..."
			mount -t tmpfs tmpfs /overlay || exit
		fi

		if ! cat /proc/mounts | grep -q ${mtdblkdev}; then
			echo "ERROR: Unable to mount overlay, using tmpfs..."
			exit 1
		fi
	fi

	if grep -q overlayfs /proc/filesystems; then
		mount -t overlayfs overlayfs -o lowerdir=/,upperdir=/overlay,ro /mnt || {
			umount /overlay
			exit
		}
	else
		overlay_rootdir=/overlay/root
		overlay_workdir=/overlay/work
		mkdir -p ${overlay_rootdir} ${overlay_workdir}
		mount -t overlay overlay -o lowerdir=/,upperdir=${overlay_rootdir},workdir=${overlay_workdir} /mnt || {
			umount /overlay
			exit
		}
	fi

	pivot_root /mnt /mnt/rom
	mount -o noatime,move /rom/proc /proc
	mount -o noatime,move /rom/dev /dev
	mount -o noatime,move /rom/overlay /overlay
fi
