#!/bin/sh

DAEMON="pir_daemon"
PIDFILE="/var/run/pir_daemon.pid"
UART_DEV="/dev/ttyS0"
LOGFILE="/var/log/pir_daemon.log"

start() {
	[ -c "$UART_DEV" ] || {
		echo "skipped ($UART_DEV not present)"
		return 0
	}
	printf "Starting %s: " "$DAEMON"
	start-stop-daemon -S -q -m -b -p "$PIDFILE" -x /usr/bin/$DAEMON -- "$UART_DEV" >>"$LOGFILE" 2>&1
	rc=$?
	[ $rc = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping %s: " "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -f "$PIDFILE"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
