WIFI_BCMDHD_AP6214A_VERSION = 1.0
WIFI_BCMDHD_AP6214A_SITE = $(WIFI_BCMDHD_AP6214A_PKGDIR)/files
#WIFI_BCMDHD_AP6214A_SITE = $(LINUX_DIR)/drivers/net/wireless/bcmdhd_6214
WIFI_BCMDHD_AP6214A_SITE_METHOD = local

define WIFI_BCMDHD_AP6214A_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
	$(call KCONFIG_SET_OPT,CONFIG_BCMDHD,m)
	$(call KCONFIG_SET_OPT,CONFIG_BCMDHD_SDIO,y)
	$(call KCONFIG_SET_OPT,CONFIG_BCMDHD_SDIO_IRQ,y)
        $(call KCONFIG_SET_OPT,CONFIG_BCMDHD_FW_PATH,"/usr/lib/firmware/fw_bcm43438a1.bin")
        $(call KCONFIG_SET_OPT,CONFIG_BCMDHD_NVRAM_PATH,"/usr/lib/firmware/nv_bcm43438a1.txt")
endef

define WIFI_BCMDHD_AP6214A_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0644 $(WIFI_BCMDHD_AP6214A_PKGDIR)/files/fw_bcm43438a1.bin \
		$(TARGET_DIR)/usr/lib/firmware/fw_bcm43438a1.bin

	$(INSTALL) -D -m 0644 $(WIFI_BCMDHD_AP6214A_PKGDIR)/files/nv_bcm43438a1.txt \
		$(TARGET_DIR)/usr/lib/firmware/nv_bcm43438a1.txt
endef

$(eval $(generic-package))
