#!/bin/sh

CNET=172.16.0.1

decrement_mac() {
	local mac last_byte_dec

	mac=$ethaddr
	if [ -z "$mac" ]; then
		echo "Error: MAC address not found" >&2
		exit 1
	fi

	last_byte_dec=$((0x${mac##*:} - 1))
	if [ $last_byte_dec -lt 0 ]; then
		echo "Error: MAC address cannot be decremented below 00" >&2
		exit 1
	fi

	ethaddr=$(printf "%s:%02x" "${mac%:*}" "$last_byte_dec")
}

start() {
	decrement_mac
	echo -c 15 "Starting CDC Ethernet gadget"
	modprobe g_ncm iManufacturer=thingino host_addr=$(fw_printenv -n ethaddr) dev_addr=$ethaddr iProduct="NCM CDC Ethernet Gadget"
	usb-role -m device
	touch /run/udhcpd.leases
	start-stop-daemon -S -x /sbin/dnsd -- -i $CNET -c /etc/dnsd.conf -d
	start-stop-daemon -S -x /sbin/udhcpd -- -S -I $CNET /etc/udhcpd.conf 2>&1
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

exit 0
