#!/bin/sh

. /etc/init.d/rc.common

start() {
	decrement_mac
	starting
	modprobe g_ncm iManufacturer=thingino host_addr=$(fw_printenv -n ethaddr) dev_addr=$ethaddr iProduct="NCM CDC Ethernet Gadget"
	usb-role -m device
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
