#!/bin/sh

decrement_mac() {
	local mac last_byte_dec

	mac=$ethaddr
	if [ -z "$mac" ]; then
		echo "Error: MAC address not found" >&2
		exit 1
	fi

	last_byte_dec=$((0x${mac##*:} - 1))
	if [ $last_byte_dec -lt 0 ]; then
		echo "Error: MAC address cannot be decremented below 00" >&2
		exit 1
	fi

	ethaddr=$(printf "%s:%02x" "${mac%:*}" "$last_byte_dec")
}

start() {
	usbmac=$(fw_printenv -n usbmac)
	if [ -z "$usbmac" ]; then
		decrement_mac
		daddr=$ethaddr
	else
		daddr=$usbmac
	fi

	echo -c 15 "Starting CDC Ethernet client gadget"
	modprobe g_ncm iManufacturer=thingino host_addr=$(fw_printenv -n ethaddr) dev_addr=$daddr iProduct="NCM CDC Ethernet Gadget"
	usb-role -m device
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

exit 0
