#!/bin/sh

. /etc/init.d/rc.common

start() {
	gpionum="$(get gpio_usbnet)"
	modulename="rndis_host"

	starting

	if [ -n "$gpionum" ]; then
		num=${gpionum%[oO]}
		state=${gpionum#$num}

		case "$state" in
			O)
				gpio_cmd="high"
				;;
			o)
				gpio_cmd="low"
				;;
		esac

		echo -n " Set GPIO $num $gpio_cmd ... "
		gpio $gpio_cmd $num 2>&1 | log && ok || { fail && die }
	fi

	echo -n " Load usbserial module ... "
	modprobe usbserial && ok || { fail && die }

	if ! grep -q ^$modulename /proc/modules; then
		echo -n " Load $modulename module ... "
		modprobe $modulename && ok || { fail && die }
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		die "Usage: $0 {start}"
		;;
esac

exit 0
