#!/bin/sh

. /usr/share/common

modulename="rndis_host"

start() {
	echo_title "Starting USB NET"

	if [ -n "$gpio_usbnet" ]; then
		num=${gpio_usbnet%[oO]}
		state=${gpio_usbnet#$num}

		case "$state" in
			O) gpio_cmd="high" ;;
			o) gpio_cmd="low" ;;
		esac

		echo_info "Set GPIO $num $gpio_cmd"
		gpio $gpio_cmd $num
	fi

	echo_info "Load usbserial module"
	modprobe usbserial

	if ! grep -q ^$modulename /proc/modules; then
		echo_info "Load $modulename module"
		modprobe $modulename
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
