#!/bin/sh

ENABLE=false
HOST_IP=172.16.0

init_portal() {
	if [ "$ENABLE" = "true" ]; then
		ip a add dev wlan0 $HOST_IP.1/24
		ip link set wlan0 up
		ip route add $HOST_IP.0/24 dev wlan0
		udhcpd -S -I $HOST_IP.1 /etc/udhcpd.conf
		cdnsd -i $HOST_IP.1 -c $HOST_IP.1 -d

		mac_address=$(ip link show wlan0 | awk '/ether/ {print $2}')
		last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')
		sed -i "/ssid=\"THINGINO-\"$/ s/\"$/$last_two\"/" /etc/wpa_ap.conf

		wpa_supplicant -i wlan0 -B -c /etc/wpa_ap.conf
	fi
}

case "$1" in
	start)
		init_portal
		;;
	stop)
		killall udhcpd
		killall cdnsd
		killall wpa_supplicant
		ip address delete dev wlan0 $HOST_IP.1/24
		ip link set wlan0 down
		;;
	reload|restart)
		true
		;;
	*)
		echo "Usage: $0 {start|stop|reload|restart}"
		exit 1
		;;
esac

exit 0
