#!/bin/sh

. /etc/init.d/rc.common

CNET=172.16.0

timeout() {
	sleep 300 && $0 stop
}

init_portal() {
	# quit if no wireless, or if ethernet is present
	iface_exists "eth0" && quit
	iface_exists "wlan0" || quit

	# quit if credentials are set
	ssid="$(get wlanssid)"
	pass="$(get wlanpass)"

	starting
	[ -n "$ssid" ] && [ -n "$pass" ] && quit "Disabled"

	ip a add dev wlan0 ${CNET}.1/24
	ip link set wlan0 up
	ip route add ${CNET}.0/24 dev wlan0 > /dev/null 2>&1

	start-stop-daemon -S -x /sbin/udhcpd -- -S -I ${CNET}.1 /etc/udhcpd.conf 2>&1
	start-stop-daemon -S -x /sbin/dnsd -- -i ${CNET}.1 -c /etc/dnsd.conf -d | log

	mac_address=$(ip link show wlan0 | awk '/ether/ {print $2}')
	last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')
	sed -i "/ssid=\"THINGINO-\"$/ s/\"$/$last_two\"/" /etc/wpa_ap.conf

	start-stop-daemon -S -x /sbin/wpa_supplicant -- -i wlan0 -B -c /etc/wpa_ap.conf 2>&1 | log
	check_result

	timeout &
}

case "$1" in
	start)
		init_portal
		;;
	stop)
		start-stop-daemon -K -q -x /sbin/udhcpd
		start-stop-daemon -K -q -x /sbin/dnsd
		start-stop-daemon -K -q -x /sbin/wpa_supplicant
		ip address delete dev wlan0 ${CNET}.1/24
		ip link set wlan0 down
		;;
	reload | restart)
		true
		;;
	*)
		die "Usage: $0 {start|stop|reload|restart}"
		;;
esac

exit 0
