#!/bin/sh

. /etc/init.d/rc.common

ENABLE=true
HOST_IP=172.16.0

ssid="$(fw_printenv -n wlanssid)"
pass="$(fw_printenv -n wlanpass)"

timeout() {
	sleep 300 && /etc/init.d/S41portal stop
}

init_portal() {
	echo -n "Starting WiFi Portal: "
	if [ "$ENABLE" = "true" ]; then
		wlan_check || { echo "Disabled"; exit 1; }
		if [ -z "$ssid" ] || [ -z "$pass" ]; then
			ip a add dev wlan0 $HOST_IP.1/24
			ip link set wlan0 up
			ip route add $HOST_IP.0/24 dev wlan0 > /dev/null 2>&1
			start-stop-daemon -S -x /sbin/udhcpd -- -S -I $HOST_IP.1 /etc/udhcpd.conf 2>&1
			start-stop-daemon -S -x /sbin/dnsd -- -i $HOST_IP.1 -c /etc/dnsd.conf -d | logger -p daemon.info -t $0

			mac_address=$(ip link show wlan0 | awk '/ether/ {print $2}')
			last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')
			sed -i "/ssid=\"THINGINO-\"$/ s/\"$/$last_two\"/" /etc/wpa_ap.conf

			start-stop-daemon -S -x /sbin/wpa_supplicant -- -i wlan0 -B -c /etc/wpa_ap.conf 2>&1 | logger -p daemon.info -t $0

			[ $? = 0 ] && echo "OK" || echo "FAIL"

			timeout &
		else
			echo "Disabled"
		fi
	fi
}

case "$1" in
	start)
		init_portal
		;;
	stop)
		start-stop-daemon -K -q -x /sbin/udhcpd
		start-stop-daemon -K -q -x /sbin/dnsd
		start-stop-daemon -K -q -x /sbin/wpa_supplicant
		ip address delete dev wlan0 $HOST_IP.1/24
		ip link set wlan0 down
		;;
	reload | restart)
		true
		;;
	*)
		echo "Usage: $0 {start|stop|reload|restart}"
		exit 1
		;;
esac

exit 0
