#!/bin/sh

RECORD_WEBUI_CONF=/etc/webui/record.conf
. $RECORD_WEBUI_CONF

terminate() {
	# Reset webui config record_enabled to false and print error message
	sed -i 's/record_enabled=\"true\"/record_enabled=\"false\"/g' /etc/webui/record.conf
	logger "$1"
	/etc/init.d/S96record stop
}

getUsedSpace() {
	if [ $record_path = "/mnt/nfs*" ]; then
		usedSpace=$(df /mnt/nfs/ | awk 'NR==3{print $4}' | cut -d'%' -f1)
	else
		usedSpace=$(df /mnt/mmcblk0p1/ | awk 'END{print $5}' | cut -d'%' -f1)
}

while :
do
	getUsedSpace
	[ "$record_debug" = "true" ] && logger "Used disk space is $usedSpace%"

	if [ "$usedSpace" -ge "$record_diskusage" ]; then
		# Delete oldest file if loop recording is enabled, otherwise exit with error
		if [ "$record_loop" = "true" ]; then
			[ "$record_debug" = "true" ] && logger "Loop recording enabled. Deleting oldest files in save location"
			while [ "$usedSpace" -ge "$record_diskusage" ]
			do
				oldestFile=$(ls -1tr --group-directories-first $record_path | head -1)
				[ "$record_debug" = "true" ] && logger "deleting $oldestFile"
				rm "$oldestFile"
				getUsedSpace
				[ "$record_debug" = "true" ] && logger "Used disk space is $usedSpace%"

				if [ -z $(ls -A $record_path 2>/dev/null) ]; then
					[ "$record_debug" = "true" ] && logger "Deleted all files in $record_path yet no more space!"
					terminate "Deleted all files in $record_path yet no more space!"
				fi
			done
		else
			terminate "Loop recording is disabled and not enough disk space. Exiting."
		fi
	fi

	# Run this check every 60 seconds
	sleep 60

	# Check if openRTSP process is still running
	if [ -z $(pidof openRTSP) ]; then
		terminate "openRTSP is not running. Shutting down recorder"
	fi
done
