#!/bin/sh

die() { echo -e "\e[38;5;160m$@\e[0m" >&2; exit 1; }
log() { echo "$1" >&2; }

create_directory_for() {
	dir="$(dirname "$1")"
	[ -d "$dir" ] || mkdir -p "$dir"
	[ -d "$dir" ] || die "Cannot create directory $dir"
	[ -w "$dir" ] || die "Cannot write to $dir"
}

hesitate() {
	echo "$1" >&2
	sleep 5
	exit 0
}

cleanup() {                                                                                                         
    if [ -n "$archive_pid" ] && kill -0 "$archive_pid" 2>/dev/null; then
        echo "Parent exiting, killing subprocess $archive_pid..."                  
        kill -TERM "$archive_pid"                                          
    fi                                                                             
}

fix_duration() {
  if [ -z "$align_minutes" ]; then
        echo "$1"
    elif [ "$1" -eq 60 ]; then
        n_ms=$(uptime | cut -d'.' -f2)  # e.g., 67 (from 12345.67)
        s=$(date +%S)                   # e.g., 05
        if [ "$n_ms" -lt "$base_ms" ]; then
            s=$((s - 1))
            n_ms=$((n_ms + 100)) 
        fi
        echo "$(( $1 - s )).$(( n_ms - base_ms ))"
    elif [ $(( $1 % 60 )) -eq 0 ]; then
        m_inc=$(( $1 / 60 ))
        mpart=$(( m_inc - ( $(date +%M) % m_inc ) ))
        echo $(( mpart * 60 ))
    else
        echo "$1"
    fi
    #to do - handle cases different than 60 second durations or videos longer than an hour
}

get_free_space() {
	available_space=$(df -k "$record_mount" | sed 1d | tr -d '\n' | awk 'END{print $4}') # in KiB
	log "Space available: $available_space KiB"
}

get_occupied_space() {
        occupied_space=$(du -s "$record_storage" | awk '{print $1}') # in KiB
	log "Space occupied: $occupied_space KiB"
}

# "parameter" "default"
read_config() {
	sed -nE "s/^.*$1\s*[:=]\s*\"?([^\"]+)\"?;.*$/\1/p" /etc/prudynt.cfg | head -1
	[ -z "$_" ] || echo "$2"
}

# "default"
read_fps() {
	logcat | grep "fps" | head -1 | awk -F '[=,]' '{print $2}'
	[ -z "$_" ] || echo "$1"
}

# "parameter" "default"
read_size() {
	logcat | grep "VBMCreatePool()-${stream_number}: w=" | head -1 | awk -F '[= ]' "{print \$$1}"
	[ -z "$_" ] || echo "$2"
}

# "path"
remove_oldest_file_in() {
	[ -z "$del_count" ] && del_count=10
	log "started removing old files started"
	oldest_files=$(find "$1" -type f -exec ls -ltr {} + | head -n"$del_count" | awk '{print $9}')
	if [ -z "$oldest_files" ]; then
        	echo "No files found to delete in $1" >&2
        	return 1
    	fi
    	echo "$oldest_files" | while IFS= read -r oldest_file; do
        if [ -n "$oldest_file" ]; then
            oldest_file_dir=$(dirname "$oldest_file")
            rm -v "$oldest_file"
            if [ -z "$(ls -A "$oldest_file_dir" 2>/dev/null)" ]; then
                rm -rv "$oldest_file_dir"
		#support going up a further directory (record_dir_count = /% |<- count slashes from /%/% 
		if [ "$record_dir_count" -gt 1 ]; then
                    parent_dir=$(dirname "$oldest_file_dir")
                    if [ -n "$parent_dir" ] && [ -z "$(ls -A "$parent_dir" 2>/dev/null)" ]; then
                        rm -rv "$parent_dir"
                    fi
                fi   
            fi
        fi
	done
	log "remove_oldest_file_in finished "
}

has_files() {
	[ "$(find "$1" -type f | wc -l)" -gt 0 ]
}

uptime() {
    echo $(cat /proc/uptime | cut -d' ' -f1)
}

find_ms() {
    u1=$(uptime)
    s1=$(date +%S)
    s2="$s1"
    while [ "$s2" = "$s1" ]; do
        sleep 0.05
        s2=$(date +%S)
        u2=$(uptime)
    done
    offset=$(echo "$u2" | cut -d'.' -f2)
    log "offset is  $offset"
    echo "$offset" 
}

fmanager() {         
    check_so=0
    while :; do           
        get_free_space                                       
        if [ "$available_space" -le "$required_space" ]; then
            log "Space required: $required_space KiB"                 
            log "Not enough space: $required_space > $available_space"
            while [ "$available_space" -le "$required_space" ]; do
                remove_oldest_file_in "$record_storage"
                get_free_space                                                           
                has_files "$record_storage" || die "$record_mount is empty yet no space!"
            done
        fi
        if [ "$check_so" -le 0 ]; then           
            if [ "$record_limit_kb" -gt 0 ]; then      
                log "Space limit: $record_limit_kb KiB"
                get_occupied_space                                                                
                if [ "$((occupied_space + (required_space * 100)))" -lt "$record_limit_kb" ]; then
                    log "lots of space - skipping check for 60 runs"
                    check_so=60
                fi                                                                         
                while [ "$((occupied_space + required_space))" -gt "$record_limit_kb" ]; do    
                    log "Occupied space $occupied_space KiB exceeds limit $record_limit_kb KiB"
                    remove_oldest_file_in "$record_storage"
                    get_occupied_space                                                       
                    has_files "$record_storage" || die "$record_mount is empty yet no space!"
                done
            fi
        else                        
            check_so=$((check_so - 1))
        fi                           
        sleep $((record_duration))
    done
}


show_help() {
	log "Usage: $0 [<params>]
Where params are:
	-u <string>  RTSP username
	-p <string>  RTSP password
	-c <int>     RTSP stream number
	-h <int>     Frame height
	-w <int>     Frame width
	-f <int>     Frames per second
	-t <int>     Duration in seconds
	-v <str>     Record video format
	-m <path>    Mount point for storing files
	-s <path>    Subdirectory for the device
	-n <string>  File name template (supports strftime format)
	-d <int>     Maximum disk usage, GiB
	-x           One-time run
"
}

pidof -o $$ record > /dev/null && die "is already running"

CONFIG_FILE="/etc/web.conf"
[ -f "$CONFIG_FILE" ] && . $CONFIG_FILE

RECORD_FLAG="/tmp/record.$$"

while getopts "c:d:f:h:m:n:p:s:t:u:v:w:xz:" flag; do
	case "$flag" in
		c) stream_number=$OPTARG ;;
		d) record_limit=$OPTARG ;;
		f) stream_fps=$OPTARG ;;
		h) stream_height=$OPTARG ;;
		m) record_mount=$OPTARG ;;
		n) record_filename=$OPTARG ;;
		p) rtsp_password=$OPTARG ;;
		s) record_device_path=$OPTARG ;;
		t) record_duration=$OPTARG ;;
		u) rtsp_username=$OPTARG ;;
		v) record_videofmt=$OPTARG ;;
		w) stream_width=$OPTARG ;;
		x) one_time="true" ;;
		*) show_help && exit ;;
	esac
done
shift "$((OPTIND - 1))"

record_mount=${record_mount%/}
record_device_path=${record_device_path%/}

[ -z "$record_mount"     ] && hesitate "Mountpoint record_mount is not set"
mountpoint -q "$record_mount" || hesitate "Mountpoint $record_mount is not mounted"
[ -w "$record_mount"     ] || hesitate "Mountpoint $record_mount is not writable"
[ -z "$record_duration"  ] && record_duration=10
[ -z "$record_filename"  ] && record_filename="%hostname/%Y/%m/%d/%H-%M-%S"
[ -z "$record_videofmt"  ] && record_videofmt="mp4"
rtsp_username=$(read_config "username" "thingino")
rtsp_password=$(read_config "password" "thingino")
[ -z "$stream_number"    ] && stream_number=0
# FIXME: based on default stream endpoint name, won't work on custom endpoints
stream_endpoint="ch$stream_number"
[ -z "$stream_fps"       ] && stream_fps=$(read_fps "25")
[ -z "$stream_height"    ] && stream_height=$(read_size "7" "1080")
[ -z "$stream_width"     ] && stream_width=$(read_size "5" "1920")
[ -z "$align_minutes"    ] && align_minutes=true  

log "
stream_number: $stream_number
stream_endpoint: $stream_endpoint
stream_fps: $stream_fps
stream_height: $stream_height
stream_width: $stream_width
"

[ -z "$stream_number"   ] && die "Cannot determine stream number"
[ -z "$stream_endpoint" ] && die "Cannot determine stream endpoint"
[ -z "$stream_fps"      ] && die "Cannot determine stream fps"
[ -z "$stream_height"   ] && die "Cannot determine stream height"
[ -z "$stream_width"    ] && die "Cannot determine stream width"

case "$record_videofmt" in
	avi) vformat="-i" ;;
	mov) vformat="-q -y -H" ;;
	mp4) vformat="-4 -y -H" ;;
	  *) die "Unknown video format $record_videofmt"
esac

touch $RECORD_FLAG

record_storage="$record_mount/$record_device_path"
if [ ! -d "$record_storage" ]; then
	log "Creating $record_storage"
	mkdir -p "$record_storage" || die "Cannot create directory $record_storage"
fi
[ -w "$record_storage" ] || die "Cannot write to $record_storage"

record_limit_kb=$((record_limit * 1024 * 1024)) # GiB to KiB
required_space=$((100 * record_duration)) # KiB

record_dir_count=0
after_percent="${record_filename#*%}"
record_dir_count=$(echo "$after_percent" | tr -cd '/' | wc -c)

# align_minutes initialization
if [ -n "$align_minutes" ]; then
    base_ms=$(find_ms)
fi

if [ -z "$one_time" ]; then
	#if we are not running a one-off, then we start a subprocess to manage file cleanup
	fmanager & 
	archive_pid=$!
	log "Spun up rarchive $archive_pid"
	trap cleanup EXIT
else
    get_free_space                                                             
    if [ "$available_space" -le "$required_space" ]; then                      
        log "Space required: $required_space KiB"                                        
        log "Not enough space: $required_space > $available_space"                       
        while [ "$available_space" -le "$required_space" ]; do                           
            remove_oldest_file_in "$record_storage"                                  
            get_free_space                                                           
            has_files "$record_storage" || die "$record_mount is empty yet no space!"                                                                                               
        done                                                                                  
    fi      
    if [ "$record_limit_kb" -gt 0 ]; then                                                        
        log "Space limit: $record_limit_kb KiB"                                                  
        get_occupied_space                                                                       
        while [ "$((occupied_space + required_space))" -gt "$record_limit_kb" ]; do              
            log "Occupied space $occupied_space KiB exceeds limit $record_limit_kb KiB"          
            remove_oldest_file_in "$record_storage"                                              
            get_occupied_space                                                                   
            has_files "$record_storage" || die "$record_mount is empty yet no space!"            
        done                                                                                     
    fi         
fi

while :; do
    [ -f $RECORD_FLAG ] || break

    record_file="$record_storage/$(date +"$record_filename").$record_videofmt"
    create_directory_for "$record_file"

    real_duration=$(fix_duration $record_duration)
    log "openRTSP -u $rtsp_username $rtsp_password -w $stream_width -h $stream_height -f $stream_fps -d $real_duration $vformat -b 1048576 -t rtsp://[::1]/$stream_endpoint > $record_file"
    # Removed timeout from record2.txt
    openRTSP -u $rtsp_username $rtsp_password -w $stream_width -h $stream_height -f $stream_fps \
        -d $real_duration $vformat -b 1048576 -t rtsp://[::1]/$stream_endpoint > "$record_file" 2> /dev/null

    [ "true" = "$one_time" ] && rm $RECORD_FLAG
done

log "Cannot find recording flag $RECORD_FLAG"
[ -n "$LEDD_FLAG" ] && [ -f "$LEDD_FLAG" ] && rm $LEDD_FLAG
log "Exit"

exit 0
