#!/bin/sh

. /etc/init.d/rc.common

COMMAND="/bin/env -- LD_PRELOAD=/lib/libimp_control.so $DAEMON_FULL"
SNAPSHOT="/tmp/snapshot.jpg"

start() {
	starting
	is_streamer_disabled && quit "Streamer disabled"
	start_daemon_with_pid
}

stop() {
	stopping
	is_streamer_disabled && quit "Streamer disabled"
	[ -f "$SNAPSHOT" ] && run "rm $SNAPSHOT"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop || true
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
