#!/bin/sh

. /usr/share/common

COMMAND="/bin/env -- LD_PRELOAD=/lib/libimp_control.so $DAEMON_FULL"

start() {
	starting

	if is_streamer_disabled; then
		quit "Streamer disabled"
	fi

	start_daemon
}

stop() {
	stopping

	if is_streamer_disabled; then
		quit "Streamer disabled"
	fi

	[ -f "$SNAPSHOT_FILE" ] && rm -f "$SNAPSHOT_FILE"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop || true
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
