#!/bin/sh

. /etc/init.d/rc.common

COMMAND="/usr/bin/env -- LD_PRELOAD=/usr/lib/libimp_control.so $DAEMON_FULL"

start() {
	starting
	is_streamer_disabled && quit "Disabled"
	start_daemon_with_pid
}

stop() {
	stopping
	is_streamer_disabled && quit "Disabled"
	stop_daemon_with_pid
}

restart() {
	stop || true
	sleep 1
	reload
}

reload() {
	start
}

case "$1" in
	start | stop | restart | reload)
		$1
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
