#!/bin/sh

# http://www.live555.com/openRTSP/

WEBUI_CONF=/etc/webui/record.conf

. /etc/init.d/rc.common

read_config() {
	sed -nE "s/^.*$1:\s*\"?([^\"]+)\"?;.*$/\1/p" /etc/prudynt.cfg | head -1
}

start() {
	starting
	pidof $DAEMON > /dev/null && quit "$DAEMON is already running"

	is_streamer_disabled && quit "Streamer disabled"
	is_streamer_running || quit "Streamer is not running"
	[ -f $WEBUI_CONF ] || quit "Not configured"
	. $WEBUI_CONF
	[ "true" = "$record_enabled" ] || quit "Disabled in $WEBUI_CONF"
	[ -d "$record_mount" ] || quit "Storage is not mounted"
	record_path=$(dirname "$record_mount/$(date +"$record_filename")")
	[ -d "$record_path" ] || quit "No access to $record_path"
	start_daemon_with_pid
}

stop() {
	stopping
	is_streamer_disabled && quit "Streamer disabled"
	rm /tmp/record.do
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;

	reload | restart)
		stop
		sleep 1
		start
		;;

	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
