#!/bin/sh

PRUDYNT_APP="prudynt"
PRUDYNT_CONFIG="/etc/prudynt.json"
FIFO_PATH="/run/prudynt/mp4ctl"

start() {
	echo -c 15 "Starting Record service"

	if ! pidof $PRUDYNT_APP >/dev/null 2>&1; then
		echo "Streamer is not running" >&2
		exit 1
	fi

	if [ "true" != "$(jct $PRUDYNT_CONFIG get recorder.autostart 2>/dev/null)" ]; then
		echo "Autostart is not set"
		exit 0
	fi

	/sbin/record || echo "record command failed"
}

stop() {
	echo -c 15 "Stopping Recording service"

	pidof prudynt || return 0

	[ -p "$FIFO_PATH" ] && printf 'STOP\n' >"$FIFO_PATH"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;

	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0
