#!/bin/sh

PRUDYNT_APP="prudynt"
PRUDYNT_CONFIG="/etc/prudynt.json"
FIFO_PATH="/run/prudynt/mp4ctl"

. /usr/share/common

start() {
	echo_title "Starting Record service"

	if ! pidof $PRUDYNT_APP >/dev/null 2>&1; then
		echo_error "Streamer is not running"
		exit 1
	fi

	if [ "true" != "$(jct $PRUDYNT_CONFIG get recorder.autostart 2>/dev/null)" ]; then
		echo_warning "Autostart is not set"
		exit 0
	fi

	/sbin/record || echo_warning "record command failed"
}

stop() {
	echo_title "Stopping Recording service"

	[ -p "$FIFO_PATH" ] && printf 'STOP\n' > "$FIFO_PATH"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;

	restart)
		stop
		sleep 1
		start
		;;
	*)
		usage "{start|stop|restart}"
		;;
esac

exit 0
