#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

show_help() {
	echo "Usage: $0 [options]
Where:
	-s host     FTP server FQDN or IP address
	-p port     FTP server port
	-d path     Directory on server, relative to FTP root
	-f file     File to upload
	-u username FTP username
	-P password FTP password
	-v          Verbose output
	-S          Send photo
	-V          Send video
" >&2
	exit 0
}

read_config() {
	local CONFIG_FILE=/etc/send2.json
	[ -f "$CONFIG_FILE" ] || return

	      host=$(jct $CONFIG_FILE get ftp.host)
	      port=$(jct $CONFIG_FILE get ftp.port)
	  username=$(jct $CONFIG_FILE get ftp.username)
	  password=$(jct $CONFIG_FILE get ftp.password)
	      path=$(jct $CONFIG_FILE get ftp.path)
	  template=$(jct $CONFIG_FILE get ftp.template)
	send_photo=$(jct $CONFIG_FILE get ftp.send_photo)
	send_video=$(jct $CONFIG_FILE get ftp.send_video)
}

# Files to send
queue=""

add_to_queue() {
	queue="$queue $1"
}

# rename file by the template
process_file() {
	local file="$1"
	local ext="${file##*.}"
	local name="/tmp/$(date +"$template").$ext"
	mv "$file" "$name"
	add_to_queue "$name"
	add_to_garbage "$name"
}

read_config

while getopts d:f:p:P:s:u:vSV flag; do
	case "$flag" in
		s) host=$OPTARG ;;
		p) port=$OPTARG ;;
		P) password=$OPTARG ;;
		u) username=$OPTARG ;;
		d) path=$OPTARG ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) file=$OPTARG; send_photo="false"; send_video="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "FTP host not found"
	exit 1
fi

[ -z "$port" ] && port=21
[ -z "$username" ] && username="anonymous" && password="anonymous"

if [ -n "$file" ]; then
	add_to_queue "$file"
fi

if [ "true" = "$send_video" ]; then
	process_file $(copy_video)
fi

if [ "true" = "$send_photo" ]; then
	process_file $(copy_photo)
fi

url="ftp://"
[ -n "$username" ] && [ -n "$password" ] && url="$url$username:$password"
url="$url@$host:$port"
[ -n "$path" ] && url="$url/${path// /%20}"

for local_file in $queue; do
	if [ "true" = "$verbose" ]; then
		command="$CURL --verbose"
	else
		command="$CURL --silent"
	fi
	command="$command --url $url/$(basename $local_file) --upload-file $local_file --ftp-create-dirs"

	[ "true" = "$verbose" ] && echo_command "$command"

	if ! sh -c "$command"; then
		echo_error "Failed to upload file to FTP server"
		exit 1
	fi
done

exit 0
