#!/bin/env sh
# Sends data to ntfy.sh
# https://docs.ntfy.sh/publish/

. /usr/share/prudynt-helpers
. /usr/share/send2common

domain="ntfy"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      NTFY server FQDN or IP address
	-p port      NTFY server port
	-u username  NTFY username
	-P password  NTFY password
	-T token     NTFY token
	-t topic     Topic
	-n title     Message title
	-m message   Message body
	-a URL       Attachment URL
	-c URL       Click URL
	-f file      Attach file
	-i URL       Icon URL
	-z N         Priority: 1-lowest, 5-highest
	-d N         Delay
	-S           Send photo
	-V           Send video
	-v           Verbose output
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	actions=$(get_value actions)
	attach=$(get_value attach)
	call=$(get_value call)
	click=$(get_value click)
	delay=$(get_value delay)
	email=$(get_value email)
	filename=$(get_value filename)
	host=$(get_value host)
	icon=$(get_value icon)
	message=$(get_value message)
	password=$(get_value password)
	port=$(get_value port)
	prority=$(get_value priority)
	tags=$(get_value tags)
	title=$(get_value title)
	token=$(get_value token)
	topic=$(get_value topic)
	twilio_token=$(get_value twilio_token)
	username=$(get_value username)
}

read_config

while getopts a:c:d:h:i:m:n:t:p:u:vz:P:T:f:SV flag; do
	case "$flag" in
		a) attach=$OPTARG ;;
		c) click=$OPTARG ;;
		d) delay==$OPTARG ;;
		h) host=$OPTARG ;;
		i) icon=$OPTARG ;;
		m) message=$OPTARG ;;
		n) title=$OPTARG ;;
		p) port=$OPTARG ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		z) priority=$OPTARG ;;
		P) password=$OPTARG ;;
		T) token=$OPTARG ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) filename=$OPTARG; send_photo="false"; send_video="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

# use config settings only if not set from command line
if [ -z "$filename" ] && [ "true" != "$send_photo" ] && [ "true" != "$send_video" ]; then
        send_photo=$(get_value send_photo)
        send_video=$(get_value send_video)
fi

if [ -z "$topic" ]; then
	echo_error "NTFY topic is not set"
	exit 1
fi

[ -z "$host" ] && host="ntfy.sh"
[ -z "$port" ] && port=80

command="curl -X POST -H p:${priority:-3}"

if [ "true" = "$verbose" ]; then
	command="$command --verbose"
else
	command="$command --silent"
fi

if [ -n "$message" ]; then
	message="$(date +"$message")"
fi

# --- Sanitize config values for safe shell interpolation ---
s_token=$(shell_escape "Authorization: Bearer $token")
s_userpass=$(shell_escape "$username:$password")
s_message=$(shell_escape "Message: $message")
s_host_topic=$(shell_escape "$host/$topic")

if [ -n "$token" ]; then
	command="$command -H $s_token"
elif [ -n "$username" ] && [ -n "$password" ]; then
	command="$command -u $s_userpass"
fi

if [ -n "$message" ]; then
	command="$command -H $s_message"
fi

# Seems only one attachment is allowed at a time
# so we prioritize file over snapshot over video.
if [ -n "$filename" ] && [ -f "$filename" ]; then
	s_filename=$(shell_escape "$filename")
	s_filename_header=$(shell_escape "Filename: $filename")
	command="$command -T $s_filename -H $s_filename_header"
elif [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	s_photo=$(shell_escape "$photo")
	s_photo_header=$(shell_escape "Filename: $photo")
	command="$command -T $s_photo -H $s_photo_header"
elif [ "true" = "$send_video" ]; then
	video=$(copy_video)
	s_video=$(shell_escape "$video")
	s_video_header=$(shell_escape "Filename: $video")
	command="$command -T $s_video -H $s_video_header"
fi

#[ -n "$title" ] && command="$command -H 'Title: $title'"
#[ -n "$delay" ] && command="$command -H 'Delay: $delay'"
#[ -n "$tags" ] && command="$command -H 'Tags: $tags'"
#[ -n "$attach" ] && command="$command -H 'Attach: $attach'"
#[ -n "$click" ] && command="$command -H 'Click: $click'"
#[ -n "$icon" ] && command="$command -H 'Icon: $icon'"
#[ -n "$email" ] && command="$command -H 'Email: $email'"
#[ -n "$actions" ] && command="$command -H 'Actions: $actions'"
#[ -n "$call" ] && [ -n "$twilio_token" ] && command="$command -H 'Call: $call' -u :$twilio_token"

command="$command $s_host_topic"

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send NTFY message"
	exit 1
fi

exit 0
