#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

show_help() {
	echo "Usage: $0 [options]
Where:
	-s host     FTP server FQDN or IP address.
	-p port     FTP server port.
	-d path     Directory on server, relative to FTP root.
	-f file     File to upload.
	-u username FTP username.
	-P password FTP password.
	-v          Verbose output.
	-V          If -f not specified, sends the video currently in vbuffer.
	-S          If -f not specified, sends the current camera snapshot.
	-h          Show this help.
" >&2
	exit 0
}

read_config() {
	local CONFIG_FILE=/etc/send2.json
	[ -f "$CONFIG_FILE" ] || return

	    host=$(jct $CONFIG_FILE get ftp.host)
	    port=$(jct $CONFIG_FILE get ftp.port)
	username=$(jct $CONFIG_FILE get ftp.username)
	password=$(jct $CONFIG_FILE get ftp.password)
	    path=$(jct $CONFIG_FILE get ftp.path)
	template=$(jct $CONFIG_FILE get ftp.template)
}

# Files to send
queue=""

add_to_queue() {
	local ext="${1##*.}"
	local tempfile="$(mktemp -u).$ext"
	cp -f "$1" "$tempfile"
	queue="$queue $tempfile"
}

read_config

while getopts d:f:hp:P:s:Su:vV flag; do
	case "$flag" in
		d) path=$OPTARG ;;
		f) file=$OPTARG ;;
		p) port=$OPTARG ;;
		P) password=$OPTARG ;;
		s) host=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		h | *) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "FTP host not found"
	exit 1
fi

if [ -z "$port" ]; then
	port=21
fi

if [ -z "$username" ]; then
	ftp_username="anonymous"
	ftp_password="anonymous"
fi

if [ -z "$file" ]; then
	if [ "true" = "$send_video" ]; then
		check_vbuffer

		inode=$(stat -c%i $VBUFFER_FILE)

		# Video preceeding the event
		video1=$(copy_video)
		add_to_queue "$video1"

		# Wait until the inode changes, meaning the video buffer file was recreated
		while [ $inode -eq $(stat -c%i $VBUFFER_FILE) ]; do
			n=$((n + 1))
			if [ "$n" -ge 10 ]; then
				echo_error "Give up after $n attempts."
				exit 1
			fi
			sleep 1
		done

		# Video following the event
		video2=$(copy_video)
		add_to_queue "$video2"
	fi

	if [ "true" = "$send_photo" ]; then
		photo=$(copy_photo)
		add_to_queue "$photo"
	fi
else
	add_to_queue "$file"
fi

url="ftp://"
if [ -n "$username" ] && [ -n "$password" ]; then
	url="$url$username:$password"
fi
url="$url@$host:$port"
if [ -n "$path" ]; then
	url="$url/${path// /%20}"
fi

n=0
for local_file in $queue; do
	ext="${local_file##*.}"
	filename=$(date +"$template-$(printf %02d $n)").$ext
	final_url="$url/$filename"

	set -x
	if [ "true" = "$verbose" ]; then
		command="$CURL --verbose"
	else
		command="$CURL --silent"
	fi
	command="$command --url $final_url --upload-file $local_file --ftp-create-dirs"
	set +x

	if [ "true" = "$verbose" ]; then
		echo_command "$command"
	fi

	if ! sh -c "$command"; then
		echo_error "Failed to upload file to FTP server"
		exit 1
	fi

	n=$(($n + 1))
done

exit 0
