#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

show_help() {
	echo "Usage: $0 [options]
Where:
	-f address  Sender's email address
	-t address  Recipient's email address
	-n host     SMTP server host.
	-p port     SMTP server port.
	-s subject  Subject line.
	-b body     Letter body.
	-k          Ignore SSL certificate validity.
	-v          Verbose output.
	-h          Show this help.
" >&2
	exit 0
}

read_config() {
	local CONFIG_FILE=/etc/send2.json
	[ -f "$CONFIG_FILE" ] || return

	from_address=$(jct $CONFIG_FILE get email.from_address)
	   from_name=$(jct $CONFIG_FILE get email.from_name)
	  to_address=$(jct $CONFIG_FILE get email.to_address)
	     to_name=$(jct $CONFIG_FILE get email.to_name)
	     subject=$(jct $CONFIG_FILE get email.subject)
	        body=$(jct $CONFIG_FILE get email.body)
	        host=$(jct $CONFIG_FILE get email.host)
	        port=$(jct $CONFIG_FILE get email.port)
	    username=$(jct $CONFIG_FILE get email.username)
	    password=$(jct $CONFIG_FILE get email.password)
	     use_ssl=$(jct $CONFIG_FILE get email.use_ssl)
	  trust_cert=$(jct $CONFIG_FILE get email.trust_cert)
	  send_photo=$(jct $CONFIG_FILE get email.send_photo)
	  send_video=$(jct $CONFIG_FILE get email.send_video)
}

read_config

while getopts b:f:hkn:p:s:t:v flag; do
	case "$flag" in
		b) body=$OPTARG ;;
		f) from_address=$OPTARG ;;
		h) host=$OPTARG ;;
		k) use_ssl="true" ;;
		p) port=$OPTARG ;;
		s) subject=$OPTARG ;;
		t) to_address=$OPTARG ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "SMTP host not found"
	exit 1
fi

if [ -z "$port" ]; then
	port=25
fi

if [ -z "$from_address" ]; then
	echo_error "Sender's email address not found"
	exit 1
fi

if [ -z "$to_address" ]; then
	echo_error "Recipient's email address not found"
	exit 1
fi

if [ -z "$body" ]; then
	echo_error "Email body not found"
	exit 1
fi

if ! echo "$from_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
	echo_error "Invalid sender email address format"
	exit 1
fi

if ! echo "$to_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
	echo_error "Invalid recipient email address format"
	exit 1
fi

if [ -z "$from_name" ]; then
	from_name="Thingino Camera"
fi

if [ -z "$to_name" ]; then
	to_name="Thingino Camera Admin"
fi

if [ -z "$subject" ]; then
	subject="Snapshot from Thingino Camera"
fi

if [ "true" = "$verbose" ]; then
	command="$CURL --verbose"
else
	command="$CURL --silent"
fi
command="$command --mail-from $from_address --mail-rcpt $to_address"

if [ -n "$username" ] && [ -n "$password" ]; then
	command="$command --user '$username:$password'"
fi

if [ "true" = "$use_ssl" ]; then
	command="$command --url smtps://$host:$port --ssl"
	[ "true" = "$trust_cert" ] && command="$command --insecure"
else
	command="$command --url smtp://$host:$port"
fi

email_body=${body//"/\\"}
command="$command -H 'From: \"$from_name\" <$from_address>'"
command="$command -H 'To: \"$to_name\" <$to_address>'"
command="$command -H 'Subject: $subject'"
command="$command -F '=(;type=multipart/mixed'"
command="$command -F \"=${body};type=text/plain\""

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	command="$command -F 'snapshot=@$photo;type=image/jpeg;encoder=base64'"
fi

if [ "true" = "$send_video" ]; then
	video="$(copy_video)"
	case "${VBUFFER_FILE##*.}" in
		mkv) mime="video/matroska" ;;
		mov) mime="video/quicktime" ;;
		mp4) mime="video/mp4" ;;
		*) mime="application/octet-stream" ;;
	esac
	command="$command -F 'video=@$video;type=$mime;encoder=base64'"
fi

command="$command -F '=)'"

if [ "true" = "$verbose" ]; then
	echo_command "$command"
fi

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send email"
	exit 1
fi

exit 0
