#!/bin/env sh
# Sends data to MQTT server
# https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
# https://mosquitto.org/documentation/

. /usr/share/common
. /usr/share/send2common

message_looks_like_json() {
	# Treat payload as JSON when it is wrapped in braces or brackets
	local trimmed
	trimmed=$(printf '%s' "$1" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
	case "$trimmed" in
		\{*\}|\[*\])
			return 0
			;;
		*)
			return 1
			;;
	esac
}

escape_single_quotes() {
	# Escape single quotes for safe inclusion inside single-quoted strings
	printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      Server host
	-m message   Message body
	-t topic     Topic
	-u username  Username
	-w password  Password
	-S           Send photo
	-V           Send video
	-v           Verbose output
" >&2
	exit 0
}

read_config() {
	local CONFIG_NAME=/etc/send2.json
	[ -f "$CONFIG_NAME" ] || return

	       host=$(jct $CONFIG_NAME get mqtt.host)
	       port=$(jct $CONFIG_NAME get mqtt.port)
	   username=$(jct $CONFIG_NAME get mqtt.username)
	   password=$(jct $CONFIG_NAME get mqtt.password)
	  client_id=$(jct $CONFIG_NAME get mqtt.client_id)
	      topic=$(jct $CONFIG_NAME get mqtt.topic)
	    message=$(jct $CONFIG_NAME get mqtt.message)
	topic_photo=$(jct $CONFIG_NAME get mqtt.topic)
	 send_photo=$(jct $CONFIG_NAME get mqtt.send_photo)
	 send_video=$(jct $CONFIG_NAME get mqtt.send_video)
}

read_config

while getopts h:m:st:u:w:v flag; do
	case "$flag" in
		h) host=$OPTARG ;;
		m) message=$OPTARG ;;
		s) send_photo="true" ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		w) password=$OPTARG ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "MQTT broker host is not set"
	exit 1
fi

if [ -z "$port" ]; then
	echo_error "MQTT broker port is not set"
	exit 1
fi

if [ -z "$topic" ]; then
	echo_error "MQTT topic not found"
	exit 1
fi

if [ -z "$message" ]; then
	echo_error "MQTT message template not found"
	exit 1
fi

if [ "true" = "$send_photo" ] && [ -z "$topic_photo" ]; then
	echo_error "MQTT topic for sending snapshot not found in config"
	exit 1
fi

[ -z "$client_id" ] && client_id=$(hostname)

message=$(date +"$message")

command="mosquitto_pub -h $host -p $port -i $client_id"

[ "true" = "$verbose" ] && command="$command -d"
[ -n "$username" ] && command="$command -u $username"
[ -n "$password" ] && command="$command -P $password"

failed=0

if message_looks_like_json "$message"; then
	tmpfile="$(mktemp -u).json"
	echo "$message" > $tmpfile
	send_command="$command -t $topic -f $tmpfile"
	garbage="$garbage $tmpfile"
else
	sanitized_message=$(escape_single_quotes "$message")
	send_command="$command -t $topic -m '$sanitized_message'"
fi

[ "true" = "$verbose" ] && echo_command "$send_command"
if ! sh -c "$send_command"; then
	echo_error "Failed to send MQTT message"
	failed=1
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	if [ -z "$photo" ]; then
		echo_error "Failed to get photo"
		failed=1
	else
		send_command="$command -t $topic_photo -f '$photo'"
		[ "true" = "$verbose" ] && echo_command "$send_command"
		if ! sh -c "$send_command"; then
			echo_error "Failed to send photo via MQTT"
			failed=1
		fi
	fi
fi

if [ "true" = "$send_video" ]; then
	video=$(copy_video)
	if [ -z "$video" ]; then
		echo_error "Failed to get video"
		failed=1
	else
		send_command="$command -t $topic_video -f '$video'"
		[ "true" = "$verbose" ] && echo_command "$send_command"
		if ! sh -c "$send_command"; then
			echo_error "Failed to send video via MQTT"
			failed=1
		fi
	fi
fi

exit $failed
