#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

domain="telegram"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options] [clip|motion|snap]
Where:
	-c channel  Telegram channel ID.
	            See https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35
	-f file     Send file.
	-m message  Send message.
	-s          Disable notification.
	-t token    Telegram bot token. See https://t.me/botfather if you need one.
	-v          Verbose output.
	-S          Send snapshot.
	-V          Send video.
	-h          Show this help.
" >&2
	exit 0
}

parse_caption() {
	echo "$caption" | sed "s/%hostname/$(hostname -s)/;s/%datetime/$(date @$(stat -c%Z $1))/"
}

read_config() {
	[ -f "$config_file" ] || return

	     token=$(get_value token)
	   channel=$(get_value channel)
	   message=$(get_value message)
	      file=$(get_value file)
	    silent=$(get_value silent)
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
}

read_config

# override config values with command line arguments
while getopts c:f:m:Sst:Vvh flag; do
	case "$flag" in
		c) channel=$OPTARG ;;
		m) message=$OPTARG ;;
		f) file=$OPTARG ;;
		s) silent="true" ;;
		t) token=$OPTARG ;;
		v) verbose="true" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		h) show_help ;;
	esac
done

shift $((OPTIND - 1))

if [ $# -ne 0 ]; then
	case "$1" in
		clip)
			send_photo="false"
			send_video="true"
			;;
		motion)
			send_photo="true"
			send_video="true"
			;;
		snap)
			send_photo="true"
			send_video="false"
			;;
	esac
fi

if [ -z "$token" ]; then
	echo_error "Telegram token not found"
	exit 1
fi

if [ -z "$channel" ]; then
	echo_error "Telegram channel not found"
	exit 1
fi

if [ "true" = "$verbose" ]; then
	command="curl --verbose"
else
	command="curl --silent"
fi

command="$command -H 'Content-Type: multipart/form-data'"
command="$command -F 'chat_id=$channel'"

if [ "true" = "$silent" ]; then
	command="$command -F 'disable_notification=true'"
fi
command="$command --url https://api.telegram.org/bot$token/"
# no further modifications to command after this point

if [ "true" = "$send_video" ] && [ "true" = "$send_photo" ]; then
	# https://core.telegram.org/bots/api#sendmediagroup
	photo=$(copy_photo)
	caption=$(parse_caption $photo)
	command="${command}sendMediaGroup -F 'snap=@$photo'"
	[ -n "$message" ] && caption="$caption $message"
	media='[{"type":"photo","media":"attach://snap","caption":"'$caption'"},'

	check_vbuffer
	inode=$(stat -c%i $VBUFFER_FILE)

	video1=$(copy_video)
	command="$command -F 'video1=@$video1'"
	media=$media'{"type":"video","media":"attach://video1"},'

	while [ $inode -eq $(stat -c%i $VBUFFER_FILE) ]; do
		n=$((n + 1))
		if [ "$n" -ge 10 ]; then
			echo_error "Give up after $n attempts."
			exit 1
		fi
		sleep 1
	done

	video2=$(copy_video)
	command="$command -F 'video2=@$video2'"
	media=$media'{"type":"video","media":"attach://video2"}]'
	command="$command -F 'media=$media'"

elif [ "true" = "$send_video" ]; then
	# https://core.telegram.org/bots/api#sendvideo
	video1=$(copy_video)
	caption="$(parse_caption $video1)"
	[ -n "$message" ] && caption="$caption $message"
	command="${command}sendVideo -F 'video=@$video1' -F 'caption=$caption'"

elif [ "true" = "$send_photo" ]; then
	# https://core.telegram.org/bots/api#sendphoto
	photo=$(copy_photo)
	caption="$(parse_caption $photo)"
	[ -n "$message" ] && caption="$caption $message"
	command="${command}sendPhoto -F 'photo=@$photo' -F 'caption=$caption'"

elif [ -n "$message" ]; then
	# https://core.telegram.org/bots/api#sendmessage
	command="${command}sendMessage -F 'text=$message'"

elif [ -n "$file" ] && [ -f "$file" ]; then
	# https://core.telegram.org/bots/api#senddocument
	caption="$(parse_caption $file)"
	[ -n "$message" ] && caption="$caption $message"
	command="${command}sendDocument -F 'document=@$1' -F 'caption=$caption'"

else
	echo_error "Nothing to send"
	exit 1
fi

if [ "true" = "$verbose" ]; then
	echo_command "$command"
fi

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send message to Telegram"
	exit 1
fi

exit 0
