#!/bin/env sh
# Sends data to MQTT server
# https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
# https://mosquitto.org/documentation/

. /usr/share/common
. /usr/share/send2common

domain="mqtt"
config_file="/etc/send2.json"

message_looks_like_json() {
	# Treat payload as JSON when it is wrapped in braces or brackets
	local trimmed
	trimmed=$(printf '%s' "$1" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
	case "$trimmed" in
		\{*\}|\[*\])
			return 0
			;;
		*)
			return 1
			;;
	esac
}

escape_single_quotes() {
	# Escape single quotes for safe inclusion inside single-quoted strings
	printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      MQTT server FQDN or IP address
	-p port      MQTT port
	-u username  MQTT username
	-P password  MQTT password
	-t topic     Topic
	-m message   Message body
	-v           Verbose output
	-S           Send photo
	-V           Send video
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	client_id=$(get_value client_id)
	host=$(get_value host)
	message=$(get_value message)
	password=$(get_value password)
	port=$(get_value port)
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
	topic=$(get_value topic)
	topic_photo=$(get_value topic_photo)
	topic_video=$(get_value topic_video)
	username=$(get_value username)
}

read_config

while getopts h:m:p:t:u:vP:SV flag; do
	case "$flag" in
		h) host=$OPTARG ;;
		m) message=$OPTARG ;;
		p) port=$OPTARG ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		P) password=$OPTARG ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) file=$OPTARG; send_photo="false"; send_video="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "MQTT broker host is not set"
	exit 1
fi

if [ -z "$topic" ]; then
	echo_error "MQTT topic is not set"
	exit 1
fi

if [ -z "$message" ]; then
	echo_error "MQTT message template is not set"
	exit 1
fi

if [ "true" = "$send_photo" ] && [ -z "$topic_photo" ]; then
	echo_error "MQTT topic for sending snapshot is not set"
	exit 1
fi

[ -z "$client_id" ] && client_id=$(hostname)
[ -z "$port" ] && port=1883

message=$(date +"$message")

command="mosquitto_pub -h $host -p $port -i $client_id"

[ "true" = "$verbose" ] && command="$command -d"
[ -n "$username" ] && command="$command -u $username"
[ -n "$password" ] && command="$command -P $password"

failed=0

if message_looks_like_json "$message"; then
	tmpfile="$(mktemp -u).json"
	echo "$message" > $tmpfile
	send_command="$command -t $topic -f $tmpfile"
	garbage="$garbage $tmpfile"
else
	sanitized_message=$(escape_single_quotes "$message")
	send_command="$command -t $topic -m '$sanitized_message'"
fi

[ "true" = "$verbose" ] && echo_command "$send_command"
if ! sh -c "$send_command"; then
	echo_error "Failed to send MQTT message"
	failed=1
fi

if [ -n "$file" ] && [ -f "$file" ]; then
	send_command="$command -t $topic -f '$file'"
	[ "true" = "$verbose" ] && echo_command "$send_command"
	if ! sh -c "$send_command"; then
		echo_error "Failed to send file via MQTT"
		failed=1
	fi
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	if [ -z "$photo" ]; then
		echo_error "Failed to get photo"
		failed=1
	else
		send_command="$command -t $topic_photo -f '$photo'"
		[ "true" = "$verbose" ] && echo_command "$send_command"
		if ! sh -c "$send_command"; then
			echo_error "Failed to send photo via MQTT"
			failed=1
		fi
	fi
fi

if [ "true" = "$send_video" ]; then
	video=$(copy_video)
	if [ -z "$video" ]; then
		echo_error "Failed to get video"
		failed=1
	else
		send_command="$command -t $topic_video -f '$video'"
		[ "true" = "$verbose" ] && echo_command "$send_command"
		if ! sh -c "$send_command"; then
			echo_error "Failed to send video via MQTT"
			failed=1
		fi
	fi
fi

exit $failed
