#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

domain="email"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-n host      SMTP server FQDN or IP address
	-p port      SMTP server port
	-u username  SMTP username
	-P password  SMTP password
	-f address   Sender's email address
	-t address   Recipient's email address
	-s subject   Subject line
	-b body      Letter body
	-k           Ignore SSL certificate validity
	-v           Verbose output
	-S           Send photo
	-V           Send video
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	body=$(get_value body)
	from_address=$(get_value from_address)
	from_name=$(get_value from_name)
	host=$(get_value host)
	password=$(get_value password)
	port=$(get_value port)
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
	subject=$(get_value subject)
	to_address=$(get_value to_address)
	to_name=$(get_value to_name)
	trust_cert=$(get_value trust_cert)
	use_ssl=$(get_value use_ssl)
	username=$(get_value username)
}

read_config

while getopts b:f:h:kp:s:t:u:vP:SV flag; do
	case "$flag" in
		b) body=$OPTARG ;;
		f) from_address=$OPTARG ;;
		h) host=$OPTARG ;;
		k) use_ssl="true" ;;
		p) port=$OPTARG ;;
		s) subject=$OPTARG ;;
		t) to_address=$OPTARG ;;
		u) username=$OPTARG ;;
		v) verbose="true" ;;
		P) password=$OPTARG ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "SMTP host not found"
	exit 1
fi

if [ -z "$from_address" ]; then
	echo_error "Sender's email address not found"
	exit 1
fi

if [ -z "$to_address" ]; then
	echo_error "Recipient's email address not found"
	exit 1
fi

if [ -z "$body" ]; then
	echo_error "Email body not found"
	exit 1
fi

if ! echo "$from_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
	echo_error "Invalid sender email address format"
	exit 1
fi

if ! echo "$to_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
	echo_error "Invalid recipient email address format"
	exit 1
fi

[ -z "$port" ] && port=25
[ -z "$from_name" ] && from_name="Thingino Camera"
[ -z "$to_name" ] && to_name="Thingino Camera Admin"
[ -z "$subject" ] && subject="Snapshot from Thingino Camera"

if [ "true" = "$verbose" ]; then
	command="$CURL --verbose"
else
	command="$CURL --silent"
fi
command="$command --mail-from $from_address --mail-rcpt $to_address"
[ -n "$username" ] && [ -n "$password" ] && command="$command --user '$username:$password'"

if [ "true" = "$use_ssl" ]; then
	command="$command --url smtps://$host:$port --ssl"
	[ "true" = "$trust_cert" ] && command="$command --insecure"
else
	command="$command --url smtp://$host:$port"
fi

email_body=${body//"/\\"}
command="$command -H 'From: \"$from_name\" <$from_address>'"
command="$command -H 'To: \"$to_name\" <$to_address>'"
command="$command -H 'Subject: $subject'"
command="$command -F '=(;type=multipart/mixed'"
command="$command -F \"=${body};type=text/plain\""

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	command="$command -F 'snapshot=@$photo;type=image/jpeg;encoder=base64'"
fi

if [ "true" = "$send_video" ]; then
	video="$(copy_video)"
	case "${video##*.}" in
		mkv) mime="video/matroska" ;;
		mov) mime="video/quicktime" ;;
		mp4) mime="video/mp4" ;;
		*) mime="application/octet-stream" ;;
	esac
	command="$command -F 'video=@$video;type=$mime;encoder=base64'"
fi

command="$command -F '=)'"

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send email"
	exit 1
fi

exit 0
