#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

domain="telegram"
config_file="/etc/send2.json"

get_value() {
	jct "$config_file" get "$domain.$1" 2>/dev/null
}

show_help() {
	echo "Usage: $0 [options]
Where:
	-c channel  Telegram channel ID.
	            See https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35
	-f file     Send file.
	-m message  Send message.
	-s          Disable notification.
	-t token    Telegram bot token. See https://t.me/botfather if you need one.
	-v          Verbose output.
	-S          Send photo.
	-V          Send video.
	-h          Show this help.
" >&2
	exit 0
}

parse_caption() {
	local file="$1"
	local caption_template="${2:-}"
	[ -z "$caption_template" ] && caption_template=$(get_value caption)
	[ -z "$caption_template" ] && caption_template=""
	echo "$caption_template" | sed "s/%hostname/$(hostname -s)/g;s/%datetime/$(date +%Y-%m-%d\ %H:%M:%S)/g"
}

read_config() {
	[ -f "$config_file" ] || return

	channel=$(get_value channel)
	file=$(get_value file)
	message=$(get_value message)
	silent=$(get_value silent)
	token=$(get_value token)
}

read_config

# override config values with command line arguments
while getopts c:f:m:st:vSV flag; do
	case "$flag" in
		c) channel=$OPTARG ;;
		f) file=$OPTARG ;;
		m) message=$OPTARG ;;
		s) silent="true" ;;
		t) token=$OPTARG ;;
		v) verbose="true" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

# use config settings only if not set from command line
if [ -z "$send_photo$send_video" ]; then
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
fi

if [ -z "$token" ]; then
	echo_error "Telegram token not found"
	exit 1
fi

if [ -z "$channel" ]; then
	echo_error "Telegram channel not found"
	exit 1
fi

command="curl --silent --tlsv1.2 --tls-max 1.2"
[ "true" = "$verbose" ] && command="$command --verbose"
command="$command -F 'chat_id=$channel'"
[ "true" = "$silent" ] && command="$command -F 'disable_notification=true'"
command="$command -F 'rand=$RANDOM'"

url="https://api.telegram.org/bot$token/"

if [ "true" = "$send_video" ] && [ "true" = "$send_photo" ]; then
	# https://core.telegram.org/bots/api#sendmediagroup
	url="${url}sendMediaGroup"

	photo=$(copy_photo)
	caption=$(parse_caption $photo)
	command="$command -F 'photo=@$photo'"
	[ -n "$message" ] && caption="$caption $message"
	media='{"type":"photo","media":"attach://photo","caption":"'$caption'"},'

	video=$(copy_video)
	command="$command -F 'video=@$video'"
	media=$media'{"type":"video","media":"attach://video"}'

	command="$command -F 'media=[$media]' $url"

elif [ "true" = "$send_video" ]; then
	# https://core.telegram.org/bots/api#sendvideo
	url="${url}sendVideo"
	video=$(copy_video)
	caption="$(parse_caption $video)"
	[ -n "$message" ] && caption="$caption $message"
	command="$command -F 'video=@$video' -F 'caption=\"$caption\"' $url"

elif [ "true" = "$send_photo" ]; then
	# https://core.telegram.org/bots/api#sendphoto
	url="${url}sendPhoto"
	photo=$(copy_photo)
	caption="$(parse_caption $photo)"
	[ -n "$message" ] && caption="$caption $message"
	command="$command -F 'photo=@$photo' -F 'caption=\"$caption\"' $url"

elif [ -n "$message" ]; then
	# https://core.telegram.org/bots/api#sendmessage
	url="${url}sendMessage"
	command="$command -F 'text=$message' $url"

elif [ -n "$file" ] && [ -f "$file" ]; then
	# https://core.telegram.org/bots/api#senddocument
	url="${url}sendDocument"
	caption="$(parse_caption $file)"
	[ -n "$message" ] && caption="$caption $message"
	command="$command -F 'document=@$1' -F 'caption=\"$caption\"' $url"

else
	echo_error "Nothing to send"
	exit 1
fi

if [ "true" = "$verbose" ]; then
	echo_command "$command"
fi

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send message to Telegram"
	exit 1
fi

exit 0
