#!/bin/env sh
# Sends data to MQTT server
# https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
# https://mosquitto.org/documentation/

. /usr/share/common
. /usr/share/send2common

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      Server host.
	-j           Message is JSON.
	-m message   Message body.
	-s           Send a snapshot.
	-t topic     Topic.
	-u username  Username.
	-w password  Password.
	-v           Verbose output.
" >&2
	exit 0
}

read_config() {
	local CONFIG_NAME=/etc/send2.json
	[ -f "$CONFIG_NAME" ] || return

	       host=$(jct $CONFIG_NAME get mqtt.host)
	       port=$(jct $CONFIG_NAME get mqtt.port)
	   username=$(jct $CONFIG_NAME get mqtt.username)
	   password=$(jct $CONFIG_NAME get mqtt.password)
	  client_id=$(jct $CONFIG_NAME get mqtt.client_id)
	      topic=$(jct $CONFIG_NAME get mqtt.topic)
	    message=$(jct $CONFIG_NAME get mqtt.message)
	    is_json=$(jct $CONFIG_NAME get mqtt.is_json)
	topic_photo=$(jct $CONFIG_NAME get mqtt.topic)
	 send_photo=$(jct $CONFIG_NAME get mqtt.send_photo)
}

read_config

while getopts h:jm:st:u:w:v flag; do
	case "$flag" in
		h) host=$OPTARG ;;
		j) is_json="true" ;;
		m) message=$OPTARG ;;
		s) send_photo="true" ;;
		t) topic=$OPTARG ;;
		u) username=$OPTARG ;;
		w) password=$OPTARG ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$host" ]; then
	echo_error "MQTT broker host is not set"
	exit 1
fi

if [ -z "$port" ]; then
	echo_error "MQTT broker port is not set"
	exit 1
fi

if [ -z "$topic" ]; then
	echo_error "MQTT topic not found"
	exit 1
fi

if [ -z "$message" ]; then
	echo_error "MQTT message template not found"
	exit 1
fi

if [ "true" = "$send_photo" ] && [ -z "$topic_photo" ]; then
	echo_error "MQTT topic for sending snapshot not found in config"
	exit 1
fi

if [ -z "$client_id" ]; then
	client_id=$(hostname)
fi

message=$(date +"$message")

command="mosquitto_pub -h $host -p $port -i $client_id"

if [ "true" = "$verbose" ]; then
	command="$command -d"
fi

if [ -n "$username" ]; then
	command="$command -u $username"
fi

if [ -n "$password" ]; then
	command="$command -P $password"
fi

failed=0

if [ "true" = "$is_json" ]; then
	tmpfile=$(mktemp)
	echo "$message" > $tmpfile
	send_command="$command -t $topic -f $tmpfile"
	garbage="$garbage $tmpfile"
else
	send_command="$command -t $topic -m '$message'"
fi

if [ "true" = "$verbose" ]; then
	echo_command "$send_command"
fi

if ! sh -c "$send_command"; then
	echo_error "Failed to send MQTT message"
	failed=1
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	send_command="$command -t $topic_photo -f '$photo'"

	if [ "true" = "$verbose" ]; then
		echo_command "$send_command"
	fi

	if ! sh -c "$send_command"; then
		echo_error "Failed to send snapshot via MQTT"
		failed=1
	fi
fi

exit $failed
