#!/bin/env sh
# Sends data to ntfy.sh
# https://docs.ntfy.sh/publish/

. /usr/share/common
. /usr/share/send2common

domiain="ntfy"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-h host      NTFY server FQDN or IP address
	-u username  NTFY username
	-P password  NTFY password
	-T token     NTFY token
	-t topic     Topic
	-n title     Message title
	-m message   Message body
	-a URL       Attachment URL
	-c URL       Click URL
	-f file      Attach file
	-i URL       Icon URL
	-z N         Priority: 1-lowest, 5-highest
	-d N         Delay
	-S           Send photo
	-V           Send video
	-v           Verbose output
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	host=$(get_value host)
	port=$(get_value port)
	username=$(get_value username)
	password=$(get_value password)
	token=$(get_value token)
	message=$(get_value message)
	topic=$(get_value topic)
	title=$(get_value title)
	tags=$(get_value tags)
	icon=$(get_value icon)
	delay=$(get_value delay)
	prority=$(get_value priority)
	send_photo=$(get_value send_photo)
	attach=$(get_value attach)
	click=$(get_value click)
	filename=$(get_value filename)
	email=$(get_value email)
	call=$(get_value call)
	actions=$(get_value actions)
	twilio_token=$(get_value twilio_token)
}

read_config

while getopts h:p:u:P:T:m:n:t:i:z:d:a:c:f:SVv flag; do
	case "$flag" in
		h) host=$OPTARG ;;
		u) username=$OPTARG ;;
		P) password=$OPTARG ;;
		T) token=$OPTARG ;;
		m) message=$OPTARG ;;
		n) title=$OPTARG ;;
		t) topic=$OPTARG ;;
		i) icon=$OPTARG ;;
		z) priority=$OPTARG ;;
		d) delay==$OPTARG ;;
		a) attach=$OPTARG ;;
		c) click=$OPTARG ;;
		f) filename=$OPTARG ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

[ -z "$host" ] && host="ntfy.sh"
[ -z "$port" ] && port=80

if [ -z "$topic" ]; then
	echo_error "NTFY topic is not set"
	exit 1
fi

command="curl -X POST -H p:${priority:-3}"

if [ "true" = "$verbose" ]; then
	command="$command --verbose"
else
	command="$command --silent"
fi

if [ -n "$token" ]; then
	command="$command -H 'Authorization: Bearer $token'"
elif [ -n "$username" ] && [ -n "$password" ]; then
	command="$command -u $username:$password"
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	command="$command -T $photo -H 'Filename: $photo'"
fi

if [ -n "$filename" ] && [ -f "$filename" ]; then
	command="$command -T $filename -H 'Filename: $filename'"
fi

if [ -n "$message" ]; then
	message="$(date +"$message")"
	command="$command -H 'Message: $message'"
fi

#[ -n "$title" ] && command="$command -H 'Title: $title'"
#[ -n "$delay" ] && command="$command -H 'Delay: $delay'"
#[ -n "$tags" ] && command="$command -H 'Tags: $tags'"
#[ -n "$attach" ] && command="$command -H 'Attach: $attach'"
#[ -n "$click" ] && command="$command -H 'Click: $click'"
#[ -n "$icon" ] && command="$command -H 'Icon: $icon'"
#[ -n "$email" ] && command="$command -H 'Email: $email'"
#[ -n "$actions" ] && command="$command -H 'Actions: $actions'"
#[ -n "$call" ] && [ -n "$twilio_token" ] && command="$command -H 'Call: $call' -u :$twilio_token"

command="$command $host/$topic"

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send NTFY message"
	exit 1
fi

exit 0
