#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

domain="webhook"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-u url       Webhook URL
	-m message   Message to send to webhook
	-v           Verbose output
	-S           Send photo
	-V           Send video
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	url=$(get_value url)
	message=$(get_value message)
	send_photo=$(get_value send_photo)
	send_video=$(get_value send_video)
}

read_config

while getopts u:m:SVv flag; do
	case "$flag" in
		u) url=$OPTARG ;;
		m) message=$OPTARG ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		v) verbose="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$url" ]; then
	echo_error "Webhook URL not found"
	exit 1
fi

if [ "true" = "$verbose" ]; then
	command="$CURL --verbose"
else
	command="$CURL --silent"
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	command="$command -F 'image=@$photo'"
fi

if [ "true" = "$send_video" ]; then
	check_vbuffer
	inode=$(stat -c%i $VBUFFER_FILE)

	video1=$(copy_video)
	command="$command -F 'video1=@$video1'"

	while [ $inode -eq $(stat -c%i $VBUFFER_FILE) ]; do
		n=$((n + 1))
		if [ "$n" -ge 10 ]; then
			echo_error "Give up after $n attempts."
			exit 1
		fi
		sleep 1
	done

	video2=$(copy_video)
	command="$command -F 'video2=@$video2'"
fi

command="$command -F \"message=$message\""
command="$command --url \"$url\""

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send webhook message"
	exit 1
fi

exit 0
