#!/bin/env sh

. /usr/share/common
. /usr/share/send2common

domain="webhook"
config_file="/etc/send2.json"

show_help() {
	echo "Usage: $0 [options]
Where:
	-u url       Webhook URL
	-m message   Message to send to webhook
	-v           Verbose output
	-f file      Send file
	-S           Send photo
	-V           Send video
" >&2
	exit 0
}

read_config() {
	[ -f "$config_file" ] || return

	message=$(get_value message)
	url=$(get_value url)
}

read_config

while getopts f:m:u:vSV flag; do
	case "$flag" in
		m) message=$OPTARG ;;
		u) url=$OPTARG ;;
		v) verbose="true" ;;
		# sending a file from the command line disables sending photo
		# and video defined in config unless explicitly set so (-S/-V)
		f) file=$OPTARG; send_photo="false"; send_photo="false" ;;
		S) send_photo="true" ;;
		V) send_video="true" ;;
		*) show_help ;;
	esac
done

# use config settings only if not set from command line
if [ -z "$send_photo$send_video" ]; then
        send_photo=$(get_value send_photo)
        send_video=$(get_value send_video)
fi

if [ -z "$url" ]; then
	echo_error "Webhook URL not found"
	exit 1
fi

if [ "true" = "$verbose" ]; then
	command="$CURL --verbose"
else
	command="$CURL --silent"
fi

if [ -n "$file" ]; then
	command="$command -F 'file=@$file'"
fi

if [ "true" = "$send_photo" ]; then
	photo=$(copy_photo)
	command="$command -F 'image=@$photo'"
fi

if [ "true" = "$send_video" ]; then
	video=$(copy_video)
	command="$command -F 'video=@$video'"
fi

command="$command -F \"message=$message\""
command="$command --url \"$url\""

[ "true" = "$verbose" ] && echo_command "$command"

if ! sh -c "$command" >/dev/null; then
	echo_error "Failed to send webhook message"
	exit 1
fi

exit 0
