#!/bin/sh
# TTS client
set -eu

PLAY_BIN="/usr/sbin/play"
PORTAL_MODE_FLAG="/run/portal_mode"
CURL_BIN="/usr/bin/curl"
CURL_ARGS="--show-error --fail --connect-timeout 10 --max-time 30 --retry 3 --location --max-redirs 5"
TMP_FILE=""

cleanup() {
	if [ -n "$TMP_FILE" ] && [ -f "$TMP_FILE" ]; then
		rm -f "$TMP_FILE"
	fi
}

trap cleanup EXIT INT TERM

no_internet() {
	ping -c1 -W1 1.1.1.1 >/dev/null 2>&1 || return 0
	return 1
}

portal_is_up() {
	[ -f "$PORTAL_MODE_FLAG" ]
}

if [ -z "$1" ]; then
	echo "Usage: $0 \"<phrase to say>\"
Shortcuts:
	%ip     Tell IP address
	%time   Tell recent time
" >&2
	exit 1
fi

if no_internet; then
	if portal_is_up; then
		"$PLAY_BIN" /usr/share/sounds/configurationportalmode.opus
	else
		"$PLAY_BIN" /usr/share/sounds/configurationportalisdown.opus \
			/usr/share/sounds/pleasepowercycletorestart.opus
		exit 1
	fi
fi

case "$1" in
	%ip)
		iface="$(ip r | awk '/default/{print $5}' | uniq)"
		ipaddr=$(ip r | sed -nE "/$iface/s/.+src ([0-9\.]+).+?/\1/p" | uniq)
		phrase="IP address is $ipaddr" ;;
	%time)
		phrase="$(date)" ;;
	*)
		phrase="$*" ;;
esac

TMP_FILE="$(mktemp /tmp/tell.XXXXXX.opus)"
"$CURL_BIN" $CURL_ARGS --silent --get --url https://thingino.com/say2 \
	--data-urlencode q="$phrase" -o "$TMP_FILE"
"$PLAY_BIN" "$TMP_FILE"

exit 0
