LIBJUICE_VERSION = 1.7.0
LIBJUICE_SITE = $(call github,paullouisageneau,libjuice,v$(LIBJUICE_VERSION))
LIBJUICE_LICENSE = MIT
LIBJUICE_LICENSE_FILES = LICENSE

LIBJUICE_INSTALL_STAGING = YES

LIBJUICE_DEPENDENCIES =

$(eval $(cmake-package))
