#!/bin/sh

case "$(echo $0 | cut -d / -f 4)" in
	cli)
		yaml-cli -i /etc/majestic.yaml "$@"
		;;

	sensor_cli)
		sensor=$(fw_printenv -n sensor)
		if [ -z "$sensor" ]; then
			echo "Sensor is not defined in u-boot environment"
			exit 1
		fi
		yaml-cli -i /etc/sensor/${sensor}.yaml $@
		;;

	ipctool)
		IPCTOOL=/tmp/ipctool
		if [ ! -x $IPCTOOL ]; then
			curl -s -L -o $IPCTOOL https://github.com/OpenIPC/ipctool/releases/download/latest/ipctool-mips32
			chmod +x $IPCTOOL
			echo "The ipctool installed as remote GitHub plugin"
		fi
		$IPCTOOL $@
		;;

	*)
		;;
esac
