#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 <mmc port>" && exit 1

endpoint=/sys/devices/platform/jzmmc_v1.2.${1}/present

[ ! -f "$endpoint" ] && echo "No endpoint $endpoint" && exit 2

echo INSERT > $endpoint
exit 0
