#!/bin/sh
#
# OpenIPC.org | v.20220722
#

mpp=$(awk '/Version:/ {print $3,$4"]"}' /proc/umap/sys) || echo "unknown MPP"
soc=$(ipcinfo --chip-name)

PQL_URL="https://github.com/widgetii/pqtools/raw/master"
PQT_DL_URL="https://raw.githubusercontent.com/widgetii/pqtools/master"

case ${soc} in
	hi3516ev200 | hi3516ev300 | hi3516dv200 | hi3518ev300)
		pqtools_url="${PQL_URL}/hi3516ev300/PQTools.tgz"
		ittb_url="${PQT_DL_URL}/hi3516ev300/ittb_V1.0.1.2.tgz"
		ittb_folder="ittb_V1.0.1.2"
		;;
	gk7205v200 | gk7205v300)
		pqtools_url="${PQL_URL}/gk7205v200/PQTools.tgz"
		ittb_url="${PQT_DL_URL}/gk7205v200/ittb_V1.0.2.0.tgz"
		ittb_folder="ittb_V1.0.2.0"
		;;
	*)
		echo "${soc} is not supported"
		exit 1
		;;
esac

echo "SoC with ${mpp}"
echo "Download PQTools from ${pqtools_url}"

if [ ! -d /tmp/${ittb_folder} ]; then
	curl -s ${ittb_url} | gzip -d - | tar xvf - -C /tmp
fi

echo "Calibrate sensor"
cd /tmp/${ittb_folder}
./start.sh
