#!/bin/sh
# Controls system services

. /usr/share/common

if [ "$1" != "list" ] && [ "$#" -ne 2 ]; then
	echo "Usage: $0 <action> <servicename>
Where actions:
	start     Start the service
	stop      Stop the service
	restart   Restart the service
	reload    Reload the service
	force     Start the service even if disabled
	enable    Enable the service on boot
	disable   Disable the service on boot
	list      List all services
	status    Status of the service
" >&2
	exit 1
fi

VALID_ACTIONS="start stop restart reload enable disable list status force"

if echo "$VALID_ACTIONS" | grep -w -q "$1"; then
	ACTION=$1
	SERVICE=$2
else
	ACTION=$2
	SERVICE=$1
fi

SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)
if [ "list" != "$ACTION" ] && [ -z "$SCRIPT" ]; then
	echo_error "Service $SERVICE not found"
	exit 1
fi

case "$ACTION" in
	start | reload | restart | force)
		if ! $SCRIPT $ACTION; then
			echo_error "Failed to $ACTION $SERVICE"
			exit 1
		fi
		;;
	stop)
		# force stop action on a disabled script
		if ! sh -c "$SCRIPT $ACTION"; then
			echo_error "Failed to $ACTION $SERVICE"
			exit 1
		fi
		;;
	list)
		ls -1 /etc/init.d/[FKS][0-9][0-9]* | \
			awk -F/ '{gsub(/[FKS]\d{2}/,"",$4);print $4}' | sort
		;;
	enable)
		chmod +x $SCRIPT
		;;
	disable)
		chmod -x $SCRIPT
		;;
	status)
		case "$(stat -c%a $SCRIPT)" in
			755) echo "enabled" ;;
			644) echo "disabled" ;;
			*) echo "unknown" ;;
		esac
		;;
	*)
		echo_error "Invalid action: $ACTION"
		exit 1
		;;
esac

exit 0
