#!/bin/sh

show_help() {
	echo "Usage: $0 [OPTIONS]
  -n          Reset network config.
  -h          Show this help.
"
	exit 0
}

reset_network() {
	cp -f /rom/etc/network/interfaces /etc/network/interfaces
}

while getopts hn flag; do
	case ${flag} in
		n)
			reset_network
			;;
		h)
			show_help
			;;
	esac
done

exit 0
