#!/bin/sh

profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' /etc/os-release)

if [ -z "$profile" ]; then
	echo "Building profile is not set in /etc/os-release"
	exit 1
fi

case "$1" in
	full)
		mtd_dev="mtd6"
		fw_file="/thingino-${profile}.bin"
		;;
	part)
		mtd_dev="mtd5"
		fw_file="_update/thingino-${profile}-update.bin"
		;;
	*)
		echo "Usage: $0 [full|part]"
		exit 2
		;;
esac

if ! grep -q "$mtd_dev" /proc/mtd; then
	echo "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
	exit 3
fi

url="https://github.com/themactep/thingino-firmware/releases/download/firmware${fw_file}"
tmp_file=$(mktemp -u)
echo "Downloading firmware."
if curl -# -L -f -o $tmp_file $url; then
	echo "Performing upgrade. Do not turn off the power!"
	if flashcp -v $tmp_file /dev/$mtd_dev; then
		echo "Rebooting..."
		echo 1 > /proc/jz/watchdog/reset
	else
		echo "Upgrade failed!"
		echo "You have to perform a recovery flashing before rebooting the camera!"
		exit 13
	fi
else
	echo "Failed to download firmware from $url. Exiting."
	exit 4
fi

exit 0
