USBNET_VERSION = 1.0
USBNET_SITE_METHOD = local
USBNET_SITE = $(USBNET_PKGDIR)/files

ifeq ($(BR2_PACKAGE_USBNET_USB_DIRECT_NCM),y)
define USBNET_LINUX_CONFIG_FIXUPS_USB_DIRECT_NCM
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_LIBCOMPOSITE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_U_ETHER)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_F_NCM)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_G_NCM)
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_CDC_ETHER),y)
define USBNET_LINUX_CONFIG_FIXUPS_CDC_ETHER
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_NET_CDCETHER)
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_WWAN_SERIAL),y)
define USBNET_LINUX_CONFIG_FIXUPS_CDC_ETHER
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL_WWAN,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_SERIAL_OPTION,m)

####ADDITIONAL MODES FUTURE

#USBSERIAL:

#CONFIG_USB_SERIAL
#CONFIG_USB_SERIAL_GENERIC
#CONFIG_USB_SERIAL_OPTION
#CONFIG_USB_ACM

#RNDIS:

#CONFIG_USB_SERIAL
#CONFIG_USB_SERIAL_OPTION
#CONFIG_USB_USBNET
#CONFIG_USB_NET_CDCETHER

#PPP:

#CONFIG_USB_SERIAL
#CONFIG_USB_SERIAL_OPTION
#CONFIG_PPP
#CONFIG_PPP_FILTER
#CONFIG_PPP_MULTILINK
#CONFIG_PPP_BSDCOMP
#CONFIG_PPP_ASYNC
#CONFIG_PPP_SYNC_TTY
#CONFIG_PPP_DEFLATE

endef
define USBNET_INSTALL_TARGET_CMDS
	$(INSTALL) -m 755 -D $(USBNET_PKGDIR)/files/S38usbnet $(TARGET_DIR)/etc/init.d/S38usbnet
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_RNDIS),y)
define USBNET_LINUX_CONFIG_FIXUPS_RNDIS
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_SET_OPT,CONFIG_USB_NET_RNDIS_HOST,m)
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_ASIX),y)
define USBNET_LINUX_CONFIG_FIXUPS_ASIX
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_NET_AX8817X)
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_ASIX_179_178A),y)
define USBNET_LINUX_CONFIG_FIXUPS_ASIX_179_178A
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_NET_AX88179_178A)
endef
endif

ifeq ($(BR2_PACKAGE_USBNET_R8152),y)
define USBNET_LINUX_CONFIG_FIXUPS_R8152
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_USBNET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_RTL8152)
endef
endif

####################################################
#This is required for BR to successfully concatenate the kernel options when used with modules
define USBNET_LINUX_CONFIG_FIXUPS
	$(call USBNET_LINUX_CONFIG_FIXUPS_USB_DIRECT_NCM)
	$(call USBNET_LINUX_CONFIG_FIXUPS_CDC_ETHER)
	$(call BR2_PACKAGE_USBNET_WWAN_SERIAL)
	$(call USBNET_LINUX_CONFIG_FIXUPS_RNDIS)
	$(call USBNET_LINUX_CONFIG_FIXUPS_ASIX)
	$(call USBNET_LINUX_CONFIG_FIXUPS_ASIX_179_178A)
	$(call USBNET_LINUX_CONFIG_FIXUPS_R8152)
endef

$(eval $(generic-package))
