#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 OUTPUT_DIR" >&2
	exit 1
fi

output_dir=$1
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "${script_dir}/.." && pwd)
buildroot_dir="${repo_dir}/buildroot"
graphs_dir="${output_dir}/graphs"
show_info_json="${graphs_dir}/show-info.json"
host_graph_dot="${graphs_dir}/host-package-depends.dot"
host_graph_svg="${graphs_dir}/host-package-depends.svg"
host_graph_txt="${graphs_dir}/host-package-depends.txt"
summary_file="${graphs_dir}/build-info-summary.txt"

require_path() {
	path=$1
	label=$2

	if [ ! -e "$path" ]; then
		echo "Missing ${label}: ${path}" >&2
		exit 1
	fi
}

run_buildroot() {
	make -C "${buildroot_dir}" \
		BR2_EXTERNAL="${repo_dir}" \
		O="${output_dir}" \
		BR2_DL_DIR="${repo_dir}/dl" \
		"$@"
}

require_path "${buildroot_dir}/Makefile" "Buildroot checkout"
require_path "${output_dir}/.config" "Buildroot config"
mkdir -p "${graphs_dir}"

echo "Generating package dependency graph..."
run_buildroot BR2_GRAPH_OUT=svg graph-depends

if [ -f "${output_dir}/build/build-time.log" ]; then
	echo "Generating build-time graphs..."
	run_buildroot BR2_GRAPH_OUT=png graph-build
else
	echo "Skipping build-time graphs: missing ${output_dir}/build/build-time.log" >&2
fi

if [ -d "${output_dir}/target" ]; then
	echo "Generating filesystem size graph..."
	run_buildroot BR2_GRAPH_OUT=png BR2_GRAPH_SIZE_OPTS=--biggest-first graph-size
else
	echo "Skipping filesystem size graph: missing ${output_dir}/target" >&2
fi

echo "Exporting package metadata..."
run_buildroot -s --no-print-directory show-info > "${show_info_json}"

echo "Generating host package dependency graph..."
python3 - <<'PY' "${show_info_json}" "${host_graph_dot}" "${host_graph_txt}" "${summary_file}"
import json
import sys
from collections import defaultdict
from pathlib import Path

show_info_path = Path(sys.argv[1])
dot_path = Path(sys.argv[2])
txt_path = Path(sys.argv[3])
summary_path = Path(sys.argv[4])
data = json.loads(show_info_path.read_text())


def pkg_type(pkg):
    return data[pkg].get("type", "target")


incoming = defaultdict(set)
outgoing = defaultdict(set)

for pkg, meta in data.items():
    for dep in meta.get("dependencies", []):
        if dep not in data or pkg_type(dep) != "host":
            continue
        incoming[dep].add(pkg)
        outgoing[pkg].add(dep)

source_nodes = set(outgoing)
host_nodes = set(incoming)

lines = [
    "digraph host_package_depends {",
    '  rankdir=LR;',
    '  graph [fontname="Helvetica", bgcolor="white"];',
    '  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=10];',
    '  edge [color="#666666"];',
]

for pkg in sorted(source_nodes | host_nodes):
    kind = pkg_type(pkg)
    if kind == "host":
        fill = "#ffd6cc"
    elif kind == "rootfs":
        fill = "#d6f5d6"
    else:
        fill = "#e6e6e6"
    lines.append(f'  "{pkg}" [fillcolor="{fill}"];')

for host, pkgs in sorted(incoming.items()):
    for pkg in sorted(pkgs):
        lines.append(f'  "{pkg}" -> "{host}";')

lines.append("}")
dot_path.write_text("\n".join(lines) + "\n")

txt_lines = [
    "Host package reverse dependencies",
    "",
    f"Host packages: {len(host_nodes)}",
    f"Packages that directly pull host packages: {len(source_nodes)}",
    "",
]

for host in sorted(host_nodes):
    txt_lines.append(f"{host}:")
    for pkg in sorted(incoming[host]):
        txt_lines.append(f"  - {pkg}")
    txt_lines.append("")

txt_path.write_text("\n".join(txt_lines))

summary_lines = [
    "Build analysis artifacts",
    "",
    "Generated by scripts/generate_build_info.sh",
    "",
    f"show-info JSON: {show_info_path.name}",
    "dependency graph: graph-depends.svg",
    "host package graph: host-package-depends.svg",
    "host package summary: host-package-depends.txt",
]

if (show_info_path.parent / "build.hist-duration.png").exists():
    summary_lines.append("build-time graphs: build.hist-*.png, build.pie-*.png")
else:
    summary_lines.append("build-time graphs: skipped")

if (show_info_path.parent / "graph-size.png").exists():
    summary_lines.append("filesystem size graph: graph-size.png")
    summary_lines.append("filesystem size CSVs: package-size-stats.csv, file-size-stats.csv")
else:
    summary_lines.append("filesystem size graph: skipped")

summary_lines.extend(
    [
        "",
        "Most shared host packages:",
    ]
)

for host, pkgs in sorted(incoming.items(), key=lambda item: (-len(item[1]), item[0]))[:10]:
    summary_lines.append(f"  - {host}: {len(pkgs)} direct dependents")

summary_lines.append("")
summary_lines.append("Packages with the most direct host dependencies:")

for pkg, deps in sorted(outgoing.items(), key=lambda item: (-len(item[1]), item[0]))[:10]:
    summary_lines.append(f"  - {pkg}: {len(deps)} host dependencies")

summary_path.write_text("\n".join(summary_lines) + "\n")
PY

dot -Tsvg "${host_graph_dot}" -o "${host_graph_svg}"

echo "Build analysis artifacts:"
for artifact in \
	"${graphs_dir}/graph-depends.svg" \
	"${graphs_dir}/build.hist-duration.png" \
	"${graphs_dir}/build.pie-packages.png" \
	"${graphs_dir}/graph-size.png" \
	"${graphs_dir}/package-size-stats.csv" \
	"${graphs_dir}/file-size-stats.csv" \
	"${show_info_json}" \
	"${host_graph_svg}" \
	"${host_graph_txt}" \
	"${summary_file}"; do
	if [ -e "${artifact}" ]; then
		printf '  - %s\n' "${artifact}"
	fi
done
