#!/bin/bash
# shellcheck disable=SC2155
#
# prosody-test.sh — spin up a local Prosody XMPP server for testing send2xmpp.
#
# Creates a throwaway Prosody container with BOSH (XEP-0124/0206) enabled,
# internal_plain auth and two test accounts, then prints the send2xmpp
# configuration to use from a camera.
#
# Usage:
#   scripts/prosody-test.sh [start|stop|restart|status] [options]
#
# Options:
#   -n NAME        container name        (default: prosody-test)
#   -p PORT        BOSH HTTP port        (default: 5280)
#   -d DOMAIN      virtual host domain   (default: test.local)
#   -c JID         camera account        (default: camera@<domain>)
#   -P PASS        camera password       (default: camera123)
#   -r JID         recipient account     (default: paul@<domain>)
#   -R PASS        recipient password    (default: paul123)
#   -f FILE        write camera-side send2.json snippet to FILE (default: print)
#
# Examples:
#   scripts/prosody-test.sh start                 # start + provision + print config
#   scripts/prosody-test.sh start -p 5281 -d xmpp.lan
#   scripts/prosody-test.sh stop                  # stop (keep data)
#   scripts/prosody-test.sh rm                    # stop and delete container+volume

set -eu

# --- container engine detection (same as build-container.sh) ---------------
if command -v podman >/dev/null 2>&1; then
	CE="podman"
elif command -v docker >/dev/null 2>&1; then
	CE="docker"
else
	echo "ERROR: neither podman nor docker found" >&2
	exit 1
fi

# --- defaults ---------------------------------------------------------------
NAME="prosody-test"
PORT=5280
DOMAIN="test.local"
CAMERA_JID="camera@${DOMAIN}"
CAMERA_PASS="camera123"
RECIPIENT_JID="paul@${DOMAIN}"
RECIPIENT_PASS="paul123"
OUT_FILE=""
IMAGE="docker.io/prosody/prosody"
ACTION="start"

usage() {
	sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
	exit 1
}

while [ $# -gt 0 ]; do
	case "$1" in
		start | stop | restart | status | rm) ACTION="$1" ;;
		-n) NAME="$2"; shift ;;
		-p) PORT="$2"; shift ;;
		-d) DOMAIN="$2"; shift ;;
		-c) CAMERA_JID="$2"; shift ;;
		-P) CAMERA_PASS="$2"; shift ;;
		-r) RECIPIENT_JID="$2"; shift ;;
		-R) RECIPIENT_PASS="$2"; shift ;;
		-f) OUT_FILE="$2"; shift ;;
		-h | --help) usage ;;
		*) echo "Unknown option: $1" >&2; usage ;;
	esac
	shift
done

VOLUME="${NAME}-data"
CFG_DIR="${XDG_RUNTIME_DIR:-/tmp}/${NAME}-etc"

make_config() {
	cat > "$CFG_DIR/prosody.cfg.lua" <<EOF
-- generated by scripts/prosody-test.sh — throwaway test server for send2xmpp
admins = {}
modules_enabled = {
    "roster";
    "saslauth";
    "tls";
    "disco";
    "ping";
    "bosh";
}
allow_registration = false
authentication = "internal_plain"
storage = "internal"
http_ports = { $PORT }
https_ports = { }
pidfile = "/tmp/prosody.pid"
log = { { levels = { min = "info" }, to = "console" } }

-- Plain HTTP BOSH for camera testing (no TLS in the container).
c2s_require_encryption = false
s2s_require_encryption = false
allow_unencrypted_plain_auth = true
consider_bosh_secure = true

VirtualHost "$DOMAIN"
EOF
}

start() {
	echo "==> [$CE] creating Prosody test server '$NAME' (domain $DOMAIN, BOSH :$PORT)"
	"$CE" pull "$IMAGE" >/dev/null 2>&1 || true

	mkdir -p "$CFG_DIR"
	make_config
	"$CE" volume create "$VOLUME" >/dev/null 2>&1 || true
	"$CE" rm -f "$NAME" >/dev/null 2>&1 || true

	"$CE" run -d --name "$NAME" \
		-p "${PORT}:${PORT}" \
		-v "$CFG_DIR/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro" \
		-v "$VOLUME:/var/lib/prosody" \
		"$IMAGE" >/dev/null

	# wait for the server to come up
	for _ in $(seq 1 20); do
		"$CE" ps --format '{{.Status}}' -f "name=$NAME" 2>/dev/null | grep -q Up && break
		sleep 1
	done
	if ! "$CE" ps --format '{{.Status}}' -f "name=$NAME" 2>/dev/null | grep -q Up; then
		echo "ERROR: container failed to start" >&2
		"$CE" logs "$NAME" 2>&1 | tail -20 >&2
		exit 1
	fi

	provision
	print_config
	echo
	echo "==> Server ready. Point send2xmpp at the BOSH URL below (host IP :$PORT)."
}

provision() {
	local cam_user="${CAMERA_JID%%@*}" cam_domain="${CAMERA_JID##*@}"
	local rec_user="${RECIPIENT_JID%%@*}"
	"$CE" exec "$NAME" prosodyctl register "$cam_user" "$cam_domain" "$CAMERA_PASS" >/dev/null
	"$CE" exec "$NAME" prosodyctl register "$rec_user" "$cam_domain" "$RECIPIENT_PASS" >/dev/null
	echo "==> registered $CAMERA_JID and $RECIPIENT_JID"
}

print_config() {
	local host_ip
	host_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
	[ -n "$host_ip" ] || host_ip="<THIS-HOST-IP>"
	local snippet
	snippet=$(cat <<EOF
# send2xmpp configuration for this test server
# /etc/send2xmpp.conf (or the WebUI Services -> XMPP page / send2.json "xmpp" section)
XMPP_JID="$CAMERA_JID"
XMPP_PASSWORD="$CAMERA_PASS"
XMPP_RECIPIENT="$RECIPIENT_JID"
XMPP_BOSH_URL="http://$host_ip:$PORT/http-bind"
XMPP_RESOURCE="thingino"
XMPP_TLS_VERSION=""
EOF
)
	if [ -n "$OUT_FILE" ]; then
		printf '%s\n' "$snippet" > "$OUT_FILE"
		echo "==> config written to $OUT_FILE"
	else
		printf '%s\n' "$snippet"
	fi
}

stop() {
	"$CE" stop "$NAME" >/dev/null 2>&1 && echo "==> stopped $NAME (data kept in volume $VOLUME)" || echo "==> $NAME not running"
}

rm() {
	"$CE" rm -f "$NAME" >/dev/null 2>&1 || true
	"$CE" volume rm "$VOLUME" >/dev/null 2>&1 || true
	echo "==> removed $NAME and volume $VOLUME"
}

status() {
	"$CE" ps -a --format '{{.Names}}\t{{.Status}}' | grep "^$NAME" || echo "==> $NAME not found"
}

case "$ACTION" in
	start) start ;;
	stop) stop ;;
	restart) stop; start ;;
	rm) rm ;;
	status) status ;;
esac
