LIBDATACHANNEL_VERSION = 0.24.5
LIBDATACHANNEL_SITE = $(call github,paullouisageneau,libdatachannel,v$(LIBDATACHANNEL_VERSION))
LIBDATACHANNEL_INSTALL_STAGING = YES
LIBDATACHANNEL_INSTALL_TARGET = YES
LIBDATACHANNEL_LICENSE = MPL-2.0
LIBDATACHANNEL_LICENSE_FILES = LICENSE

# Configure SSL/TLS library - prefer OpenSSL if available
ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBDATACHANNEL_DEPENDENCIES = usrsctp libjuice libsrtp plog openssl host-pkgconf
LIBDATACHANNEL_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DUSE_MBEDTLS=OFF \
	-DUSE_GNUTLS=OFF \
	-DUSE_NICE=OFF \
	-DUSE_SYSTEM_JUICE=ON \
	-DUSE_SYSTEM_USRSCTP=ON \
	-DUSE_SYSTEM_SRTP=ON \
	-DUSE_SYSTEM_PLOG=ON \
	-DUSE_SYSTEM_JSON=OFF \
	-DNO_WEBSOCKET=ON \
	-DNO_TESTS=ON \
	-DNO_EXAMPLES=ON
else
LIBDATACHANNEL_DEPENDENCIES = usrsctp libjuice libsrtp plog mbedtls
LIBDATACHANNEL_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DUSE_MBEDTLS=ON \
	-DUSE_GNUTLS=OFF \
	-DUSE_NICE=OFF \
	-DUSE_SYSTEM_JUICE=ON \
	-DUSE_SYSTEM_USRSCTP=ON \
	-DUSE_SYSTEM_SRTP=ON \
	-DUSE_SYSTEM_PLOG=ON \
	-DUSE_SYSTEM_JSON=OFF \
	-DNO_WEBSOCKET=ON \
	-DNO_TESTS=ON \
	-DNO_EXAMPLES=ON
endif

$(eval $(cmake-package))
