LIBDATACHANNEL_VERSION = v0.24.0
LIBDATACHANNEL_SITE = https://github.com/paullouisageneau/libdatachannel
LIBDATACHANNEL_SITE_METHOD = git
LIBDATACHANNEL_GIT_SUBMODULES = YES
LIBDATACHANNEL_INSTALL_STAGING = YES
LIBDATACHANNEL_INSTALL_TARGET = YES
LIBDATACHANNEL_LICENSE = MPL-2.0
LIBDATACHANNEL_LICENSE_FILES = LICENSE

# Configure SSL/TLS library - prefer OpenSSL if available
ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBDATACHANNEL_DEPENDENCIES = usrsctp libjuice openssl host-pkgconf
LIBDATACHANNEL_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DUSE_MBEDTLS=OFF \
	-DUSE_GNUTLS=OFF \
	-DUSE_NICE=OFF \
	-DUSE_SYSTEM_JUICE=ON \
	-DUSE_SYSTEM_USRSCTP=ON \
	-DUSE_SYSTEM_JSON=OFF \
	-DUSE_SYSTEM_PLOG=OFF \
	-DNO_WEBSOCKET=ON \
	-DNO_TESTS=ON \
	-DNO_EXAMPLES=ON \
	-DBUILDROOT_ALLOW_IN_SOURCE=ON
else
LIBDATACHANNEL_DEPENDENCIES = usrsctp libjuice mbedtls
LIBDATACHANNEL_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DUSE_MBEDTLS=ON \
	-DUSE_GNUTLS=OFF \
	-DUSE_NICE=OFF \
	-DUSE_SYSTEM_JUICE=ON \
	-DUSE_SYSTEM_USRSCTP=ON \
	-DUSE_SYSTEM_JSON=OFF \
	-DUSE_SYSTEM_PLOG=OFF \
	-DNO_WEBSOCKET=ON \
	-DNO_TESTS=ON \
	-DNO_EXAMPLES=ON \
	-DBUILDROOT_ALLOW_IN_SOURCE=ON
endif

$(eval $(cmake-package))
