PLOG_VERSION = 1.1.11
PLOG_SITE = $(call github,SergiusTheBest,plog,$(PLOG_VERSION))
PLOG_LICENSE = MIT
PLOG_LICENSE_FILES = LICENSE
PLOG_INSTALL_STAGING = YES
PLOG_INSTALL_TARGET = NO

PLOG_CONF_OPTS = -DPLOG_INSTALL=ON -DPLOG_BUILD_SAMPLES=OFF -DPLOG_BUILD_TESTS=OFF

$(eval $(cmake-package))
