#!/bin/sh

PIDFILE="/var/run/odhcp6c_$IFACE.pid"

if [ ! -d "/sys/class/net/$IFACE" ]; then
	echo -c 160 -e "$IFACE not found" >&2
	exit 0
fi

if [ "$(sysctl -n net.ipv6.conf.all.disable_ipv6)" -ne 0 ]; then
	echo -c 160 -e "IPv6 disabled globally" >&2
	exit 0
fi

if [ "true" != "$IF_DHCP_V6_ENABLED" ]; then
	echo -c 160 -e "DHCPv6 disabled on $IFACE" >&2
	exit 0
fi

echo -c 240 -e "- DHCPv6 on $IFACE"

start_post_up() {
	echo -c 15 "Starting odhcp6c on $IFACE"

	TMP_LOG="/tmp/odhcp6c.log"

	/sbin/odhcp6c -d -v -p "$PIDFILE" -t120 "$IFACE"
}

stop_pre_down() {
	echo -c 15 "Stopping odhcp6c on $IFACE"

	if [ -f "$PIDFILE" ]; then
		pid=$(cat $PIDFILE)
		echo -c 240 -e "- Running service with PID $pid"

		echo -c 101 -e "kill -9 $pid" >&2
		kill -9 $pid

		echo -c 101 -e "rm -f $PIDFILE" >&2
		rm -f "$PIDFILE"
	else
		echo -c 240 -e "- Nothing to stop"
	fi
}

case "$MODE" in
	start)
		case "$PHASE" in
			post-up)
				start_post_up
				;;
		esac
		;;

	stop)
		case "$PHASE" in
			pre-down)
				stop_pre_down
				;;
		esac
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 0
		;;
esac

exit 0
