WIFI_ATBM6441_SITE_METHOD = local
WIFI_ATBM6441_SITE = $(BR2_EXTERNAL_THINGINO_PATH)/package/wifi-atbm6441/files/atbm6441_sdk
WIFI_ATBM6441_VERSION = local

WIFI_ATBM6441_LICENSE = Proprietary
WIFI_ATBM6441_REDISTRIBUTE = NO

WIFI_ATBM6441_DEPENDENCIES = linux

ATBM6441_MODULE_NAME = atbm6441_wifi_sdio
ATBM6441_MODULE_OPTS = atbm_printk_mask=0

WIFI_ATBM6441_KERN_LOCALVER = $(call qstrip,$(shell \
	awk -F= '/^CONFIG_LOCALVERSION=/ {v=$$2} END {print v}' \
		$(LINUX_DIR)/.config 2>/dev/null))

define WIFI_ATBM6441_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC)
	$(call KCONFIG_SET_OPT,CONFIG_JZMMC_V12,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1_PB_4BIT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC1_FORCE_1BIT)
	$(call KCONFIG_SET_OPT,CONFIG_MMC1_MAX_FREQ,48000000)
	# SD card slot on MSC0 (PB bank, like other T23 boards incl. jooan_a6m).
	# Card-detect GPIO 61 is passed on the kernel cmdline (jzmmc built-in).
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC0)
	$(call KCONFIG_ENABLE_OPT,CONFIG_JZMMC_V12_MMC0_PB_4BIT)
	$(call KCONFIG_SET_OPT,CONFIG_MMC0_MAX_FREQ,24000000)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
	$(call KCONFIG_ENABLE_OPT,CONFIG_BUG)
	$(call KCONFIG_DISABLE_OPT,CONFIG_DYNAMIC_DEBUG)
endef

define WIFI_ATBM6441_BUILD_CMDS
	# Build using Makefile.build (CONFIG_HERA=y, SDIO_BUS=y hardcoded)
	# Firmware download disabled (firmware lives in MCU NVM)
	# ATBM_WIFI_PLATFORM=22 = Ingenic T31/T40 (same SDIO controller, uses jzmmc_manual_detect)
	$(MAKE) -C $(@D) -f $(@D)/Makefile.build \
		ARCH=mips \
		CROSS_COMPILE=$(TARGET_CROSS) \
		KDIR=$(LINUX_DIR) \
		MODULES_NAME=atbm6441_wifi_sdio \
		ATBM_WIFI__EXT_CCFLAGS="-DATBM_WIFI_PLATFORM=22 -DPLATFORM_INGENIC_T31=22"
endef

define WIFI_ATBM6441_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0644 $(@D)/hal_apollo/atbm6441_wifi_sdio.ko \
		$(TARGET_DIR)/usr/lib/modules/3.10.14$(WIFI_ATBM6441_KERN_LOCALVER)/extra/atbm6441_wifi_sdio.ko
endef

$(eval $(generic-package))
