#!/bin/sh

OS_RELEASE_FILE="/etc/os-release"

start() {
	echo -c 15 "Setting initial system time"

	if [ ! -f "$OS_RELEASE_FILE" ]; then
		echo "No release file found, not setting system clock" >&2
		exit 1
	fi

	if date -u -s "@$(awk -F'=' '/^TIME_STAMP/{print $2}' "$OS_RELEASE_FILE")" >/dev/null; then
		echo "$(date) (fail-safe)"
	else
		echo "Failed to set time" >&2
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
