#!/bin/sh
# shellcheck disable=SC1090

# shellcheck source=/dev/null
. /etc/init.d/lib-log

USB_SCRIPT="/etc/init.d/F02failsafe-usb"
OS_RELEASE_FILE="/etc/os-release"

usb_console=$(jct /etc/thingino.json get usb_console 2>/dev/null || fw_printenv -n usb_console)

start() {
	if [ "true" = "$usb_console" ] && [ -f "$USB_SCRIPT" ]; then
		exit 0
	fi

	# Always enter failsafe if enable_failsafe is true
	if [ "true" = "$(fw_printenv -n enable_failsafe 2>/dev/null)" ]; then
		log -c 118 "Automatically entering failsafe mode..."
		touch /tmp/.fs
		. /etc/profile
		exec setsid /sbin/getty -n -l /bin/sh -L console 0 vt100
		return
	fi

	echo
	log -c 104 "Press the [f] key to enter failsafe mode"
	echo

	stty -icanon min 0 time 20 -echo
	key=$(dd bs=1 count=1 2>/dev/null)
	stty sane

	if [ "f" = "$key" ]; then
		touch /tmp/.fs
		. /etc/profile
		log -c 118 "Failsafe mode..."
		exec setsid /sbin/getty -n -l /bin/sh -L console 0 vt100
	fi

	if [ -f "$OS_RELEASE_FILE" ]; then
		. "$OS_RELEASE_FILE"
		log -c 208 "Thingino firmware built for $IMAGE_ID"
		log -c 208 "[$BUILD_ID]"
	fi

	/etc/init.d/rcS
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		true
		;;
	*)
		true
		;;
esac

exit 0
