#!/bin/sh

get_wd_device() {
	jct /dev/thingino.json get watchdog.device 2>/dev/null ||
		fw_printenv -n watchdog_device
}

get_wd_enabled() {
	jct /dev/thingino.json get watchdog.enabled 2>/dev/null ||
		fw_printenv -n watchdog_enabled
}

get_wd_timeout() {
	jct /dev/thingino.json get watchdog.timeout 2>/dev/null ||
		fw_printenv -n watchdog_timeout
}

watchdog_device=$(get_wd_device)
watchdog_enabled=$(get_wd_enabled)
watchdog_timeout=$(get_wd_timeout)

DAEMON="/usr/sbin/watchdog"
DAEMON_ARGS="-T ${watchdog_timeout:-60} ${watchdog_device:-/dev/watchdog}"
PIDFILE="/var/run/watchdog.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo -c 15 "Starting watchdog"

	if [ "false" = "$watchdog_enabled" ]; then
		echo "$DAEMON is disabled" >&2
		exit 1
	fi

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo -c 15 "Stopping watchdog"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop | kill)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
