#!/bin/sh
# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.

for i in $(ls -r /etc/init.d/S??*); do

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set stop
				/bin/sh -c ". $i" 2>&1 | tee >(logger -t $i)
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			/bin/sh -c "$i stop" 2>&1 | tee >(logger -t $i)
			;;
	esac
done
