#!/bin/sh

# Set up the timezone
TZCODE_FILE="/etc/TZ"
if [ -s "$TZCODE_FILE" ]; then
	TZ="$(cat $TZCODE_FILE)"
	export TZ
else
	echo -c 240 -e "- Cannot find $TZCODE_FILE"
fi

# Run init scripts in numerical order
for i in $(find /etc/init.d/ -name "S*" -executable | sort -n); do
	/bin/sh -c "$i start"
done

# stop blinking
rm /run/ledd/*

exit 0
