#!/bin/sh
# Find the first available indicator LED and start blinking

THINGNIO_CONF="/etc/thingino.json"

# order: blue, green, white, yellow, red
for color in "b g w y r"; do
	PIN=$(jct "$THINGINO_CONF" "get.gpio.led_$color.pin" 2>/dev/null)
	if [ -n "$PIN"]; then
		echo "1000" >"/run/ledd/$PIN"
		exit 0
	fi
done

echo -c 160 "No LED indicator GPIO found."

exit 1
