#!/bin/sh
# Find the first available indicator LED and start blinking

# order: blue, green, white, yellow, violet, red
for color in b g w y v r; do
	if [ -d "/sys/class/leds/led_$color" ]; then
		[ -w "/sys/class/leds/led_$color/trigger" ] && printf 'timer\n' >"/sys/class/leds/led_$color/trigger"
		[ -w "/sys/class/leds/led_$color/delay_on" ] && printf '1000\n' >"/sys/class/leds/led_$color/delay_on"
		[ -w "/sys/class/leds/led_$color/delay_off" ] && printf '1000\n' >"/sys/class/leds/led_$color/delay_off"
		exit 0
	fi
done

echo -c 160 "No LED indicator GPIO found."

exit 1
