#!/bin/sh

# shellcheck source=/dev/null
. /etc/init.d/lib-log

start() {
	log -c 15 "Applying sysctl settings"

	if sysctl -q -p; then
		log -c 240 -e "- Sysctl settings applied"
	else
		log -c 160 -e "Failed to apply sysctl settings" >&2
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
