#!/bin/sh

start() {
	echo -c 15 "Applying sysctl settings"

	if sysctl -q -p; then
		echo "Sysctl settings applied"
	else
		echo "Failed to apply sysctl settings" >&2
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
