#!/bin/sh

json_get() {
	local key="$1" value="$2"
	jct /etc/thingino.json get "$key" 2>/dev/null || printf '%s' "$value"
}

DAEMON="syslogd"
DAEMON_ARGS="-n -C64 -S -t -D $RSYSLOG_ADDRESS"
RSYSLOG_CONFIG_DOMAIN="rsyslog"

# -n              Run in foreground
# -R HOST[:PORT]  Log to HOST:PORT (default PORT:514)
# -L              Log locally and via network (default is network only if -R)
# -C[size_kb]     Log to shared mem buffer (use logread to read it)
# -O FILE         Log to FILE (default: /var/log/messages, stdout if -)
# -s SIZE         Max size (KB) before rotation (default 200KB, 0=off)
# -b N            N rotated logs to keep (default 1, max 99, 0=purge)
# -l N            Log only messages more urgent than prio N (1-8)
# -S              Smaller output
# -t              Strip client-generated timestamps
# -D              Drop duplicates

PIDFILE="/run/$DAEMON.pid"

. /usr/share/common

start() {
	echo_title "Starting syslogd"

	rsyslog_enabled=$(json_get rsyslog.enabled "false")
	rsyslog_host=$(json_get rsyslog.host "$rsyslog_host")
	rsyslog_port=$(json_get rsyslog.port 514)
	rsyslog_file=$(json_get rsyslog.file "false")
	rsyslog_local=$(json_get rsyslog.local "$rsyslog_file")

	if [ -z "$rsyslog_host" ]; then
		echo_warning "Remote logging not configured"
	elif [ "true" != "$rsyslog_enabled" ]; then
		echo_warning "Remote logging disabled"
	else
		echo_info "Adding remote logging to $rsyslog_host:${rsyslog_port}"
		DAEMON_ARGS="$DAEMON_ARGS -R $rsyslog_host:${rsyslog_port}"
	fi

	if [ "true" = "$rsyslog_local" ] || [ "true" = "$rsyslog_file" ]; then
		echo_info "Adding local logging"
		DAEMON_ARGS="$DAEMON_ARGS -L"
	fi

	start_daemon
}

stop() {
	echo_title "Stopping syslogd"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
