#! /bin/sh
# shellcheck disable=SC2086

# shellcheck source=/dev/null
. /etc/init.d/lib-log

DAEMON="$(command -v seedrng 2>/dev/null || echo /sbin/seedrng)"
DAEMON_ARGS="-d /etc/seedrng"
PIDFILE="/run/seedrng.pid"

start_daemon() {
	if [ ! -x "$DAEMON" ]; then
		echo "seedrng not installed"
		return 1
	fi

	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	log -c 15 "Starting seedrng"

	start_daemon
}

stop() {
	log -c 15 "Stopping seedrng"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
