#!/bin/sh

# shellcheck source=/dev/null
. /etc/init.d/lib-log

start() {
	log -c 15 "Setting timezone"

	name=$(cat /etc/timezone 2>/dev/null)
	[ -n "$name" ] || name="Etc/GMT"
	log -c 240 -e "- Timezone name: $name"

	timectl refresh
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
