#!/bin/sh

# shellcheck source=/dev/null
. /etc/init.d/lib-log

RESOLV_DEFAULT_FILE="/etc/default/resolv.conf"
RESOLV_WORKING_FILE="/tmp/resolv.conf"

start() {
	log -c 15 "Configuring DNS"

	if [ -f "$RESOLV_DEFAULT_FILE" ]; then
		cat "$RESOLV_DEFAULT_FILE" >"$RESOLV_WORKING_FILE"
		log -c 240 -e "- Using default DNS servers"
	else
		log -c 240 -e "- No static DNS servers found"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
