#!/bin/sh

start() {
	echo -n "Starting ircut: "
	ircut ~ >/dev/null 2>&1
	sleep 0.5
	ircut ~ >/dev/null 2>&1

	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
esac

exit 0
