#!/bin/sh

SOC_FAMILY=$(/usr/sbin/soc -f)
SOC_MODEL=$(/usr/sbin/soc -m)

MMC_MODULE="jzmmc_v12"

MMC_GPIO_CD=$(fw_printenv -n gpio_mmc_cd)
MMC_GPIO_PWR=$(fw_printenv -n gpio_mmc_power)

# Default CD-PIN for Ingenic PB27 (GPIO59)
[ -z "$MMC_GPIO_CD" ] && MMC_GPIO_CD="59"

set_gpios() {
	# Set addtional MMC GPIOs
	# This needs to run AFTER the driver has been loaded for the sd card to mount during boot
	if [ ${#MMC_GPIO_PWR} -eq 3 ] && [ "${MMC_GPIO_PWR%[oO]}" != "$MMC_GPIO_PWR" ]; then
		case "${MMC_GPIO_PWR#??}" in
			"O") gpio set ${MMC_GPIO_PWR%[oO]} ;;
			"o") gpio clear ${MMC_GPIO_PWR%[oO]} ;;
		esac
	fi
}

start() {
	echo -n "Starting MMC: "

	MMC_PARAM="cd_gpio_pin=$MMC_GPIO_CD"

	# Check if MDIO directory exists
	if [ -d /proc/jz/mdio ]; then
		echo -n "/proc/jz/mdio directory exists, MSC1 disabled... "
		load_module
	else
		case "$SOC_FAMILY" in
			t10 | t20 | t21 | t30 | t40 | t41)
				# do nothing
				;;
			t23)
				echo "Unsupported: T23"
				exit 1
				;;
			t31)
				if [ "$SOC_MODEL" = "t31a" ] || [ "$SOC_MODEL" = "t31al" ]; then
					echo "Skipping GPIO setup for $SOC_MODEL"
					return 1
				else
					gpio-diag pb08 func 1 drive 2
					gpio-diag pb09 func 1 drive 1
					gpio-diag pb10 func 1 drive 1
					gpio-diag pb11 func 1 drive 1
					gpio-diag pb13 func 1 drive 1
					gpio-diag pb14 func 1 drive 1
				fi
				;;
			*)
				echo "Unsupported SOC type: $SOC_FAMILY"
				exit 1
				;;
		esac
	load_module
	fi
}

load_module() {
	if grep -q "$MMC_MODULE" /proc/modules; then
		echo "$MMC_MODULE is already loaded"
		exit 1
	else
		if modprobe $MMC_MODULE ${MMC_PARAM}; then
			echo "OK"
			set_gpios
		else
			echo "FAIL"
			exit 1
		fi
	fi
}

case "$1" in
	start)
		$1
		;;
	stop)
		true
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
esac

exit 0
