#!/bin/sh

NAME="rngd"
DAEMON="/usr/sbin/${NAME}"
DAEMON_ARGS="-r /dev/urandom"

start() {
	printf "Starting ${NAME}: "
	start-stop-daemon -S -q -x "${DAEMON}" -- ${DAEMON_ARGS}
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping ${NAME}: "
	if start-stop-daemon -K -q -x $DAEMON; then
		rm -f "${PID_FILE}"
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start | stop)
		$1
		;;

	restart | reload)
		stop
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
