#!/bin/sh

case "$1" in
	start)
		echo -n "Starting mdev: "
		echo /sbin/mdev > /proc/sys/kernel/hotplug
		/sbin/mdev -s
		status=$?
		if [ "$status" -eq 0 ]; then
				echo "OK"
		else
				echo "FAIL"
		fi
		return "$status"
		;;

	stop | restart | reload)
		true
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit $?
