#!/bin/sh

MDEV="/sbin/mdev"

start() {
	echo -c 15 "Configuring mdev"

	if [ -w /proc/sys/kernel/hotplug ]; then
		echo "$MDEV" >/proc/sys/kernel/hotplug
	fi
	$MDEV -s
}

case "$1" in
	start)
		start
		;;
	stop)
		true
		;;
	restart)
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
