#!/bin/sh

. /usr/share/common

NFS_MOUNT="/mnt/nfs"

nfs_share="$(jct /etc/thingino.json get nfs_share 2>/dev/null)"

start() {
	echo_title "Mount $NFS_MOUNT"

	if [ -z "$nfs_share" ]; then
		echo_info "Mount share is not set"
		return 0
	fi

	if mountpoint -q "$NFS_MOUNT"; then
		echo_error "$NFS_MOUNT already mounted"
		exit 1
	fi

	if mount -o nolock "$nfs_share" "$NFS_MOUNT"; then
		echo_info "Mounted $nfs_share on $NFS_MOUNT"
	else
		echo_error "Failed to mount $nfs_share on $NFS_MOUNT"
		exit 1
	fi
}

stop() {
	echo_title "Unmount $NFS_MOUNT"

	if ! mountpoint -q "$NFS_MOUNT"; then
		echo_info "$NFS_MOUNT is not mounted"
		return 0
	fi

	if umount -l "$NFS_MOUNT"; then
		echo_info "$NFS_MOUNT unmounted"
	else
		echo_error "Failed to unmount $nfs_share"
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 2
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0

