#!/bin/sh

NFS_MOUNT="/mnt/nfs"

nfs_share="$(jct /etc/thingino.json get nfs_share 2>/dev/null)"

start() {
	echo -c 15 "Mount $NFS_MOUNT"

	if [ -z "$nfs_share" ]; then
		echo "Mount share is not set"
		return 0
	fi

	if mountpoint -q "$NFS_MOUNT"; then
		echo "$NFS_MOUNT already mounted" >&2
		exit 1
	fi

	if mount -o nolock "$nfs_share" "$NFS_MOUNT"; then
		echo "Mounted $nfs_share on $NFS_MOUNT"
	else
		echo "Failed to mount $nfs_share on $NFS_MOUNT" >&2
		exit 1
	fi
}

stop() {
	echo -c 15 "Unmount $NFS_MOUNT"

	if ! mountpoint -q "$NFS_MOUNT"; then
		echo "$NFS_MOUNT is not mounted"
		return 0
	fi

	if umount -l "$NFS_MOUNT"; then
		echo "$NFS_MOUNT unmounted"
	else
		echo "Failed to unmount $nfs_share" >&2
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 2
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
