#!/bin/sh

DAEMON="/usr/sbin/ntpd"
PIDFILE="/run/ntpd.pid"
NTP_DEFAULT_FILE="/etc/default/ntp.conf"
NTP_WORKING_FILE="/tmp/ntp.conf"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

wlanap_enabled="$(jct /dev/prudynt.json get wlan_ap.enabled 2>/dev/null)"

start() {
	echo -c 15 "Starting NTP daemon"

	if [ "true" = "$wlanap_enabled" ]; then
		touch "$NTP_WORKING_FILE"
		DAEMON_ARGS="-n -l"
	else
		DAEMON_ARGS="-n -S /etc/ntpd_callback"
	fi

	if [ -f "$NTP_WORKING_FILE" ]; then
		echo "working configuration found"
	else
		if [ -f "$NTP_DEFAULT_FILE" ]; then
			echo "default configuration found"
		else
			echo "restore default config from ROM"
			cp "/rom$NTP_DEFAULT_FILE" "$NTP_DEFAULT_FILE"
		fi

		echo "use default configuration"
		cp "$NTP_DEFAULT_FILE" "$NTP_WORKING_FILE"
	fi

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS

	if [ "true" = "$wlanap_enabled" ]; then
		echo "WLAN AP mode. Skip sync time"
	elif [ -f /run/portal_mode ]; then
		echo "Portal mode. Skip sync time"
	else
		echo "Sync time"
		ntpd -q -N &
	fi
}

stop() {
	echo -c 15 "Stopping NTP daemon"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
