#!/bin/sh

DAEMON="/usr/sbin/crond"
DAEMON_ARGS="-f -c /etc/cron/crontabs"
PIDFILE="/run/crond.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo -c 15 "Starting crond"

	if [ ! -x "$DAEMON" ]; then
		echo "Disabled" >&2
		exit 1
	fi

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo -c 15 "Stopping crond"

	if [ ! -x "$DAEMON" ]; then
		echo "Disabled" >&2
		exit 1
	fi

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
