#!/bin/sh

DROPBEAR_DIR="/etc/dropbear"
DROPBEAR_PID="/run/dropbear.pid"
DROPBEAR_ARGS="-R -k -K 300"

start() {
	printf "Starting dropbear sshd: "
	[ -L "$DROPBEAR_DIR" ] && rm -r "$DROPBEAR_DIR"
	[ ! -d "$DROPBEAR_DIR" ] && mkdir -p "$DROPBEAR_DIR"
	umask 077
	start-stop-daemon -q -p $DROPBEAR_PID -S -x /usr/sbin/dropbear -- $DROPBEAR_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping dropbear sshd: "
	start-stop-daemon -q -p $DROPBEAR_PID -K
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit $?
