#!/bin/sh

DAEMON="/usr/sbin/dropbear"
DAEMON_ARGS="-k -K 300 -R"
DROPBEAR_KEY_FILE="/etc/dropbear/dropbear_ed25519_host_key"
PIDFILE="/run/dropbear.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo -c 15 "Starting dropbear sshd"

	umask 077

	if [ ! -f $DROPBEAR_KEY_FILE ]; then
		dropbearkey -t ed25519 -f $DROPBEAR_KEY_FILE
	fi

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo -c 15 "Stopping dropbear sshd"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
