#!/bin/sh

DAEMON_ARGS="-i $(ip -o link show up | awk -F': ' '!/lo/{print $2; exit}') -s"

. /usr/share/common

start() {
	echo_title "Starting mdnsd"

	start_daemon
}

stop() {
	echo_title "Stopping mdnsd"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
