#!/bin/sh

DAEMON=telegram-bot
PIDFILE=/var/run/telegrambot.pid
DAEMON_ARGS=""

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x /sbin/$DAEMON -- $DAEMON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
	start | stop | restart)
		$1
		;;
	reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
