#!/bin/sh

DAEMON=telegram-bot
PIDFILE=/var/run/telegrambot.pid
TELEGRAMBOT_ARGS=""

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $TELEGRAMBOT_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	if [ ! -f "$PIDFILE" ]; then
		printf 'Stopping %s: ' "$DAEMON"
		start-stop-daemon -K -q -p "$PIDFILE"
		status=$?
		if [ "$status" -eq 0 ]; then
			rm -f "$PIDFILE"
			echo "OK"
		else
			echo "FAIL"
		fi
		return "$status"
	fi
}

case "$1" in
	start | stop | restart)
		$1
		;;
	reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
