#!/bin/sh

PORTAL_MODE_FLAG="/run/portal_mode"

start() {
	echo -c 15 "Checking sysupgrade"

	if [ "true" != "$(fw_printenv -n sysupgrade_complete)" ]; then
		echo -c 240 -e "- Mark sysupgrade complete"
		fw_setenv sysupgrade_complete true

		if [ -f "$PORTAL_MODE_FLAG" ]; then
			echo -c 240 -e "- Portal mode is active"
		else
			play /usr/share/sounds/thingino.opus
		fi
	fi
}

stop() {
	echo -c 15 "Checking for upgrade"

	if [ -f "/tmp/upgrade.me" ]; then
		echo -c 142 -e "Running full upgrade" >&2
		yes yes | sysupgrade -f
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
