WIFI_SSW101B_SITE_METHOD = git
WIFI_SSW101B_SITE = https://github.com/gtxaspec/atbm-wifi
WIFI_SSW101B_SITE_BRANCH = main
WIFI_SSW101B_VERSION = $(shell git ls-remote $(WIFI_SSW101B_SITE) $(WIFI_SSW101B_SITE_BRANCH) | head -1 | cut -f1)

SSW101B_LICENSE = GPL-2.0

define WIFI_SSW101B_LINUX_CONFIG_FIXUPS
		$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
		$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
		$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
		$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
		$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

$(eval $(kernel-module))
$(eval $(generic-package))
