#!/bin/sh

. /usr/share/common

singleton $0

MODE_FILE="/tmp/nightmode.txt"

[ -f "$MODE_FILE" ] || echo "day" >"$MODE_FILE"

controls_color() {
	if [ "true" != "$day_night_color" ]; then
		echo_warning "Color not enabled"
		return 1
	fi
}

controls_ircut() {
	if [ "true" != "$day_night_ircut" ]; then
		echo_warning "IR-CUT filter not enabled"
		return 1
	fi
}

controls_ir850() {
	if [ "true" != "$day_night_ir850" ]; then
		echo_warning "IR LED 850mn not enabled"
		return 1
	fi

	if [ -z "$gpio_ir850" ]; then
		echo_warning "IR LED 850mn not configured"
		return 1
	fi
}

controls_ir940() {
	if [ "true" != "$day_night_ir940" ]; then
		echo_warning "IR LED 940mn not enabled"
		return 1
	fi

	if [ -z "$gpio_ir940" ]; then
		echo_warning "IR LED 940mn not configured"
		return 1
	fi
}

controls_white() {
	if [ "true" != "$day_night_white" ]; then
		echo_warning "White Light not enabled"
		return 1
	fi

	if [ -z "$gpio_white" ]; then
		echo_warning "White Light not configured"
		return 1
	fi
}

switch_to_day() {
	echo_info "Switching to day mode..."

	if controls_ircut; then
		echo_info "set IR-CUT filter"
		ircut on &
	fi

	if controls_ir850; then
		echo_info "turn IR LED 850mn OFF"
		irled off ir850 &
	fi

	if controls_ir940; then
		echo_info "turn IR LED 940mn OFF"
		irled off ir940 &
	fi

	if controls_white; then
		echo_info "turn White Light OFF"
		irled off white &
	fi

	if controls_color; then
		echo_info "switch to color mode"
		color on &
	fi

	echo "day" >"$MODE_FILE"
}

switch_to_night() {
	echo_info "Switched to night mode"

	if controls_color; then
		echo_info "switch to monocrome mode"
		color off &
	fi

	if controls_ircut; then
		echo_info "remove IR-CUT filter"
		ircut off &
	fi

	if controls_ir850; then
		echo_info "turn IR LED 850mn ON"
		irled on ir850 &
	fi

	if controls_ir940; then
		echo_info "- turn IR LED 940mn ON"
		irled on ir940 &
	fi

	if controls_white; then
		echo_info "- turn White Light ON"
		irled on white &
	fi

	echo "night" >"$MODE_FILE"
}

function limit_break()
{
	if [ "$2" -gt "$day_night_max" ] && [ "night" != "$1" ]; then
		echo "night"
	elif [ "$2" -lt "$day_night_min" ] && [ "day" != "$1" ]; then
		echo "day"
	fi
	echo ""
}

function slimit_break()
{
	if [ "$3" -le "$day_night_toggle_limit" ]; then
		echo $(limit_break "$1" "$2")
	fi
}

function get_luminence()
{
	value=$(imp-control gettotalgain)
	if [ -z "$value" ] || [ "error" = "$value" ]; then
		echo_error "failed to get luminance"
		rm "$DN_FLAG"
		exit 1
	fi
	echo "$value"
}

function toggle_day_night()
{
	if [ "$1" = "day" ]; then
		echo "night"
	else
		echo="day"
	fi
}

last_value=$(get_luminence)
function light_switch()
{
	abs_diff=$(expr "$2" - "$last_value") 
	if [ "$abs_diff" -gt "$day_night_switch" ]; then
		echo $(toggle_day_night "$1")
	fi
}

function check_sched()
{
	mode="dummy"
	if  ["$day_night_sched" = "none" ]; then
		mode="limit" 
	elif ["$day_night_sched" = "file"]; then
		mode=$(cat "$DN_MODE_FILE")
	else
		#put code here to do time-based scheduling
	fi
	echo "$mode"
}

# fail-safe defaults
[ -z "$day_night_min" ] && day_night_min=500
[ -z "$day_night_max" ] && day_night_max=15000
[ -z "$day_night_color" ] && day_night_color="true"
[ -z "$day_night_ircut" ] && day_night_ircut="true"
[ -z "$day_night_ir850" ] && day_night_ir850="true"
[ -z "$day_night_ir940" ] && day_night_ir940="true"
[ -z "$day_night_white" ] && day_night_white="true"
[ -z "$day_night_wait" ] && day_night_wait=60
[ -z "$day_night_switch" ] && day_night_switch=1000
[ -z "$day_night_toggle_limit" ] && day_night_toggle_limit=3
[ -z "$day_night_sched" ] && day_night_sched="none"



DN_FLAG="/tmp/daynight.$$"
touch "$DN_FLAG"
dn_switch_repeat=0

while : ; do
	[ -f $DN_FLAG ] || break

	# determine luminance of the scene
	value=$(get_luminance)
	state=$(cat "$MODE_FILE" 2>/dev/null)

	#if we were given a parameter then we will only run once and do the parameter
	if [! -z "$1" ]; then 
		case "$1" in
			night) action="night" ;;
			day) action="day" ;;
			~ | toggle) action=$(toggle_day_night "$state") ;;
		esac
		dn_mode="once"
		rm "$DN_FLAG"
	else 
		dn_mode=$(check_sched)
	fi

	echo_info "day_night_min: $day_night_min"
	echo_info "day_night_max: $day_night_max"
	echo_info "state: $state"
	if [ "day" = "$state" ]; then
		echo_info "active range: 0-$day_night_max"
	else
		echo_info "active range: $day_night_min-Infinity"
	fi
	echo_info "value: $value"

	case "$dn_mode" in
		limit) 	action=$(limit_break "$state" "$value") ;;
		slimit) action=$(slimit_break "$state" $value" "$dn_switch_repeat") ;;
		switch) action=$(ligth_switch "$state" $value") ;;
		dummy) action="";;
	esac

	if [! -z "$action"]; then
		if [ "$action" = "$state" ]; then
			dn_switch_repeat=$((dn_switch_repeat - 1))
		else
			dn_switch_repeat=$((dn_switch_repeat + 1))
			echo_info "new state: $state"
			case "$action" in
				night) switch_to_night ;;
				day) switch_to_day ;;
			esac
		fi
	else
		dn_switch_repeat=$((dn_switch_repeat - 1))
	fi

	sleep "$dn_wait"

esac

done

exit 0
