#!/bin/sh

show_help() {
	echo "Usage: $0 <mode> <type>
Where:
	mode	on|off
	type	ir850|ir940|white
" >&2
	exit 1
}

[ "$#" -lt 1 ] && show_help

# set parameters from cli, if empty
[ -z "$mode" ] && mode=$1
[ -z "$type" ] && type=$2

case "$type" in
	ir850)
		pin=$gpio_ir850
		;;
	ir940)
		pin=$gpio_ir940
		;;
	white)
		pin=$gpio_white
		;;
	*)
		# select first non-empty pin of available
		[ -z "$pin" ] && pin=$gpio_ir850
		[ -z "$pin" ] && pin=$gpio_ir940
		[ -z "$pin" ] && pin=$gpio_white
		;;
esac

if [ -z "$pin" ]; then
	echo "Please define LED GPIO pin" >&2
	exit 1
fi

# default to output high
case "$pin" in
	*[!0-9]*) ;;
	*) pin="${pin}O" ;;
esac

pin_last=$(printf '%s' "$pin" | tail -c 1)
case "$pin_last" in
	o)
		pin_on=0
		pin_off=1
		;;
	O)
		pin_on=1
		pin_off=0
		;;
esac
pin=${pin%?}

case "$mode" in
	0 | off)
		gpio set $pin $pin_off
		;;
	1 | on)
		gpio set $pin $pin_on
		;;
	~ | toggle)
		gpio toggle $pin
		;;
	\? | read | status)
		if [ "$(gpio value $pin | tr -d '\n')" = "$pin_on" ]; then
			echo -n "1"
		else
			echo -n "0"
		fi
		;;
	*)
		echo "Error: Unknown mode" >&2
		exit 1
		;;
esac

exit 0
