#!/bin/sh

. /usr/share/common

DAEMON="daynight"

start() {
	echo_title "Starting daynight daemon"

	if pidof -o $$ $DAEMON > /dev/null; then
		echo_error "$DAEMON is already running"
		exit 1
	fi

	$DAEMON > /dev/null 2>&1 &
}

stop() {
	echo_title "Stopping Daynight daemon"

	find /tmp/ -name "daynight.*" -maxdepth 1 -delete


}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;

	restart)
		stop
		sleep 1
		start
		;;
	*)
		usage "{start|stop|restart}"
		;;
esac

exit 0
