WIFI_SSV615X_SITE_METHOD = git
WIFI_SSV615X_SITE = https://github.com/openipc/ssv6x5x
WIFI_SSV615X_SITE_BRANCH = ssv615x
WIFI_SSV615X_VERSION = 7f27e6e2e0ebc3d8b8ab98211e72c4fb78ef464e
# $(shell git ls-remote $(WIFI_SSV615X_SITE) $(WIFI_SSV615X_SITE_BRANCH) | head -1 | cut -f1)

WIFI_SSV615X_LICENSE = GPL-2.0
WIFI_SSV615X_LICENSE_FILES = COPYING

WIFI_SSV615X_MODULE_MAKE_OPTS = \
	KSRC=$(LINUX_DIR)

define WIFI_SSV615X_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

define WIFI_SSV615X_INSTALL_TARGET_CMDS
	$(INSTALL) -m 755 -d $(TARGET_DIR)/etc
	$(INSTALL) -m 644 -t $(TARGET_DIR)/etc $(WIFI_SSV615X_PKGDIR)/files/ssv6155-usb-40M.cfg
        $(INSTALL) -m 644 -t $(TARGET_DIR)/etc $(WIFI_SSV615X_PKGDIR)/files/ssv6006c-wifi.cfg
endef

$(eval $(kernel-module))
$(eval $(generic-package))
