#!/bin/sh

DAEMON="/usr/bin/iad"

DAEMON_ARGS="-r -c /etc/iad.json"
PIDFILE="/run/iad.pid"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

start() {
	echo "Starting Ingenic Audio Daemon"

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo "Stopping Ingenic Audio Daemon"

	stop_daemon
}

restart() {
	stop || true
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
