#!/bin/sh

DAEMON="iad -r -c /etc/iad.json"

. /etc/init.d/rc.common

start() {
	starting
	is_streamer_disabled && die 0 "Disabled"
	start_daemon
}

stop() {
	stopping
	is_streamer_disabled && die 0 "Disabled"
	stop_daemon
}

restart() {
	stop || true
	sleep 1
	reload
}

reload() {
	start
}

case "$1" in
	start | stop | restart | reload)
		$1
		;;
	*)
		die 1 "Usage: $0 {start|stop|restart|reload}"
esac

exit 0
