#!/bin/sh

. /usr/share/common

DAEMON="zerotier-one"
action="$1"

case "$action" in
	start)
		config_file=/etc/zerotier.json
		if [ ! -f "$config_file" ]; then
			echo_error "ZeroTier configuration file $config_file not found"
			exit 1
		fi

		if [ "true" != "$(jct "$config_file" get zerotier.enabled)" ]; then
			echo_error "ZeroTier-One service is disabled in $config_file"
			exit 1
		fi

		echo_title "Starting ZeroTier-One"
		modprobe tun && $DAEMON -d >/dev/null 2>&1
		;;
	stop)
		echo_title "Stopping ZeroTier-One"
		killall -q -9 $DAEMON && rmmod tun
		;;
	*)
		echo_error "Unknown action $action"
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
