#!/bin/sh

DAEMON="/usr/sbin/zerotier-one"
DAEMON_NAME="zerotier-one"
action="$1"
config_file=/etc/zerotier.json

validate() {
	nwid=$(jct "$config_file" get zerotier.nwid)
	if [ -z "$nwid" ]; then
		echo "No network defined" >&2
		exit 1
	fi
}

join() {
	if [ ! -e "/var/lib/zerotier-one/networks.d/${nwid}.conf" ]; then
		sleep 2
		if zerotier-cli join "$nwid"; then
			play /usr/share/sounds/zerotiervpnisup.opus
		fi
	fi
}

abort_if_running() {
	pidof zerotier-one >/dev/null
	if [ $? = 0 ]; then
		echo "ZeroTier already running" >&2
		exit 1
	fi
}

case "$action" in
	force)
		abort_if_running
		validate
		echo -c 15 "Starting ZeroTier-One"
		modprobe tun && $DAEMON -d >/dev/null 2>&1
		join
		;;
	start)
		abort_if_running
		validate
		if [ "true" != "$(jct "$config_file" get zerotier.enabled)" ]; then
			echo "ZeroTier-One service is disabled in $config_file" >&2
			exit 1
		fi

		echo "Starting ZeroTier-One"
		modprobe tun && $DAEMON -d >/dev/null 2>&1
		join
		;;
	stop)
		echo -c 15 "Stopping ZeroTier-One"
		killall -q -9 "$DAEMON_NAME" &&
			sleep 2 &&
			rmmod tun &&
			play /usr/share/sounds/zerotiervpnisdown.opus
		;;
	*)
		echo "Unknown action $action" >&2
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
