#!/bin/sh

config_file=/etc/webui/zerotier.conf
[ -f "$config_file" ] && . $config_file

case "$1" in
	start)
		if [ "false" = "$zerotier_enabled" ]; then
			echo "Zerotier-One service is disabled in $config_file"
			exit 3
		fi

		echo "Starting zerotier-one daemon..."
		modprobe tun
		zerotier-one -d
		;;
	stop)
		echo "Stopping zerotier-one daemon..."
		kill -9 $(pidof zerotier-one)
		rmmod -w tun
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
