#!/bin/sh
PTZ_CONF_FILE="/etc/ptz_presets.conf"

usage() {
	echo "Usage: $0 [-g] [-a <preset_name> <x_coord> <y_coord>] [-r <preset_number>]"
	echo "  -g: Display all presets"
	echo "  -a: Add a new preset with name, coordinates <optional> "
	echo "  -r: Remove a preset by number"
	echo "  <preset_number>: Run the specified preset"
	exit 1
}

[ $# -lt 1 ] && usage

case "$1" in
	-g)
		while IFS='=,' read -r PNUM PNAME PX PY; do
			[ "${PNUM#\#}" != "$PNUM" ] || echo "$PNUM=$PNAME,$PX,$PY"
		done < "$PTZ_CONF_FILE"
		exit 0
		;;
	-a)
		[ $# -lt 2 ] && echo "Error: Missing arguments." && usage
		PRESET_NAME=$2; PRESET_X=$3; PRESET_Y=$4
		# get 1st available free slot
		PRESET_NUM=$(cat "$PTZ_CONF_FILE" | sort -t, -k1 | grep -m1 =,, | cut -c1)
		# check if there is any free slots available
		[ -z "$PRESET_NUM" ] && echo "No free preset available" && exit 1
		# get current motor coords if user didn't provide it
		if [ -z "$PRESET_X" ] || [ -z "$PRESET_Y" ]; then
			POS=$(motors -p)
        	PRESET_X=$(echo $POS | cut -d ',' -f 1)
	        PRESET_Y=$(echo $POS | cut -d ',' -f 2)
		fi
		# insert the newly created ptz location
		sed -i "s/$PRESET_NUM=.*/$PRESET_NUM=$PRESET_NAME,$PRESET_X,$PRESET_Y/g" "$PTZ_CONF_FILE"
		echo "Preset $PRESET_NUM added."
		exit 0
		;;
	-r)
		[ $# -ne 2 ] && echo "Error: Missing preset number." && usage
		PRESET_NUM=$2
		if grep -q "^$PRESET_NUM=" "$PTZ_CONF_FILE"; then
			sed -i "s/^$PRESET_NUM=.*/$PRESET_NUM=,,/" "$PTZ_CONF_FILE"
			echo "Preset $PRESET_NUM removed."
		else
			echo "Preset $PRESET_NUM not found."
		fi
		exit 0
		;;
	*)
		PRESET_NUM=$1
		while IFS='=,' read -r PNUM PNAME PX PY; do
			[ "${PNUM#\#}" != "$PNUM" ] && continue
			if [ "$PNUM" = "$PRESET_NUM" ]; then
				if [ -n "$PX" ] && [ -n "$PY" ]; then
					logger -t ptz_presets "Running: motors -d h -x $PX -y $PY"
					motors -d h -x "$PX" -y "$PY"
					exit 0
				else
					echo "Invalid preset or missing coordinates for $PRESET_NUM."
					exit 1
				fi
			fi
		done < "$PTZ_CONF_FILE"
		echo "Preset $PRESET_NUM not found."
		exit 1
		;;
esac