#!/bin/sh

DAEMON="motors-daemon"
DAEMON_ARGS="-d -p"

. /etc/init.d/rc.common

set_motor_phases() {
	[ "$(echo $2 | wc -w)" -lt 4 ] && die "Missing phase for ${1}motor"

	local i=1
	for gpio in $2; do
		eval "${1}st${i}=$gpio"
		i=$((i + 1))
	done
}

home_motors() {
	info "Home motors"
	motors -r > /dev/null 2>&1
}

set_motors_speed() {
	info "Set motors speed to $motor_speed"
	motors -s $1 > /dev/null 2>&1
}

position_motors() {
	local x=$((motor_maxstep_h / 2))
	local y=$((motor_maxstep_v / 2))
	local motor_pos_0=$(get motor_pos_0)
	if [ -n "$motor_pos_0" ]; then
		x=$(echo $motor_pos_0 | cut -d, -f1)
		y=$(echo $motor_pos_0 | cut -d, -f2)
	fi

	info "Move to $x,$y"
	motors -d h -x $x -y $y > /dev/null 2>&1
}

start() {
	starting

	motors_app=$(which motors)
	gpio_motor_h=$(fw_printenv -n gpio_motor_h)
	gpio_motor_v=$(fw_printenv -n gpio_motor_v)
	gpio_motor_invert=$(fw_printenv -n gpio_motor_invert)
	gpio_motor_switch=$(fw_printenv -n gpio_motor_switch)
	motor_maxstep_h=$(fw_printenv -n motor_maxstep_h)
	motor_maxstep_v=$(fw_printenv -n motor_maxstep_v)
	motor_speed=$(fw_printenv -n motor_speed)

	# Check if motors are supported
	[ -z "$motors_app"      ] && die " No motors app found"
	[ -z "$gpio_motor_h"    ] && die " Pan motor GPIO pins are not set"
	[ -z "$gpio_motor_switch" ] && [ -z "$gpio_motor_v" ] && die " Tilt motor GPIO pins are not set"
	[ -z "$motor_maxstep_h" ] && die " Pan motor Steps are not set"
	[ -z "$motor_maxstep_v" ] && die " Tilt motor Steps are not set"
	[ -z "$motor_speed"     ] && motor_speed=900

	[ "$gpio_motor_invert" = "true" ] && gpio_motor_invert_opt="invert_gpio_dir=1"

	[ -n "$gpio_motor_switch" ] && direction_select_gpio="shared_gpio_mode=0 direction_select_gpio=$gpio_motor_switch"

	if grep -qE "^motor" /proc/modules; then
		info "Module motor already loaded."
	else
		info "Set GPIO per motor phase"
		set_motor_phases "h" "$gpio_motor_h"
		[ -z "$gpio_motor_switch" ] && set_motor_phases "v" "$gpio_motor_v"

		info "Load module with parameters"

		modprobe_args="hmaxstep=$motor_maxstep_h vmaxstep=$motor_maxstep_v \
			hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4 \
			$gpio_motor_invert_opt $direction_select_gpio"

		[ -z "$gpio_motor_switch" ] && modprobe_args="$modprobe_args vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4"

		modprobe motor $modprobe_args || die "Failed to load motor module"

	fi

	start_daemon
	# FIXME: daemon should be reporting running state from the very first moment
	sleep 1

	set_motors_speed $motor_speed

	if [ "true" = "$(get disable_homing)" ]; then
		warn "Homing disabled"
	else
		home_motors
		position_motors
	fi
}

stop() {
	stopping
	stop_daemon
	# FIXME: motor.ko crashes on upload
	# rmmod motor || die "Failed to unload motor module."
	ok
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
