VALISA_VERSION = bf135896dd07d80ee2f32a288e97d5af8e5bc65c
VALISA_SITE = https://github.com/themactep/valisa
VALISA_SITE_METHOD = git
VALISA_LICENSE = MIT
VALISA_DEPENDENCIES = thingino-jct

define VALISA_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIA_SUPPORT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIA_CAMERA_SUPPORT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIA_CONTROLLER)
	$(call KCONFIG_ENABLE_OPT,CONFIG_VIDEO_DEV)
	$(call KCONFIG_ENABLE_OPT,CONFIG_VIDEO_V4L2)
	$(call KCONFIG_ENABLE_OPT,CONFIG_VIDEO_V4L2_SUBDEV_API)
	$(call KCONFIG_ENABLE_OPT,CONFIG_VIDEO_TX_ISP)
endef

define VALISA_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/valisa $(TARGET_DIR)/usr/bin/valisa
	$(INSTALL) -D -m 0644 $(@D)/valisa.json.example $(TARGET_DIR)/etc/valisa.json
endef

$(eval $(cmake-package))
