#!/bin/sh

DAEMON="motors-daemon"
DAEMON_ARGS="-d -p"

. /usr/share/common

MOTORS_CONFIG="/etc/motors.json"

ensure_command "motors"

set_motor_phases() {
	if [ "$(echo $2 | wc -w)" -lt 4 ]; then
		echo_error "Missing phase for ${1}motor"
		exit 1
	fi

	local i=1
	for gpio in $2; do
		eval "${1}st${i}=$gpio"
		i=$((i + 1))
	done
}

home_motors() {
	echo_info "Home motors"
	motors -r
}

set_motors_speed() {
	echo_info "Set motors speed to $speed_pan"
	motors -s $1
}

position_motors() {
	local x y

	pos_0=$(jct $MOTORS_CONFIG get motors.pos_0)

	if [ -n "$pos_0" ]; then
		x=$(echo $pos_0 | cut -d, -f1)
		y=$(echo $pos_0 | cut -d, -f2)
	else
		x=$((steps_pan / 2))
		y=$((steps_tilt / 2))
	fi

	echo_info "Move to $x,$y"
	motors -d h -x $x -y $y
}

start() {
	echo_title "Setting up motors"

	   gpio_pan=$(jct $MOTORS_CONFIG get motors.gpio_pan)
	  gpio_tilt=$(jct $MOTORS_CONFIG get motors.gpio_tilt)
	gpio_switch=$(jct $MOTORS_CONFIG get motors.gpio_switch)
	  steps_pan=$(jct $MOTORS_CONFIG get motors.steps_pan)
	 steps_tilt=$(jct $MOTORS_CONFIG get motors.steps_tilt)
	  speed_pan=$(jct $MOTORS_CONFIG get motors.speed_pan)
	 speed_tilt=$(jct $MOTORS_CONFIG get motors.speed_tilt)
	     homing=$(jct $MOTORS_CONFIG get motors.homing)

	[ -z "$gpio_pan" ] && echo_warning "gpio_pan is not set"
	[ -z "$gpio_tilt" ] && echo_warning "gpio_tilt is not set"
	[ -z "$gpio_switch" ] && echo_warning "gpio_switch is not set"

	# defaults
	[ -z "$steps_pan" ] && steps_pan=4000
	[ -z "$steps_tilt" ] && steps_tilt=2000
	[ -z "$speed_pan" ] && speed_pan=900
	[ -z "$speed_tilt" ] && speed_tilt=900

	if grep -qE "^motor" /proc/modules; then
		echo_info "Module motor already loaded."
	else
		modprobe_args="hmaxstep=$steps_pan vmaxstep=$steps_tilt"

		if [ -z "$motor" ]; then
			modprobe_args="$modprobe_args tcu_channels=2"

			echo_info "Set GPIO per motor phase"
			set_motor_phases "h" "$gpio_pan"
			set_motor_phases "v" "$gpio_tilt"
			modprobe_args="$modprobe_args hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4"
			[ -z "$vst1" ] && vst1="$hst1"
			[ -z "$vst2" ] && vst2="$hst2"
			[ -z "$vst3" ] && vst3="$hst3"
			[ -z "$vst4" ] && vst4="$hst4"
			modprobe_args="$modprobe_args vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4"

			if echo "$gpio_switch" | grep -qE '^[0-9]+$'; then
				modprobe_args="$modprobe_args motor_switch_gpio=$gpio_switch"
			fi

			if [ "true" = "$gpio_invert" ]; then
				modprobe_args="$modprobe_args invert_gpio_dir=1"
			fi
		fi

		echo_info "Load motor module with parameters: $modprobe_args"

		if ! modprobe motor $modprobe_args; then
			echo_error "Failed to load motor module"
			exit 1
		fi
	fi

	start_daemon
	# FIXME: daemon should be reporting running state from the very first moment
	sleep 1

	# FIXME: motors may have different speeds for pan and tilt
	set_motors_speed $speed_pan

	if [ "false" = "$homing" ]; then
		echo_info "Homing disabled"
	else
		home_motors
		position_motors
	fi
}

stop() {
	echo_title "Stopping motors"

	stop_daemon

	if ! rmmod motor; then
		echo_error "Failed to unload motor module."
		exit 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
