#!/bin/sh

. /etc/init.d/rc.common

DEV_MOUNT_POINT="/var/www"

start() {
	starting_batch

	if [ -f /etc/webui/development.conf ]; then
		. /etc/webui/development.conf
	else
		development_enabled=$(get development_enabled)
		development_nfs_ip=$(get development_nfs_ip)
		development_nfs_share=$(get development_nfs_share)
	fi

	if [ "true" != "$development_enabled" ]; then
		info "Not in development mode"
		quit
	fi

	if [ -z "$development_nfs_ip" ]; then
		info "Remote machine IP is not set"
		quit
	else
		info "Remote machine is $development_nfs_ip"
	fi

	if [ -z "$development_nfs_share" ]; then
		development_nfs_share="/srv/nfs/www"
	fi

	grep -q $DEV_MOUNT_POINT /etc/mtab && quit "Already mounted"
	{
		info "Shadow original web"
		rm -r $DEV_MOUNT_POINT

		info "Create a blank mountpoint"
		mkdir $DEV_MOUNT_POINT

		info "Mount remote share"
		mount -t nfs -o nolock,tcp,nfsvers=3 ${development_nfs_ip}:${development_nfs_share} $DEV_MOUNT_POINT
	}
	# check_result
}

stop() {
	stopping_batch

	if grep -q /var/www /etc/mtab; then
		info "Unmount /var/www"
		umount /var/www

		info "Unshadow mountpoint"
		rm -r /overlay/var/www

		info "Remount overlay"
		mount -o remount /
	else
		info "Nothing to unmount"
		quit
	fi
	# check_result
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac
