#!/bin/sh

. /etc/init.d/rc.common

MOUNT_POINT="/var/www"

start() {
	starting

	local nfs_ip=$(get development_nfs_ip)
	local nfs_share=$(get development_nfs_share)

	[ "true" != "$(get development_enabled)" ] && quit "Not in development mode"
	[ -z "$nfs_ip" ] && quit "Remote machine IP is not set"
	info "Remote machine is $nfs_ip"
	[ -z "$nfs_share" ] && nfs_share="/srv/nfs/www"
	grep -q $MOUNT_POINT /etc/mtab && quit "Already mounted"
	{
		run "rm -r $MOUNT_POINT"
		run "mkdir $MOUNT_POINT"
		run "mount -t nfs -o nolock,tcp,nfsvers=3 $nfs_ip:$nfs_share $MOUNT_POINT"
	}
	check_result
}

stop() {
	stopping
	grep -q $MOUNT_POINT /etc/mtab || quit "Nothing to unmount"
	{
		run "umount $MOUNT_POINT"
		run "rm -r /overlay$MOUNT_POINT"
		run "mount -o remount /"
	}
	check_result
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
