#!/bin/sh

. /etc/init.d/rc.common

HTTP_CONF="/etc/httpd.conf"
PORTAL_CONF="/etc/httpd-portal.conf"
ssid="$(get wlanssid)"
pass="$(get wlanpass)"

if ! iface_exists "eth0" && ([ -z "$ssid" ] || [ -z "$pass" ]) && ip link show wlan0 &> /dev/null; then
	DAEMON_ARGS="-f -c $PORTAL_CONF"
else
	DAEMON_ARGS="-f -c $HTTP_CONF -r Authentication"
fi

start() {
	starting
	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon_with_pid
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
