#!/bin/sh

PID_FILE="/run/blink.pid"
echo $$ > $PID

cleanup() {
	[ -z "$pin" ] || gpio set $pin 0
	[ -f "$PID_FILE" ] && rm "$PID_FILE"
	exit 0
}
trap cleanup 1 2 3 6 15

if [ "$#" -lt 1 ]; then
	echo "Usage: blink <pin> [interval in sec.]" >&2
	exit 1
fi

pin=$1
interval=${2:-1}

if [ "$interval" -eq 0 ]; then
	gpio set $pin 1
	sleep infinity
else
	while :; do
		gpio toggle $pin
		sleep $interval
	done
fi
