#!/bin/sh

. /sbin/common-motion

# set parameters from cli, if empty
[ -z "$mode" ] && mode=$1

MODE_FILE=/tmp/colormode.txt
[ -f $MODE_FILE ] || touch $MODE_FILE

# NB! ISP mode is set backwards: 0 - color, 1 - monochrome

switch_to_color() {
	touch_motion_cork
	imp-control ispmode 0
	echo "Switched to full-color mode"
	echo 1 > $MODE_FILE
}

switch_to_monochrome() {
	touch_motion_cork
	imp-control ispmode 1
	echo "Switched to monochrome mode"
	echo 0 > $MODE_FILE
}

case "$1" in
	0 | off)
		switch_to_monochrome
		;;
	1 | on)
		switch_to_color
		;;
	~ | toggle)
		if [ "$(cat $MODE_FILE 2> /dev/null)" -eq 1 ]; then
			switch_to_monochrome
		else
			switch_to_color
		fi
		;;
	status)
		cat $MODE_FILE
		;;
	\? | read)
		cat $MODE_FILE | tr -d '\n'
		;;
	*)
		echo -e "Usage: $0 [on|off|toggle|status|read]" >&2
		exit 1
		;;
esac

exit 0
