#!/bin/sh

# set parameters from cli, if empty
[ -z "$mode" ] && mode=$1

MODE_FILE=/tmp/colormode.txt

switch_to_color() {
	imp-control ispmode 0
	echo "Switched to full-color mode"
	echo "day" > $MODE_FILE
}

switch_to_monochrome() {
	imp-control ispmode 1
	echo "Switched to monochrome mode"
	echo "night" > $MODE_FILE
}

case "$1" in
	0 | off)
		switch_to_monochrome
		;;
	1 | on)
		switch_to_color
		;;
	~ | toggle)
		if [ "$(cat $MODE_FILE 2> /dev/null)" = "day" ]; then
			switch_to_monochrome
		else
			switch_to_color
		fi
		;;
	status)
		cat $MODE_FILE
		;;
	\? | read)
		cat $MODE_FILE | tr -d '\n'
		;;
	*)
		echo -e "Usage: $0 [on|off|toggle|status|read]" >&2
		exit 1
		;;
esac

exit 0
