#!/bin/sh

PID=$$
LOCK_FILE="/run/process-${PID}.pid"
LOG_FILE=/tmp/webui.log
LOG_SIZE_LIMIT=50000

SOCKS5_CONFIG=/etc/webui/socks5.conf

curl_timeout=100
if [ "true" = "$verbose" ]; then
	curl_verbosity="--verbose"
else
	curl_verbosity="--silent"
fi

CURL="curl $curl_verbosity --connect-timeout $curl_timeout --max-time $curl_timeout"

build_cmd() {
	command="$command $1"
}

die() {
	log "$1"
	quit_clean ${2:-1}
}

is_debug_mode() {
	[ $((0 + debug)) -gt 0 ] || [ "true" = "$debug" ]
}

is_interactive_shell() {
	tty > /dev/null
}

tag() {
	echo "$(ts) [$PID:$plugin]"
}

ts() {
	date +"%F %T"
}

log() {
	# poor man's logrotate
	if [ -f $LOG_FILE ] && [ "$(stat -c%s $LOG_FILE)" -gt $LOG_SIZE_LIMIT ]; then
		# redundant, but calling log() from within log() is wrong!
		echo "$(tag) Rotate log file" >> $LOG_FILE
		mv "$LOG_FILE" "${LOG_FILE}.1"
		echo "$(tag) Log file rotated." >> $LOG_FILE
	fi
	echo -e "$(tag) $1" >> $LOG_FILE
	echo -e "$1" >&2
}

log_and_run() {
	log "$1"
	run "$1"
}

quit_clean() {
	if [ -f $LOCK_FILE ]; then
		log "Remove lock file $LOCK_FILE"
		rm $LOCK_FILE
	fi
	log "Exit with code $1."
	exit $1
}

run() {
	echo "$(eval "$1" >> $LOG_FILE 2>&1)"
}

singleton() {
	log "Check lock file $LOCK_FILE"
	if [ -f "$LOCK_FILE" ] && ps | grep "^\s*\b$(cat "$LOCK_FILE")\b" > /dev/null; then
		log "Another instance running with PID $(cat $LOCK_FILE)."
		exit 1
	fi
	pids=$(pidof $plugin)
	if [ -n "$pids" ] && [ "$$" != "$pids" ]; then
		log "Another instances found with PIDs $pids."
		exit 1
	fi
	printf "%d\n" $PID > $LOCK_FILE
	log "Create lock file $LOCK_FILE"
}

use_socks5() {
	[ -f $SOCKS5_CONFIG ] || return
	. $SOCKS5_CONFIG
	build_cmd "--proxy-user $socks5_login:$socks5_password --socks5-hostname $socks5_host:$socks5_port"
	#"--proxy socks5h://$socks5_login:$socks5_password@$socks5_host:$socks5_port"
}
