#!/bin/sh

. /sbin/common

if [ -z "$plugin" ]; then
	log "ERROR: No plugin name found."
	log "This file should not be called directly!"
	quit_clean 2
fi

CONFIG_FILE="/etc/webui/$plugin.conf"

log "Plugin $plugin initialized"

[ -f "$CONFIG_FILE" ] && . $CONFIG_FILE
