#!/bin/sh

. /sbin/common

if [ -z "$plugin" ]; then
	log "ERROR: No plugin name found."
	log "This file should not be called directly!"
	quit_clean 2
fi

CONFIG_FILE="/etc/webui/${plugin}.conf"

log "Plugin ${plugin} initialized"

[ -f "$CONFIG_FILE" ] && . $CONFIG_FILE

clone_snapshot() {
	snapshot=/tmp/snapshot.jpg
	[ -f "$snapshot" ] || die "Cannot find a snapshot"
	delete_tempfile="true"
	cp $snapshot $1
}
