#!/bin/sh

. /sbin/common

if [ -z "$plugin" ]; then
	log "ERROR: No plugin name found."
	log "This file should not be called directly!"
	quit_clean 2
fi

CONFIG_FILE="/etc/webui/${plugin}.conf"

log "Plugin ${plugin} initialized"

if [ -f "$CONFIG_FILE" ]; then
	log "Reading configuration from $CONFIG_FILE"
	. $CONFIG_FILE
else
	log "Configuration file $CONFIG_FILE not found"
fi

clone_snapshot() {
	snapshot=/tmp/snapshot.jpg
	[ -f "$snapshot" ] || die "Cannot find a snapshot"
	delete_tempfile="true"
	cp $snapshot $1
}
