#!/bin/sh

die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }

pidof -o %PPID $(basename $0) > /dev/null && die "is already running"

STOP_FILE=/tmp/daynight.stop

MODE_FILE=/tmp/nightmode.txt
[ -f $MODE_FILE ] || echo "day" > $MODE_FILE

. /etc/web.conf

is_disabled() {
	[ -f "$STOP_FILE" ]
}

controls_color() {
	[ "true" = "$day_night_color" ]
}

controls_ircut() {
	[ "true" = "$day_night_ircut" ]
}

controls_ir850() {
	[ "true" = "$day_night_ir850" ]
}

controls_ir940() {
	[ "true" = "$day_night_ir940" ]
}

controls_white() {
	[ "true" = "$day_night_white" ]
}

switch_to_day() {
	is_disabled && return
	echo "switch to day"
	controls_ircut && ircut on
	controls_ir850 && irled off ir850
	controls_ir940 && irled off ir940
	controls_white && irled off white
	controls_color && color on
	echo "day" > $MODE_FILE
}

switch_to_night() {
	is_disabled && return
	echo "switch to night"
	controls_color && color off
	controls_ircut && ircut off
	controls_ir850 && irled on ir850
	controls_ir940 && irled on ir940
	controls_white && irled on white
	echo "night" > $MODE_FILE
}

# determine luminance of the scene
value=$(imp-control gettotalgain)
reversed=1
state=$(cat $MODE_FILE 2>/dev/null)

case "$1" in
	night)
		switch_to_night
		;;
	day)
		switch_to_day
		;;
	~ | toggle)
		if [ "day" = "$state" ]; then
			switch_to_night
		else
			switch_to_day
		fi
		;;
	\? | read | status)
		echo $state
		;;
	*)
		echo "$day_night_min - $value - $day_night_max" >&2

		if [ "$reversed" -eq 0 ]; then
			if [ "$value" -lt "$day_night_min" ] && [ "day" != "$state" ]; then
				switch_to_day
			elif [ "$value" -gt "$day_night_max" ] && [ "night" != "$state" ]; then
				switch_to_night
			else
				echo "within limits"
			fi
		else
			if [ "$value" -gt "$day_night_max" ] && [ "night" != "$state" ]; then
				switch_to_night
			elif [ "$value" -lt "$day_night_min" ] && [ "day" != "$state" ]; then
				switch_to_day
			else
				echo "within limits"
			fi
		fi
		;;
esac

exit 0
