#!/bin/sh

. /usr/share/common

singleton $0

MODE_FILE="/tmp/nightmode.txt"
[ -f "$MODE_FILE" ] || echo "day" >"$MODE_FILE"

controls_color() {
	if [ "true" != "$day_night_color" ]; then
		echo "- Color not enabled" >&2
		return 1
	fi
}

controls_ircut() {
	if [ "true" != "$day_night_ircut" ]; then
		echo "- IR-CUT filter not enabled" >&2
		return 1
	fi
}

controls_ir850() {
	if [ "true" != "$day_night_ir850" ]; then
		echo "- IR LED 850mn not enabled" >&2
		return 1
	fi

	if [ -z "$gpio_ir850" ]; then
		echo "- IR LED 850mn not configured" >&2
		return 1
	fi
}

controls_ir940() {
	if [ "true" != "$day_night_ir940" ]; then
		echo "- IR LED 940mn not enabled" >&2
		return 1
	fi

	if [ -z "$gpio_ir940" ]; then
		echo "- IR LED 940mn not configured" >&2
		return 1
	fi
}

controls_white() {
	if [ "true" != "$day_night_white" ]; then
		echo "- White Light not enabled" >&2
		return 1
	fi

	if [ -z "$gpio_white" ]; then
		echo "- White Light not configured" >&2
		return 1
	fi
}

switch_to_day() {
	echo "Switching to day mode..." >&2

	if controls_ircut; then
		echo "- set IR-CUT filter" >&2
		ircut on &
	fi

	if controls_ir850; then
		echo "- turn IR LED 850mn OFF" >&2
		irled off ir850 &
	fi

	if controls_ir940; then
		echo "- turn IR LED 940mn OFF" >&2
		irled off ir940 &
	fi

	if controls_white; then
		echo "- turn White Light OFF" >&2
		irled off white &
	fi

	if controls_color; then
		echo "- switch to color mode" >&2
		color on &
	fi

	echo "day" >"$MODE_FILE"
}

switch_to_night() {
	echo "Switched to night mode" >&2

	if controls_color; then
		echo "- switch to monocrome mode" >&2
		color off &
	fi

	if controls_ircut; then
		echo "- remove IR-CUT filter" >&2
		ircut off &
	fi

	if controls_ir850; then
		echo "- turn IR LED 850mn ON" >&2
		irled on ir850 &
	fi

	if controls_ir940; then
		echo "- turn IR LED 940mn ON" >&2
		irled on ir940 &
	fi

	if controls_white; then
		echo "- turn White Light ON" >&2
		irled on white &
	fi

	echo "night" >"$MODE_FILE"
}

# determine luminance of the scene
value=$(imp-control gettotalgain)
if [ -z "$value" ] || [ "error" = "$value" ]; then
	echo "failed to get luminance" >&2
	exit 1
fi

reversed=1
state=$(cat "$MODE_FILE" 2>/dev/null)

case "$1" in
	night)
		switch_to_night
		;;
	day)
		switch_to_day
		;;
	~ | toggle)
		if [ "day" = "$state" ]; then
			switch_to_night
		else
			switch_to_day
		fi
		;;
	\? | read | status)
		echo $state
		;;
	*)
		echo "day_night_min: $day_night_min" >&2
		echo "day_night_max: $day_night_max" >&2
		echo "state: $state" >&2
		if [ "day" = "$state" ]; then
			echo "active range: 0-$day_night_max" >&2
		else
			echo "active range: $day_night_min-Infinity" >&2
		fi
		echo "value: $value" >&2

		if [ "$reversed" -eq 0 ]; then
			if [ "$value" -lt "$day_night_min" ] && [ "day" != "$state" ]; then
				switch_to_day
			elif [ "$value" -gt "$day_night_max" ] && [ "night" != "$state" ]; then
				switch_to_night
			else
				echo "within limits" >&2
			fi
		else
			if [ "$value" -gt "$day_night_max" ] && [ "night" != "$state" ]; then
				switch_to_night
			elif [ "$value" -lt "$day_night_min" ] && [ "day" != "$state" ]; then
				switch_to_day
			else
				echo "within limits" >&2
			fi
		fi
		;;
esac

exit 0
