#!/bin/sh

. /etc/init.d/rc.common

ENV_FILE="/mnt/mmcblk0p1/uenv.txt"

[ -f "$ENV_FILE" ] || die "$ENV_FILE is missing"

tmpfile=$(mktemp)
sed 's/=/ /' $ENV_FILE >> $tmpfile
fw_setenv -s $tmpfile
rm $tmpfile

fw_printenv

exit 0
