#!/bin/sh

echo -e "\033[31;47m!!! Warning !!!\033[0m\n\nThis action will erase the overlay and env partitions, and reset the device to Thingino installation defaults, like the first boot.\n\n\033[33;40mAll saved settings and configurations will be erased!\033[0m\n\nAre you sure you want to proceed? (yes/no)"

read response
if [ "$response" != "yes" ]; then
	echo "Operation aborted."
	return 1
fi

rootfs_data_dev=$(awk '$4 ~ /"rootfs_data"/ {gsub(":","",$1); print $1}' /proc/mtd)
if [ -z "$rootfs_data_dev" ]; then
	echo "overlay partition not found!"
	return 1
fi

flash_eraseall -j "/dev/${rootfs_data_dev}" && flash_eraseall /dev/mtd1 && echo "Erase completed. Rebooting..." && reboot -f
