#!/bin/sh

if pidof -o %PPID $(basename $0) > /dev/null; then
	echo "is already running" >&2
	exit 1
fi

format_partition() {
	unmount_partition $1
	echo "Format partition" >&2
	if ! $MKFS -n thingino $1 2>&1; then
		echo "Cannot format $1 to $POST_fstype" >&2
		exit 1
	fi
}

mount_partitions() {
	echo "Mount partition" >&2
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	if ! mdev -s; then
		echo "Cannot re-mount SD card" >&2
		exit 1
	fi
}

unmount_partition() {
	echo "Unmount partition" >&2
	local limit=5
	while mountpoint -q $1; do
		if [ "$limit" -le 0 ]; then
			echo "Cannot unmount $1" >&2
			exit 1
		fi
		umount -l $1 2>&1
		sleep 0.5
		limit=$((limit-1))
	done
}

reinsert_sdcard() {
	echo "Reinsert card" >&2
	echo "" > /proc/sys/kernel/hotplug
	mmc 0 -r
	sleep 1
	mmc 0
	sleep 1
}

repartition_sdcard() {
	echo "Repartition card" >&2
	if ! echo -e "o\nn\np\n1\n\n\nt\n$FSTYPE\nw" | fdisk $1 2>&1; then
		echo "Cannot create a partition on $1" >&2
		exit 1
	fi
}

case "$1" in
	fat32)
		MKFS="mkfs.vfat"
		FSTYPE="b"
		;;
	exfat | *)
		MKFS="mkfs.exfat"
		FSTYPE="7"
		;;
esac

device_name="$(awk -F= '/DEVNAME/{print $2}' /sys/bus/mmc/devices/*/block/*/uevent)"
if [ -z "$device_name" ]; then
	echo "No SD card device found" >&2
	exit 1
fi

unmount_partition  "/mnt/${device_name}p1"
repartition_sdcard "/dev/${device_name}"
reinsert_sdcard
format_partition   "/dev/${device_name}p1"
mount_partitions

exit 0
