#!/bin/sh

die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }
info() { printf "\e[38;5;46m%s\e[0m\n" "$1" >&2; }

pidof -o %PPID $(basename $0) > /dev/null && die "is already running"

format_partition() {
	unmount_partition $1
	info "Format partition"
	$MKFS -n thingino $1 2>&1 || die "Cannot format $1 to $POST_fstype"
}

mount_partitions() {
	info "Mount partition"
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s || die "Cannot re-mount SD card"
}

unmount_partition() {
	info "Unmount partition"
	local limit=5
	while mountpoint -q $1; do
		[ "$limit" -gt 0 ] || die "Cannot unmount $1"
		umount -l $1 2>&1
		sleep 0.5
		limit=$((limit-1))
	done
}

reinsert_sdcard() {
	info "Reinsert card"
	echo "" > /proc/sys/kernel/hotplug
	mmc 0 -r
	sleep 1
	mmc 0
	sleep 1
}

repartition_sdcard() {
	info "Repartition card"
	echo -e "o\nn\np\n1\n\n\nt\n$FSTYPE\nw" | fdisk $1 2>&1 || die "Cannot create a partition on $1"
}

case "$1" in
	fat32)
		MKFS="mkfs.vfat"
		FSTYPE="b"
		;;
	exfat | *)
		MKFS="mkfs.exfat"
		FSTYPE="7"
		;;
esac

device_name="$(awk -F= '/DEVNAME/{print $2}' /sys/bus/mmc/devices/*/block/*/uevent)"
[ -z "$device_name" ] && die "No SD card device found"

unmount_partition  "/mnt/${device_name}p1"
repartition_sdcard "/dev/${device_name}"
reinsert_sdcard
format_partition   "/dev/${device_name}p1"
mount_partitions

exit 0
