#!/bin/sh

OWNER="themactep"
REPO="thingino-firmware"
TAG="firmware"

fetch_and_display_profiles() {
	echo "Gestalt selector - Fetching available profiles:"
	count=1
	curl -m 10 -s -H "Accept: application/vnd.github+json" \
		"https://api.github.com/repos/$OWNER/$REPO/releases/tags/$TAG" | \
		jsonfilter -e "@.assets[*].name" | \
		while read -r line; do
			profile="${line#thingino-}"
			profile="${profile%.bin}"
			echo "  $count) $profile"
			echo "$count:$profile" >> /tmp/gestalt_list.txt
			count=$((count + 1))
		done
}

trap 'rm -f /tmp/gestalt_list.txt; exit 0' INT

while true; do
	if [ ! -f /tmp/gestalt_list.txt ]; then
		rm -f /tmp/gestalt_list.txt
		fetch_and_display_profiles
	fi

	current_image_id=$(grep "^IMAGE_ID=" /etc/os-release | cut -d'=' -f2)
	echo -e "Current device gestalt: $current_image_id\n"
	echo "Ctrl-C or Enter without input to exit."
	read -p "Which gestalt do you want to switch to? Enter a number: " selection

	[ -z "$selection" ] && break

	selected_profile=$(grep "^$selection:" /tmp/gestalt_list.txt | cut -d':' -f2)
	if [ -n "$selected_profile" ]; then
		sed -i "s/^IMAGE_ID=.*/IMAGE_ID=$selected_profile/" /etc/os-release
		echo "Device gestalt updated to $selected_profile"
		break
	else
		echo "Invalid selection. Please try again."
	fi
done

rm -f /tmp/gestalt_list.txt
