#!/bin/sh

ENV_BACKUP=/etc/uenv.txt

res=$(awk -F"=" "/^$1=/{print \$2}" $ENV_BACKUP)
[ -n "$res" ] && echo "$res" && exit 0

res=$(fw_printenv -n $1)
[ -z "$res" ] && exit 1

fw_printenv > $ENV_BACKUP

echo "$res"
exit 0
