#!/bin/sh

die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }
info() { printf "\e[38;5;46m%s\e[0m\n" "$1" >&2; }

gpio_ircut=$(fw_printenv -n gpio_ircut)

pin1=$(echo $gpio_ircut | awk '{print $1}')
if [ -n "$pin1" ]; then
	[ "$pin1" = "${pin1//[^0-9]/}" ] && pin1="${pin1}O"
	case ${pin1:(-1)} in
		o) pin1_on=0; pin1_off=1 ;;
		O) pin1_on=1; pin1_off=0 ;;
	esac
	pin1=${pin1:0:(-1)}
else
	die "Please define IRCUT pins in bootloader environment"
fi

pin2=$(echo $gpio_ircut | awk '{print $2}')
if [ -n "$pin2" ]; then
	[ "$pin2" = "${pin2//[^0-9]/}" ] && pin2="${pin2}O"
	case ${pin2:(-1)} in
		o) pin2_on=0; pin2_off=1 ;;
		O) pin2_on=1; pin2_off=0 ;;
	esac
	pin2=${pin2:0:(-1)}
fi

MODE_FILE="/tmp/ircutmode.txt"
[ -f "$MODE_FILE" ] || touch "$MODE_FILE"

report_ir_filter() {
	case "$(cat "$MODE_FILE")" in
		0) info "IRCUT filter is removed" ;;
		1) info "IRCUT filter is set" ;;
		*) info "IRCUT filter is in unknown state" ;;
	esac
}

ir_filter_off() {
	gpio set "$pin1" "$pin1_off" > /dev/null
	if [ -n "$pin2" ]; then
		gpio set "$pin2" "$pin2_on" > /dev/null
		usleep 10000
		gpio set "$pin2" "$pin2_off" > /dev/null
	fi
	echo "0" > "$MODE_FILE"
}

ir_filter_on() {
	gpio set "$pin1" "$pin1_on" > /dev/null
	if [ -n "$pin2" ]; then
		gpio set "$pin2" "$pin2_off" > /dev/null
		usleep 10000
		gpio set "$pin1" "$pin1_off" > /dev/null
	fi
	echo "1" > "$MODE_FILE"
}

case "$1" in
	0 | off | night)
		ir_filter_off
		report_ir_filter
		;;
	1 | on | day)
		ir_filter_on
		report_ir_filter
		;;
	~ | toggle)
		[ "$(cat "$MODE_FILE")" -eq 0 ] && ir_filter_on || ir_filter_off
		report_ir_filter
		;;
	status)
		report_ir_filter
		;;
	\? | read)
		cat "$MODE_FILE" | tr -d '\n'
		;;
	*)
		die "Usage: $0 [on|off|toggle|status]"
		;;
esac

exit 0
