#!/bin/sh

die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }

# set parameters from cli, if empty
[ -z "$mode" ] && mode=$1
[ -z "$type" ] && type=$2

case "$type" in
	ir850 | ir940 | white)
		pin=$(fw_printenv -n gpio_$type)
		;;
	*)
		# select first non-empty pin of available
		for type in ir850 ir940 white; do
			pin=$(fw_printenv -n gpio_$type)
			[ -n "$pin" ] && break
		done
		# set most common type for error message below
		type=ir850
		;;
esac

[ -z "$pin" ] && die "Please define LED GPIO pin\nfw_setenv gpio_$type <pin>"

# default to output high
[ "$pin" = "${pin//[^0-9]/}" ] && pin="${pin}O"
case ${pin:(-1)} in
	o) pin_on=0; pin_off=1 ;;
	O) pin_on=1; pin_off=0 ;;
esac
pin=${pin:0:(-1)}

case "$mode" in
	0 | off)
		gpio set $pin $pin_off
		;;
	1 | on)
		gpio set $pin $pin_on
		;;
	~ | toggle)
		gpio toggle $pin
		;;
	\? | read | status)
		[ "$(gpio value $pin | tr -d '\n')" = "$pin_on" ] && echo -n "1" || echo -n "0"
		;;
	*)
		die "Unknown mode"
		;;
esac

exit 0
