#!/bin/sh

# set parameters from cli, if empty
[ -z "$mode" ] && mode=$1
[ -z "$type" ] && type=$2

case "$type" in
	ir850 | ir940 | white)
		pin=$(fw_printenv -n gpio_$type)
		;;
	*)
		# select first non-empty pin of available
		for type in ir850 ir940 white; do
			pin=$(fw_printenv -n gpio_$type)
			[ -n "$pin" ] && break
		done
		# set most common type for error message below
		type=ir850
		;;
esac

if [ -z "$pin" ]; then
	echo -e "Please define LED GPIO pin\nfw_setenv gpio_$type <pin>" >&2
	exit 1
fi

# default to output high
[ "$pin" = "${pin//[^0-9]/}" ] && pin="${pin}O"

if [ "o" = "${pin:(-1)}" ]; then
	pin_on=0
	pin_off=1
else
	pin_on=1
	pin_off=0
fi
pin=${pin:0:(-1)}

case "$mode" in
	0 | off)
		gpio set $pin $pin_off
		;;
	1 | on)
		gpio set $pin $pin_on
		;;
	~ | toggle)
		gpio toggle $pin
		;;
	\? | read | status)
		[ "$(gpio value $pin | tr -d '\n')" = "$pin_on" ] && echo -n "1" || echo -n "0"
		;;
	*)
		echo -e "Unknown mode" >&2
		exit 3
		;;
esac

exit 0
