#!/bin/sh

GPIO_R=$(fw_printenv -n gpio_led_r)
GPIO_G=$(fw_printenv -n gpio_led_g)
GPIO_B=$(fw_printenv -n gpio_led_b)

# color, pin, state
setLED() {
	if [ -z "$2" ]; then
		logger -p daemon.info -t led Status Lights: GPIO_$1 is not set in $0
	else
		gpio set "$2" "$3"
	fi
}

# R, G, B
setRGB() {
	setLED "R" "$GPIO_R" $1
	setLED "G" "$GPIO_G" $2
	setLED "B" "$GPIO_B" $3
}

case "$1" in
	b*) setRGB 0 0 1 ;;
	c*) setRGB 0 1 1 ;;
	g*) setRGB 0 1 0 ;;
	m* | p*) setRGB 1 0 1 ;;
	r*) setRGB 1 0 0 ;;
	w*) setRGB 1 1 1 ;;
	y*) setRGB 1 1 0 ;;
	off) setRGB 0 0 0 ;;
	*) echo -e "Usage: $0 <off|red|green|blue|yellow|magenta|cyan|white>" >&2 ;;
esac

exit 0
