#!/bin/sh

. /usr/share/common

show_help() {
	echo "Usage: $0 <type> <mode> [pin#]
Where:
	type	ir850 | ir940 | white | flood
	mode	on | off | toggle | read | gpio
" >&2
	exit 1
}

[ "$#" -lt 1 ] && show_help

# set parameters from cli, if empty
[ -z "$type" ] && type="$1"
[ -z "$mode" ] && mode="${2:-read}"

get_config_pin() {
	local type="$1"
	jct /etc/thingino.json get "gpio_$type" 2>/dev/null
}

set_config_pin() {
	local type="$1"
	local pin="$2"
	jct /etc/thingino.json set "gpio_$type" "$pin" 2>/dev/null
}

case "$type" in
	ir850 | ir940 | white | flood)
		pin=$(get_config_pin "$type")
		if [ -z "$pin" ] && [ "set" != "$mode" ]; then
			echo_error "GPIO pin for $type light is not defined"
			exit 1
		fi
		;;
	*)
		echo_error "Unknown light type $type"
		show_help
		;;
esac

# default to output high
if [ "$pin" = "${pin//[^0-9]/}" ]; then
	pin="${pin}O"
fi

case ${pin:(-1)} in
	o) pin_on=0; pin_off=1 ;;
	O) pin_on=1; pin_off=0 ;;
esac
pin=${pin:0:(-1)}

case "$mode" in
	0 | off)
		gpio set "$pin" "$pin_off"
		;;
	1 | on)
		gpio set "$pin" "$pin_on"
		;;
	~ | toggle)
		gpio toggle "$pin"
		;;
	\? | read | status)
		if [ "$(gpio value $pin | tr -d '\n')" = "$pin_on" ]; then
			echo -n "1"
		else
			echo -n "0"
		fi
		;;
	gpio | pin)
		new_pin="$3"
		if [ -n "$new_pin" ]; then
			set_config_pin "$type" "$new_pin"
		else
			pin=$(get_config_pin "$type")
			if [ -z "$pin" ]; then
				echo_error "GPIO pin is missing"
				show_help
			else
				echo "$pin"
			fi
		fi
		;;
	*)
		echo_error "Error: Unknown mode" >&2
		show_help
		;;
esac

exit 0
