#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 <mmc port> [-r]"
	exit 1
fi

endpoint=/sys/devices/platform/jzmmc_v1.2.${1}/present

if [ ! -f "$endpoint" ]; then
	echo "No endpoint $endpoint"
	exit 1
fi

# Check for the -r flag to determine whether to echo REMOVE or INSERT
if [ "$2" = "-r" ]; then
	echo REMOVE > $endpoint
else
	echo INSERT > $endpoint
fi

exit 0
