#!/bin/sh

plugin="motion"

. /sbin/common-plugins
singleton

MOTION_ALARM="/run/motion/motion_alarm"

start() {
	# send alerts
	[ -d $(dirname $MOTION_ALARM) ] && touch $MOTION_ALARM
	[ "$motion_send2email" = "true" ] && send2email
	[ "$motion_send2ftp" = "true" ] && send2ftp
	[ "$motion_send2mqtt" = "true" ] && send2mqtt
	[ "$motion_send2telegram" = "true" ] && send2telegram
	[ "$motion_send2webhook" = "true" ] && send2webhook
	[ "$motion_send2yadisk" = "true" ] && send2yadisk
	[ "$motion_playonspeaker" = "true" ] && playonspeaker
}

stop() {
	[ -f "$MOTION_ALARM" ] && rm -f $MOTION_ALARM
}

case "$1" in
	start | stop)
		$1
		;;
	*)
		start
		;;
esac

quit_clean 0
