#!/bin/sh

DATA_FILE="/etc/shadow"
ENV_VAR="pwbackup"

. /etc/init.d/rc.common

read_env() {
	backup="$(fw_printenv -n $ENV_VAR)"
}

read_file() {
	b64="$(awk -F: '/root/{print $2}' $DATA_FILE | base64 | tr -d '\n')"
}

case $1 in
	backup | save)
		[ -f "${DATA_FILE}-" ] || quit "Default root password"
		[ -f "$DATA_FILE" ] || quit "No root password to back up"
		read_file
		read_env
		[ "$backup" = "$b64" ] && quit "Same root password"
		info "Back up root password"
		fw_setenv $ENV_VAR $b64
		quit "Saved"
		;;
	restore)
		read_env
		[ -z "$backup" ] && quit "No backup of root password found"
		data=$(echo "$backup" | base64 -d)
		[ -z "$data" ] && quit "Backup of root password is empty"
		read_file
		[ "$backup" = "$b64" ] && quit "Same root password"
		info "Restore root password from backup"
		doe=$(($(date +%s) / 86400))
		tmpfile=$(mktemp -u)
		cp $DATA_FILE $tmpfile
		sed -i "/^root:/croot:$data:$doe::::::" $tmpfile
		mv -f $DATA_FILE ${DATA_FILE}-
		mv -f $tmpfile $DATA_FILE
		quit "Restored"
		;;
	*)
		die "Usage: $0 [backup|restore]"
		;;
esac

# unreachable?
exit 0
