#!/bin/sh

plugin="webhook"

. /sbin/common-plugins

show_help() {
	echo "Usage: $0 [-u url] [-v] [-h]
  -u url      Webhook URL.
  -v          Verbose output.
  -h          Show this help.
"
	quit_clean 0
}

# override config values with command line arguments
while getopts u:vh flag; do
	case "$flag" in
		u) webhook_url=$OPTARG ;;
		v) verbose="true" ;;
		h | *) show_help ;;
	esac
done

[ "false" = "$webhook_enabled" ] && die "Sending to webhook is disabled."
# validate mandatory values
[ -z "$webhook_url" ] && die "Webhook URL not found"

command="$CURL"
if [ "true" = "$webhook_attach_snapshot" ]; then
	attachment=$(mktemp -u /tmp/snapshot-XXXXXX).jpg
	clone_snapshot $attachment
	build_cmd "-F 'image=@$attachment'"
fi
build_cmd "--url \"$webhook_url\""

log_and_run "$command"

[ "true" = "$delete_tempfile" ] && [ -f "$attachment" ] && rm "$attachment"
[ "true" = "$verbose" ] && cat "$LOG_FILE"

quit_clean 0
