#!/bin/sh

if [ -t 0 ]; then
	[ -z "$1" ] && die 1 "Usage: $0 <command>"

	file=$(mktemp)
	sh -c "$*" > $file 2>&1
else
	file=$(mktemp)
	cat - > $file
fi

[ -s "$file" ] || die 3 "File $file is empty"

url=$(nc termbin.com 9999 < $file)
echo $url

rm -f $file

exit 0
