#!/bin/sh

plugin="yadisk"

. /sbin/common-plugins

show_help() {
	echo "Usage: $0 [-u username] [-P password] [-v] [-h]
  -d path     Directory on server.
  -f file     File to upload.
  -u username Yandex Disk username.
  -P password Yandex Disk username.
  -v          Verbose output.
  -h          Show this help.
"
	quit_clean 0
}

# override config values with command line arguments
while getopts d:f:P:u:vh flag; do
	case "$flag" in
		d) yadisk_path=$OPTARG ;;
		f) yadisk_file=$OPTARG ;;
		P) yadisk_password=$OPTARG ;;
		u) yadisk_username=$OPTARG ;;
		v) verbose="true" ;;
		h | *) show_help ;;
	esac
done

[ "false" = "$yadisk_enabled" ] && die "Sending to Yandex Disk is disabled."

[ -z "$yadisk_username" ] && die "Yandex Disk username not found"
[ -z "$yadisk_password" ] && die "Yandex Disk password not found"

if [ -z "$yadisk_file" ]; then
	attachment=$(mktemp -u /tmp/snapshot-XXXXXX).jpg
	clone_snapshot $attachment
	yadisk_file=$attachment
fi

command="$CURL --user '${yadisk_username}:$yadisk_password'"

url="https://webdav.yandex.ru"
yadisk_path=$(date +"$yadisk_path")
yadisk_path=${yadisk_path#/} # drop leading slash
yadisk_path=${yadisk_path%/} # drop trailing slash

# create path to destination directory
subdirs="$yadisk_path"
subdir="${subdir// /%20}" # convert each space into %20
for subdir in ${subdirs//\// }; do
	subdir="${subdirs%%/*}"  # leftmost directory
	suburl="$suburl/$subdir"
	[ -n "$subdir" ] && log_and_run "$command --request MKCOL $url$suburl"
	subdirs="${subdirs#*/}" # remove the processed directory
done

# upload file
build_cmd "--request PUT --upload-file $yadisk_file --url $url/$yadisk_path/$(TZ=$(cat /etc/TZ) date +"%G%m%d-%H%M%S").jpg"

log_and_run "$command"

[ "true" = "$delete_tempfile" ] && [ -f "$attachment" ] && rm "$attachment"
[ "true" = "$verbose" ] && cat "$LOG_FILE"

quit_clean 0
