#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-m message  Message to send to webhook.
	-s          Attach snapshot to the webhook.
	-u url      Webhook URL.
	-v          Verbose output.
	-h          Show this help.
"
	exit 0
}

verbosity="--silent"
while getopts m:su:vh flag; do
	case "$flag" in
		m) webhook_message=$OPTARG ;;
		s) webhook_attach_snapshot="true" ;;
		u) webhook_url=$OPTARG ;;
		v) verbosity="--verbose" ;;
		h | *) show_help ;;
	esac
done

[ -z "$webhook_url" ] && die "Webhook URL not found"

if [ "true" = "$webhook_attach_snapshot" ]; then
	attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$attachment"
	data="-F 'message=$webhook_message' -F 'image=@$attachment'"
else
	data="-d '$webhook_message'"
fi

command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
command="$command $data --url $webhook_url"

sh -c "$command" || die "Failed to send webhook message"

[ -f "$attachment" ] && rm "$attachment"

exit 0
