#!/bin/env sh

SNAPSHOT_FILE="/tmp/snapshot.jpg"
VBUFFER_FILE="/tmp/vbuffer.mov"

CONFIG_FILE="/etc/web.conf"
[ -f "$CONFIG_FILE" ] && . "$CONFIG_FILE"

die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }

show_help() {
	echo "Usage: $0 [options]
Where:
	-t topic    MQTT topic.
	-m message  Message playload.
	-s          Send a snapshot.
	-v          Verbose output.
	-h          Show this help.
"
	exit 0
}

verbosity="--quiet"
while getopts m:st:vh flag; do
	case "$flag" in
		m) mqtt_message=$OPTARG ;;
		s) mqtt_send_snap="true" ;;
		t) mqtt_topic=$OPTARG ;;
		v) verbosity="-d" ;;
		h | *) show_help ;;
	esac
done

[ -z "$mqtt_host" ] && die "MQTT broker host not found in config"
[ -z "$mqtt_port" ] && die "MQTT broker port not found in config"
[ -z "$mqtt_topic" ] && die "MQTT topic not found"
[ -z "$mqtt_message" ] && die "MQTT message template not found"

[ "true" = "$mqtt_send_snap" ] && [ -z "$mqtt_snap_topic" ] && \
	die "MQTT topic for sending snapshot not found in config"

[ -z "$mqtt_client_id" ] && mqtt_client_id="$network_hostname"

mqtt_message=$(date +"$mqtt_message")

command="mosquitto_pub -h $mqtt_host -p $mqtt_port -i $mqtt_client_id"
[ -n "$mqtt_username" ] && command="$command -u $mqtt_username"
[ -n "$mqtt_password" ] && command="$command -P $mqtt_password"

if [ "true" = "$mqtt_send_snap" ]; then
	attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$attachment"
	command="$command -t $mqtt_snap_topic -f \"$attachment\""
else
	command="$command -t $mqtt_topic -m \"$mqtt_message\""
fi

sh -c "$command" || die "Failed to send MQTT message"

[ -f "$attachment" ] && rm "$attachment"

exit 0
