#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-t topic    MQTT topic.
	-m message  Message playload.
	-s          Send a snapshot.
	-v          Verbose output.
	-h          Show this help.
" >&2
	exit 0
}

verbosity="--quiet"
while getopts m:st:vh flag; do
	case "$flag" in
		m) mqtt_message=$OPTARG ;;
		s) mqtt_send_snap="true" ;;
		t) mqtt_topic=$OPTARG ;;
		v) verbosity="-d" ;;
		h | *) show_help ;;
	esac
done

if [ -z "$mqtt_host" ]; then
	echo "MQTT broker host not found in config" >&2
	exit 1
fi

if [ -z "$mqtt_port" ]; then
	echo "MQTT broker port not found in config" >&2
	exit 1
fi

if [ -z "$mqtt_topic" ]; then
	echo "MQTT topic not found" >&2
	exit 1
fi

if [ -z "$mqtt_message" ]; then
	echo "MQTT message template not found" >&2
	exit 1
fi

if [ "true" = "$mqtt_send_snap" ] && [ -z "$mqtt_snap_topic" ]; then
	echo "MQTT topic for sending snapshot not found in config" >&2
	exit 1
fi

if [ -z "$mqtt_client_id" ]; then
	mqtt_client_id="$network_hostname"
fi

mqtt_message=$(date +"$mqtt_message")

command="mosquitto_pub -h $mqtt_host -p $mqtt_port -i $mqtt_client_id"

if [ -n "$mqtt_username" ]; then
	command="$command -u $mqtt_username"
fi

if [ -n "$mqtt_password" ]; then
	command="$command -P $mqtt_password"
fi

if [ "true" = "$mqtt_send_snap" ]; then
	attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$attachment"
	command="$command -t $mqtt_snap_topic -f \"$attachment\""
else
	command="$command -t $mqtt_topic -m \"$mqtt_message\""
fi

if ! sh -c "$command"; then
	echo "Failed to send MQTT message" >&2
	exit 1
fi

[ -f "$attachment" ] && rm "$attachment"

exit 0
