#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-f address  Sender's email address
	-t address  Recipient's email address
	-n host     SMTP server host.
	-p port     SMTP server port.
	-s subject  Subject line.
	-b body     Letter body.
	-k          Ignore SSL certificate validity.
	-v          Verbose output.
	-h          Show this help.
" >&2
	exit 0
}

while getopts b:f:kn:p:s:t:vh flag; do
	case "$flag" in
		b) email_body=$OPTARG ;;
		f) email_from_address=$OPTARG ;;
		k) email_insecure_ssl="true" ;;
		n) email_smtp_host=$OPTARG ;;
		p) email_smtp_port=$OPTARG ;;
		s) email_subject=$OPTARG ;;
		t) email_to_address=$OPTARG ;;
		v) verbose="true" ;;
		h | *) show_help ;;
	esac
done

# validators
[ -z "$email_smtp_host" ] && die "SMTP host not found"
[ -z "$email_from_address" ] && die "Sender's email address not found"
[ -z "$email_to_address" ] && die "Recipient's email address not found"
[ -z "$email_body" ] && die "Email body not found"

echo "$email_from_address" | grep -E -q $EMAIL_FORMAT >/dev/null || die "Invalid sender email address format"
echo "$email_to_address" | grep -E -q $EMAIL_FORMAT >/dev/null || die "Invalid recipient email address format"

# defaults
[ -z "$email_smtp_port" ] && email_smtp_port=25
[ -z "$email_from_name" ] && email_from_name="Thingino Camera"
[ -z "$email_to_name" ] && email_to_name="Thingino Camera Admin"
[ -z "$email_subject" ] && email_subject="Snapshot from Thingino Camera"

# sanitizers
email_body=${email_body//"/\\"}

# command
if [ "true" = "$verbose" ]; then
	command="$CURL --verbose"
else
	command="$CURL --silent"
fi

command="$command --mail-from $email_from_address --mail-rcpt $email_to_address"

if [ -n "$email_smtp_username" ] && [ -n "$email_smtp_password" ]; then
	command="$command --user '$email_smtp_username:$email_smtp_password'"
fi

if [ "true" = "$email_smtp_use_ssl" ]; then
	command="$command --url smtps://$email_smtp_host:$email_smtp_port --ssl"
	[ "true" = "$email_insecure_ssl" ] && command="$command --insecure"
else
	command="$command --url smtp://$email_smtp_host:$email_smtp_port"
fi

command="$command -H 'From: \"$email_from_name\" <$email_from_address>'"
command="$command -H 'To: \"$email_to_name\" <$email_to_address>'"
command="$command -H 'Subject: $email_subject'"
command="$command -F '=(;type=multipart/mixed'"
command="$command -F \"=${email_body};type=text/plain\""

if [ "true" = "$email_attach_snapshot" ]; then
	photo_attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$photo_attachment"
	command="$command -F 'snapshot=@$photo_attachment;type=image/jpeg;encoder=base64'"
fi

if [ "true" = "$email_attach_video" ] && [ -f "$MOTION_VIDEO_FILE" ]; then
	video_attachment="$(mktemp -u).mp4"
	cp -f "$MOTION_VIDEO_FILE" "$video_attachment"
	command="$command -F 'video=@$video_attachment;type=video/mp4;encoder=base64'"
fi

command="$command -F '=)'"

[ "true" = "$verbose" ] && echo_command "$command"

sh -c "$command" || die "Failed to send email"

[ -f "$photo_attachment" ] && rm "$photo_attachment"
[ -f "$video_attachment" ] && rm "$video_attachment"

exit 0
