#!/bin/sh

if [ -t 0 ]; then
	if [ -z "$1" ]; then
		echo "Usage: $0 <command>"
		exit 1
	fi

	file=$(mktemp)
	sh -c "$*" > $file 2>&1
else
	file=$(mktemp)
	cat - > $file
fi

if [ ! -s "$file" ]; then
	echo "File $file is empty"
	exit 1
fi

url=$(nc termbin.com 9999 < $file)
echo $url

rm -f $file

exit 0
