#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-d path     Directory on server.
	-f file     File to upload.
	-u username Yandex Disk username.
	-P password Yandex Disk username.
	-v          Verbose output.
	-h          Show this help.
" >&2
	exit 0
}

verbosity="--silent"
while getopts d:f:P:u:vh flag; do
	case "$flag" in
		d) yadisk_path=$OPTARG ;;
		f) yadisk_file=$OPTARG ;;
		P) yadisk_password=$OPTARG ;;
		u) yadisk_username=$OPTARG ;;
		v) verbosity="--verbose" ;;
		h | *) show_help ;;
	esac
done

if [ -z "$yadisk_username" ]; then
	echo "Yandex Disk username not found" >&2
	exit 1
fi

if [ -z "$yadisk_password" ]; then
	echo "Yandex Disk password not found" >&2
	exit 1
fi

if [ -z "$yadisk_file" ]; then
	attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$attachment"
	yadisk_file=$attachment
fi

command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
command="$command --user '${yadisk_username}:$yadisk_password'"

url="https://webdav.yandex.ru"
yadisk_path=$(date +"$yadisk_path")
yadisk_path=${yadisk_path#/} # drop leading slash
yadisk_path=${yadisk_path%/} # drop trailing slash

# create path to destination directory
subdirs="$yadisk_path"
subdir="${subdir// /%20}" # convert each space into %20
for subdir in ${subdirs//\// }; do
	subdir="${subdirs%%/*}"  # leftmost directory
	suburl="$suburl/$subdir"
	if [ -n "$subdir" ]; then
		sh -c "$command --request MKCOL $url$suburl"
	fi
	subdirs="${subdirs#*/}" # remove the processed directory
done

command="$command --request PUT --upload-file $yadisk_file"
command="$command --url $url/$yadisk_path/$(TZ=$(cat /etc/TZ) date +"%G%m%d-%H%M%S").jpg"

if ! sh -c "$command"; then
	echo "Failed to upload file to Yandex Disk" >&2
	exit 1
fi

[ -f "$attachment" ] && rm "$attachment"

exit 0
