#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-a URL       Attachment URL.
	-c URL       Click URL.
	-f file      Attach file.
	-i URL       Icon URL.
	-m message   Message body.
	-n title     Message title.
	-p N         Priority. 1-lowest, 5-highest.
	-s host      NTFY host.
	-t topic     Topic.
	-u username  Username.
	-w password  Password.
	-v           Verbose output.
	-h           Show this help.
" >&2
	exit 0
}

verbosity="--silent"
while getopts a:c:f:i:l:m:n:p:s:t:u:vh flag; do
	case "$flag" in
		a) ntfy_attach=$OPTARG ;;
		c) ntfy_click=$OPTARG ;;
		f) ntfy_filename=$OPTARG ;;
		i) ntfy_icon=$OPTARG ;;
		m) ntfy_message=$OPTARG ;;
		n) ntfy_title=$OPTARG ;;
		p) ntfy_priority=$OPTARG ;;
		s) ntfy_host=$OPTARG ;;
		t) ntfy_topic=$OPTARG ;;
		u) ntfy_username=$OPTARG ;;
		w) ntfy_password=$OPTARG ;;
		v) verbosity="--verbose" ;;
		h | *) show_help ;;
	esac
done

if [ -z "$ntfy_topic" ]; then
	echo "NTFY topic is not set" >&2
	exit 1
fi

command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
command="$command -H p:${ntfy_priority:-3}"

if [ -n "$ntfy_title" ]; then
	command="$command -H 'Title: $ntfy_title'"
fi

if [ -n "$ntfy_tags" ]; then
	command="$command -H 'Tags: $ntfy_tags'"
fi

if [ -n "$ntfy_delay" ]; then
	command="$command -H 'Delay: $ntfy_delay'"
fi

if [ -n "$ntfy_username" ] && [ -n "$ntfy_password" ]; then
	command="$command -u $ntfy_username:$ntfy_password"
fi

if [ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ]; then
	command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
fi

if [ -n "$ntfy_attach" ]; then
	command="$command -H 'Attach: $ntfy_attach'"
fi

if [ -n "$ntfy_click" ]; then
	command="$command -H 'Click: $ntfy_click'"
fi

if [ -n "$ntfy_icon" ]; then
	command="$command -H 'Icon: $ntfy_icon'"
fi

if [ -n "$ntfy_email" ]; then
	command="$command -H 'Email: $ntfy_email'"
fi

if [ -n "$ntfy_actions" ]; then
	command="$command -H 'Actions: $ntfy_actions'"
fi

if [ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ]; then
	command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
fi

if [ -n "$ntfy_message" ]; then
	command="$command -d '$ntfy_message'"
fi

command="$command ${ntfy_host:-ntfy.sh}/$ntfy_topic"

if ! sh -c "$command"; then
	echo "Failed to send NTFY message" >&2
	exit 1
fi

exit 0
