#!/bin/env sh

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-s host     FTP server FQDN or IP address.
	-p port     FTP server port.
	-d path     Directory on server, relative to FTP root.
	-f file     File to upload.
	-u username FTP username.
	-P password FTP password.
	-v          Verbose output.
	-h          Show this help.
" >&2
	exit 0
}

verbosity="--silent"
while getopts d:f:p:P:s:u:vVh flag; do
	case "$flag" in
		d) ftp_path=$OPTARG ;;
		f) ftp_file=$OPTARG ;;
		p) ftp_port=$OPTARG ;;
		P) ftp_password=$OPTARG ;;
		s) ftp_host=$OPTARG ;;
		u) ftp_user=$OPTARG ;;
		v) verbosity="--verbose" ;;
		V) ftp_sendvideo="true" ;;
		h | *) show_help ;;
	esac
done

if [ -z "$ftp_host" ]; then
	echo_error "FTP host not found"
	exit 1
fi

if [ -z "$ftp_port" ]; then
	ftp_port=21
fi

if [ -z "$ftp_user" ]; then
	ftp_user="anonymous"
	ftp_password="anonymous"
fi

if [ -z "$ftp_file" ]; then
	if [ "true" = "$ftp_sendvideo" ]; then
		attachment=$(mktemp -u).mov
		cp -f "$VBUFFER_FILE" "$attachment"
		ftp_filename=$(date +"$ftp_template").mov
	else
		attachment=$(mktemp -u).jpg
		cp -f "$SNAPSHOT_FILE" "$attachment"
		ftp_filename=$(date +"$ftp_template").jpg
	fi

	ftp_file=$attachment
fi

url="ftp://"
if [ -n "$ftp_user" ] && [ -n "$ftp_password" ]; then
	url="$url$ftp_user:$ftp_password"
fi
url="$url@$ftp_host:$ftp_port"
if [ -n "$ftp_path" ]; then
	url="$url/${ftp_path// /%20}"
fi
url="$url/$ftp_filename"

command="$CURL $verbosity --url $url --upload-file $ftp_file --ftp-create-dirs"
if ! sh -c "$command"; then
	echo_error "Failed to upload file to FTP server"
	exit 1
fi

[ -f "$attachment" ] && rm "$attachment"

exit 0
