#!/bin/sh

. /usr/share/common

file=$(mktemp)

if [ -t 0 ]; then
	[ -z "$1" ] && die "Usage: $0 <command>"
	sh -c "$*" > "$file" 2>&1
else
	cat - > "$file"
fi

[ -s "$file" ] || die "File $file is empty"

curl -s -T - telnet://tb.thingino.com:9999 < "$file"

rm -f "$file"

exit 0
