#!/bin/env sh
# Sends data to ntfy.sh
# https://docs.ntfy.sh/publish/

. /usr/share/common

show_help() {
	echo "Usage: $0 [options]
Where:
	-a URL       Attachment URL.
	-c URL       Click URL.
	-f file      Attach file.
	-h host      Server host.
	-i URL       Icon URL.
	-m message   Message body.
	-n title     Message title.
	-p N         Priority. 1-lowest, 5-highest.
	-s           Send a snapshot.
	-t topic     Topic.
	-u username  Username.
	-w password  Password.
	-v           Verbose output.
" >&2
	exit 0
}

verbosity="false"
while getopts a:c:f:h:i:l:m:n:p:st:u:w:vh flag; do
	case "$flag" in
		a) ntfy_attach=$OPTARG ;;
		c) ntfy_click=$OPTARG ;;
		f) ntfy_filename=$OPTARG ;;
		h) ntfy_host=$OPTARG ;;
		i) ntfy_icon=$OPTARG ;;
		m) ntfy_message=$OPTARG ;;
		n) ntfy_title=$OPTARG ;;
		p) ntfy_priority=$OPTARG ;;
		s) ntfy_send_snap="true" ;;
		t) ntfy_topic=$OPTARG ;;
		u) ntfy_username=$OPTARG ;;
		w) ntfy_password=$OPTARG ;;
		v) verbosity="true" ;;
		*) show_help ;;
	esac
done

if [ -z "$ntfy_host" ]; then
	ntfy_host="ntfy.sh"
	#echo_warning "NFTY host is not set"
fi

if [ -z "$ntfy_port" ]; then
	ntfy_port=80
	#echo_error "NTFY port is not set"
fi

if [ -z "$ntfy_topic" ]; then
	echo_error "NTFY topic is not set"
	exit 1
fi

remove_ntfy_file="false"

# Prepare snapshot as attachment
if [ "true" = "$ntfy_send_snap" ]; then
	ntfy_filename=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$ntfy_filename"
	remove_ntfy_file="true"
fi

command="$CURL -X POST -H p:${ntfy_priority:-3}"
if [ "true" = "$verbosity" ]; then
	command="$command --verbose"
else
	command="$command --silent"
fi

if [ -n "$ntfy_title" ]; then
	command="$command -H 'Title: $ntfy_title'"
fi

if [ -n "$ntfy_tags" ]; then
	command="$command -H 'Tags: $ntfy_tags'"
fi

if [ -n "$ntfy_delay" ]; then
	command="$command -H 'Delay: $ntfy_delay'"
fi

if [ -n "$ntfy_username" ] && [ -n "$ntfy_password" ]; then
	command="$command -u $ntfy_username:$ntfy_password"
fi

if [ "true" = "$ntfy_send_snap" ]; then
	attachment=$(mktemp -u).jpg
	cp -f "$SNAPSHOT_FILE" "$attachment"
	command="$command -T $attachment -H 'Filename: $attachment'"
fi

if [ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ]; then
	command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
fi

if [ -n "$ntfy_attach" ]; then
	command="$command -H 'Attach: $ntfy_attach'"
fi

if [ -n "$ntfy_click" ]; then
	command="$command -H 'Click: $ntfy_click'"
fi

if [ -n "$ntfy_icon" ]; then
	command="$command -H 'Icon: $ntfy_icon'"
fi

if [ -n "$ntfy_email" ]; then
	command="$command -H 'Email: $ntfy_email'"
fi

if [ -n "$ntfy_actions" ]; then
	command="$command -H 'Actions: $ntfy_actions'"
fi

if [ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ]; then
	command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
fi

if [ -n "$ntfy_message" ]; then
	ntfy_message="$(date +"$ntfy_message")"
	command="$command -H 'Message: $ntfy_message'"
fi

command="$command ${ntfy_host:-ntfy.sh}/$ntfy_topic"

if [ "true" = "$verbosity" ]; then
	echo_command "$command"
fi

if ! sh -c "$command"; then
	echo_error "Failed to send NTFY message"
	exit 1
fi

if [ "true" = "$remove_ntfy_file" ] && [ -f "$ntfy_filename" ]; then
	rm "$ntfy_filename"
fi

exit 0
