#!/bin/sh

plugin="ntfy"

. /sbin/common

show_help() {
	echo "Usage: $0 [options]
Where:
  -s host      NTFY host.
  -u username  Username.
  -w password  Password.
  -t topic     Topic.
  -p N         Priority. 1-lowest, 5-highest.
  -n title     Message title.
  -m message   Message body.
  -f [file]    Attach file.
  -a URL       Attachment URL.
  -c URL       Click URL.
  -i URL       Icon URL.
  -v           Verbose output.
  -h           Show this help.
"
	exit 0
}

verbosity="--silent"
# override config values with command line arguments
while getopts a:c:f:i:l:m:n:p:s:t:u:vh flag; do
	case "$flag" in
		a) ntfy_attach=$OPTARG ;;
		c) ntfy_click=$OPTARG ;;
		f) ntfy_filename=$OPTARG ;;
		i) ntfy_icon=$OPTARG ;;
		m) ntfy_message=$OPTARG ;;
		n) ntfy_title=$OPTARG ;;
		p) ntfy_priority=$OPTARG ;;
		s) ntfy_host=$OPTARG ;;
		t) ntfy_topic=$OPTARG ;;
		u) ntfy_username=$OPTARG ;;
		w) ntfy_password=$OPTARG ;;
		v) verbosity="--verbose" ;;
		h | *) show_help ;;
	esac
done

[ -z "$ntfy_topic" ] && die "NTFY topic is not set."

command="curl $verbosity -H p:${ntfy_priority:-3}"
[ -n "$ntfy_title" ] && command="$command -H 'Title: $ntfy_title'"
[ -n "$ntfy_tags" ] || command="$command -H 'Tags: $ntfy_tags'"
[ -n "$ntfy_delay" ] && command="$command -H 'Delay: $ntfy_delay'"
[ -n "$ntfy_username" ] && [ -n "$ntfy_password" ] && command="$command -u $ntfy_username:$ntfy_password"
[ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ] && command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
[ -n "$ntfy_attach" ] && command="$command -H 'Attach: $ntfy_attach'"
[ -n "$ntfy_click" ] && command="$command -H 'Click: $ntfy_click'"
[ -n "$ntfy_icon" ] && command="$command -H 'Icon: $ntfy_icon'"
[ -n "$ntfy_email" ] && command="$command -H 'Email: $ntfy_email'"
[ -n "$ntfy_actions" ] && command="$command -H 'Actions: $ntfy_actions'"
[ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ] && command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
[ -n "$ntfy_message" ] && command="$command -d '$ntfy_message'"
command="$command ${ntfy_host:-ntfy.sh}/$ntfy_topic"

sh -c "$command" || die "Failed to send NTFY message"

exit 0
