#!/bin/env sh

. /usr/share/common

if [ -t 0 ]; then
	if [ -z "$1" ]; then
		echo "Usage: $0 <command>" >&2
		exit 1
	fi

	file=$(mktemp)
	sh -c "$*" > "$file" 2>&1
else
	file=$(mktemp)
	cat - > "$file"
fi

if [ ! -s "$file" ]; then
	echo_error "File $file is empty"
	exit 1
fi

curl -s -T - telnet://tb.thingino.com:9999 < "$file"
rm -f "$file"

exit 0
