#!/bin/sh

params="name chip_id i2c_addr width height min_fps max_fps version"

case "$1" in
	name | chip_id | i2c_addr | width | height | min_fps | max_fps | version)
		cat /proc/jz/sensor/$1
		;;
	all | -a)
		for i in $params; do
			printf '%-10s %s\n' "$i:" $(cat /proc/jz/sensor/$i)
		done
		;;
	*)
		echo "Usage: $0 [${params} all]"
		;;
esac

exit 0
