#!/bin/sh

. /etc/init.d/rc.common

[ "$#" -ne 2 ] && die "Usage: service <start|stop|restart|reload> <servicename>"

ACTION=$1
SERVICE=$2

case "$ACTION" in
	start | stop | reload | restart) true ;;
	*) die "Invalid action: $ACTION" ;;
esac

SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)

[ -z "$SCRIPT" ] && die "Service $SERVICE not found"

$SCRIPT $ACTION || die "Failed to $ACTION $SERVICE"
