#!/bin/sh

. /usr/share/common

if [ "$1" != "list" ] && [ "$#" -ne 2 ]; then
	echo "Usage: $0 <action> <servicename>
Where actions:
	start     Start the service
	stop      Stop the service
	restart   Restart the service
	reload    Reload the service
	enable    Enable the service on boot
	disable   Disable the service on boot
	list      List all services
"
	exit 1
fi

ACTION=$1
SERVICE=$2

SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)
if [ "$1" != "list" ] && [ -z "$SCRIPT" ]; then
	echo "Service $SERVICE not found"
	exit 1
fi

case "$ACTION" in
	start | stop | reload | restart)
		if ! $SCRIPT $ACTION; then
			echo "Failed to $ACTION $SERVICE"
			exit 1
		fi
		;;
	list)
		ls -1 /etc/init.d/[FKS][0-9][0-9]* | \
			awk -F/ '{gsub(/[FKS]\d{2}/,"",$4);print $4}' | sort
		;;
	enable)
		chmod +x $SCRIPT
		;;
	disable)
		chmod -x $SCRIPT
		;;
	*)
		echo "Invalid action: $ACTION"
		exit 1
		;;
esac

exit 0
