#!/bin/sh

KERNEL_MAGIC="27051956"
U_BOOT_MAGIC="06050403"
ROOTFS_MAGIC="68737173"
BB_BINARY=/tmp/busybox

downloaded_file=0  # Flag to track if the file was downloaded

if [ -z "$RUNNING_WITH_TMP_BUSYBOX" ]; then
	if [ ! -f /tmp/busybox ]; then
		cp /bin/busybox /tmp/busybox
		cp $0 /tmp/sysupgrade
		cp /sbin/fw_printenv /tmp/fw_printenv
		ln -s /tmp/fw_printenv /tmp/fw_setenv
	fi

	RUNNING_WITH_TMP_BUSYBOX=1 exec /tmp/busybox sh /tmp/sysupgrade "$@"
fi

show_help() {
	echo "Usage: $0 <filename> | [-f | -p] | <URL>
Where:
  -f          full upgrade with a binary from GitHub
  -p          partial upgrade with a binary from GitHub
  <filename>  full or partial upgrade from a local file
  <URL>       full or partial upgrade from a URL
  -h          this help
"
}

stop_service() {
	if [ ! -f "/etc/init.d/$1" ]; then
		echo "Not found"
		return
	fi
	/etc/init.d/"$1" stop
}

verify_checksum() {
	checksum_url="${checksum_url}/${sha256_file}"

	checksum_file=$(mktemp)
	echo "Downloading SHA-256 checksum from $checksum_url"
	if ! curl -# -L -f -o "$checksum_file" "$checksum_url"; then
		echo "Failed to download checksum from $checksum_url"
		exit 1
	fi

	# Extract the expected checksum (first field) from the downloaded file
	expected_checksum=$(awk '{print $1}' "$checksum_file")
	actual_checksum=$($BB_BINARY sha256sum "$binary_file" | awk '{print $1}')

	if [ "$expected_checksum" = "$actual_checksum" ]; then
		echo "SHA-256 checksum verification succeeded."
	else
		echo "SHA-256 checksum verification failed! Firmware file might be corrupted."
		exit 1
	fi
}

reboot_func() {
	echo "Rebooting in 5 seconds..."
	sleep 5
	echo wdt > /proc/jz/reset/reset
}

stop_services() {
	services="S01syslogd S09motor S15thingino-button S49ntpd S50httpd S50crond S50mdnsd S50mosquitto S93telegrambot S95prudynt S96iad S96onvif"
	for service in $services; do
		stop_service "$service"
	done
}

flush_memory(){
	echo "Sync changes"
	sync

	echo "Drop caches"
	echo 3 > /proc/sys/vm/drop_caches
}

flash_firmware() {
	$BB_BINARY flashcp -v $binary_file /dev/$mtd_dev

	if [ $? -ne 0 ]; then
		echo "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
		exit 1
	fi

	[ "mtd5" = "$mtd_dev" ] && /tmp/fw_setenv sysupgrade_complete false

	echo "Upgrade complete."
	reboot_func
}

cleanup() {
	echo "Clean up temporary files."

	# Only delete files that were downloaded (flag = 1)
	[ "$downloaded_file" -eq 1 ] && [ -n "$binary_file" ] && [ -f "$binary_file" ] && rm -f "$binary_file"
	[ -n "$checksum_file" ] && [ -f "$checksum_file" ] && rm -f "$checksum_file"
	rm -f /tmp/busybox /tmp/fw_setenv /tmp/fw_printenv /tmp/sysupgrade
}

# Trap signals to ensure cleanup on exit
trap cleanup EXIT INT TERM

while getopts "fhp" flag; do
	case "$flag" in
		f)
			upgrade="full"
			;;
		p)
			upgrade="part"
			;;
		h|*)
			show_help
			exit 1
			;;
	esac
done

if [ -z "$upgrade" ]; then
	if [ -z "$1" ]; then
		show_help
		exit 1
	fi
	upgrade="local"
fi

shift $((OPTIND-1))

echo "Stop services"
stop_services

echo "Remove snapshot"
rm -f /tmp/snapshot.jpg

flush_memory

if [ "local" = "$upgrade" ]; then
	echo "Upgrading from a provided file"
	if echo "$1" | grep -qE '^https?://'; then
		binary_file=$(mktemp)
		echo "Downloading firmware from $1"
		if ! curl -# -L -f -o "$binary_file" "$1"; then
			echo "Failed to download firmware from $1"
			exit 1
		fi
		downloaded_file=1  # Set flag indicating the file was downloaded
	else
		binary_file="$1"
	fi
else
	echo "Upgrading from GitHub"
	data=/etc/os-release
	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
	if [ -z "$profile" ]; then
		echo "Building profile is not set in $data"
		exit 1
	fi

	url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
	checksum_url="https://github.com/themactep/thingino-firmware/releases/download/verify"

	if [ "$upgrade" = "part" ]; then
		fw_file="_update/thingino-${profile}-update.bin"
		sha256_file="thingino-${profile}-update.bin.sha256sum"
	else
		fw_file="/thingino-${profile}.bin"
		sha256_file="thingino-${profile}.bin.sha256sum"
	fi

	binary_file=$(mktemp) # Create a temporary file to hold the firmware
	echo "Downloading firmware from ${url}${fw_file}."
	if ! curl -# -L -f -o "$binary_file" ${url}"${fw_file}"; then
		echo "Failed to download firmware from ${url}${fw_file}"
		exit 1
	fi

	downloaded_file=1  # Set flag indicating the file was downloaded

	verify_checksum
fi

# Detect magic directly from the binary file
internal_magic=$(xxd -l 4 -p "$binary_file")

case "$internal_magic" in
	"$U_BOOT_MAGIC")
		fsize=$(stat -c%s "$binary_file")
		if [ "$fsize" -le $((256 * 1024)) ]; then
			mtd_dev="mtd0"
		else
			mtd_dev="mtd6"
		fi
		;;
	"$KERNEL_MAGIC")
		mtd_dev="mtd5"
		;;
	"$ROOTFS_MAGIC")
		echo "We cannot flash only rootfs"
		exit 1
		;;
	*)
		echo "Unknown file"
		exit 1
		;;
esac

if ! grep -q -e "mtd6" -e "mtd5" /proc/mtd; then
	echo "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
	exit 1
fi

echo "Unmount overlay"
umount /overlay

echo "Unmount rootfs"
umount /

flush_memory
echo -e "\nPerforming upgrade\nDo not turn off the power!\n"
flash_firmware

exit 0
