#!/bin/sh

output_file="/tmp/support.txt"
width=46

center_text() {
	local text="$1"
	local text_length=${#text}
	local border="=============================================="
	local padding=$(( (width - text_length - 2) / 2 ))
	local left_border=${border:0:padding}
	local right_border=${border:0:(width - padding - text_length - 2)}
	echo "${border}"
	echo "${left_border} ${text} ${right_border}"
	echo "${border}"
}

echo "thingino diagnostics"
echo "This script requires network access."
echo "It is designed to generate log information to share with developers for diagnostic issues."
echo "It may contain sensitive or personal information, so make sure to review the log before sharing the link!"
echo -e "We use termbin to share the log. Please review their acceptable use policy at https://www.termbin.com\n"
read -p "Do you wish to proceed? (yes/no): " response

if [ "$response" != "yes" ]; then
	echo "Operation aborted by the user."
	exit 1
fi

{
	date
	uname -a
	center_text "THINGINO"
	cat /etc/os-release
	center_text "DMESG"
	dmesg
	center_text "SYSLOG"
	logread
	center_text "LOGCAT"
	logcat
	center_text "PS"
	ps aux
	center_text "DF"
	df -h
	center_text "IPC"
	ipcs
	center_text "KMOD"
	lsmod
	center_text "KMOD-2"
	for file in /etc/modules.d/*; do echo "== $file =="; cat "$file"; done
	center_text "USB"
	lsusb
	center_text "MEMORY"
	free -h
	center_text "LSOF"
	lsof
	center_text "MOUNT"
	mount
	center_text "GPIO"
	gpio list
	center_text "ENV"
	fw_printenv | awk -F'=' '{if (/wlanpass|sshkey|ssh_authorized_keys|root_pw_hash|wlanmac|ethaddr|gatewayip|ipaddr|serverip/) print $1 "=REDACTED"; else print}' | sort
	center_text "CMDLINE"
	cat /proc/cmdline

	center_text "CLOCKS"
	cat /proc/jz/clock/clocks

	if [ -f /proc/jz/isp/isp-m0 ]; then
		center_text "isp-fs"
		cat /proc/jz/isp/isp-fs
	fi

	if [ -f /proc/jz/isp/isp-m0 ]; then
		center_text "isp-m0"
		cat /proc/jz/isp/isp-m0
	fi

	if [ -f /proc/jz/isp/isp_info ]; then
		center_text "isp_info"
		cat /proc/jz/isp/isp_info
	fi

	center_text "sensor"
	sensor -a
} > $output_file

echo -e "\nYour diagnostics log link is ready:"
send2termbin cat $output_file
rm -f $output_file

