#!/bin/sh

header() {
	local border="=============================================="
	local width=46
	local text="$1"
	local text_length=${#text}
	local padding=$(((width - text_length - 2) / 2))
	local left_border=${border:0:padding}
	local right_border=${border:0:(width - padding - text_length - 2)}
	echo -e "$border\n$left_border $text $right_border\n$border"
}

infocat() {
	[ -f "$1" ] || return
	[ -n "$2" ] && header "$2"
	cat $1
}

inforun() {
	[ -n "$2" ] && header "$2"
	eval $1
}

echo "thingino diagnostics"
echo "This script requires network access."
echo "It is designed to generate log information to share with developers for diagnostic issues."
echo "It may contain sensitive or personal information, so make sure to review the log before sharing the link!"
echo "We use termbin to share the log. Please review their acceptable use policy at https://www.termbin.com/"
echo
read -p "Do you wish to proceed? (yes/no): " response
if [ "yes" != "$response" ]; then
	echo "Operation aborted by the user."
	exit 1
fi

output_file=$(mktemp)
{
	inforun "date"
	inforun "uptime"
	inforun "uname -a"
	inforun "grep -a \"Ingenic U-Boot Flex\" /dev/mtd0"
	infocat "/etc/os-release" "THINGINO"
	inforun "soc -w" "SOC"
	inforun "dmesg" "DMESG"
	inforun "logread" "SYSLOG"
	inforun "logcat" "LOGCAT"
	inforun "ps" "PS"
	inforun "df -h" "DF"
	inforun "ipcs" "IPC"
	inforun "lsmod" "KMOD"

	header "KMOD-2"
	for file in /etc/modules.d/*; do echo "== $file =="; cat "$file"; done

	inforun "lsusb" "USB"
	inforun "free -h" "MEMORY"
	inforun "lsof" "LSOF"
	inforun "mount" "MOUNT"
	inforun "gpio list" "GPIO"

	header "ENV"
	fw_printenv | awk -F'=' '{if (/ethaddr|gatewayip|ipaddr|root_pw_hash|serverip|ssh_authorized_keys|sshkey|wlanmac|wlanpass/) print $1 "=REDACTED"; else print}' | sort

	infocat "/proc/cmdline" "CMDLINE"
	infocat "/proc/jz/clock/clocks" "CLOCKS"
	infocat "/proc/jz/isp/isp-fs" "isp-fs"
	infocat "/proc/jz/isp/isp-m0" "isp-m0"
	infocat "/proc/jz/isp/isp_info" "isp_info"
	infocat "/tmp/continuous_mem_info" "libimp meminfo"

	inforun "sensor -a" "sensor"

	header "streamer"
	awk -F':' '{if (/password/) print $1 " REDACTED"; else print}' /etc/prudynt.cfg

	infocat "/etc/crontabs/root" "crontab"
} > $output_file

url=$(cat $output_file | send2termbin)
rm -f $output_file

echo
if [ -z "$url" ]; then
	echo "There was an error."
	exit 1
fi

echo "Your diagnostics log link:"
echo $url

exit 0
