#!/bin/sh

output_file="/tmp/support.txt"
width=46

center_text() {
	local text="$1"
	local text_length=${#text}
	local border="=============================================="
	local padding=$(( (width - text_length - 2) / 2 ))
	local left_border=${border:0:padding}
	local right_border=${border:0:(width - padding - text_length - 2)}
	echo "${border}"
	echo "${left_border} ${text} ${right_border}"
	echo "${border}"
}

echo "thingino diagnostics"
echo "This script requires network access."
echo "It is designed to generate log information to share with developers for diagnostic issues."
echo "It may contain sensitive or personal information."
read -p "Do you wish to proceed? (yes/no): " response

if [ "$response" != "yes" ]; then
	echo "Operation aborted by the user."
	exit 1
fi

{
	date
	uname -a
	center_text "THINGINO"
	cat /etc/os-release
	center_text "DMESG"
	dmesg
	center_text "SYSLOG"
	logread
	center_text "LOGCAT"
	logcat
	center_text "PS"
	ps aux
	center_text "DF"
	df -h
	center_text "IPC"
	ipcs
	center_text "KMOD"
	lsmod
	center_text "USB"
	lsusb
	center_text "MEMORY"
	free -h
	center_text "LSOF"
	lsof
	center_text "MOUNT"
	mount
	center_text "GPIO"
	gpio list
	center_text "JZ"

	if [ -f /proc/jz/isp/isp-m0 ]; then
		echo "isp-fs:"
		cat /proc/jz/isp/isp-fs
	fi

	if [ -f /proc/jz/isp/isp-m0 ]; then
		echo "isp-m0:"
		cat /proc/jz/isp/isp-m0
	fi

	if [ -f /proc/jz/isp/isp_info ]; then
		echo "isp_info:"
		cat /proc/jz/isp/isp_info
	fi

	echo "sensor:"
	sensor -a
} > $output_file

echo "Your diagnostics log link is ready:"
send2pastebin cat $output_file
rm -f $output_file


