#!/bin/sh
# Grabs a snapshot for timelapse by cron

. /usr/share/common

hesitate() {
	echo_warning "$1"
	sleep 5
	exit 0
}

# drop trailing slashes
timelapse_mount=${timelapse_mount%/}
timelapse_device_path=${timelapse_device_path%/}

if [ -z "$timelapse_mount" ]; then
	echo_error "'timelapse_mount' is not set"
	exit 1
fi

# wait for mount point
if ! mountpoint -q "$timelapse_mount" >/dev/null; then
	hesitate "$timelapse_mount is not mounted"
fi

if [ ! -w "$timelapse_mount" ]; then
	hesitate "$timelapse_mount is not writable"
fi

# storage directory
timelapse_storage="$timelapse_mount/$timelapse_device_path"
ensure_dir "$timelapse_storage"

if [ -z "$timelapse_depth" ]; then
	timelapse_depth=7
fi

if [ -z "$timelapse_filename" ]; then
	timelapse_filename="%Y/%m/%d/%H%M.jpg"
fi

if [ -z "$timelapse_interval" ]; then
	timelapse_interval=1
fi

# delete older files
find "$timelapse_storage" -type f -name '*.jpg' -mtime +$timelapse_depth -delete

# delete empty directories
find "$timelapse_storage" -mindepth 1 -type d -empty -delete

target="$timelapse_storage/$(date +"$timelapse_filename")"
ensure_dir "$(dirname "$target")"
cp -f "$SNAPSHOT_FILE" "$target"

exit 0
