#!/bin/sh

. /etc/init.d/rc.common

wlandev=$(get wlandev)
[ -z "$wlandev" ] && die "wlandev is empty, exit."

echo_c 208 "Thingino Wi-Fi setup"
echo "Wi-Fi driver: $(echo_c 10 $wlandev)"
read -p "Enter Wi-Fi SSID: " ssid
while :; do
	read -p "Enter Wi-Fi Password: " password
	[ ${#password} -ge 8 ] && [ ${#password} -le 64 ] && break
	echo_c 160 "Passwords is not between 8 and 64 characters. Please try again."
done

fw_setenv wlanssid "$ssid"
fw_setenv wlanpass "$password"

echo_c 40 "Wi-Fi settings updated. Please restart for changes to take effect.\n"

exit 0
