#!/bin/sh
# Add this camera's buttons from its thingino.json to a 4.4 kernel device tree.
# The camera's pins are board-specific while the tree is per-SoC, so they are
# generated into this build's copy. The vendor trees also carry the dev board's
# keys (power, boot select) as "gpio_keys: gpio_keys"; thingino-linux drops
# them from the trees it builds, and they are deleted here if a tree still has
# them, since gpio-keys would otherwise claim those pins on every camera.
#
# A camera profile's own .dts is usually a decompiled dtb: it has no labels, so
# its GPIO banks are referenced by phandle and its gpio_keys node is deleted by
# name. Those trees still carry the dev board's keys, or the camera's button
# under another key code.
#
# Key codes match thingino-button.conf and the 3.10 gpio-userkeys module:
# gpio.button_reset is KEY_ENTER, gpio.chime is KEY_1. Buttons pull the pin to
# ground against a pull-up, so they are active-low with the pull-up enabled.
# Numeric gpio flags are emitted (GPIO_ACTIVE_LOW=1, INGENIC_GPIO_PULLUP=2) so
# the fragment needs no dt-bindings include.
#
# The node's "label" names the input device "gpio-keys", which thingino-button
# auto-detects (needs the gpio_keys label support in thingino-linux).
#
# Usage: inject-button-dt.sh <thingino.json> <linux-dir>
set -e

JSON="$1"
LINUX="$2"
DTSDIR="$LINUX/arch/mips/boot/dts/ingenic"
[ -f "$DTSDIR/Makefile" ] && [ -f "$LINUX/.config" ] || exit 0

# Print the fragment for tree $1; the buttons it adds go to stderr.
fragment() {
	python3 - "$JSON" "$1" <<'PY'
import json, os, re, sys

conf, dts = sys.argv[1], sys.argv[2]
src = open(dts).read()

keys = []
if os.path.isfile(conf):
    g = json.load(open(conf)).get("gpio", {})
    for name, key, code in (("reset", "button_reset", 28), ("chime", "chime", 2)):
        v = g.get(key)
        pin = v.get("pin") if isinstance(v, dict) else v
        if isinstance(pin, int) and not isinstance(pin, bool) and 0 <= pin < 192:
            keys.append((name, code, pin))


# A bank node in this file is a decompiled one; otherwise the label comes
# from the SoC .dtsi the tree includes.
def bank(gp):
    for m in re.finditer(r"^(\t+)%s(@\S+)?\s*\{(.*?)^\1\};" % gp, src, re.M | re.S):
        p = re.search(r"^\s*phandle\s*=\s*<(\w+)>;", m.group(3), re.M)
        if "gpio-controller" in m.group(3):
            return p and p.group(1)
    return "&" + gp


print("/* Generated by thingino-button from thingino.json. */")
if re.search(r"^\s*gpio_keys\s*:", src, re.M):
    print("/delete-node/ &gpio_keys;")
for node in re.findall(r"^\t(gpio[-_]keys)\s*\{", src, re.M):
    print("/ {\n\t/delete-node/ %s;\n};" % node)

added, body = [], ""
for name, code, pin in keys:
    gp = "gp" + "abcdef"[pin // 32]
    ref = bank(gp)
    if not ref:
        print("thingino-button: %s: %s has no phandle, %s skipped"
              % (os.path.basename(dts), gp, name), file=sys.stderr)
        continue
    body += ("\n\t\t%s {\n\t\t\tlabel = \"%s\";\n\t\t\tlinux,code = <%d>;\n"
             "\t\t\tgpios = <%s %d 1 2>;\t/* GPIO_ACTIVE_LOW, INGENIC_GPIO_PULLUP */\n"
             "\t\t};\n" % (name, name, code, ref, pin % 32))
    added.append("%s=gpio%d" % (name, pin))
if body:
    sys.stdout.write("\n/ {\n\tgpio-keys {\n\t\tcompatible = \"gpio-keys\";\n"
                     "\t\tlabel = \"gpio-keys\";\n" + body + "\t};\n};\n")
print("thingino-button: %s buttons: %s"
      % (os.path.basename(dts), " ".join(added) or "none"), file=sys.stderr)
PY
}

# The trees this kernel config builds, from the dtb-$(CONFIG_...) lines.
# shellcheck disable=SC2016
sed -n 's/^dtb-\$(\(CONFIG_[A-Z0-9_]*\))[[:space:]]*+=[[:space:]]*\([^[:space:]]*\)\.dtb.*/\1 \2/p' "$DTSDIR/Makefile" | while read -r opt name; do
	grep -q "^$opt=y" "$LINUX/.config" || continue
	dts="$DTSDIR/$name.dts"
	[ -f "$dts" ] || continue

	inc="$name-thingino-buttons.dtsi"
	# Rewritten only on change, so an unchanged board does not rebuild the dtb.
	fragment "$dts" >"$DTSDIR/$inc.tmp"
	if cmp -s "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"; then
		rm -f "$DTSDIR/$inc.tmp"
	else
		mv "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"
	fi
	grep -q "#include \"$inc\"" "$dts" || printf '\n#include "%s"\n' "$inc" >>"$dts"
done
exit 0
