#!/bin/sh
# Add this camera's buttons from its thingino.json to a 4.4 kernel device tree.
# The camera's pins are board-specific while the tree is per-SoC, so they are
# generated into this build's copy. The vendor trees also carry the dev board's
# keys (power, boot select) as "gpio_keys: gpio_keys"; thingino-linux drops
# them from the trees it builds, and they are deleted here if a tree still has
# them, since gpio-keys would otherwise claim those pins on every camera.
#
# Key codes match thingino-button.conf and the 3.10 gpio-userkeys module:
# gpio.button_reset is KEY_ENTER, gpio.chime is KEY_1. Buttons pull the pin to
# ground against a pull-up, so they are active-low with the pull-up enabled.
# Numeric gpio flags are emitted (GPIO_ACTIVE_LOW=1, INGENIC_GPIO_PULLUP=2) so
# the fragment needs no dt-bindings include.
#
# The node's "label" names the input device "gpio-keys", which thingino-button
# auto-detects (needs the gpio_keys label support in thingino-linux).
#
# Usage: inject-button-dt.sh <thingino.json> <linux-dir>
set -e

JSON="$1"
LINUX="$2"
DTSDIR="$LINUX/arch/mips/boot/dts/ingenic"
[ -f "$DTSDIR/Makefile" ] && [ -f "$LINUX/.config" ] || exit 0

# "<name> <keycode> <gpio>" per button the board defines.
keys=""
if [ -f "$JSON" ]; then
	keys=$(
		python3 - "$JSON" <<'PY'
import json, sys
g = json.load(open(sys.argv[1])).get("gpio", {})
for name, key, code in (("reset", "button_reset", 28), ("chime", "chime", 2)):
    v = g.get(key)
    pin = v.get("pin") if isinstance(v, dict) else v
    if isinstance(pin, int) and not isinstance(pin, bool) and 0 <= pin < 192:
        print(name, code, pin)
PY
	)
fi

# $1 = 1 when the tree has the dev board's gpio_keys node to delete
fragment() {
	echo "/* Generated by thingino-button from thingino.json. */"
	[ "$1" = 1 ] && echo "/delete-node/ &gpio_keys;"
	[ -n "$keys" ] || return 0
	printf '\n/ {\n\tgpio-keys {\n\t\tcompatible = "gpio-keys";\n\t\tlabel = "gpio-keys";\n'
	echo "$keys" | while read -r btn code pin; do
		bank=$(echo abcdef | cut -c$((pin / 32 + 1)))
		printf '\n\t\t%s {\n' "$btn"
		printf '\t\t\tlabel = "%s";\n' "$btn"
		printf '\t\t\tlinux,code = <%s>;\n' "$code"
		printf '\t\t\tgpios = <&gp%s %s 1 2>;\t/* GPIO_ACTIVE_LOW, INGENIC_GPIO_PULLUP */\n' "$bank" "$((pin % 32))"
		printf '\t\t};\n'
	done
	printf '\t};\n};\n'
}

# The trees this kernel config builds, from the dtb-$(CONFIG_...) lines.
# shellcheck disable=SC2016
sed -n 's/^dtb-\$(\(CONFIG_[A-Z0-9_]*\))[[:space:]]*+=[[:space:]]*\([^[:space:]]*\)\.dtb.*/\1 \2/p' "$DTSDIR/Makefile" | while read -r opt name; do
	grep -q "^$opt=y" "$LINUX/.config" || continue
	dts="$DTSDIR/$name.dts"
	[ -f "$dts" ] || continue

	inc="$name-thingino-buttons.dtsi"
	if grep -q '^[[:space:]]*gpio_keys:' "$dts"; then
		devboard=1
	else
		devboard=0
	fi
	# Rewritten only on change, so an unchanged board does not rebuild the dtb.
	fragment "$devboard" >"$DTSDIR/$inc.tmp"
	if cmp -s "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"; then
		rm -f "$DTSDIR/$inc.tmp"
	else
		mv "$DTSDIR/$inc.tmp" "$DTSDIR/$inc"
	fi
	grep -q "#include \"$inc\"" "$dts" || printf '\n#include "%s"\n' "$inc" >>"$dts"

	summary=$(echo "$keys" | awk 'NF {printf "%s%s=gpio%s", sep, $1, $3; sep = " "}')
	echo "thingino-button: $name.dts buttons: ${summary:-none}"
done
exit 0
