#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic
SOC=$(ipcinfo -f || fw_printenv -n soc)

echo 1 >/proc/sys/vm/overcommit_memory

check_return() {
	if [ $? -ne 0 ]; then
		echo err: $1
		echo exit
		exit
	fi
}

log() {
	logger -s -p daemon.info -t ingenic "$1"
}

if ! grep -q "^sinfo" /proc/modules; then
	modprobe sinfo
	check_return "modprobe sinfo"
fi

if fw_printenv -n sensor >/dev/null; then
	export SENSOR=$(fw_printenv -n sensor)
	log "Get data from environment and set SENSOR as ${SENSOR}"
else
	echo 1 >/proc/jz/sinfo/info
	check_return "start sinfo"
	SENSOR_INFO=$(cat /proc/jz/sinfo/info)
	check_return "get sensor type"
	SENSOR=${SENSOR_INFO#*:}
	if [ "sensor not found" = "$SENSOR" ]; then
		unset SENSOR
		fw_setenv sensor
	else
		log "Get data from sinfo and set SENSOR as ${SENSOR}"
		fw_setenv sensor $SENSOR && log "Write detected ${SENSOR} to U-Boot ENV"
	fi
fi

case "$SENSOR" in
	imx307)
		AVPU_PARAM="clk_name=mpll avpu_clk=550000000"
		ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
		SENSOR_PARAM=""
		;;
	imx335)
		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
		ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
		SENSOR_PARAM=""
		;;
	imx415)
		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
		ISP_PARAM="isp_clk=350000000"
		SENSOR_PARAM=""
		;;
	*)
		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
		ISP_PARAM="isp_clk=350000000"
		SENSOR_PARAM=""
		;;
esac

echo --------------------
echo "AVPU_PARAM: ${AVPU_PARAM}"
echo "ISP_PARAM: ${ISP_PARAM}"
echo "SENSOR: ${SENSOR}"
echo "SENSOR_PARAM: ${SENSOR_PARAM}"
echo --------------------

if ! grep -q "^avpu" /proc/modules; then
	modprobe avpu $AVPU_PARAM
	check_return "insmod avpu"
fi

if ! grep -q "^tx_isp" /proc/modules; then
	modprobe tx-isp-${SOC} $ISP_PARAM
	check_return "modprobe isp drv"
fi

if ! grep -q "^${SENSOR}" /proc/modules; then
	modprobe sensor_${SENSOR}_${SOC} $SENSOR_PARAM
	check_return "modprobe sensor drv"
fi

if ! grep -q "^audio" /proc/modules; then
	modprobe audio spk_gpio=-1
	check_return "modprobe audio"
fi

if ! grep -q "^gpio" /proc/modules; then
	modprobe gpio
	check_return "modprobe gpio"
fi

if grep -q "^gpio" /proc/modules; then
	for GPIO in ".nightMode.irCutPin1 .nightMode.irCutPin2 .nightMode.irSensorPin .nightMode.backlightPin .audio.speakerPin"; do
		G=$(yaml-cli -g $GPIO)
		[ ! -z "$G" ] && echo $G > /proc/gpio_claim/gpio
	done
fi
