#!/bin/sh

DAEMON=wsd_simple_server

. /etc/init.d/rc.common

model=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' /etc/os-release)
firmware_ver=$(awk -F '[:=, ]+' '/^BUILD_ID=/ {print $2}' /etc/os-release)
serial_num=$(fw_printenv -n ethaddr)
iface=$(awk '$2 == "00000000" && $3 != "00000000" {print $1}' /proc/net/route)
username=$(awk -F '"' '/username:/ {print $2}' /etc/prudynt.cfg)
password=$(awk -F '"' '/password:/ {print $2}' /etc/prudynt.cfg)

COMMAND="$DAEMON --pid_file /var/run/$DAEMON.pid --if_name $iface --xaddr "http://%s/onvif/device_service" -m $model -n thingino"

update_config() {
	local key=$1 value=$2 file="/etc/onvif.conf"
	local current=$(awk -F "=" -v key="$key" '$1==key {print $2}' $file)

	if [ "$current" != "$value" ]; then
		sed -i "s/^$key=.*/$key=$value/" $file
	fi
}

start() {
	starting "ONVIF"
	is_streamer_disabled && echo "Disabled" && exit 0
	start_daemon

	update_config "model" "$model"
	update_config "firmware_ver" "$firmware_ver"
	update_config "serial_num" "$serial_num"
	update_config "ifs" "$iface"
	update_config "user" "$username"
	update_config "password" "$password"
}

stop() {
	stopping "ONVIF"
	is_streamer_disabled && echo "Disabled" && exit 0
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
