#!/bin/sh

DAEMON=wsd_simple_server

. /etc/init.d/rc.common

# needed for args
iface=$(awk '($2~/0{8}/&&$3!~/0{8}/){print $1;exit}' /proc/net/route); [ -z "$iface" ] && iface="wlan0"
model=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' /etc/os-release)

# extract iface for daemon from onvif.conf
DAEMON_ARGS="--if_name $(awk -F= '/^ifs=/{print $2}' /etc/onvif.conf) --xaddr http://%s/onvif/device_service -m $model -n thingino --pid_file /var/run/$DAEMON_SHORT.pid"

# read web config, create if missing
ONVIF_WEBUI_CONF=/etc/webui/onvif.conf
[ ! -d $(dirname $ONVIF_WEBUI_CONF) ] && mkdir -p $(dirname $ONVIF_WEBUI_CONF)
[ ! -f $ONVIF_WEBUI_CONF ] && touch $ONVIF_WEBUI_CONF
. $ONVIF_WEBUI_CONF

# default to "enabled" and update config
if [ -z "$onvif_enabled" ]; then
	onvif_enabled="true"
	echo "onvif_enabled=$onvif_enabled" >> $ONVIF_WEBUI_CONF
fi

is_onvif_disabled() {
	[ "true" != "$onvif_enabled" ]
}

update_config() {
	local key=$1 value=$2 file="/etc/onvif.conf"
	local current=$(awk -F "=" -v key="$key" '$1==key {print $2}' $file)
	[ "$current" = "$value" ] || sed -i "s!^$key=.*!$key=$value!" $file
}

start() {
	starting "ONVIF"
	is_gateway_reachable || quit "Disabled"
	is_streamer_disabled && quit "Streamer disabled"
	is_onvif_disabled && quit "ONVIF disabled"
	start_daemon

	if ! grep -q "^# GENERATED" "/etc/onvif.conf"; then
		update_config "model" "$model"
		update_config "hardware_id" "ingenic_$(soc -m)"
		update_config "serial_num" "$(get ethaddr)"
		update_config "firmware_ver" "$(awk -F '[:=, "]+' '/^BUILD_ID=/ {print $2}' /etc/os-release)"
		update_config "ifs" "$iface"
		update_config "user" "$(awk -F '"' '/username:/ {print $2}' /etc/prudynt.cfg)"
		update_config "password" "$(awk -F '"' '/password:/ {print $2}' /etc/prudynt.cfg)"
		update_config "ptz" "$([ -n "$(fw_printenv -n gpio_motor_h)" ] && echo 1 || echo 0)"
		update_config "max_step_x" "$(get motor_maxstep_h)"
		update_config "max_step_y" "$(get motor_maxstep_v)"
		update_config "move_right" "motors -d h -x $(get motor_maxstep_h) > /dev/null"
		update_config "move_up" "motors -d h -y $(get motor_maxstep_v) > /dev/null"
		sed -i '1i # GENERATED On '"$(date)" /etc/onvif.conf
	fi
}

stop() {
	stopping "ONVIF"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
