#!/bin/sh

DAEMON=wsd_simple_server
ONVIF_CONFIG=/etc/onvif.conf
ONVIF_WEBUI_CONF=/etc/webui/onvif.conf
OS_RELEASE=/etc/os-release
PRUDYNT_CONFIG=/etc/prudynt.cfg

. /etc/init.d/rc.common

iface="$(iface_default)"

model=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $OS_RELEASE)

# extract iface for daemon from onvif.conf
DAEMON_ARGS="--if_name $iface --xaddr http://%s/onvif/device_service -m $model -n thingino --pid_file /var/run/$DAEMON_SHORT.pid"

# read web config, create if missing
[ -d $(dirname $ONVIF_WEBUI_CONF) ] || mkdir -p $(dirname $ONVIF_WEBUI_CONF)
[ -f $ONVIF_WEBUI_CONF ] || touch $ONVIF_WEBUI_CONF
. $ONVIF_WEBUI_CONF

# default to "enabled" and update config
if [ -z "$onvif_enabled" ]; then
	onvif_enabled="true"
	echo "onvif_enabled=$onvif_enabled" >> $ONVIF_WEBUI_CONF
fi

is_onvif_disabled() {
	[ "true" != "$onvif_enabled" ]
}

update_config() {
	local file=$1
	local key=$2
	local value=$3
	local current=$(awk -F= -v key="$key" '$1==key {print $2}' $file)
	[ -z "$value" ] && value="0"
	[ "$current" = "$value" ] && return
	sed -i "s/^$key=.*/$key=$value/" $file
}

start() {
	starting "ONVIF discovery"
	is_gateway_reachable || quit "Disabled"
	is_streamer_disabled && quit "Streamer disabled"
	is_onvif_disabled && quit "ONVIF discovery disabled"
	start_daemon

	grep -q "^# GENERATED" $ONVIF_CONFIG && return

	tempfile=$(mktemp -u)
	cp $ONVIF_CONFIG $tempfile
	update_config $tempfile "model" "$model"
	update_config $tempfile "hardware_id" "ingenic_$(soc -m)"
	update_config $tempfile "serial_num" "$(fw_printenv -n ethaddr)"
	update_config $tempfile "firmware_ver" "$(awk -F '[:=, "]+' '/^BUILD_ID=/ {print $2}' $OS_RELEASE)"
	update_config $tempfile "ifs" "$iface"
	update_config $tempfile "user" "$(awk -F '"' '/username:/ {print $2}' $PRUDYNT_CONFIG)"
	update_config $tempfile "password" "$(awk -F '"' '/password:/ {print $2}' $PRUDYNT_CONFIG)"
	update_config $tempfile "ptz" "$([ -n "$(fw_printenv -n gpio_motor_h)" ] && echo 1 || echo 0)"
	update_config $tempfile "max_step_x" "$(fw_printenv -n motor_maxstep_h)"
	update_config $tempfile "max_step_y" "$(fw_printenv -n motor_maxstep_v)"
	update_config $tempfile "move_right" "motors -d h -x $(fw_printenv -n motor_maxstep_h)"
	update_config $tempfile "move_down" "motors -d h -y $(fw_printenv -n motor_maxstep_v)"
	sed -i '1i # GENERATED On '"$(date)" $tempfile
	mv $tempfile $ONVIF_CONFIG
}

stop() {
	stopping "ONVIF discovery"
	stop_daemon_with_pid
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
