#!/bin/sh

DAEMON="onvif_notify_server"
DAEMON_ARGS="--conf_file /etc/onvif.conf --pid_file /run/$DAEMON.pid"
MOTION="/run/motion"

. /usr/share/common

# read web config
ONVIF_WEBUI_CONF=/etc/webui/onvif.conf
[ -f $ONVIF_WEBUI_CONF ] && . $ONVIF_WEBUI_CONF

# default to "enabled" (config is managed by S96onvif_discovery)
[ -z "$onvif_enabled" ] && onvif_enabled="true"

start() {
	starting

	if is_streamer_disabled; then
		quit "Streamer disabled"
	fi

	if is_onvif_disabled; then
		quit "ONVIF disabled"
	fi

	if [ ! -d "$MOTION" ]; then
		mkdir -p $MOTION
	fi

	start_daemon
}

stop() {
	stopping
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
