#!/bin/sh

devip=$(fw_printenv -n devip)
[ -z "$devip" ] && exit
[ -z "$(fw_printenv -n debug)" ] && exit

start() {
	if ! grep -q /var/www /etc/mtab; then
		logger -t httpd "mount development webui"
		rm -r /var/www
		mkdir /var/www
		mount -t nfs -o nolock,tcp,nfsvers=3 ${devip}:/srv/nfs/www /var/www
	fi
}

stop() {
	if grep -q /var/www /etc/mtab; then
		logger -t httpd "unmount development webui"
		umount /var/www
		rm -r /overlay/var/www
		mount -o remount /
	fi
}

case "$1" in
	start|stop)
		$1
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
