#!/bin/sh

. /etc/init.d/rc.common

CONFFILE="/etc/httpd.conf"
PORTAL_CONFFILE="/etc/httpd-portal.conf"
ssid="$(envvar wlanssid)"
pass="$(envvar wlanpass)"

if ([ -z "$ssid" ] || [ -z "$pass" ]) && ip link show wlan0 &>/dev/null; then
    DAEMON_ARGS="-f -c $PORTAL_CONFFILE"
else
    DAEMON_ARGS="-f -c $CONFFILE -r Authentication"
fi

start() {
	starting
	[ -f $DAEMON_FULL ] || disabled
	start_daemon_with_pid
}

stop() {
	stopping
	[ -f $DAEMON_FULL ] || disabled
	stop_daemon_with_pid
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		$1
		;;
	reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
