#!/bin/sh

DAEMON="httpd"
PIDFILE="/var/run/$DAEMON.pid"
CONFFILE="/etc/httpd.conf"
PORTAL_CONFFILE="/etc/httpd-portal.conf"
ssid="$(fw_printenv -n wlanssid)"
pass="$(fw_printenv -n wlanpass)"

if ([ -z "$ssid" ] || [ -z "$pass" ]) && ip link show wlan0 &>/dev/null; then
    HTTPD_ARGS="-f -c $PORTAL_CONFFILE"
else
    HTTPD_ARGS="-f -c $CONFFILE -r Authentication"
fi

start() {
	printf 'Starting %s: ' "$DAEMON"
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $HTTPD_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		$1
		;;
	reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
