#!/bin/sh

. /etc/init.d/rc.common

MOUNT_POINT="/var/www"

start() {
	starting

	[ "true" = "$(fw_printenv -n development_enabled)" ] || quit "Not in development mode"

	local nfs_ip nfs_share
	nfs_ip=$(fw_printenv -n development_nfs_ip)
	[ -z "$nfs_ip" ] && quit "Remote machine IP is not set"
	info "Remote machine is $nfs_ip"

	nfs_share=$(fw_printenv -n development_nfs_share)
	[ -z "$nfs_share" ] && nfs_share="/srv/nfs/www"
	mountpoint -q $MOUNT_POINT && quit "Already mounted"
	{
		rm -r $MOUNT_POINT
		mkdir $MOUNT_POINT
		mount -t nfs -o nolock,tcp,nfsvers=3 $nfs_ip:$nfs_share $MOUNT_POINT
	}
	check_result
}

stop() {
	stopping
	mountpoint -q $MOUNT_POINT || quit "Nothing to unmount"
	{
		umount $MOUNT_POINT
		rm -r /overlay$MOUNT_POINT
		mount -o remount /
	}
	check_result
}

case "$1" in
	start | stop)
		$1
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop}"
		;;
esac

exit 0
