#!/bin/sh

MOUNT_SHARE=
MOUNT_POINT="/var/www"

start() {
	echo "Mounting $MOUNT_SHARE to $MOUNT_POINT"

	mountpoint -q $MOUNT_POINT && quit "Already mounted"
	rm -r $MOUNT_POINT
	mkdir $MOUNT_POINT
	mount -t nfs -o nolock,tcp,nfsvers=3 $MOUNT_SHARE $MOUNT_POINT
}

stop() {
	echo "Unmounting $MOUNT_POINT"

	mountpoint -q $MOUNT_POINT || quit "Nothing to unmount"
	umount $MOUNT_POINT
	rm -r /overlay$MOUNT_POINT
	mount -o remount /
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
