#!/bin/sh

. /etc/init.d/rc.common

HTTPD_CONF="/etc/httpd.conf"
PORTAL_CONF="/etc/httpd-portal.conf"

no_iface() {
	[ -z "$(ip link show $1 2> /dev/null)" ]
}

no_wlan_ap() {
	[ -z "$wlanap_enabled" ] || [ "$wlanap_enabled" = "false" ]
}

no_wlan_creds() {
	[ -z "$wlan_ssid" ] || [ -z "$wlan_pass" ]
}

if no_iface eth0 && no_iface usb0 && iface_exists wlan0 && no_wlan_ap && no_wlan_creds; then
	DAEMON_ARGS="-f -c $PORTAL_CONF"
else
	DAEMON_ARGS="-f -c $HTTPD_CONF -r Authentication"
fi

if [ "0$(fw_printenv -n debug)" -gt 1 ]; then
	sed -i 's/^\/x:root/#\/x:root/' $HTTPD_CONF
else
	sed -i 's/^#\/x:root/\/x:root/' $HTTPD_CONF
fi

start() {
	echo "Starting WLAN AP"

	[ -f $DAEMON_FULL ] || quit "Disabled"
	start_daemon
}

stop() {
	echo "Stopping WLAN AP"

	[ -f $DAEMON_FULL ] || quit "Disabled"
	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
