#!/bin/sh

DAEMON="/usr/sbin/httpd"
PIDFILE="/var/run/httpd.pid"
PORTAL_MODE_FLAG="/run/portal_mode"

start_daemon() {
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- $@
}

stop_daemon() {
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
		status=$?
		rm -f "$PIDFILE"
		return $status
	fi

	start-stop-daemon -K -x "$DAEMON"
}

if [ -f "$PORTAL_MODE_FLAG" ]; then
	DAEMON_ARGS="-f -c /etc/httpd-portal.conf"
else
	DAEMON_ARGS="-f -c /etc/httpd.conf"
fi

start() {
	echo -c 15 "Starting HTTPD"

	# shellcheck disable=SC2086
	start_daemon $DAEMON_ARGS
}

stop() {
	echo -c 15 "Stopping HTTPD"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
