#!/bin/sh

DAEMON="mqtt-sub-dispatcher"
PIDFILE="/var/run/mqtt-sub.pid"
CONFIG_FILE="/etc/thingino.json"

is_enabled() {
	enabled=$(jct "$CONFIG_FILE" get mqtt_sub.enabled 2>/dev/null)
	[ "$enabled" = "true" ]
}

start() {
	is_enabled || return 0
	printf "Starting %s: " "$DAEMON"
	start-stop-daemon -S -q -m -b -p "$PIDFILE" -x /usr/sbin/mqtt-sub-dispatcher
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping %s: " "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -f "$PIDFILE"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
