WOLFSSL_CERTGEN_SITE_METHOD = local
WOLFSSL_CERTGEN_SITE = $(WOLFSSL_CERTGEN_PKGDIR)/files
WOLFSSL_CERTGEN_LICENSE = MIT
WOLFSSL_CERTGEN_DEPENDENCIES = thingino-wolfssl

define WOLFSSL_CERTGEN_INSTALL_WOLFSSL_CERTGEN
	$(INSTALL) -D -m 0755 $(WOLFSSL_CERTGEN_PKGDIR)/files/usr/bin/wolfssl-certgen \
		$(TARGET_DIR)/usr/bin/wolfssl-certgen
endef
WOLFSSL_CERTGEN_POST_INSTALL_TARGET_HOOKS += WOLFSSL_CERTGEN_INSTALL_WOLFSSL_CERTGEN

$(eval $(generic-package))
