WIFI_ATBM6132CU_SITE_METHOD = git
WIFI_ATBM6132CU_SITE = https://github.com/gtxaspec/atbm-wifi
WIFI_ATBM6132CU_SITE_BRANCH = atbm-606x-c
WIFI_ATBM6132CU_VERSION = 31615cc8357bd8bbe86e964bff0ec211a2fbd6c1

WIFI_ATBM6132CU_LICENSE = GPL-2.0

ATBM6132CU_MODULE_NAME = atbm6132cu
ATBM6132CU_MODULE_OPTS = atbm_printk_mask=0

WIFI_ATBM6132CU_MODULE_MAKE_OPTS = \
	KERDIR=$(LINUX_DIR)

define WIFI_ATBM6132CU_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

define WIFI_ATBM6132CU_INSTALL_CONFIGS
	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/lib/modules/$(LINUX_VERSION_PROBED)
	touch $(TARGET_DIR)/usr/lib/modules/$(LINUX_VERSION_PROBED)/modules.builtin.modinfo

	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/share/wifi
	$(INSTALL) -m 0644 -t $(TARGET_DIR)/usr/share/wifi \
		$(WIFI_ATBM_WIFI_PKGDIR)/files/*.txt

	$(INSTALL) -D -m 0644 $(@D)/firmware/firmware_usb_ocea.bin \
		$(TARGET_DIR)/usr/lib/firmware/$(call qstrip,$(ATBM6132CU_MODULE_NAME))_fw.bin
endef

WIFI_ATBM6132CU_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6132CU_INSTALL_CONFIGS

define WIFI_ATBM6132CU_COPY_CONFIG
	$(INSTALL) -D -m 0644 $(@D)/configs/atbm6132cu_ingenic.config \
		$(@D)/.config
endef

WIFI_ATBM6132CU_PRE_CONFIGURE_HOOKS += WIFI_ATBM6132CU_COPY_CONFIG

$(eval $(kernel-module))
$(eval $(generic-package))
