WIFI_ATBM6132CU_SITE_METHOD = git
WIFI_ATBM6132CU_SITE = https://github.com/gtxaspec/atbm-wifi
WIFI_ATBM6132CU_SITE_BRANCH = atbm-606x-c
WIFI_ATBM6132CU_VERSION = 8d06d948cc0d24405faf5429cd4bebf95640d705

WIFI_ATBM6132CU_LICENSE = GPL-2.0

ATBM6132CU_MODULE_NAME = atbm6132cu
ATBM6132CU_MODULE_OPTS = wifi_bt_comb=1

WIFI_ATBM6132CU_MODULE_MAKE_OPTS = \
	KERDIR=$(LINUX_DIR) \
	
define WIFI_ATBM6132CU_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

LINUX_CONFIG_LOCALVERSION = $(shell awk -F "=" '/^CONFIG_LOCALVERSION=/ {print $$2}' $(BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE))

define WIFI_ATBM6132CU_INSTALL_CONFIGS
	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)
	touch $(TARGET_DIR)/usr/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)/modules.builtin.modinfo

	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/share/wifi
	$(INSTALL) -m 0644 -t $(TARGET_DIR)/usr/share/wifi \
		$(WIFI_ATBM6132CU_PKGDIR)/files/set_rate_power.txt
	$(INSTALL) -m 0644 -t $(TARGET_DIR)/usr/share/wifi \
		$(WIFI_ATBM6132CU_PKGDIR)/files/atbm_txpwer_dcxo_cfg.txt
	# Install vendor firmware for the device 
	$(INSTALL) -D -m 0644 $(@D)/firmware/firmware_usb_wifi_bt_comb_ocea.bin \
		$(TARGET_DIR)/usr/lib/firmware/$(call qstrip,$(ATBM6132CU_MODULE_NAME))_fw.bin
endef

WIFI_ATBM6132CU_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6132CU_INSTALL_CONFIGS

define WIFI_ATBM6132CU_COPY_CONFIG
	$(INSTALL) -D -m 0644 $(WIFI_ATBM6132CU_PKGDIR)/files/atbm6132cu-6162.config \
		$(@D)/.config
endef

WIFI_ATBM6132CU_PRE_CONFIGURE_HOOKS += WIFI_ATBM6132CU_COPY_CONFIG

$(eval $(kernel-module))
$(eval $(generic-package))
