WIFI_SYN43436_SITE_METHOD = git
WIFI_SYN43436_SITE = https://github.com/acvigue/bcmdhd
WIFI_SYN43436_SITE_BRANCH = main
WIFI_SYN43436_VERSION = $(shell git ls-remote $(WIFI_SYN43436_SITE) $(WIFI_SYN43436_SITE_BRANCH) | head -1 | cut -f1)

WIFI_SYN43436_MODULE_MAKE_OPTS = \
	KVER=$(LINUX_VERSION_PROBED) \
	KSRC=$(LINUX_DIR) \
        CONFIG_BCMDHD=m \
        CONFIG_BCMDHD_SDIO=y \
        CONFIG_BCMDHD_OOB=y \
        CONFIG_CFG80211=y \
        CONFIG_BCMDHD_AG=y

define WIFI_SYN43436_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

define WIFI_SYN43436_INSTALL_TARGET_CMDS
	$(INSTALL) -m 755 -d $(TARGET_DIR)/usr/lib/firmware
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_SYN43436_PKGDIR)/files/fw_bcm43436b0.bin
	$(INSTALL) -m 644 -t $(TARGET_DIR)/usr/lib/firmware $(WIFI_SYN43436_PKGDIR)/files/nv_bcm43436b0.txt
endef

$(eval $(kernel-module))
$(eval $(generic-package))
