#!/bin/sh

DAEMON="httpd"
PIDFILE="/var/run/$DAEMON.pid"
CONFFILE="/etc/httpd.conf"

HTTPD_ARGS="httpd -p 85 -f -c $CONFFILE -r Authentication"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

if [ "$(fw_printenv -n debug)" ]; then
	echo "Development mode"
	if [ -z "$(cat /etc/mtab | grep /tmp/dev)" ]; then
		mkdir -p /tmp/dev
		mount -t nfs -o nolock,tcp,nfsvers=3 $(fw_printenv -n devip):/srv/nfs/openipc/dev /tmp/dev
	fi

	pid=$(ps ax | grep httpd | grep 85 | xargs | cut -d " " -f 1)
	[ ! -z "$pid" ] && kill -9 $pid
	sleep 3
	sed -i "/^H:\/var\/www/H:\/tmp\/dev\/files\/var\/www/" $CONFFILE
	sed -i "/^\/cgi-bin:admin:/s/^/#/" $CONFFILE
	# HTTP_MODE=development httpd -p 86 -h "/tmp/dev/files/var/www" -c /dev/null $1
else
	echo "Production mode"
	sed -i "/^H:\/tmp\/dev\/files\/var\/www/H:\/var\/www/" $CONFFILE
	sed -i "/^#\/cgi-bin:admin:/s/^#//" $CONFFILE
fi

# The httpd does not create a pidfile, so pass "-n" in the command line
# and use "-m" to instruct start-stop-daemon to create one.
start() {
	printf 'Starting %s: ' "$DAEMON"
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" \
		-- $HTTPD_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
