#!/bin/sh

if [ -z "$MDEV" ]; then
	echo -c 160 -e "No device name to mount!" >&2
	exit 1
fi

device_node="/dev/$MDEV"
echo -c 240 -e "- Device node: $device_node"

mount_point="/mnt/$MDEV"
echo -c 240 -e "- Mount point: $mount_point"

diag="$mount_point/.diag"
run="$mount_point/run.sh"
run_once="$mount_point/runonce.sh"
run_once_flag="${run_once%.sh}.done"

#log() {
#	logger -p daemon.info -t automount[$$] -s "$1"
#}

cleanup() {
	if [ -d "$mount_point" ]; then
		if rm -r "$mount_point"; then
			echo -c 240 -e "- Removed mount point $mount_point"
		else
			echo -c 142 -e "Failed to remove mount point $mount_point" >&2
		fi
	else
		echo -c 240 -e "- No mount point $mount_point found"
	fi
}

do_fsck() {
	res=$(fsck -V -y "$device_node" 2>&1)
	fsck_status=$?

	echo "$res" | while IFS= read -r line; do
		echo -c 240 -e "- $line"
	done

	if [ "$fsck_status" -eq 0 ]; then
		echo -c 240 -e "- fsck check succeeded on $device_node"
	else
		echo -c 142 -e "fsck check failed on $device_node" >&2

		if [ "$fsck_status" -eq 8 ] || [ "$fsck_status" -eq 16 ] ||
			[ "$fsck_status" -eq 32 ] || [ "$fsck_status" -eq 128 ]; then
			echo -c 142 -e "Critical fsck error with exit status $fsck_status, mounting process aborted" >&2
			return 1
		else
			echo -c 142 -e "Non-critical fsck error with exit status $fsck_status, continuing" >&2
		fi
	fi
}

do_mount() {
	if mkdir -p "$mount_point"; then
		echo -c 240 -e "- Created mount point $mount_point"
	else
		echo -c 142 -e "Cannot create mount point $mount_point" >&2
		return 1
	fi

	if ! do_fsck; then
		echo -c 142 -e "Failed to fsck $device_node" >&2
		return 1
	fi

	if mount -t auto -o noatime,sync "$device_node" "$mount_point"; then
		echo -c 240 -e "- Mounted $device_node to $mount_point"
	else
		echo -c 142 -e "Failed to mount $device_node to $mount_point" >&2
		cleanup
		return 1
	fi

	[ -f "$diag" ] && do_run_diag
	[ -f "$run_once" ] && do_run_once
	[ -f "$run" ] && do_run_always
}

do_umount() {
	if lsof | grep -q "$mount_point"; then
		echo -c 240 -e "- Killing processes that are using $mount_point"
		lsof | awk "/$mount_point/{print \$1}" | xargs kill -9
	else
		echo -c 240 -e "- No processes are using $mount_point"
	fi

	if grep -qs "^$device_node " /proc/mounts; then
		if umount -l "$mount_point"; then
			echo -c 240 -e "- Unmounted $mount_point"
		else
			echo -c 142 -e "Failed to unmount $mount_point" >&2
		fi
	else
		echo -c 240 -e "- $device_node is not mounted"
	fi

	cleanup
}

do_run_always() {
	if sh $run; then
		echo -c 240 -e "- Executed $run script"
	else
		echo -c 142 -e "Failed to execute $run script" >&2
	fi
}

do_run_diag() {
	rm -f $mount_point/.diag
	thingino-diag -l $mount_point
	sync
	do_umount
	play -l 3 /usr/share/sounds/chime_1.opus
}

do_run_once() {
	if [ -f "$run_once_flag" ]; then
		echo -c 142 -e "Stop flag $run_once_flag exists" >&2
		return 1
	fi

	if sh "$run_once"; then
		touch "$run_once_flag"
		echo -c 240 -e "- Executed $run_once script"
	else
		echo -c 142 -e "Failed to execute $run_once script" >&2
	fi
}

case "$ACTION" in
	add | "")
		do_umount
		do_mount
		;;
	remove)
		do_umount
		;;
esac

exit 0
