#!/bin/sh

erase_mtd1=true

while getopts "efh" opt; do
	case $opt in
		e)
			erase_mtd1=false
			;;
		f)
			force_wipe=true
			;;
		h)
			printf 'Usage: %s [options]\n  -e    Do not erase /dev/mtd1\n  -h    Show help information\n' "$0"
			exit 0
			;;
		\?)
			echo "Invalid option. Use -h for help."
			exit 1
			;;
	esac
done

wipe() {
	data_dev=$(awk '$4 ~ /"data"/ {gsub(":","",$1); print $1}' /proc/mtd)
	if [ -z "$data_dev" ]; then
		echo "Overlay partition not found!" >&2
		exit 1
	fi
	echo "Erasing overlay partition..."
	flash_eraseall -j "/dev/${data_dev}"

	if [ "$erase_mtd1" = true ]; then
		echo "Erasing U-Boot ENV..."
		flash_eraseall /dev/mtd1
	fi
	echo "Erase completed. Rebooting..."
	reboot -f
}

warn() {
	printf 'Warning\nThis action will reset the device to defaults and erase all configurations, leaving the device like the first boot.\nAll saved settings will be erased!\nAre you sure you want to proceed? (yes/no)\n'
	read response
	if [ "$response" != "yes" ]; then
		echo "Operation aborted." >&2
		exit 1
	else
		wipe
	fi
}

if [ "$force_wipe" = true ]; then
	wipe
else
	warn
fi

exit 0
