#!/bin/sh

DAEMON_ARGS="-d"

. /usr/share/common

start() {
	starting
	start_daemon
}

stop() {
	stopping
	stop_daemon_process
}

case "$1" in
	start | stop)
		$1
		;;
	restart | reload)
		stop || true
		sleep 1
		start
		;;
	*)
		die "Usage: $0 {start|stop|restart|reload}"
		;;
esac

exit 0
