#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic

echo 1 >/proc/sys/vm/overcommit_memory

log() {
	logger -s -p daemon.info -t ingenic "$1"
}

case "$SENSOR" in
	gc2053)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_max_fps=30 data_interface=1"
		;;
	gc2083)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=200000000"
		SENSOR_PARAM="shvflip=1"
		;;
	gc4653)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=200000000"
		SENSOR_PARAM=""
		;;
	imx307)
		if [ "t40" = "$soc" ]; then
			AVPU_PARAM="clk_name=mpll avpu_clk=550000000"
			ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
		else
			AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
			ISP_PARAM="isp_clk=125000000"
		fi
		SENSOR_PARAM=""
		;;
	imx327)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM=""
		;;
	imx335)
		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
		ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
		SENSOR_PARAM=""
		;;
	imx415)
		AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
		ISP_PARAM="isp_clk=350000000"
		SENSOR_PARAM=""
		;;
	jxf22)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	jxf23)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	jxf37)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=200000000 isp_memopt=1 isp_day_night_switch_drop_frame_num=1 isp_ch0_pre_dequeue_time=12 isp_ch0_pre_dequeue_interrupt_process=0 isp_ch0_pre_dequeue_valid_lines=540"
		SENSOR_PARAM="shvflip=1"
		;;
	jxh42)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	jxh62)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM=""
		SENSOR_PARAM=""
		;;
	jxk04)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=125000000 isp_ch0_pre_dequeue_time=14 isp_ch0_pre_dequeue_interrupt_process=0 isp_ch0_pre_dequeue_valid_lines=540 isp_memopt=1"
		SENSOR_PARAM="shvflip=1"
		;;
	jxq03 | jxq03p)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=150000000"
		SENSOR_PARAM=""
		;;
	os03b10)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=200000000"
		SENSOR_PARAM=""
		;;
	ov2735b)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	sc200ai)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=100000000 isp_ch0_pre_dequeue_time=20 isp_ch0_pre_dequeue_interrupt_process=0 isp_memopt=1"
		SENSOR_PARAM="shvflip=1"
		;;
	sc2135)
		ISP_PARAM="isp_clk=100000000"
		SENSOR_PARAM=""
		;;
	sc2232)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM=""
		;;
	sc2232h)
		ISP_PARAM="isp_clk=125000000"
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	sc2235)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2300)
		ISP_PARAM="isp_clk=90000000"
		SENSOR_PARAM=""
		;;
	sc2332)
		ISP_PARAM=""
		SENSOR_PARAM="sensor_gpio_func=0"
		;;
	sc2335)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=100000000 isp_ch0_pre_dequeue_time=20 isp_ch0_pre_dequeue_interrupt_process=0 isp_memopt=1"
		SENSOR_PARAM=""
		;;
	sc2336)
		AVPU_PARAM="clk_name=vpll avpu_clk=500000000"
		ISP_PARAM="isp_clk=200000000 isp_ch0_pre_dequeue_time=24 isp_ch0_pre_dequeue_interrupt_process=0 isp_memopt=1"
		SENSOR_PARAM="shvflip=1"
		;;
	sc3335)
		AVPU_PARAM="clk_name=mpll avpu_clk=500000000"
		ISP_PARAM="isp_clk=200000000 isp_memopt=1"
		SENSOR_PARAM=""
		;;
	sc3338)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=150000000"
		SENSOR_PARAM=""
		;;
	sc4236)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=150000000"
		SENSOR_PARAM=""
		;;
	sc5235)
		AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
		ISP_PARAM="isp_clk=200000000"
		SENSOR_PARAM=""
		;;
	*)
		if [ "t40" = "$soc" ]; then
			AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
			ISP_PARAM="isp_clk=350000000"
		else
			AVPU_PARAM="clk_name=vpll avpu_clk=400000000"
			ISP_PARAM="isp_clk=125000000"
		fi
		SENSOR_PARAM=""
		;;
esac

echo ------------------------------------------------------------
echo "SOC:           $SOC"
echo "SENSOR:        $SENSOR"
echo "SENSOR_PARAM:  $SENSOR_PARAM"
echo "AVPU_PARAM:    $AVPU_PARAM"
echo "ISP_PARAM:     $ISP_PARAM"
echo ------------------------------------------------------------

if find /lib/modules/ -name gpio.ko | grep -q .; then
	if ! grep -q ^gpio /proc/modules; then
		echo -n "Load gpio module ... "
		modprobe gpio && echo "OK" || echo "FAIL"
	fi
fi

if find /lib/modules/ -name avpu.ko | grep -q .; then
	if ! grep -q ^audio /proc/modules; then
		echo -n "Load audio module ... "
		modprobe audio spk_gpio=-1 && echo "OK" || echo "FAIL"
	fi
fi

if ! grep -q ^tx_isp /proc/modules; then
	echo -n "Load tx-isp-${SOC} module ... "
	modprobe tx-isp-${SOC} $ISP_PARAM && echo "OK" || echo "FAIL"
fi

if ! grep -q ^$SENSOR /proc/modules; then
	echo -n "Load sensor_${SENSOR}_${SOC} module ... "
	modprobe sensor_${SENSOR}_${SOC} $SENSOR_PARAM && echo "OK" || echo "FAIL"
fi

if find /lib/modules/ -name avpu.ko | grep -q .; then
	if ! grep -q ^avpu /proc/modules; then
		echo -n "Load avpu module ... "
		modprobe avpu $AVPU_PARAM && echo "OK" || echo "FAIL"
	fi
fi

