WIFI_RT5370_VERSION = 1.0
WIFI_RT5370_SITE_METHOD = local
WIFI_RT5370_SITE = $(LINUX_DIR)/drivers/net/wireless/rt2x00

WIFI_RT5370_LICENSE = GPL-2.0

RT5370_MODULE_NAME = rt2800usb
RT5370_MODULE_OPTS =

define WIFI_RT5370_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,y)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
	$(call KCONFIG_ENABLE_OPT,CONFIG_RT2X00)
	$(call KCONFIG_SET_OPT,CONFIG_RT2800USB,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_RT2800USB_RT53XX)
endef

$(eval $(kernel-module))
$(eval $(generic-package))
